### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#10]
Hi, I'm not sure what would be the best way to provide suggestions, so just a couple this way:

- ~~DAX Dependencies: should be visible under the "View" Menu~~
- ~~DAX Dependencies: there should be an option to automatically track the object selected in the TOM Explorer view~~
- Themes: Could there be a theme with a light-grey background? White is too white, and black too black. Similar to basic, but every shade of white-grey a bit darker...
- ~~DAX Query results: show the number of rows returned by the query~~
- ~~TOM Explorer: missing "duplicate" function on right-click~~ 
- ~~Tom Explorer: the default "are you sure you want to delete" multiple objects should default to "NO"
(actually, ~~any deletion should warn, even a single object!~~)~~

If you would prefer different suggestions as multiple issues, or a different way to present them, just tell me

Thanks!

**Comment by otykier** [comment]
[3.0.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.6) addresses the DAX query row count. Leaving this open to track the remaining suggestions.

**Comment by otykier** [comment]
The duplicate menu option will not come in TE3, as it is equivalent to copy + paste (ctrl+c followed by ctrl+v). Trying to prevent menu cluttering :-)

We don't show warnings when deleting single objects since hitting undo (ctrl+z) restores the object in the exact same state it was in originally.

Regarding Themes - have you tried some of the new palettes available with the "Basic" or "Bezier" skin?

**Comment by zenzeinet** [comment]
Hi Daniel,

Regarding delete warnings, I respectfully disagree. You can also undo ctrl-z when deleting 10 tables, so why warn it there? (I'm being ironic on purpose :-) The whole point is about preventing human error - on large and/or on critical models, you want to be sure you don't unwillingly delete stuff. E.g. you might think the cursor was on a property while it really was on an object; you might have wanted to hit the "end" key but hit delete just when the phone rings; or the cat might walk on the keyboard. 

No duplicate button: your call, but then with Ctrl-C+V you overwrite the clipboard, something you might not want to do. Minor point, but I did use it quite often. I don't see it as cluttering, but then again I'm not the average ;)

Thanks for everything!

**Comment by otykier** [comment]
Good points. Let's introduce an option to always show delete warnings, as I don't think every user wants that (using myself as an example).

Your point about not overwriting the clipboard is excellent - many users have asked for the "Duplicate" feature, and I didn't understand why - until now. Will add it back in :-)

**Comment by zenzeinet** [comment]
Great to hear you agree. And always show delete as an option is perfect, super.
BR

**Comment by otykier** [comment]
[3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6) addresses the remaining points (except for the theming, which is a separate task).

**Comment by zenzeinet** [comment]
Daniel, did you implement the "Duplicate" feature in 3.1.6 and onwards? I don't see it in the right menu of the TOM Explorer, using 3.2.2.
