### ISSUE TITLE
No option to refresh a calculation group table

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#100]
Maybe I'm missing something, but there is no option to refresh a calculation group table like you can a regular table.

![image](https://user-images.githubusercontent.com/62320770/123370528-0181d100-d5d4-11eb-8ca4-16d063347603.png)

**Comment by otykier** [comment]
That's a bug. Thanks for reporting.

**Comment by otykier** [comment]
Fixed in [3.0.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.7). Thanks for reporting!
