### ISSUE TITLE
[Issue] : Facing issues while importing a table in AAS model using TE3

### ISSUE THREAD

**Issue by kkmalik89** [TabularEditor/TabularEditor3#1007]
**Describe the issue**
A clear and concise description of what the issue is.

** Which version are you currently using? **
3.10.1

**To Reproduce**
Are you connected to SSAS/AAS/Power BI or working offline? - AAS

1. Import the model in TE
2. Right click on Tables and import tables.
3. Choose any table/view.  It shows 'Update Schema' popup. 

![image](https://github.com/TabularEditor/TabularEditor3/assets/12782555/e76839e4-7b3b-4be6-b8b4-6ad8b59cf8de)

**Expected behavior**
Table import successful.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version: 11

**Additional context**

**Comment by otykier** [comment]
Hi @kkmalik89 
Are you connecting to a dedicated synapse SQL pool, by any chance? If so, we are currently aware of an issue in that regard, and will make a fix available with our next update.

As a workaround, enable **Use Analysis Services for change detection** and import tables by copying existing ones, modifying the M expression, and running a schema update, as [described here](https://docs.tabulareditor.com/te3/tutorials/importing-tables.html#updating-table-schema-through-analysis-services).

**Comment by otykier** [comment]
Fixed in [3.12.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.12.0), thanks for reporting!

**Comment by kkmalik89** [comment]
> Hi @kkmalik89 Are you connecting to a dedicated synapse SQL pool, by any chance? If so, we are currently aware of an issue in that regard, and will make a fix available with our next update.
> 
> As a workaround, enable **Use Analysis Services for change detection** and import tables by copying existing ones, modifying the M expression, and running a schema update, as [described here](https://docs.tabulareditor.com/te3/tutorials/importing-tables.html#updating-table-schema-through-analysis-services).

Yes, We are connecting to Synapse dedicated SQL pool.

**Comment by kkmalik89** [comment]
> Fixed in [3.12.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.12.0), thanks for reporting!

Thanks. Will download this version.

**Comment by kkmalik89** [comment]
It works in version [3.12.0].  Thanks @otykier !!

**Comment by otykier** [comment]
Thanks for the confirmation :)
