### ISSUE TITLE
[Issue] TargetInvocationException while deserializing TMDL. Prevents AAS connection.

### ISSUE THREAD

**Issue by hayescode** [TabularEditor/TabularEditor3#1009]
**Describe the issue**
Starting today I cannot connect a local model to the Power BI Service. I get this error:
![image](https://github.com/TabularEditor/TabularEditor3/assets/35790761/bf56d67d-d72c-414a-83aa-18d6b03b4759)
This model was working on Friday and nothing has changed with this model. The only thing that seems different is the Power BI service now has new icons so I guess there was a service update?
![image](https://github.com/TabularEditor/TabularEditor3/assets/35790761/ffd09200-9074-43a0-9d33-b78c566e9fa8)

** Which version are you currently using? **
3.11.0
Using TMDL

**To Reproduce**
Are you connected to SSAS/AAS/Power BI or working offline? Trying to

1. Open from Folder
2. Connect to AAS via SSO
3. Fail

**Expected behavior**
Connect locally/remotely like normal.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**

**Comment by otykier** [comment]
Unfortunately, this issue seems to arise from within the TMDL engine, when deserializing the model metadata. Please raise a support ticket with Microsoft. You can also try to post the issue on the [Analysis Services GitHub](https://github.com/microsoft/analysis-services), although please keep in mind that TMDL is still a preview feature from Microsoft.

**Comment by hayescode** [comment]
@otykier I can connect to AAS just fine so there seems to be a conflict between AAS TMDL engine and TE3's, no? I've seen TMDL updates come through where certain fields have quotations added/removed, but this seems like a breaking change this time. Is this a widespread issue or is this localized to tenant-specific service changes ("upgrades") we're a part of?

**Comment by otykier** [comment]
@hayescode the exception you’re seeing is thrown when Tabular Editor tries to load the TMDL metadata, before it’s actually deploying anything to AS. You would get the same error, if you tried to load the same TMDL folder without using a workspace database.

**Comment by hayescode** [comment]
For anyone who has this issue in the future, this issue was fixed (at least for me) by applying the latest Windows update and restarting my computer. Kind of embarassing I forgot step 1 - turn it off/on - of IT troubleshooting!
