### ISSUE TITLE
TabularEditor publish the wrong informations for a non-legacy Oracle Data Source

### ISSUE THREAD

**Issue by samusaran** [TabularEditor/TabularEditor3#101]
I have a Tabular Model that reads from an Oracle Database. It works fine with Visual Studio.

If I open the model with tabular editor, the following issues occurs when trying to process any table related to the data source:

- The `PrivacySetting` property is set to an empty string, leading to `Microsoft.Data.Mashup: The given privacy setting is not recognized.`. That can be solved by manually specifying `None`
- Tabular Editor fails to publish the credential password, leading to `Microsoft.Data.Mashup: The given credential is missing a required property. Data source kind: Oracle. Authentication kind: UsernamePassword. Property name: Password.`. This can be fixed by re-typing the password on the data source in tabular editor, even if the password was asked while opening the model.

Both are minor issues solveable with a bit of manual inputs, but they can still be confusing.

**Comment by otykier** [comment]
Thanks for reporting. Can you confirm you're using v. 3.0.6 of Tabular Editor?

**Comment by samusaran** [comment]
Yes, 3.0.6 Trial version

**Comment by otykier** [comment]
Could you post a screenshot of the data source properties that needs to be manually entered to workaround the issue? It seems that these may be different for an Oracle source, which is why I'm curious (since both the authentication and the PrivacySetting should be correctly set when using SQL Server-based data sources, see #28).

**Comment by DBojsen** [comment]
Hi @samusaran 

We have made significantly imporvements to our Oracle support in [3.5.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.5.0).
I'll close this issue for now - if you still have issues, please reopen or open a new one with more info.

BR David - TE Support
