### ISSUE TITLE
Is there a way to loop through an Excel file or Power BI Dataset inside C# script?

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#105]
I have a C# script that reads to a tab-delimited file and performs some logic for each row. I would like to change this process to use an Excel file or better yet one of the tables in the data model. Is there a way to do this in TE3?

Below is an example of the current logic that I am trying to replace for reading Excel or Datatable.

Is this doable?
*******************************************************************************
...
...
_table = ReadFile(@"D:\Users\dpesante\OneDrive - Beeline\myfile.txt");
tsvRows = _table.Split(new[] {'\r','\n'},StringSplitOptions.RemoveEmptyEntries);
// Loop through all rows but skip the first one:
foreach(var row in tsvRows.Skip(1))
{
    var tsvColumns = row.Split('\t');
    ...
    ...

**Comment by m-kovalsky** [comment]
See my Model Auto Build tool. It uses C# from Tabular Editor to directly reference an Excel file.

https://github.com/m-kovalsky/ModelAutoBuild

**Comment by dpesante** [comment]
@m-kovalsky thanks for the example. In the process of implementing. What about reading (looping) thru a model dataset. Is this supported?

**Comment by otykier** [comment]
@dpesante by "loping thru a model dataset" do you mean executing a DAX query and iterating the results?

That's certainly possible! Darren Gosbell wrote an [excellent article on this](https://darren.gosbell.com/2020/08/the-best-way-to-generate-data-driven-measures-in-power-bi-using-tabular-editor/) (he's using Tabular Editor 2.x but the same technique is possible in Tabular Editor 3).

Hope this helps!
