### ISSUE TITLE
Find All in Expression Editor doesn't seem to do anything

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#107]
I am using Marco Russo / Alberto Ferrari 1560 line Date file and when I do Ctrl + F, type in WeeklyType and click on Find All, nothing happens. I would expect all occurrences of WeeklyType to appear. The Find Next option seems to work fine.

![Image](https://user-images.githubusercontent.com/20615192/123521578-91338800-d685-11eb-8d58-52c859b08ad2.png)

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
