### ISSUE TITLE
ORDER BY Clause prevents result from being displayed

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#108]
In a DAX query if I use ORDER BY clause then the results pane doesn't show anything but the result is shown if I remove ORDER BY.
With ORDER BY
![11](https://user-images.githubusercontent.com/73054674/123537744-9d374c80-d74e-11eb-9861-fa68ee7ab1de.png)

Without ORDER BY
![12](https://user-images.githubusercontent.com/73054674/123537751-a4f6f100-d74e-11eb-9240-2e7b9b4b68ff.png)

**Comment by otykier** [comment]
Fixed in [3.0.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.7). Thanks for reporting!
