### ISSUE TITLE
RELATED suggests columns of a that isn't connected through a relationship.

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#112]
When using RELATED in an Iterator, columns from disconnected tables are being suggested:
![image](https://user-images.githubusercontent.com/73054674/123846016-7d607e00-d932-11eb-9d24-df5c4f99396e.png)

![image](https://user-images.githubusercontent.com/73054674/123846051-85b8b900-d932-11eb-8a8e-e8edfe78ee8b.png)

**Comment by otykier** [comment]
Fixed in [3.0.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.7). Thanks for reporting!
