### ISSUE TITLE
Measure renaming went wrong in the dependent measures

### ISSUE THREAD

**Issue by avatorl** [TabularEditor/TabularEditor3#115]
I can't replicate the problem, but earlier today when I was renaming some measures in TE3.06, after saving the changes I found an error in the dependent measures.  In the dependent measures the renamed measure looked odd and wrong (and it caused a error):

> [_Measures[New Measure Name]

instead of just [New Measure Name]

_Measures is my measures table name.

**Comment by otykier** [comment]
I'm not able to reproduce this. Leaving this open in case someone is able to provide a reproducible example.

**Comment by samusaran** [comment]
I had the same problem with Columns rename that affected measures. Sometimes it breaks the syntax. What happened to me was something on the line of:

I rename a column from `'MyTable'[ColumnA]` to `'MyTable'[ColumnB]`, the column reference in a measure gets changed to `'M'MyTable'[ColumnB]`.

The only way this seems to trigger is when I'm renaming a column from the Properties panel, and without confirming the rename with Enter, I click somewhere else. This usually gives an error regarding a key not being present in a dictionary, and all references of this column are now broken.

**Comment by otykier** [comment]
Thanks @samusaran, that's really helpful! Will look into it. Please let me know if you discover other ways to trigger this error.

**Comment by otykier** [comment]
@samusaran and @avatorl do you still have this issue with newer versions of TE3?
