### ISSUE TITLE
Width of Auto Complete Box starts too narrow

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1152]
### Description

1-2 versions ago you enhanced the auto-complete box so it would be as wide as the widest item in the box. With 3.11 though it starts off narrow again. Once you make it wider manually it starts to autoadjust correctly on subsequent uses. This is just that first use or two that it happens.

### Tabular Editor 3 Version

3.11

### Screenshots

<img width="419" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/45298358/7659ff59-c5e4-46f6-ad10-d8d3a7dadbbf">

### Steps to Reproduce

This is in a calculation item and as just looking for SELECTEDMEASURE().

### Expected behavior

That it would be as wide as SELECTEDMEASUREFORMATSTRING(), which seems to be the widest name in the list.
<img width="415" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/45298358/4d75ddc7-d5d8-421e-9d46-d0a5d38f2ecc">

### Windows Version

11

**Comment by mlonsk** [comment]
Hi @edhans 
Thank you for reporting. We will investigate how to get this working correctly again.

**Comment by otykier** [comment]
Fixed in [3.12.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.12.0), thanks for reporting!
