### ISSUE TITLE
Auto complete does not give you the full list of column names from a table when using the || operator

### ISSUE THREAD

**Issue by festusgrp** [TabularEditor/TabularEditor3#1156]
### Description

Create a DAX query by and type in the line         Customers[Country] = "Canada" || Customers[Country] = "China" and you'll notice after the || Country is not available in the auto complete list.

EVALUATE{
    CALCULATE(
        [Sales Amount],
        Customers[Country] = "Canada" || Customers[Country] = "China",
    )
}

### Tabular Editor 3 Version

3.11.0.26496

### Screenshots

<img width="480" alt="auto complete bug in TE3 version 3 11 0 26496" src="https://github.com/TabularEditor/TabularEditor3/assets/37704825/0cd34951-c1a2-459a-85c4-bda72e72a6ed">

### Steps to Reproduce

Create a DAX query by and type in the line         Customers[Country] = "Canada" || Customers[Country] = "China" and you'll notice after the || Country is not available in the auto complete list.

EVALUATE{
    CALCULATE(
        [Sales Amount],
        Customers[Country] = "Canada" || Customers[Country] = "China",
    )
}

### Expected behavior

Country should be part of the fields available

### Windows Version

10

**Comment by mlonsk** [comment]
Hi @festusgrp 
Thank you for reporting, we will look into getting this fixed.

**Comment by otykier** [comment]
This is now fixed in [3.14.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.14.0). Thanks for reporting!
