### ISSUE TITLE
Is there a way in TE3 c# scripting to get the full path of the current PBIX file (e.g. C:/folder/myap.pbix) that opened TE3 in the first place

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#116]
something like: (speudo code)

var _filename_pbix = system.pbixfile;

_filename_config = _filename_pbix + ".config";

....
....

**Comment by otykier** [comment]
To my knowledge, that's not possible. Tabular Editor can only communicate with PBI Desktop through the XMLA endpoint of the Analysis Services instance hosted by Desktop. This instance of Analysis Services does not have any information about the .pbix file itself.
