### ISSUE TITLE
Unable to Detect Schema - location of the comment is the issue

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1167]
### Description

I am getting this error when I try to Detect Schema Changes on an M based partition:
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/5c46d50c-9f33-48a4-9e59-957fb0edc746)

I finally figured out it was my comment that was causing it:
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/34856d43-6ca0-4efd-9d14-40f5be7ad670)

When I moved the comment to be before the final line, it worked fine.
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/792e45de-cced-4077-8abe-40e913fcbee9)

Not sure if I have violated some M code recommendation. The **_code refreshes fine_** no matter where the comment is, but Detect Schema Changes doesn't like it.

This is against the Power BI Service.

### Tabular Editor 3 Version

3.11

### Windows Version

10

**Comment by otykier** [comment]
Thanks Ed. Seems to be a bug in our M code parser. We'll make sure that's fixed.

**Comment by otykier** [comment]
Fixed in [3.12.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.12.0), thanks for reporting!
