### ISSUE TITLE
Red Error lines in the Expression Editor Appearing. 

### ISSUE THREAD

**Issue by CraigsterT** [TabularEditor/TabularEditor3#1173]
### Description

When writing a measure which includes variables in the expression editor the red error lines appear and persist until you move forward to your next variable. Then the error lines seem to disappear but move onto the next variable and so forth until you have completed your measure. It's a little off putting when writing the code as you do stare at the variable you have just wrote wondering what the error may be when there is in fact nothing wrong with it. Once you finalise the measure with return the red error lines seem to disappear , though . I am not sure if Tabular Editor has now just become super sensitive to variables in some way as a result of the new functionality introduced to detect unused variables. It would be great if we could clear this up and the expression editor could revert back to only identifying true errors in the code , please. I think this could speed up the process of creating measures, avoid the developer send guessing themselves and eliminate any doubts with their code and improve productivity. 

### Tabular Editor 3 Version

3.12.0

### Steps to Reproduce

Simply write a measure in the expression editor that contains variables.

### Expected behavior

Same as before , please. Red error lines only of there is a 'true' error, please.

**Comment by otykier** [comment]
@CraigsterT just to clarify, is this showing up as an _error_ or a _warning_? In my tests, unused variables should only produce warnings, not errors:

<img width="478" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/8976200/7bc01b08-aa61-4e35-8ce1-c3bbfec3dae1">

That being said, we could probably improve this, so the warning isn't showed until the variable block has been completed (including the `RETURN` statement). Or even add an option to disable unused variable warnings (i.e. same behavior as pre-3.12.0)

**Comment by CraigsterT** [comment]
![image](https://github.com/TabularEditor/TabularEditor3/assets/66374274/e45845d9-e7dc-4c6f-b4c4-fe801f7a9053)
Hi Daniel , 
No, it seems to be that if you have not completed the subsequent variable in your code that you have this red line appearing as in my screen shot, In this , I just need to add the customer segment table argument to calculate and then after I complete the code with good old  'Return Result'  then the red line vanishes and it appears that I am now good to go but up until that point it does appear as though Tabular Editor is telling me that I have written some rubbish code and that I have absolutely no chance with the measure I am writing , that's what makes it very off putting and slows you down quite a bit ,while you examine your code with the potential to second guess yourself and then write some rubbish code in order to get rid of the red lines. Which isn't going to happen.  Please try the code that I snipped and tell me what you think please. All the best and speak soon.

**Comment by otykier** [comment]
Yeah, currently the squiggly line will appear throughout the variable expression, until the variable is referenced somewhere. I believe the following changes would be better:

1. If there are no references to the variable, we only show the squiggly line under the variable name, not the full expression assigned to the variable:

    VAR <ins>CustomerSegments</ins> = FILTER( ... )
  
2. We only perform this validation once the `RETURN` statement is added to the code and no other errors are present. This way, you won't see the squiggly line while typing out the code.

What do you think about that solution?

**Comment by CraigsterT** [comment]
Hi Daniel,
Sorry for the delay in responding. The solution to the issue that you have
provided sounds very good. I think a feint red line, similar to the one we
see now underneath the expression,  but instead underneath the variable
name would be a very good solution. I don't believe that this will be as
distracting or confusing as when it appears below each line of the
expression. I look forward to seeing it at some point in the near future.
Thanks for your time and assistance in resolving the issue. I guess just
like DAX itself, it's the small details that make a world of difference.
Thanks again and kind regards
Craig.

**Comment by CraigsterT** [comment]
Hi Daniel ,
A big thank you to you.  Works perfectly. Have a great Xmas, 
Craig.

**Comment by mlonsk** [comment]
Hi @CraigsterT 
Thank you for suggesting the improvement!
Happy holidays to you too!
