### ISSUE TITLE
3.12 TMDL Bug - "This folder does not contain a database.json file"

### ISSUE THREAD

**Issue by hayescode** [TabularEditor/TabularEditor3#1175]
### Description

After upgrading to 3.12 I couldn't open my local semantic models in TMDL format. I had to open from the workspace and save locally which changed all the files from `.tmd` to `.tmdl`. Now I cannot open the dataset at all. For some reason it's looking for a database.json file even though it's TMDL format and preferences 'Save-To-Folder` is set to TMDL.

After reverting to 3.11 I am able to open the dataset from folder and connect to the workspace like normal.

### Tabular Editor 3 Version

3.12

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/35790761/4df06e64-ab39-436c-9f8c-3829618d06b3)

![image](https://github.com/TabularEditor/TabularEditor3/assets/35790761/8571ca09-8e90-4741-9b9a-b619bbe0d658)

### Windows Version

11

**Comment by otykier** [comment]
Are you able to open the model.tmdl file directly (File > Open > Model from File…) instead of using the “Open from folder” option?

**Comment by hayescode** [comment]
@otykier Thanks! That did work, do we not use `Open from folder` with `.tmdl` now?

**Comment by otykier** [comment]
"Open from Folder" was indeed intended to work with TMDL. Looks like we do indeed have a bug after the file extensions were changed from `.tmd` to `.tmdl`. Leaving this issue open to track this.

**Comment by mlonsk** [comment]
This issue has been fixed in Tabular Editor 3.13.0
Thank you for reporting!
