### ISSUE TITLE
Tabular Editor 3 Website Log In - Create Account

### ISSUE THREAD

**Issue by GreyskullAnalytics** [TabularEditor/TabularEditor3#1176]
### Description

I'm trying to create account so I can log in and manage my TE3 license. The button to send a verification code doesn't seem to be working. I've tried several times and have not received an email - I've also been checking junk/spam but there's nothing there. I need to get in my account!

### Tabular Editor 3 Version

3..12

### Windows Version

11

**Comment by DBojsen** [comment]
Hi Johnny

Please try again. 

BR David

**Comment by GreyskullAnalytics** [comment]
sorted. Thanks for sorting so quick!
