### ISSUE TITLE
Menu bar disabled

### ISSUE THREAD

**Issue by JFreddyPC** [TabularEditor/TabularEditor3#1177]
### Description

Hello!
My TE 3.11.0 does not show the menu bar, which does not allow me to open my workspace.
I need to open the model from a folder.

![image](https://github.com/TabularEditor/TabularEditor3/assets/152329452/54062db3-e2ea-4248-b5b7-fa720db670b9)

I already tried the latest version of TE and the menu bar is still hidden.

Any idea how to enable it?

Regards

### Tabular Editor 3 Version

3.11.0

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/152329452/00185dd3-0e48-4acb-9fbb-694cf538992e)

### Steps to Reproduce

1. Open TE 3.11.0
2. Search menu bar

### Expected behavior

Somebody shoe me how to enable the menu bar y TE 3.11.0

### Crash Report

No crash reports I have received.

### Windows Version

11

**Comment by otykier** [comment]
Sounds like you accidentally dragged it out of the application, which unfortunately can happen quite easily…

Anyway, the fix is simple: Close the app, delete the `%LocalAppData%\TabularEditor3\layouts.json` file, then launch the app again.

**Comment by JFreddyPC** [comment]
Thanks otykier, works!
