### ISSUE TITLE
Semantic analysis: wrong error flagged when using EARLIER in a filter

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#118]
Hi,
With the following code on a calculated column:

```
    sumx(
        values( 'Table'[Col] )
        , [Measure]
        * CALCULATE(
            sum('Table2'[Col2])
            , keepfilters(Table2[Col2] <= EARLIER('Table'[Col]))
        )
    )   
```
There is a semantic error flagged (Only a single column can be used in a scalar predicate filter expression), which I believe should not be an error, given that the EARLIER is getting a scalar from the SUMX row context (and also the fact that it works ;)). If I remove the Table reference (i.e. I write EARLIER([col]), then the error dissapears, but a -column should be prefixed- warning appears.
Using 3.0.7

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
