### ISSUE TITLE
Model name changes with TE3 lost after datamodel refresh

### ISSUE THREAD

**Issue by alfgon** [TabularEditor/TabularEditor3#1181]
### Description

I am suffering a behaviour that I am not sure if it is a bug or the expected behaviour. 

 
These are the steps I follow:
 

1) Open PBI Desktop (Version Novembre 2013) Save a pbix as pbip

2) Open model from Tabular Editor 3 desktop (version 3.12)

3) Rename several object names using TE3 (I prefer do it instead of using PBI). I have also added descriptions

4) Save changes from TE3

At that point changes done are visible on PBI desktop as expected
 
Therefore I refresh the model (ths one is connected to a Power BI dataflow) and all names changes are lost (but rest of changes applied from TE3, e.g: descriptions) not

It sounds me as a bug but not sure where proble

### Tabular Editor 3 Version

3.12

### Windows Version

10

**Comment by otykier** [comment]
Hi @alfgon 
What type of objects did you lose the name changes for? Please note that [Power BI Desktop specifically **does not** support editing tables (including their names) through 3rd party tools](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations).

If you often have the need to make name changes through Tabular Editor, a better option is to use [Power BI Desktop's Developer Mode feature](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-overview) which supports [3rd party tools editing the Model.bim file within the PBIP project folder](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-overview#model-authoring).

Closing the ticket, but feel free to reopen if you or create a new ticket if you face any other issues.

**Comment by alfgon** [comment]
Hi Daniel,

You are right. I saw now that on the documentation

[image: image.png]

What confused me is that I enabled the option mentioned here, which
provided me the capability to rename the table columns... As I can see this
change is lost once the model is refreshed on PBI Desktop because Microsoft
probably does not support such a change.

Thx

Alfons
