### ISSUE TITLE
START AT not supported

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#1182]
Looks like START AT keyword throws an error in TE3 but works in DAX Studio.
![START AT](https://github.com/TabularEditor/TabularEditor/assets/73054674/37fe11be-cfdc-4b47-8224-8febc48b55cb)

**Comment by otykier** [comment]
Hi @SharmaAntriksh 
Looks like we have a bug in our query row limiter, when a query includes the `START AT` syntax. You can work around this limitation by setting the "Row limit" setting to 0 under **Tools > Preferences > Data Browsing > DAX Query**:

<img width="423" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/8976200/49b20fba-e82a-4849-a357-a15283b0d8ce">

**Comment by otykier** [comment]
This is now fixed in [3.14.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.14.0). Thanks for reporting!
