### ISSUE TITLE
TE Crashes when querying with DEFINE & MEASURE

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#1183]
### Description

When querying the model with DEFINE & MEASURE application crashes, specially when defining second measure or when the MEASURE & DEFINE are not on the same line, here is a video:

https://github.com/TabularEditor/TabularEditor3/assets/73054674/4e4dd672-1757-4242-b32f-8569f68dbd4e

### Tabular Editor 3 Version

3.12.0.26765

**Comment by otykier** [comment]
Could you send the full stack trace, please? (Click on "View error report" in the crash dialog)

**Comment by otykier** [comment]
Never mind the previous comment - we have found the root cause of this issue and will provide a fix asap.

**Comment by otykier** [comment]
We now have a hotfix available which fixes this issue: [v. 3.12.1](https://docs.tabulareditor.com/te3/other/release-notes/3_12_1.html?tabs=downloads). Thanks for reporting!
