### ISSUE TITLE
What's New tab breaking captured layouts, Expression Editor

### ISSUE THREAD

**Issue by joe-smith-powerbi** [TabularEditor/TabularEditor3#1189]
### Description

After installing 3.12.0 (issue persists in 3/12/1), the What's New tab appears on open, with no Expression Editor tab. I closed this tab, and selected my captured layout from Window menu; my captured layout appears, the What's New tab is re-opened, and the Expression Editor is no longer visible. Window list shows Expression Editor tab as open, but it is not visible on page.  Also, using File -> New list also shows tabs open, but none are visible except What's New. Window -> Reset Window Layout re-opened the Expression Editor and What's New tab.  

### Tabular Editor 3 Version

3.12.1

### Screenshots

TE3 on open: ![image](https://github.com/TabularEditor/TabularEditor3/assets/103209268/acac8011-e7aa-4172-a3e1-f3e0479efda8)
TE3 on open Window List: 
![image](https://github.com/TabularEditor/TabularEditor3/assets/103209268/bc84c5bf-7625-4522-ac0f-36c950d9c3dc)
After selecting "My Workspace": 
![image](https://github.com/TabularEditor/TabularEditor3/assets/103209268/6bec9b54-c123-4d96-8920-0c323dcb5784)

### Steps to Reproduce

It should be noted I am running a super-ultrawide monitor, with non-standard resolution. I mention this because the Expression Editor tab shows as open in the Window list, but does not appear anywhere on my desktop; I have seen this behavior in other applications, and usually means the window/menu/control has opened in a new window with an X/Y location outside the bounds of my desktop. However, these windows usually show up in the Windows Open Task view, and I see none for the Expression Editor in this situation. 

My Workspace.xml (my layout file)
[My Workspace.xml.txt](https://github.com/TabularEditor/TabularEditor3/files/13548948/My.Workspace.xml.txt)

### Expected behavior

What's New tab should not affect existing layout presets, and should not prevent the Expression Editor tab from appearing.

### Windows Version

Windows 11

**Comment by otykier** [comment]
Just to clarify, are you also seeing this issue after recreating your preferred window layout by starting from either the Default or Classic layout?

**Comment by joe-smith-powerbi** [comment]
@otykier No, I don't believe so. If I select Reset Window Layout and close either Expression Editor tab or What's New tab, then selecting Default or Classic layouts bring back both tabs. However, I was messing with the layouts a lot when I first experienced this issue, so I can't guarantee the Default or Classic layouts are the original defaults. I will uninstall/reinstall to get back to the defaults, and see if the issue persists.

**Comment by joe-smith-powerbi** [comment]
@otykier Uninstall/reinstall completed, issue does not persist. Must've been environmental. Thanks!
