### ISSUE TITLE
TE3 latest version: Find and Replace not working

### ISSUE THREAD

**Issue by antonycatella** [TabularEditor/TabularEditor3#1192]
### Description

I upgraded to the latest version today. Opened TE3 from within Power BI Desktop. Duplicated 4 measures. DAX Scripted out the 4 duplicate measures. Then tried to use Find and Replace to replace 'USD-copy' for 'EUR' text in the scripted measures. TE3 then crashed. I closed the pbix file and reopened TE3 and followed the above steps but the Find and Replace does not do anything when I click Replace All

### Tabular Editor 3 Version

3.12.1.25781

### Steps to Reproduce

1. I upgraded to the latest version today
2. Opened TE3 from within Power BI Desktop
3. Duplicated 4 measures from the local model
4. DAX Scripted out the 4 duplicate measures
5. Then tried to use Find and Replace to replace 'USD-copy' for 'EUR' text in the scripted measures by pressing Replace All

### Expected behavior

I expected the text in the DAX script to be replaced

### Crash Report

No crash report appeared

### Windows Version

Windows 11

**Comment by otykier** [comment]
As we are not able to reproduce the behavior you describe, could you provide some screenshots or a short recording to demonstrate this issue? Thank you!

**Comment by antonycatella** [comment]
Daniel, I cannot reproduce the issue again so will close the issue

**Comment by otykier** [comment]
Thanks for the update. Don't hesitate to reopen the ticket if the issue occurs again, thanks!
