### ISSUE TITLE
Unable to edit Dax Expression for Calculated tables

### ISSUE THREAD

**Issue by qureshq** [TabularEditor/TabularEditor3#120]
I am unable to edit the dax expression for my Calculated tables and make changes to it in TE3, how do i do that?

**Comment by otykier** [comment]
Power BI Desktop [does not support making changes to calculated tables through external tools](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations), so Tabular Editor blocks this by default. You can override this under Tools > Preferences… > Allow unsupported editing, but you risk breaking your pbix file.

**Comment by otykier** [comment]
@qureshq did you get the answer you needed? Can we close this issue?

**Comment by qureshq** [comment]
Yes I did thank you.
