### ISSUE TITLE
Error when attempting to save Macro

### ISSUE THREAD

**Issue by Kealkil4** [TabularEditor/TabularEditor3#121]
I am getting a C# script error when attempting to save a script as a Macro.

I had copied the details from a Github example ... so I must be doing something wrong.

Apologies!

![image](https://user-images.githubusercontent.com/32125650/124386308-b81b3b00-dcd1-11eb-942b-b188514b9ebb.png)

**Comment by otykier** [comment]
The FormatDax(<string>) function has been removed. Please see this: https://docs.tabulareditor.com/FormatDax.html

**Comment by Kealkil4** [comment]
Sorted.  Thank you.
