### ISSUE TITLE
Rename a field from a calculated table without DAX

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#1215]
### Description

this is possible in PBI Desktop but not in TE3
If I add an extra column to a field parameter table, i can rename it in the field pane of PBID, but the option is greyed out in TE3

### Tabular Editor 3 Version

3.0.11

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/40455069/4cd47160-8efd-43ce-9963-cc96f7548293)
![image](https://github.com/TabularEditor/TabularEditor3/assets/40455069/fdafb68f-a983-4050-aa26-4a2cf6c3aa0c)
![image](https://github.com/TabularEditor/TabularEditor3/assets/40455069/e617669e-115f-4d10-832c-65bc88fa297b)

### Windows Version

10

**Comment by mlonsk** [comment]
Hi @bernatagulloesbrina 
Thanks for reporting, we are looking into it

**Comment by mlonsk** [comment]
Hi @bernatagulloesbrina 
We have determined that this is not a bug. The property "Name Infered" needs to be set to false for you to change names on columns in calculated columns. (See screenshots bellow)
This actually applies to all calculated tables not just Field Parameters.
In the same way you also need to set Data Type Infered to false if you want to change the data type for the column. 
![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/8ec80962-b91e-4c89-b30d-38b63409da7a)

**Comment by bernatagulloesbrina** [comment]
Oh!
Wasn't aware of this one.
Thank you!

El dl., 8 de gen. 2024, 14:19, Morten Lønskov ***@***.***> va
escriure:
