### ISSUE TITLE
TOM doesn't show Calculation Item in error state when the expression is invalid

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1217]
### Description

I entered a long expression into a Calculation Item, but missed a closing parenthesis. Long SWITCH() statement. I saved it and the TOM looked ok. Refreshed the viz on the thin report (model in service) and got a gray box. 

Note that the DAX Formatter feature does recognize the expression is invalid, but even though this is saved, the TOM shows it is ok.

### Tabular Editor 3 Version

3.13.0

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/2ebff9fa-d63d-4e7c-a5a9-da863e1294ca)

### Steps to Reproduce

Create a calculation item with an invalid expression, save the model and recalc the Calculation Group if necessary in the service, then try and format the expression. It won't format because it isn't valid, but the TOM shows it is ok.

### Windows Version

10

**Comment by mlonsk** [comment]
Hi @edhans 

This is confirmed as a bug. Thank you for reporting, we will keep you updated when we have a timeline to share.

**Comment by otykier** [comment]
This is now fixed in [3.14.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.14.0). Thanks for reporting!
