### ISSUE TITLE
Error - A measure reference has been used in a scalar predicate filter expression.

### ISSUE THREAD

**Issue by gerhardvdw65** [TabularEditor/TabularEditor3#122]
I have searched the issues, but could not find a reference to the error that I am receiving.  The measures worked previously as currently defined.  So it would seem that after upgrade to V 3.0.7, I get this message.

The measure definition in the attached file.  I also can't seem to find any information on this error.

![Tabular Editor 3-0-7 error](https://user-images.githubusercontent.com/15626119/124422634-e184a700-dd63-11eb-8851-f9beda701a0f.jpg)

**Comment by marcosqlbi** [comment]
Not related to the syntax issues discussed (possibly a bug), but KEEPFILTERS is either useless or not providing the expected outcome.

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
