### ISSUE TITLE
Command line Options reference?

### ISSUE THREAD

**Issue by speedmind** [TabularEditor/TabularEditor3#123]
I'm considering the use of TE3 for a project, but so far I've not been able to use the same features from a command line as for TE2 as described in the documentation [Command line Options](https://docs.tabulareditor.com/Command-line-Options.html).

I'm using the portable version of TE3 but so far I've not been able to invoke it using a similar approach to TE2:

`start /wait TabularEditor.exe /?
`
or
`$p = Start-Process -filePath TabularEditor.exe -Wait -NoNewWindow -PassThru -ArgumentList "/?"
`

Both methods (command line & PowerShell) throw an Unexpected exception upon GUI startup, which is not the expected behavior.

I've also looked in the roadmap for TE3 and I've not seen anything regarding command line options.

So the ultimate question is. Is this a bug with the current release (latest as of now using 3.0.7 with trial license) or just something that's not enabled in TE3? If it's the latter can this aspect be added to the roadmap?

Thx in advance,
Vas.

**Comment by otykier** [comment]
Hi @speedmind.

TE3 does not support the command line syntax yet. There will be a separate .exe for use with the command line, with a much smaller footprint than the current TE3 executable (this is mentioned on the [roadmap](https://github.com/TabularEditor/TabularEditor3/issues/12) as "Standalone CLI application").

For the time being, please use TE2 for any command line requirements, as it is fully compatible with the file formats used by TE3.

**Comment by speedmind** [comment]
Hi @otykier and thanks for the prompt response.

Sorry I missed the CLI reference in the roadmap.
If you're looking for beta testers let me know ;-)

Thx again,
Vas.

**Comment by rvgfox** [comment]
Hi @otykier  I've a similar Issue with TE2. I've a C# script that works ok using the GUI but I'm not be able to execute it using this power shell script:

```
# Definir los valores de los parámetros
$ServerName = "My Azure AS"
$DatabaseName = "my DB"
$UserName = "my user"
$PasswordFile = "C:\SYSTEM\UCCE\MyPassword.xml"
$ScriptType ="Csharp"
$ScriptPath = "C:\SYSTEM\UCCE\SetCustomdataRLS.csx"
$TabularEditorPath = "C:\Program Files (x86)\Tabular Editor"
$LogFilePath = "C:\SYSTEM\UCCE\TabularEditorLog.txt"


# Obtener la contraseña del archivo cifrado
$SecurePassword = Get-Content $PasswordFile | ConvertTo-SecureString

$Password = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword))

# Crear una cadena de conexión para conectarse a Azure Analysis Services
$ConnectionString = "Provider=MSOLAP;Data Source=$ServerName;Initial Catalog=$DatabaseName;User ID=$UserName;Password=$Password;"


& "$TabularEditorPath\TabularEditor.exe" $ConnectionString -S $ScriptPath
```

Can you help me?
Thanks in advance
