### ISSUE TITLE
Ignore lineage tags option doesn't stay selected

### ISSUE THREAD

**Issue by philip-charbonneau** [TabularEditor/TabularEditor3#1245]
### Description

When I select the option 'Ignore lineage tags' from TE3 preferences (Tools --> Preferences --> File Formats --> General), it always reverts back to not being selected.

### Tabular Editor 3 Version

3.14.0

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/71849131/bc8f61ea-27cd-4572-a2be-895361d42b05)

### Steps to Reproduce

1. Go to Tools --> Preferences --> File Formats --> General
2. Click on 'Ignore lineage tags'
3. Click on 'OK'
4. Go to Tools --> Preferences --> File Formats --> General
5. The option 'Ignore lineage tags' is no longer selected

### Expected behavior

The option 'Ignore lineage tags' is selected

### Windows Version

Windows 10

**Comment by otykier** [comment]
Thanks for reporting this. As a workaround, until we get this fixed, open the `%localappdata%\TabularEditor3\Preferences.json` file in a text editor, and manually change the IgnoreLineageTags property to "true" as shown below:

![image](https://github.com/TabularEditor/TabularEditor3/assets/8976200/cf013fac-392c-4408-a428-5392587ded2e)

**Comment by otykier** [comment]
Hi @philip-charbonneau 
Just letting you know, that our [latest Tabular Editor 3 release](https://docs.tabulareditor.com/te3/other/release-notes/3_15_0.html?tabs=downloads) fixes this issue.
