### ISSUE TITLE
Update table schema is not available for a model with CL 1200

### ISSUE THREAD

**Issue by samusaran** [TabularEditor/TabularEditor3#125]
I have a couple of Tabular Models, but on models with legacy datasources (compatibility 1200) I can't see the feature at all, while I can on M Data Sources (1400).

Is it a bug or the feature is not available at all for legacy sources?

**Comment by otykier** [comment]
Support for schema updates on Legacy Data Sources against relational data sources is on the backlog (coming very soon).

**Comment by otykier** [comment]
Update table schema now works for legach data sources as of version [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
