### ISSUE TITLE
Hierarchies not showing in TE3

### ISSUE THREAD

**Issue by Anonymous-mojo** [TabularEditor/TabularEditor3#1254]
### Description

Below is a screen snip showing the same model in TE3 and TE2.  Hierarchies are not showing in TE3.

<img width="590" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/102637831/091ba688-9f84-4932-ba4b-f1734d4b8fc9">

### Tabular Editor 3 Version

3.14.0.18176

### Screenshots

<img width="590" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/102637831/c0bcb55f-6ad7-4754-96d4-4441bd988522">

### Steps to Reproduce

Create a hierarchy in TE3.  Try to view it in the model explorer

### Expected behavior

Hierarchies should (and used to) appear in the model explorer

### Windows Version

Windows 10 Enterprise

**Comment by DBojsen** [comment]
Hi @Anonymous-mojo 

Please click the only deselected button above the TOM Explorer and your hierarchies should be back. 

/ David

**Comment by Anonymous-mojo** [comment]
I'm an idiot...thank you

**Comment by DBojsen** [comment]
You are not the first to deselect something up there by accident.
