### ISSUE TITLE
Can't open XMLA dataset

### ISSUE THREAD

**Issue by Kaspars77** [TabularEditor/TabularEditor3#1264]
### Description

There was dataset "CR_dataset_heise".
Created copy as "CR_dataset_heise_test", modified it.
From Tablar Editor made "Deploy" and owerwrite "CR_dataset_heise".
Now i can't open "CR_dataset_heise". Shows error message:

### Tabular Editor 3 Version

3.11.0.26496

### Screenshots

![1](https://github.com/TabularEditor/TabularEditor3/assets/163521270/8acb84c8-c3f7-4fb7-a57a-a591cf709e37)
![2](https://github.com/TabularEditor/TabularEditor3/assets/163521270/479bc584-d195-4d4f-8194-07b149b64ece)

### Windows Version

Windows 11

**Comment by Kaspars77** [comment]
Dataset CR_dataset_heise refreshes normal, report works fine. Just can't open

**Comment by otykier** [comment]
Have you reported this issue to Microsoft? The error message shown is an internal Power BI error, so unfortunately not something we can assist you with.

**Comment by mlonsk** [comment]
As this is an Power Bi service issue, I will respectfully close the issue.
