### ISSUE TITLE
Visuals break if you edit any of their field names in TE3

### ISSUE THREAD

**Issue by nexus150** [TabularEditor/TabularEditor3#1265]
### Description

If you are working with TE3 connected to a Power BI Desktop model, and you change the name of any table/column or measure that is in any visual, then the visual breaks immediately. Months ago Power BI Desktop detected that change and adjusted the visuals as if the change had been in Power BI Desktop itself.  This leads to basic users who use TE3 for your DAX editor and to run simple C# scipts with local models, not being able to use the tool to make model changes with confidence (manually or through scripts), the problem is occurring with both PBIP and PBIX Files.

### Tabular Editor 3 Version

3.14.0

### Steps to Reproduce

1) Open a PBIX file with Power BI Desktop
2) Open TE3 from "External tool" Tabs
3) Change the name of any measure that is in any visual ( o Table/column name )
4) Save the model back
5) all the visuals that had that field are broken

### Expected behavior

The idea would be that after making a model change the adjustments to the visuals would be automatic just as if the change were being made with Power BI Destop.

### Windows Version

11

**Comment by DBojsen** [comment]
Hi @nexus150 

Changes to tables are not supported by Microsoft - see more here: https://docs.tabulareditor.com/te3/desktop-limitations.html?tabs=postjune2023#data-modeling-operations.

As for Power BI Desktop functionality that used to work and now doesn't, you'll have to create a support ticket with Microsoft.  That is unfortunately not something we can fix.

We (as an external tool) are not able to change anything related to the reports/visuals - only changes to the data model is supported for external tools - and everything related to the reports and visuals is only for Power BI Desktop to fix.

/ David - TE3 Support
