### ISSUE TITLE
Save model bim backup here

### ISSUE THREAD

**Issue by Klimkiv** [TabularEditor/TabularEditor3#127]
Where is this deployment option 'save model bim back up here' in te3?

And one more
If i totally commented script in detail rows expression then measure would get error red mark

And 
Sometimes Ctrl + Z works strange
In te 2 Ctrl + Z works without problems

**Comment by otykier** [comment]
> Where is this deployment option 'save model bim back up here' in te3?

See #37

> If i totally commented script in detail rows expression then measure would get error red mark

Thanks for reporting - that's a bug.

> Sometimes Ctrl + Z works strange

Could you elaborate on this? Thanks!

(PS: Going forward, please create separate issue posts if you have multiple unrelated questions/issues, as this makes it easier to track)

**Comment by otykier** [comment]
"Save backup" option will be available with 3.0.8 (Tools > Preferences > Model Deployment). Detail rows expression issue also fixed in 3.0.8.
