### ISSUE TITLE
Not able to see the Format String Expression option in some models

### ISSUE THREAD

**Issue by JanaVH** [TabularEditor/TabularEditor3#1273]
### Description

I am not able to change the format expression on any of the measures in my model.
I don't see the option "format string expression" in the property navigation dropdown, nor in the properties-Options-Format String Expression.
I tried both connecting to the model from folder and connecting to the model from DB.

I tried it with other models and there I do see the options, so it's somehow related to my model.

### Tabular Editor 3 Version

3.14.0.18176

### Screenshots

<img width="233" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/165798759/c41bf586-7c09-4ce5-b582-075627d7cbc6">
<img width="344" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/165798759/07c8a588-34c2-429e-bfef-bc6f6b766ab1">

### Windows Version

Windows 10 Enterprise

**Comment by otykier** [comment]
As can be seen on [Microsoft's docs for Measure Format String Definitions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.measure.formatstringdefinition?view=analysisservices-dotnet#microsoft-analysisservices-tabular-measure-formatstringdefinition), the property is only available on models at compatibility level 1601 or higher. Please ensure your model is at this compatibility level or upgrade accordingly.
