### ISSUE TITLE
Show Time (HH:MM:SS) for datetime data types in Table Preview 

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#1282]
**Description**
Please provide a clear and concise description of your issue here:
The Data Preview feature does not show DateTime values correctly when a Format string has not been specified:

**Tabular Editor 3 Version**
Please provide the version of Tabular Editor 3 (3.X.Y)
3.14.0

**Steps to Reproduce**
Please describe how to reproduce your issue.
1. Ensure DateTime column does not have a format string set
2. Preview Data of the table with a DateTime column.
3. The DateTime column does not have HH:MM:SS shown
**Screenshots**
Please provide one or more screenshots or GIFs that show the issue.
![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/feb081cc-f282-490f-a7d7-ec126cf573aa)

**Expected behavior**
Tabular Editor should display the values correctly if they have Time values included in the DateTime column.

**Comment by otykier** [comment]
As of [3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads) DateTime values are now shown using the long format, which includes seconds, in the table preview. This is when the column does not have an explicit format string assigned.
