### ISSUE TITLE
Show Seconds (HH:MM:SS) for datetime data types in DAX Query Results

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#1283]
**Description**
Please provide a clear and concise description of your issue here:
The DAX Query result pane does not show the seconds for DateTime values:

**Tabular Editor 3 Version**
Please provide the version of Tabular Editor 3 (3.X.Y)
3.14.0

**Steps to Reproduce**
Please describe how to reproduce your issue.
1. Open DAX Query window
2. Run Evaluate [TableName] against a table which contains a column with DateTime values
3. The results is shown without the Seconds regardless of format string has been set or not.

**Screenshots**
Please provide one or more screenshots or GIFs that show the issue.
![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/c15261a3-2b22-4a2f-b470-2b3b2994ab69)

**Expected behavior**
The DAX Query view should display the full HH:MM:SS datetime value

**Windows Version**
The version of Windows Tabular Editor is running on e.g. 10/11
Windows 11

**Comment by otykier** [comment]
DAX query results now also use the long format for DateTime values (as of [3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads)).
