### ISSUE TITLE
DAX Optimizer Integration with Group License

### ISSUE THREAD

**Issue by rmss-tech** [TabularEditor/TabularEditor3#1288]
### Description

Excited to try new preview integration of DAX Optimizer in Tabular Editor 3 (TE3).  Unfortunately, I cannot access the DAX Optimizer license under the Group and associated models

Sign in: **Microsoft Work Account**
The DAX Optimizer Account visible is my account and not the Group that I administer.  The DAX Optimizer license key is associated to the Group as well as the models that I wish to upload and analyze.

The TE3 interface (Options dropdown) shows the contract associated to the Group, but the workspace and models associated to the group is not visible in their dropdowns.  I have no models or license under my individual section of DAX Optimizer login. 

### Tabular Editor 3 Version

3.15.0

### Screenshots

<img width="159" alt="TE3_Support-DAXOptimizer_OptionsDropdown_2024-05-01" src="https://github.com/TabularEditor/TabularEditor3/assets/73752209/732a0af8-2ba5-4d8e-b9e7-36ee1c3753de">

### Steps to Reproduce

TE3 > DAX Optimizer (Preview)...
Try selecting workspace, model, etc and nothing expected is visible from DAX Optimizer Group

### Expected behavior

Expected that I could either choose to select the individual or Group and then the associated workspaces 

or

the Workspaces would list all prepended to workspaces name (e.g.: '@robs: My workspace', '@Group: My workspace')

### Windows Version

Windows 10 Enterprise 22H2

**Comment by otykier** [comment]
Thanks for reporting this. May I ask you to send an email to support@tabulareditor.com, as we need some more information about which DAX Optimizer account you’re using. Thank you!

**Comment by rmss-tech** [comment]
FYI - This is regarding the Microsoft Work Account ***@***.*** ***@***.***> that I use to log into DAX Optimizer.


Robert Solfest

**Comment by otykier** [comment]
[Tabular Editor 3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads) now lets you switch between DAX Optimizer accounts, including group licenses.
