### ISSUE TITLE
Field Parameter records messed up when measures are renamed

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1289]
### Description

When you create a field parameter that is comprised of measures, then rename measures, the record for the measure gets messed up. Extra characters are added to the beginning of the table with the measure name.
I renamed the [Direct Customer Returns] measure to [Direct/Loaner Customer Returns] and this happened:
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/ef57e437-5eec-4a15-a072-f510383dc2ea)

The table was prefixed with an extra 'Meas and the "), 3" as the 3rd parameter was removed.
Note that simple without special characters like the "/" being used also fail to work correctly.

Other renames in the model work fine - these measures were correctly renamed in other expressions. It is just the FP table.

### Tabular Editor 3 Version

3.15

### Screenshots

![FieldParameterRename](https://github.com/TabularEditor/TabularEditor3/assets/45298358/9be41beb-9ae1-447f-9f0e-c5ffd7d5eb12)

### Windows Version

10

**Comment by otykier** [comment]
Hi Ed.
Unfortunately, I was not able to reproduce this issue, even when attempting to replicate a field parameter containing measures with the same names as yours. Any chance you can send a model.bim or .pbit file to support@tabulareditor.com? In that case, we'd be happy to take a closer look.

**Comment by edhans** [comment]
I'm going to tentatively close this. I cannot get it to repeat, so closing TE/3 and reopening (from yesterday) has fixed it.

I wonder if this is somehow tied to when I search for things, it finds them, but doesn't always exactly highlight what I've looked for - it might be off a few chars, or off a line even. Closing/reopening fixes that too, and I've never had a consistent repro.
