### ISSUE TITLE
Unable to reference KPI Status in measure

### ISSUE THREAD

**Issue by jamhos** [TabularEditor/TabularEditor3#1296]
### Description

When testing a new measure in Power BI, I was able to reference the underlying (autogenerated) KPI "status" measure to do a count of entities that "passed" the KPI.

When moving this to Tabular Editor, syntax checks appear fine (although no intellisense), but when trying to deploy I get an "unexpected error" popup.

`An unexpected error occurred (file 'tmcalcengine.cpp', line 2967, function 'TMCalcEngine::HyperspaceDepInfoToIds').`

KPI DAX definition (works fine):
```
VAR x = [% Measure] / [_% Measure Goal]
RETURN
    IF(
        ISBLANK( x ),
        BLANK( ),
        IF( x < 0.9, -1, IF( x < 1, 0, 1 ) )
    )
```

Definition of measure causing the issue (works fine in Power BI):
```
COUNTX(
    FILTER(
        VALUES('Store Salesperson'[Store]),
        [_% Measure Status] >= 1 
    ),
    1
)
```

Thanks in advance! It has occurred to me that this might be supported only by Power BI but hoping not.

### Tabular Editor 3 Version

3.14.0

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/59585318/05f16844-bb50-4f87-9ee8-a39ca73cff6d)

### Steps to Reproduce

1. Create new measure (as per above DAX).
2. Attempt to save / deploy model.
3. Error occurs on deployment (either manual deployment to remove server, or automatically on save to workspace model).

### Expected behavior

Should work okay, same as Power BI.

### Crash Report

An unexpected error occurred (file 'tmcalcengine.cpp', line 2967, function 'TMCalcEngine::HyperspaceDepInfoToIds').

### Windows Version

Windows 11

**Comment by otykier** [comment]
Just to confirm, are you deploying this to the Power BI service through the XMLA endpoint? The error message you’re seeing is an internal message from the Analysis Services engine, and as such, I’m afraid there’s not much we can do from our side. Recommend you raise a support ticket with Microsoft.

**Comment by jamhos** [comment]
> Just to confirm, are you deploying this to the Power BI service through the XMLA endpoint? The error message you’re seeing is an internal message from the Analysis Services engine, and as such, I’m afraid there’s not much we can do from our side. Recommend you raise a support ticket with Microsoft.

Sorry, deploying to an on-premises SSAS instance (2019).

I thought it might be along those lines, maybe it's been fixed on their side in a newer version of SSAS.

Thanks anyway!
