### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#13]
Hi, I have a case of missing dependencies, which show properly on TE2 and not completely in TE3. Might be related (or not) to the wrongly-detected-as-incorect columns (issue #9, which does not affect TE2 either). 

Not sure how to give more details, I'd rather not publicly share the .bim file.

**Comment by otykier** [comment]
Would it be possible for you to send me the .bim file with some more details on which dependencies are missing? daniel@tabulareditor.com

**Comment by zenzeinet** [comment]
I've emailed you.

**Comment by otykier** [comment]
Fixed in [3.0.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.1). Thanks for reporting!
