### ISSUE TITLE
Unable to type square brackets on Canadian French keyboard

### ISSUE THREAD

**Issue by prdubois** [TabularEditor/TabularEditor3#1300]
### Description

When my keyboard is set up with the Canadian French (QWERTY) layout, I'm unable to type square brackets. This instead seems to trigger a shortcut that folds my code. Normally, to type a square bracket, I need to type Alt with the keys next to the letter P (the square bracket keys). In the standard English layout, the Alt key is not required. As I said, Alt seems to trigger the shortcut and it makes it basically impossible to write DAX code. I've never had this problem in any other application. I have attached the keyboard layout picture. Even more strange, when using the English layout, using the Alt key along with the square bracket key does not trigger the code folding shortcut.
![canadian_french](https://github.com/TabularEditor/TabularEditor3/assets/8712266/c781430a-9295-49d0-a076-239223e5f219)

### Tabular Editor 3 Version

3.15.0

**Comment by mlonsk** [comment]
Hi @prdubois 
I can certainly see how that is quite problematic. 
We will look into how we can fix it, but has a workaround you can find the bellow shortcut bindings under Preferences-> Keyboard and either reassign or remove the binding. This should fix the issue for you until we 

![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/48205754-9db0-4d32-b02c-30e0f05262a2)

![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/6accd8ad-5017-488b-af12-61b78cef93fc)

The reason it is happening now is that we introduced new shortcuts in 3.15.0, sorry for the inconvenience.

**Comment by mlonsk** [comment]
Hi again 
We have identified a different bug where reassigning these shortcuts does not overwrite the existing shortcut so the above mentioned workaround does not work for you. 

We are actively working on a fix that will come in our next release as we consider this a critical issue, but until we have that ready I would suggest downgrading to 3.14.0: [Download 3.14.0](https://docs.tabulareditor.com/te3/other/release-notes/3_14_0.html?tabs=downloads)

**Comment by prdubois** [comment]
I confirm that the bug is not present in 3.14.0. I'll use that for now, thanks.

**Comment by mlonsk** [comment]
Hi @prdubois 
This issue has been fixed in 3.16.0. where we have changed the shortcuts so they are no longer triggered this way. 
Thank you for making us aware of it and for your patience while we got it fixed.
