### ISSUE TITLE
Strange bug - Deploying multiple times multiplies the credential requests

### ISSUE THREAD

**Issue by samusaran** [TabularEditor/TabularEditor3#131]
This is a strange one.

If I edit a model.bim and then deploy the model (Model > Deploy...) the first time, everything is fine. I have 2 connections, and I get asked for 2 passwords.

But if after a while I deploy again, I get asked for 4 passwords.
If I deploy again right after, I get asked for 6.

It's not a big problem, mainly because the password gets saved so I can just spam Next, but that's a strange issue.

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
