### ISSUE TITLE
Known Issue in 3.16.0: Unable to open Diagram files

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#1313]
### Description

Tabular Editor 3.16.0 has a known bug that it is not possible to open saved diagram files (.te3diag)

As shown in the screenshot below, a dialog box will appear, claiming it is an unknown file type. 

We are treating this as a critical bug and will provide a few as soon as possible, most likely during the week starting Monday, the 17th of June. 

### Tabular Editor 3 Version

3.16.0

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/f78be269-2073-42cb-a7ae-696282ae1dcf)

### Steps to Reproduce

Go to File -> Open -> File
Choose a .te3diag file to open
Error message appears

### Windows Version

11

**Comment by otykier** [comment]
This issue has now been fixed in [3.16.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.16.1).
