### ISSUE TITLE
Pivot Grid Measure Format Not Matching Power BI Report

### ISSUE THREAD

**Issue by GMedlin** [TabularEditor/TabularEditor3#1314]
### Description

I noticed the format of a DAX measure doesn't always match between the Pivot Grid in TE3 and a Power BI report visual. In this cause, the measure's format string is #0.0%;(#0.0)%;"NM". NM should be displayed when the value is exactly 0, but I've confirmed the 0.0% values are actually just near-zero. The Pivot Grid version looks like the format being applied might only be taking into account the value of what's being displayed, rather than the underlying full value.

### Tabular Editor 3 Version

3.16.0

### Screenshots

![2024-06-14 09_01_47-Investor Data Mart (Power BI Desktop) (Import) - Tabular Editor 3 16 0 - Enterpr](https://github.com/TabularEditor/TabularEditor3/assets/13262106/2643bd2c-533d-4136-a316-db77faf0b294)

### Steps to Reproduce

Add a percentage measure with format #0.0%;(#0.0)%;"NM" to a Pivot Grid that includes near-zero values (0.00004, etc.) and add the same measure to a Power BI report visual (matrix in my example).

### Expected behavior

The displayed measure result should match between Power BI and the Pivot Grid.

### Windows Version

11

**Comment by otykier** [comment]
Hi @GMedlin 
Thanks for reporting this. Out of curiosity, could you try to connect an Excel PivotTable and let us know how that displays the near-zero values in this case? I’m asking because both Excel and TE3 use MDX to fetch the data, where as Power BI uses DAX. Thanks!

**Comment by GMedlin** [comment]
@otykier Ah gotcha. Yea I do see the same thing using analyze in Excel; it matched the TE3 Pivot Grid.

**Comment by mlonsk** [comment]
Hi @GMedlin 

Thank you for confirming, I am afraid that this is a built-in limitation of the Pivot Grid component.
