### ISSUE TITLE
Sort order in Pivot not maintained

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1318]
### Description

I am using an 8 digit integer for a date here. I want it descending with the latest data on top. When I click refresh though the Pivot grid removes my sort preference.

![PivotSort](https://github.com/TabularEditor/TabularEditor3/assets/45298358/0f740938-f5ee-41f9-824b-b145165cf655)

In the above image, the April 2024 data should remain on the top row, but after refreshing, it sorts so the April _2023_ data is at the top and puts it back in ascending order. 

### Tabular Editor 3 Version

3.16

### Windows Version

11

**Comment by otykier** [comment]
Good catch - thanks for reporting! We'll make sure to address this in our next update.

**Comment by otykier** [comment]
This is now also fixed in [3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads). Thanks again for reporting!
