### ISSUE TITLE
Issue when switching to DAX query from Pivot Grid tab

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1319]
### Description

When I switch from a Pivot Grid tab to a DAX query, none of the DAX query tool bar buttons are activated.

### Tabular Editor 3 Version

3.16

### Screenshots

![PivotToDaxQuery](https://github.com/TabularEditor/TabularEditor3/assets/45298358/4f975b9a-7b5b-46c5-9f65-a618d7e837e5)

### Steps to Reproduce

1. Open a DAX query view with a query, then a Pivot Grid view.
2. Refresh the Pivot.
3. Switch to the DAX query. The buttons are not active. You can click on the DAX query area and that does not fix it.
The fix is:

1. Refresh the pivot
2. Switch to DAX Query view
3. Click on the white area where the DAX query is
4. Click back to the pivot grid
5. Click back to the DAX query.
Now the DAX Query buttons work.

### Windows Version

11

**Comment by mlonsk** [comment]
Hi @edhans 
Thank you for reporting, I have reproduced this issue and we will look into getting it fixed.

**Comment by otykier** [comment]
Hi @edhans 
This is now fixed in [3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads). Thanks for reporting!
