### ISSUE TITLE
The VertiPaq Analyzer won't display the column cardinality

### ISSUE THREAD

**Issue by StEybert** [TabularEditor/TabularEditor3#1320]
### Description

For columns with the setting `Available In MDX = FALSE`, the column cardinality in the VertiPaq Analyzer is displayed as 0. This applies to both the Tables, Columns, and Relationships tabs.

### Tabular Editor 3 Version

3.16

### TABLES
![image](https://github.com/TabularEditor/TabularEditor3/assets/127849671/65bb0843-a08b-4631-b633-40237faff134)

### RELATIONSHIPS
![image](https://github.com/TabularEditor/TabularEditor3/assets/127849671/a3ab23f5-5359-4c35-9646-4cc1a52009d1)

### Steps to Reproduce

1. Flip the `Available In MDX` setting from `True` to `False`.
2. Open VertiPaq Analyzer and click "Collect stats".

### Expected behavior

DAX Studio shows the cardinality for all columns:
### TABLES
![image](https://github.com/TabularEditor/TabularEditor3/assets/127849671/f2b130c9-1584-489c-9f2a-86c80a6b98a8)

### RELATIONSHIPS
![image](https://github.com/TabularEditor/TabularEditor3/assets/127849671/d01984e0-9d6d-4585-8358-4ff423377962)

### Windows Version

11 23H2

**Comment by otykier** [comment]
Hi @StEybert 
You should be able to retrieve column cardinalities from columns with no attribute hierarchies (i.e. columns with IsAvailableInMdx = false) by enabling the **Read statistics from data** option under **Tools > Preferences > VertiPaq Analyzer**

![image](https://github.com/TabularEditor/TabularEditor3/assets/8976200/baf89ab1-25f5-4259-b046-f18a5e4f3f26)

**Comment by StEybert** [comment]
Thanks, @otykier! I didn't know that. Maybe it should be enabled by default, though?
