### ISSUE TITLE
Pop up to download appearing after download has happened

### ISSUE THREAD

**Issue by databayes** [TabularEditor/TabularEditor3#1321]
### Description

Pop up that new download is available still happens after download.
![image](https://github.com/TabularEditor/TabularEditor3/assets/87519321/6e6a006d-266e-4bc8-b7f1-a4d53fe230b2)

### Tabular Editor 3 Version

3.16.0

**Comment by mlonsk** [comment]
Hi @databayes 

Yes, because we just released 3.16.1 yesterday with a critical bug fix, so there is a newer version available 😊
