### ISSUE TITLE
Missing the Microsoft login dialog when connecting to AAS

### ISSUE THREAD

**Issue by MartinNordestgaard** [TabularEditor/TabularEditor3#1322]
### Description

Before upgrading to 3.16 (persists in 3.16.1) I used to get a login dialog/promt/MFA for Azure/Microsoft account, where I could select the user, that I would use to login to the model. This does not show anymore after the upgrade.

I have two MS accounts which I use. One for Dev-systems (as a admin) and one "admin" for test and production environments, which I'am not longer promted to use/select.
Due to the fact, that my dev account does not have admin rights on test- and production environments I get an error (see picture).

Is this a bug?

### Tabular Editor 3 Version

3.16/3.16.1

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/5088730/07c264b2-21bd-4004-b0df-2c9b6d09ae85)

### Steps to Reproduce

1. Open Model from DB
2. No dialog/promt box anymore
3. Automatically loggin in with my current user (linked to my "normal" MS account/PC)

### Expected behavior

Get login dialog where I can selected the right account for the seleced environment

### Windows Version

Windows 10 EE

**Comment by otykier** [comment]
Hi @MartinNordestgaard 

Can you confirm that the error is not present if you roll back to 3.15.0 (or whichever version you had before upgrading to 3.16.0)? 
I recommend downloading the portable version to test this: https://docs.tabulareditor.com/te3/other/release-notes/3_15_0.html?tabs=downloads

Thank you!

**Comment by MartinNordestgaard** [comment]
Hi @otykier. It works if I reinstall 3.15.0

**Comment by otykier** [comment]
Thanks for confirming.

We upgraded AMO/TOM to v. 19.80.0 in TE 3.16.0, and unfortunately we have been riddled with a lot of issues since :(
We're considering creating another hotfix (TE 3.16.2), which will go back to using AMO/TOM v. 19.79.1.1 for the time being.

**Comment by otykier** [comment]
Hi @MartinNordestgaard 

We have a new build ready where we've rolled back AMO/TOM to 19.79.1.1. This is the same version that we used in TE 3.15.0.

Could you give this new build a shot and see if this fixes the issue for you? Thanks!

Download options:

- [64 bit installer](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.Installer.x64.exe)
- [64 bit portable](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.x64.zip)
- [32 bit installer](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.Installer.x86.exe)
- [32 bit portable](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.x86.zip)
 
(Release notes identical to [3.16.1](https://docs.tabulareditor.com/te3/other/release-notes/3_16_1.html?tabs=downloads) with the addition that AMO/TOM has been downgraded to 19.79.1.1)

**Comment by MartinNordestgaard** [comment]
@otykier works perfect! Thank you guys!

**Comment by mlonsk** [comment]
Thank you for testing @MartinNordestgaard, it is much appreciated"

We have just released 3.16.2, and I am closing this issue.

**Comment by otykier** [comment]
Just an update on this. It seems that this behavior is here to stay in newer versions of the AMO/TOM client libraries, meaning that future versions of TE3 will not show the MFA popup, in some situations when an AAD/Entra ID account is already tied to Windows. However, the good news is that there is an easy way to force the MFA dialog to appear, in case you want to sign in using a different account.

In the connect dialog, *either* set **Authentication** to **Username and password** and specify the e-mail address of the account you with to use when connecting:

![image](https://github.com/user-attachments/assets/8a743e63-2c2d-4d24-b68a-98d73bd00294)

*alternatively*, specify a connection string that includes `User ID=<email>` in the **Server** property:

![image](https://github.com/user-attachments/assets/d7e50a9e-2983-40b7-a0a2-bd7b0bee1cbb)

For connections to AAS or Power BI / Fabric XMLA endpoints, the following is sufficient:

`Data Source=<servername>;User ID=<email>`

We'll make sure to document this once we release a new version of TE3 that includes the updated AMO/TOM client libraries.
