### ISSUE TITLE
Duplicated Save Icon for SSAS Tabular

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#1332]
### Description

When working with SSAS on premise TE3 shows 2 icons for saving.

### Tabular Editor 3 Version

3.16.2

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/73054674/08331b5d-f4cd-44f8-9f9d-8b29bd0a8207)

![image](https://github.com/TabularEditor/TabularEditor3/assets/73054674/c45fa447-7da4-4d99-849f-1d39d8321992)

### Expected behavior

Is there a reson for 2 save as because both of them have the same description

### Windows Version

Windows 10

**Comment by otykier** [comment]
Thanks for reporting. We’re aware of this issue and it will be addressed in our next release.

**Comment by otykier** [comment]
This is fixed in [3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads). Thanks again for reporting!
