### ISSUE TITLE
Macro Recorder duplicates the code generated

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#1335]
### Description

When using Macro Recorder if you change some property from the Properties pane then multiple lines of duplicated code are added.

### Tabular Editor 3 Version

3.16.2

### Screenshots

https://github.com/TabularEditor/TabularEditor3/assets/73054674/97df10c0-f47b-4acf-8749-d3a5c19bbcda

### Expected behavior

Only 1 line of each modification should be generated.

### Windows Version

Windows 10

**Comment by otykier** [comment]
Hi @SharmaAntriksh 
I have confirmed this as a bug. We'll make sure to get this fixed in our next update. Thanks for reporting!

**Comment by otykier** [comment]
This is fixed in [3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads). Thanks again for reporting!
