### ISSUE TITLE
Display folder properties - either a bug or design issue

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#134]
when you click on a display folder, the properties dialog box is actually for the first measure in the folder, so if you change the description, thinking you are adding additional info about what the folder contains, you are changing the description for the measure.
![image](https://user-images.githubusercontent.com/45298358/125973730-cc4e769e-92ed-4cc4-84b7-d92b5dfe05f7.png)

This is either a bug in that it is showing the properties for the wrong object, or a design issue, and selecting a display folder, if there are no other modifiable properties, should show nothing in the Properties section.

Ideally I'd like to be a able to add a description to a folder, but I know you are constrained by what the TOM allows, and I've no clue if that is possible.

**Comment by otykier** [comment]
This is a bug. The behaviour should be the same as in TE2, in which the Display Folder has a single editable property, which is its name.

**Comment by otykier** [comment]
[3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8)
