### ISSUE TITLE
Unable to update table schema

### ISSUE THREAD

**Issue by taur-us** [TabularEditor/TabularEditor3#1341]
### Description

Hi,

I am coming across an error when updating a table schema in TE3 Business Edition (latest version). The Power BI data saet is hosted in a PPU workspace, in the PBI admin portal under PPU > Dataset Workload Settings the XMLA Endpoint is set to "Read/Write". I also connect to the model from TE3 through the API using "Read/Write". The user used to connect has a PPU license and admin rights on the workspace the dataset resides in. I have also tried this on other users with the same rights, and the same error occurs. The error is as follows:

Unable to update table schema

Failed to save modifications to the server. Error returned: 'It looks like you can't make changes to this dataset. Please contact a capacity administrator to make sure XMLA read/write support is enabled in the capacity settings on the Power BI Premium capacity, and then try again. For additional information, see 'XMLA read/write support' in the product documentation.

Technical Details:
RootActivityId: 25a31e87-6745-4634-b187-cc554e2683d3
Date (UTC): 7/4/2024 12:44:16 AM
'.

TE3 Session ID: 99c7bd6f-716b-4953-917f-6cdd70289b87
TE3 Version: 3.14.0.18176

### Tabular Editor 3 Version

3.14.0.18176

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/93385619/34948750-1aab-4a7e-8586-a467067af4fa)

### Steps to Reproduce

Connect to PBI dataset in PPU capacity with XMLA Read/Write enabled, using admin user with PPU license.
Select Model > Update Schema on all tables.

### Expected behavior

Detect schema changes and present them in new window

### Windows Version

Edition	Windows Server 2022 Datacenter Version	21H2 Installed on	‎3/‎13/‎2024 OS build	20348.2527

**Comment by otykier** [comment]
Are you able to make other modifications to the model, or does this only happen when attempting to update the table schema? I.e. what happens if you add a measure to the model and then hit Save (Ctrl+S)?

Also, please note that Microsoft blocks 3rd party tools from making changes to *Default Models* through the XMLA endpoint.

**Comment by taur-us** [comment]
Hi Daniel,

Turns out the license for the workspace had been incorrectly changed to Fabric Free 60 day trial:
![image](https://github.com/TabularEditor/TabularEditor3/assets/93385619/6200577b-e38c-4d8c-b680-b9c8fa1fe67d)

Strangely enough the workspace still had the Premium Diamond icon next to it!

Closing ticket, thanks for your time.
