### ISSUE TITLE
Can't Import VPAX unless connected to a Model

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#1344]
### Description

TE3 Doesn't allow Importing VPAX unless it is connected to a Model, if someone sends their VPAX to me for review I can't review it unless I open a model and then load VPAX of a different model.

### Tabular Editor 3 Version

3.16.2

### Expected behavior

VPAX should be allowed to open even without connecting to a model as DAX Studio does, I guess?

### Windows Version

Windows 10

**Comment by MariaJoseFF** [comment]
Hi @SharmaAntriksh,

Thanks for your feedback. We were not able to reproduce this issue. Could you specify exactly the steps that triggered it? 

Do you happen to get an error message from Tabular Editor, or what does it prevent you from importing the VPAX file?

Kind regards,
Maria José
TE3 Support

**Comment by SharmaAntriksh** [comment]
The import button is actually disabled as you can see below:

https://github.com/TabularEditor/TabularEditor3/assets/73054674/f92579b6-a6ee-4357-b578-15f1a80eb027

**Comment by otykier** [comment]
The Import option is used when you want to import VPAX statistics to a model that’s already loaded in Tabular Editor. If you want to open a model from VPAX, you need to use the **File > Open > Model from File…** option (not available in [TE3 Desktop edition](https://docs.tabulareditor.com/te3/editions.html)).

**Comment by SharmaAntriksh** [comment]
@otykier Didn't get it, If I have a model loaded I can use "collect stats", then what would be the difference between collect stats and import? Useful only when collect stats option takes a lot of time?

**Comment by otykier** [comment]
Collect Stats is not available if you’re not connected to an instance of Analysis Services. I.e.: You don’t have admin access to a production environment, so you can’t connect Tabular Editor to that environment. Instead, you have access to the model metadata in a file (e.g. a model.bim file or a TMDL folder structure), and then you have a VPAX file extracted by someone else, or through DAX Studio.

**Comment by SharmaAntriksh** [comment]
Thanks for the explanation!
