### ISSUE TITLE
Data Refresh Duration for Multiple Tables Changes on Completion

### ISSUE THREAD

**Issue by EthanEverett** [TabularEditor/TabularEditor3#136]
When you kickoff a refresh for multiple tables/queries in TE3 the duration time counter shows the amount of time each table/query is taking or has taken if it has already completed. Once the refresh is completed though the counter for each table changes to the time duration of the table with the longest duration. You can see this behavior in the attached picture where the top set of highlighted table times have already completed but the lower set are actively running and the duration is different for each table. Is it possible for each table to retain its duration timing upon completion? That way it is easier to identify the table/query that is taking the longest to refresh in order to then focus on reducing its duration. This would also allow a user to duplicate a table, make changes to the query and see the potential timing impact from the change.

![TE3 Refresh Duration Timing Changes on Completion](https://user-images.githubusercontent.com/78923074/126011736-3c528120-3600-40cf-816a-f52e18babfce.PNG)

**Comment by otykier** [comment]
As of v. [3.7.0](https://docs.tabulareditor.com/te3/other/release-notes), we're no longer able to reproduce this issue. Therefore I'm closing this ticket, but please feel free to reopen, if you are still encountering this issue.
