### ISSUE TITLE
Cannot connect to DAX Optimizer

### ISSUE THREAD

**Issue by marcoseloso77** [TabularEditor/TabularEditor3#1361]
### Description

When I open the DAX Optimizer window, I cannot connect; when I press Options=>Connect, nothing happens.
A message appears in blue "Connection failed: To enable the embedded webview on Windows, reference Microsoft.Identity.Client.Desktop and call the extension method .WithWindowsEmbeddedBrowserSupport().

### Tabular Editor 3 Version

3.16.2

### Screenshots

![image](https://github.com/user-attachments/assets/33647e19-e5f2-4210-8bab-aff010970764)

### Windows Version

11

**Comment by otykier** [comment]
This is a known issue in 3.16.2. A fix is coming out next week.

**Comment by marcoseloso77** [comment]
Thank you very much!

**Comment by otykier** [comment]
Hi @marcoseloso77
Are you still seeing this issue in the latest version 3.17.1? https://docs.tabulareditor.com/te3/other/downloads.html

**Comment by otykier** [comment]
Hi @marcoseloso77 
Can we close this ticket, or are you still seeing this issue in the latest version ([3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html))?

**Comment by marcoseloso77** [comment]
Dear Daniel, not at all.
I think the problem is solved.
