### ISSUE TITLE
Model > Update schema (all tables) | Key conflict issue

### ISSUE THREAD

**Issue by taur-us** [TabularEditor/TabularEditor3#1362]
Hi Daniel,

I trust you are well. I am struggling to find the documentation on the Update Schema (all tables) menu option under Model. Can you please help me find these?

The reason I ask is I am experiencing an issue when trying to check and push schema changes to the XMLA endpoint. I use Snowflake connector and import mode model, after connecting to the model successfully, using the "Model >  Update Schema (all tables)" menu option to check for changes and the "Please wait - Detecting schema changes..." window completes, I am presented with a new dialogue "Unable to update table schema: An item with the same key has alreadyu been added. Key: <FieldName>.

![image](https://github.com/user-attachments/assets/fe4d7fa5-9d87-49cd-bdb7-1bd45c8546eb)

I have checked for the presence of duplicated columns in the same table, they do not exist in the Snowflake schema nor Tabular Model.

Thanks

Tom

**Comment by otykier** [comment]
@taur-us 
Thanks for reaching out. I'm transferring this issue to the TabularEditor3 repo, as it is unrelated to docs.

As a workaround, could you try to enable the **Use Analysis Services for change detection** option under **Tools > Preferences > Schema Compare**.

Also, it would be helpful if you could share the M query of one of the tables that fail to update the schema (please blank out any sensitive information in the query).

For reference, [here are the docs for the **Update table schema** feature](https://docs.tabulareditor.com/te3/tutorials/importing-tables.html#updating-table-schema).

**Comment by taur-us** [comment]
Hi Daniel,
 
I have resolved this, many thanks for linking the documentation.

I have another query however regarding the Update Schema (all tables) functionality. Some of my queries have a "Sorted Rows" Power Query step. For these queries created in Power BI (e.g. creating a table in M-language with a blank query) with a "Sorted Rows" step, the schema check does not identify any changes. However, for those queries from Snowflake with a "Sorted Rows" step, the schema check shows "Unknown Identifier 'Order.<SortDirection>'". Below is a screenshot of the dialogue window that appears:

![image](https://github.com/user-attachments/assets/02c92332-1626-4095-a283-d1f32619c2e2)

- 1. Binder - Snowflake table with no changes
- Date - Development - Snowflake table with "Sorted Rows" as the final step. This has the "Unknown Identifier 'Order.<SortDirection>'.

This dialogue window is titled "Apply Schema Changes", in my experience this window only appears when there are schema changes to be applied, otherwise another window appears stating that there are no schema changes to be applied. However, in this "Apply Schema Changes" you will note that the "OK" button is greyed out (as there are technically no changes to push to the XMLA endpoint. Is this the behaviour your expect to see?

I have tried to work around this Snowflake Sorting Rows issue by using a native Snowflake query (Date - Development (2)) and as you can see it does not detect the "Unknown Identifier 'Order.<SortDirection>', however this method is approximately 2x slower to refresh than the Power Query Sorted Rows approach, so ideally I want to avoid doing this. 

This nuance might seem remedial for most users, however as I have used Power Automate Desktop's UI Automation function (in lieu of an update schema API function of TE3), this particular behaviour is tricky to handle.

Many thanks for your ongoing support.

Tom

**Comment by otykier** [comment]
Could you share the M query of the 'Date - Development' table?

**Comment by taur-us** [comment]
Sure, here it is:

```
let
    _warehouseName = Client & "_WAREHOUSE",
    _roleName = Client & "_" & Access,
    _databaseName = Client & "_" & #"Database Name",
    _schemaName = "PUBLIC",
    Source = Snowflake.Databases(Server,_warehouseName,[Role=_roleName]),
    Database = Source{[Name=_databaseName,Kind="Database"]}[Data],
    Schema = Database{[Name=_schemaName,Kind="Schema"]}[Data],
    View = Schema{[Name="VWDIMDEVELOPMENTPERIOD",Kind="View"]}[Data],
    #"Sorted Rows" = Table.Sort(View,{{"ParentID", Order.Ascending}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Sorted Rows",{{"ParentID", Int64.Type}, {"Period ID", Int64.Type}, {"Lifespan - Binder", Int64.Type}, {"Lifespan - Risk Expiry", Int64.Type}, {"Lifespan - Claim Made", Int64.Type}, {"Lifespan - Risk Bdx", Int64.Type}, {"Lifespan - Claim Bdx", Int64.Type}, {"Lifespan - Risk Expiry or Claim Made", Int64.Type}, {"Lifespan - Risk Bdx or Claim", Int64.Type}, {"Lifespan - Today", Int64.Type}})
in
    #"Changed Type"
```

Note the first four lines after let are all prefixed with an underscore, it seems to be redacted in this message window

**Comment by otykier** [comment]
> Note the first four lines after let are all prefixed with an underscore, it seems to be redacted in this message window

GitHub uses [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github). I've wrapped your code in a set of triple-backticks (```), which now causes it to display properly :)

Thanks for sharing - we'll look into it. Most likely, this is an issue with our build-in M parser. The **Use Analysis Services for change detection** workaround suggested above, should still work though.

**Comment by otykier** [comment]
One more thing, @taur-us: Why do you want to sort the data in the first place? Sort order means nothing when importing data to a semantic model (with the only exception being very large tables, where the [sort order can impact compression efficiency](https://www.sqlbi.com/blog/marco/2012/03/19/investigating-on-xvelocity-vertipaq-column-size/)).

**Comment by otykier** [comment]
@taur-us just an update on this. We fixed the bug that caused the Update Table Schema feature to show **Unknown identifier 'Order.Ascending'**, so please go ahead and download our latest [release 3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads).

However, my previous comment still stands. There is no reason to perform the sort in your M expression - it will just slow down the refresh operation.

**Comment by taur-us** [comment]
Hi Daniel,

Thanks for the update I will check this out next week, much appreciated for the swift resolution! 

That is exactly the reason, wouldn't have been a deal breaker to have to remove the sort order as there are other things that are planned to improve the compression ratio of the model, but sorting was a minimal effort solution that provided some improvements.
