### ISSUE TITLE
Error on refresh partition (or table)

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#1364]
### Description

not sure if I'm doing anything wrong, but I'm trying to refresh a power query table / partition and I'm getting an instant error as in the screenshot 
![image](https://github.com/user-attachments/assets/96b25a5c-d443-4c33-8bcd-40f91ba8a743)

is this due to the fact that it comes from a shared expression ?? 
right click on table --> refresh works just fine in PBID

### Tabular Editor 3 Version

3.16.2

### Steps to Reproduce

right click on table --> refresh --> full refresh 
right click on partition --> refresh --> full refresh

### Expected behavior

good refresh

### Windows Version

11

**Comment by bernatagulloesbrina** [comment]
full error message:

Object	Description	Progress	Duration
Error	Invalid query syntax. A valid MDX or DAX query was expected.

**Comment by otykier** [comment]
Could you share the full configuration of your partition? Also, does refreshing through SSMS work, or does that result in the same error?

**Comment by bernatagulloesbrina** [comment]
Oh wait, it's because the model is local?

El dc., 14 d’ag. 2024, 15:38, Daniel Otykier ***@***.***> va
escriure:

**Comment by otykier** [comment]
If by "local" you mean running inside Power BI Desktop, then yes - it's not possible to perform refresh operations through external tools with Power BI Desktop.

**Comment by bernatagulloesbrina** [comment]
Sorry, my bad! No issue at all. But maybe a better error message would help

El dc., 14 d’ag. 2024, 16:35, Daniel Otykier ***@***.***> va
escriure:

**Comment by otykier** [comment]
A better solution would probably be that we prevent refresh operations entirely, when connected to a local PBI Desktop model. @mlonsk do you agree?

**Comment by mlonsk** [comment]
Yes, agreed that we should disable the ability to refresh Power BI Desktop models.

I have created a discussion to track this change: https://github.com/TabularEditor/TabularEditor3/discussions/1365 and will close this as an issue.

**Comment by mlonsk** [comment]
With Tabular Editor 3.19.0 it is no longer possible to refresh tables when using Tabular Editor as an external tool to Power BI Desktop
