### ISSUE TITLE
Unable to save a working C# script as a Macro

### ISSUE THREAD

**Issue by revanth-ar** [TabularEditor/TabularEditor3#1371]
### Description

I have a working C# script that won't save as a Macro in T3. I get the error message "Macro cannot be saved because the script contains one or more errors". The script runs fine when executed without saving as macro.

I narrowed the issue down to the `var numericColumnsnew` definition in the `UpdateNumericColumns()` function (line 183 to 185 in below code)

https://github.com/revanth-ar/T3-Scripts/blob/61f2a45b7edc989b0410fffde270104807460392/Script%20for%20creating%20Aggregated%20Measures%20for%20selected%20columns%20with%20bug.csx

Please let me know if this is a T3 bug or an issue with my code.

### Tabular Editor 3 Version

3.17.1

### Steps to Reproduce

Works when running the script on a table. Save as Macro button returns an error.

### Windows Version

Windows 11

**Comment by otykier** [comment]
Hi @revanth-ar 
I took the liberty to create a [PR in your repo](https://github.com/revanth-ar/T3-Scripts/pull/1) to address this issue. Hope this helps!

**Comment by revanth-ar** [comment]
Thanks, Daniel. I understand it now, and your fix works great.
