### ISSUE TITLE
VertiPaq Analyzer does not show RI violations on Relatinships tab

### ISSUE THREAD

**Issue by mario-octosgt** [TabularEditor/TabularEditor3#1381]
### Description

When using VertiPaq Analyzer to view metrics for a Power BI (sept 2024) model, the _RI Violations_ column on the _Tables_ tab correctly flags the dim tables with RI violations (tables on the _one_ side of a a relationship). However, when I go to the _Relationships_ tab, the _Missing Keys_, _Invalid Rows_ and _Sample Violations_ columns are always empty and do not show details for the RI violations.

### Tabular Editor 3 Version

3.17.1

### Screenshots

Current behavior in TE3:
![image](https://github.com/user-attachments/assets/827e1151-56b2-4311-9af9-487490ec8b32)
![image](https://github.com/user-attachments/assets/a090fe3f-3a21-4972-9a32-9c6bd1e42ecc)

Expected behavior (from DAX Studio):
![image](https://github.com/user-attachments/assets/63cc4621-e2c6-42a1-8c03-13e98e1b454b)
![image](https://github.com/user-attachments/assets/8a78342c-1092-4d13-a013-666a1dfed24b)

### Expected behavior

For every RI violation found by the VertiPaq analyzer, details on the corresponding violations should appear in the _Relationships_ tab, in the columns _Missing Keys_, _Invalid Rows_ and _Sample Violations_, under the corresponding fact tables (tables on the _many_ side of a relationship). When running VertiPaq analyzer on the same PBI model from DAX Studio, the information is show as expected.

### Windows Version

Windows 11 Pro 23H2

**Comment by otykier** [comment]
To enable the check for RI violations, please enable the **Read statistics from data** option under **Tools > Preferences > VertiPaq Analyzer**:

<img width="578" alt="image" src="https://github.com/user-attachments/assets/f8b1acb5-02a0-4dcc-8fc6-a847e89d24ed">

**Comment by mario-octosgt** [comment]
I was not aware that this behavior was governed by a specific option. After turning it on, it worked as expected. Maybe it would be helpful to have a message in the _Relationships_ tab when this option is turned off.
