### ISSUE TITLE
TE3 (3.17.1) - Installation issues.

### ISSUE THREAD

**Issue by CraigsterT** [TabularEditor/TabularEditor3#1382]
### Description

Hi Daniel, 
I seem to have encountered a real oddity while trying to install the update for TE2 (3.17.1). It sounds as though I am being asked to uninstall TE3 first. Is this correct. Needless to say, I have not got anywhere with things thus far. Could you let me know how to proceed please? Also, is this going to happen again. It's a bit of a pain to have to start uninstalling and then reinstalling things manually. Let me know when you can please.

This is the screen shot that I receive as soon as I open up the installer. 
![image](https://github.com/user-attachments/assets/38fb6e02-bd14-408a-b203-aa1fdfd62497)

Hope to hear from you soon. 
Regards,
Craig.

### Tabular Editor 3 Version

(3.17.1) almost.

### Screenshots

![image](https://github.com/user-attachments/assets/e5d0c999-6293-4ba3-b1e8-436c033b6532)

**Comment by otykier** [comment]
I think this can happen if you're trying to upgrade using a different platform (i.e. going from x64 to x86, .NET 6 to .NET 8, or vice versa). Going forward, we recommend x64 + .NET 8, so I encourage you to manually uninstall the previous installation, then install the x64/.NET 8 build. If you use the same build going forward, you should not hit this issue again.

I'm sorry for the inconvenience.

**Comment by mariussveen** [comment]
Hi,

Im having the same issue. My computer is pretty new, and I installed Tabular Editor in september, just going into tabulareditor.com and downloaded and installed x64 and did the same now and got the same error. So I think there is some issues here.

Marius

**Comment by edhans** [comment]
Same here. I was just going to wait for 3.18 and see if it fixes itself.

**Comment by mlonsk** [comment]
I have confirmed similar behavior when trying to install a new version. Clearly very annoying behavior and we are looking at fixing it in the next release.

**Comment by mlonsk** [comment]
This issue with the installer has been fixed in Tabular Editor 3.18.0
