### ISSUE TITLE
Can't access DAX Optimizer 

### ISSUE THREAD

**Issue by bdn008** [TabularEditor/TabularEditor3#1385]
### Description

Hello,
I have seen previous issues with the same subject line; however, I have waited for build 3.18 released today (Oct-31-2024), and see a new error or connection failed. 
In the previous version 3.17.1 I failed for a different reason. 

Note that I am logged in to https://www.daxoptimizer.com/account/ with my credentials but yet can't access Dax Optimizer. 

Please also see attached the screen sots from both recent versions and failures. 

### Tabular Editor 3 Version

3.18.0

### Screenshots

<img width="551" alt="2024-10-31 10_37_38-Tabular Editor 3 17 1 - Enterprise Edition" src="https://github.com/user-attachments/assets/f3836a15-9386-4de2-b45b-d9b481ac29fc">
<img width="556" alt="2024-10-31 10_44_08-Tabular Editor 3 18 0 - Enterprise Edition" src="https://github.com/user-attachments/assets/6e3234d7-f24d-440c-8830-cb34cdf464dd">

**Comment by otykier** [comment]
Are you able to access https://app.daxoptimizer.com with that account? If so, kindly send an e-mail to support@tabulareditor.com  and let us know what your Tabular Tools account e-mail or username is, so we can investigate further. Thank you!

**Comment by bdn008** [comment]
Just sent a detailed email to [support@tabulareditor.com](mailto:support@tabulareditor.com)

subject line 'Can't access DAX Optimizer #1385'

**Comment by otykier** [comment]
Thank you. As mentioned offline, the issue might be that your DAX Optimizer account does not yet have any active licenses assigned to it. Make sure to activate a license before connecting through Tabular Editor. [Here are the instructions](https://blog.tabulareditor.com/2024/10/31/free-dax-optimizer-access-in-tabular-editor-3/) on how to activate the DAX Optimizer license with the redemption code obtainable through TE3 (Enterprise Edition customers only).
