### ISSUE TITLE
Code Action Loop | Simplifiy 1-variable block <> Move constant aggregation to variable

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#1386]
### Description

the two code actions  _Simplifiy 1-variable block_ and  _Move constant aggregation to variable_ result in a  loop

### Tabular Editor 3 Version

3.18.0

### Screenshots

<img width="702" alt="image" src="https://github.com/user-attachments/assets/b50b81a4-d3d7-4616-a568-af709d4cb3dc">

### Expected behavior

no code action pops up anymore

**Comment by otykier** [comment]
Thanks for reporting this. While both refactorings are valid and both could be relevant in some cases, it probably makes sense to "downgrade" the "Simplify 1-variable block" from the **Readability** category to the **Rewrites** category. By doing this, we would no longer show the 3 dots under the `VAR` keyword, but the Code Action will still be available when placing the caret on the variable.

**Comment by otykier** [comment]
Hi @MarioMue13
This is fixed in [3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html?tabs=downloads). Thanks again for reporting!
