### ISSUE TITLE
New AOM library still causing issues. - "cannot obtain account information while trying to refresh the token"

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1387]
### Description

Using 3.18.0 I am getting the save fails, which I think is part of the new AMO/TOM library. For the last month or so I _think_ the 3.17 build I had was the custom build with the old AOM libraries, and never had an issue. Now I am getting this multiple times a day. The fix is almost always to just do the operation again (run query, save, etc). 

Where it is a problem is refreshing tables - they fail midway through more often. I've had to refresh tables using VS Code with the Power BI Studio addin, which isn't nearly as nice as using TE/3.

![image](https://github.com/user-attachments/assets/d12db00c-05a1-4288-93eb-d5416a99dc25)

### Tabular Editor 3 Version

3.18.0

### Windows Version

11

**Comment by otykier** [comment]
Hi Ed.
When connecting to the XMLA endpoint, did you try to use the new “Microsoft Entra MFA” authentication option?

**Comment by edhans** [comment]
Trying that now, but none of my connections offer that as an option for any of my saved BIM files. I have to delete the TMUO file and recreate it.

I'll see if it works any better. 

Is there a way to convert the TMUO files to use this vs the old method?

And if it is the preferred method, why isn't it the default for an ad-hoc connection to an XMLA endpoint? 
![image](https://github.com/user-attachments/assets/8bff87aa-04b1-40e0-9e00-db719162c91c)

I'll see how it goes for the next few hrs. Thanks.

**Comment by edhans** [comment]
4+ hrs later and no issues. Tentatively optimistic. 

It appears the key difference in the TMUO is this:

![image](https://github.com/user-attachments/assets/2460a120-2e97-4222-911b-10d9b6811a76)

Will adding the "user id" and email convert existing connections in the TMUO to Entra, or do I need to delete the TMUO and reconnect like I did for this model?

**Comment by otykier** [comment]
> Will adding the "user id" and email convert existing connections in the TMUO to Entra

Yes, this should do the trick!

We’re still evaluating the best option for which default setting to apply, possibly by remembering the auth setting per server. We’re also having a conversation with Microsoft as the token refresh issue is still a bug in newer versions of AMO/TOM, even though we managed to find this workaround.

**Comment by edhans** [comment]
Unfortunately, while it is much better, it still happens. This happened 22min into a refresh of a partition that normally takes 40min or so to refresh. 
![image](https://github.com/user-attachments/assets/ca837c18-c9aa-4e92-8cf0-f9eefdba73be)

This is the TMUO file, so this should be using the new connection method, correct?
![image](https://github.com/user-attachments/assets/f16c8f4e-e219-4d64-865c-8d98c062bda6)

**Comment by otykier** [comment]
Hi @edhans. Could you kindly try our newest build [3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html?tabs=downloads)? According to Microsoft, the "token refresh issue" should have been fixed in the newest AMO client library (v. 19.86.6), so I'm curious to hear if this fixes the issue for you. It should work regardless of whether you're using the **Integrated** or **Microsoft Entra MFA** authentication option.

**Comment by edhans** [comment]
Yes, installing today.

**Comment by edhans** [comment]
This seems to be better - I worked 2-3 days with 3.18.1 and haven't noticed this issue.

**Comment by mlonsk** [comment]
I will close this issue since it sounds like it has been fixed, but of course, reopen it if it shows itself again.
