### ISSUE TITLE
Diagram: <delete> key deletes the table from the model rather than remove it from the diagram view

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#139]
Hi,
Do a diagram, add  table T1, and then remove it.
If you then do "Add tables" to add T1 again, it does not show in the available tables to add.
Using 3.0.7

**EDIT**: Just realized that what the "delete" key does in the diagram view is to completely delete the table!  (rather than removing it from the diagram, which you do with right-click and then there's no bug).
I would suggest to change this behaviour - it is extremely dangerous and imho counterintuitive (a diagram view is not the place for DDL actions, but for relationship visualization).

(And by the way, if you delete it, and then "undo" the delete, you cannot add it back to the diagram).

I would recommend to please add a confirmation dialog for the deletion of objects, tables, partitions, etc - it can be very dangerous to unwillingly delete things. 

I'll leave this bug open, at least if you understand as I do that the "delete" key in a diagram view should remove the table from the diagram, not totally delete it.

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
