### ISSUE TITLE
Best Practice Analyzer issue

### ISSUE THREAD

**Issue by muhssamy** [TabularEditor/TabularEditor3#1396]
### Description

if i have 2 measures with the same definition

1. Formatted Measure
2. Non-Formatted Measure

the best practice analyzer will not detect them as duplicated

### Tabular Editor 3 Version

3.18.0

### Steps to Reproduce

i have those measures in my model

```
CALCULATE([# Transactions], 'Online Shipment Type'[Shipment Status ID] = 1)
```

```
CALCULATE(
        [# Transactions], 
        'Online Shipment Type'[Shipment Status ID] = 1		
)
```

### Expected behavior

they should be reported as duplicate

### Windows Version

10

**Comment by otykier** [comment]
Hi @muhssamy 
Kindly be aware that TE3 does not ship any Best Practice Analyzer rules out-of-the-box, and what you're describing is an issue with the rule, not with TE3 itself. From where have you gotten this rule?

**Comment by muhssamy** [comment]
![image](https://github.com/user-attachments/assets/25a94959-0c51-44f1-b38d-c67378674d14)

This is the Role

**Comment by DBojsen** [comment]
Hi @muhssamy 

You should create an issue in the repo where the rule is from, if it doesn't work as expected.
https://github.com/microsoft/Analysis-Services/tree/master/BestPracticeRules

**Comment by muhssamy** [comment]
thanks All
