### ISSUE TITLE
False 'A single value for column ... cannot be determined' error message

### ISSUE THREAD

**Issue by avatorl** [TabularEditor/TabularEditor3#140]
![TabularEditor3_2021-07-20_14-29-51 1](https://user-images.githubusercontent.com/59934292/126324083-fcc30f2e-16f0-4919-bfd1-30e22bae25de.png)

![TabularEditor3_2021-07-20_14-41-54 1](https://user-images.githubusercontent.com/59934292/126325847-895de886-a5f4-4a65-b750-d0fef96bb91b.png)

The issue can be reproduced in '29 01 - Static Ranking.pbix' file from [https://sql.bi/dax-229/](url)

Somehow related to the 'Product'[Rank in Category] calculated column. The problem disappears when this calculated column removed from the table.

'Product'[Rank in Category] =
RANKX ( 
    ALLEXCEPT ( 'Product', 'Product'[Category] ), 
    [Sales Amount] 
)

TE3 3.07

**Comment by otykier** [comment]
Fixed in [3.0.10](https://github.com/TabularEditor/TabularEditor3/releases/latest). Thanks for reporting!
