### ISSUE TITLE
Pivot Grid bug on date field

### ISSUE THREAD

**Issue by ManuelMendozaLevo** [TabularEditor/TabularEditor3#142]
So I'm having this bug where it shows crazy dates like year 19340. My calendar table only has dates from 2019 to 2021

![image](https://user-images.githubusercontent.com/72710475/126540900-15895f96-6290-48d9-a7ad-e013e817fe5f.png)

**Comment by otykier** [comment]
Should be fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Could you please check and let us know? Thanks!

**Comment by otykier** [comment]
@ManuelMendozaLevo could you check if this issue is still present in newer versions of TE3? Thanks!

**Comment by otykier** [comment]
@ManuelMendozaLevo any update on this? Are you still seeing this issue with newer versions of TE3?
