### ISSUE TITLE
Create "Measure Table" - feature request

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#147]
It would be nice if TE/3 could create a measure table. Normally I do it by using Enter Data, entering nothing and pressing OK, then add 1 measure, then deleting the [Column1] field that Enter Data added.

I've seen people create measure tables using empty Calculation Groups. That just seems wrong....

**Comment by marcosqlbi** [comment]
I don't like measure tables in general, but I see why people create an empty table for that.
But creating an empty calculation group for a measure table could be a good leading indicator for individuals with a high-risk appetite!

**Comment by otykier** [comment]
For an Analysis Services model you can simply right click on "Tables" and choose Create > Table (or hit Alt+5), and you'll have a table with no columns in which you can add your measures.

For a Power BI Desktop model I'm afraid adding a table through Tabular Editor (or any other external tools), is [not supported](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations).

For a Power BI model through the XMLA endpoint, we must provide an M query that returns an empty table (no columns, no rows). In this case we can use a simple C# script to create the table:

```csharp
var myMeasuresTable = Model.AddTable("My measures");
(myMeasuresTable.Partitions[0] as MPartition).Query = "let Source = #table({},{}) in Source";
```

Hope this helps!

**Comment by edhans** [comment]
It does indeed help @otykier - thanks!
