### ISSUE TITLE
Formatting applied in TE3 not fully reflected in PBI Desktop

### ISSUE THREAD

**Issue by l33smyth** [TabularEditor/TabularEditor3#149]
Not sure if I'm missing something, but is it a bug that PBI Desktop and TE3 don't seem to sync up in terms of formatting applied:

In TE3, I apply this formatting:
![image](https://user-images.githubusercontent.com/78022740/127208769-b11a8809-5870-4cdf-8925-985d7e590204.png)

But Power BI Desktop's model view never updates to reflect this:
![image](https://user-images.githubusercontent.com/78022740/127208825-9f5aa656-cb4c-41a1-a258-f5a08d86bbe2.png)
![image](https://user-images.githubusercontent.com/78022740/127209025-07e86062-3558-461a-9004-13464b5937bc.png)

Although in Report view, dropping these fields on to the canvas does present the formatting I'd set in TE3:
![image](https://user-images.githubusercontent.com/78022740/127209050-1cc80ff4-ce63-4ef6-94c0-6dbba8436fb8.png)

I'm using TE3 3.0.7 and Power BI Desktop 2.95.804.0 64-bit (July 2021), though I've noted that this seems to have been issues for a while, even since the open-source version of Tabular Editor.

thanks!

**Comment by l33smyth** [comment]
Further to that, I'm intending on using TE3 for most development work, but this is something that could cause confusion, especially if I should pass the Dataset PBIX file to another developer.

**Comment by samusaran** [comment]
Can confirm, it happened to me.

**Comment by otykier** [comment]
Editing column properties (such as the format string) is not currently among the [supported set of write operations for external tools against a Power BI Desktop model](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations). Please raise this as a[ request on the Microsoft Power BI forums](https://community.powerbi.com/) to gather attention.
