### ISSUE TITLE
Change license key

### ISSUE THREAD

**Issue by otykier** [TabularEditor/TabularEditor3#15]
In order to change your license key (for example for switching from an Evaluation License to a purchased license key):

1. Close Tabular Editor 3
2. Launch Registry Editor (Win+R and type "regedit")
3. Locate `Computer\HKEY_CURRENT_USER\SOFTWARE\Kapacity\Tabular Editor 3`
4. Delete `Activation`, `License` and `UserMail` (if present)
5. Restart Tabular Editor 3 - it will now prompt you for a key.

A future update will have an easier way to perform this.

**Comment by otykier** [comment]
**Update**: With [3.0.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.2) you can now change your license key from within the application itself:

Help > About Tabular Editor > Change license key...

![image](https://user-images.githubusercontent.com/8976200/120604527-70dd2880-c44d-11eb-8dbe-df935a525d38.png)

Note that for this to work, no model can be loaded in the interface, so restart Tabular Editor or use File > Close model first.

**Comment by bogdanluckygo** [comment]
Upgrading from 3.0.1 to 3.0.2 gives a "Maximum number of installations reached. It seems you have a valid license but the number of installations permitted by the lice(goes off screen here). Please contact our licensing team for more information." 

Tried reinstalling and reinstalling. Didn't work. Tried uninstalling and installing the 3.0.1 back again from the old install file. 

Going to try the registry method shown here next.

**Comment by bogdanluckygo** [comment]
Didn't work. Ended up buying an enterprise license. After doing that was able to log in, and to upgrade to 3.0.2. All good I guess.
