### ISSUE TITLE
When selecting AD Role Members, provide a way to use the Directory Object Picker

### ISSUE THREAD

**Issue by samusaran** [TabularEditor/TabularEditor3#152]
When creating roles based on AD Groups and Users, it's difficult to manually add object SIDs. 

It would be very useful if we could use the Directory Object Picker (as Visual Studio does) to easily add AD groups and users, or at least have a way to type the username and have a function like "check usernames" of the same dialog to have the SID automatically derived from that.

**Comment by otykier** [comment]
AD Object Picker dialog added in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8), when adding Windows AD Role Members. Thanks for suggesting!

**Comment by otykier** [comment]
**Update:** 3.0.8 was missing the DLL to interact with the Windows AD Object Picker. We just published [3.0.9](https://github.com/TabularEditor/TabularEditor3/releases/latest) which addresses this.
