### ISSUE TITLE
When copying a calculation group, new group is created with the same precedence number

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#156]
this causes an error, and must be manually modified. When new calculation groups are created by default they take the new highest precedence number (I think).  The same approach could be taken, even if user needs to modify this later. Not really a bug, but just a behaviour that may be perceived as one.

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
