### ISSUE TITLE
Deleted table appears again after processing the PBI model

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#157]
Step 1: Delete a table from PBI Model from within TE3 > Save the model

Step 2: Go to PBI and select 'Apply Changes' option

Step 3: Go Back to TE3 and refresh the model > the deleted table appears 

Video:

https://user-images.githubusercontent.com/73054674/127870299-f5bb8d43-11fe-4cf9-8973-0783118f811e.mp4

**Comment by otykier** [comment]
Deleting tables through external tools is not supported by Power BI Desktop. See [here](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations) for a list of supported write operations.
