### ISSUE TITLE
Uncomment code button grayed out, even after commenting code

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#158]
In the Expression Editor, I commented out the last 3 lines of code (after a RETURN to close a VAR section) using the Comment button, and the uncomment button remains grayed out - I have to manually uncomment. Just playing with it a bit, I cannot get the Uncomment button to work at all. 

3.0.7

**Comment by avatorl** [comment]
I created new issues than noticed this one. The problem is in leading spaces or tabs. https://github.com/TabularEditor/TabularEditor3/issues/159

**Comment by edhans** [comment]
Thanks. That is it. This code is indented. Daniel, merge this with #159

**Comment by otykier** [comment]
Merged with #159
