### ISSUE TITLE
Uncomment Code button doesn't work for lines with spaces or tabs before //

### ISSUE THREAD

**Issue by avatorl** [TabularEditor/TabularEditor3#159]
Uncomment Code button doesn't work for lines with spaces or tabs before //
Works only for lines that starts with //

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). In addition, you can configure whether the Comment Button should use hyphens or slashes under Tools > Preferences > DAX Editor > General.
