### ISSUE TITLE
Error connecting to database - The remote server returned an error:(401) Unauthorized

### ISSUE THREAD

**Issue by Crozza-2021** [TabularEditor/TabularEditor3#161]
Hello, 

Hope everyone is well, 

Just starting to use this software and I have hit the above error. 

Essentially I have a base .pbix which has been used to create a dataset; Report A. 
This has measures under a measures table called Measures_A

Upon opening the Tabular Editor 3 - I can see my 4 measures. 

Another .pbix has then been based off this dataset; Report B.  (Thin Report)
This has additional measures under the same measures table called Measures_A

Upon opening the Tabular Editor 3 - I can the error message. 

How would I go about opening the Report B in the Tabular Editor and then Copying those additional measures back to Report A? Is this even possible? 

I have tried looking around for the answer, with the below seeming likely (But couldn't get the solution to work): 

https://community.powerbi.com/t5/Desktop/Tabular-Editor-Error-401-Report-and-Model-in-separate-files/td-p/1452205

Any help would be greatly appreciated; hopefully this is the right place to post this. 

Many Thanks

**Comment by otykier** [comment]
You cannot edit Live Connect (thin reports) in Tabular Editor. Only reports that contain an actual data model can be edited. For an (unsupported) workaround on how to obtain measures from reports in Live Connect mode, take a look here: https://www.elegantbi.com/post/reportlevelmeasures
