### ISSUE TITLE
Mark As Date Table - where?

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#162]
I'm not seeing it as I poke around various context menus - am I just missing it?

If it's not there explicitly, is there a set of more granular properties I can set within TE3 that collectively add up to the same?

**Comment by otykier** [comment]
It’s not implemented yet. See #91 for a workaround.

**Comment by otykier** [comment]
Mark as Date table is available in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
