### ISSUE TITLE
When installing a new version of Tabular Editor 3 the task bar Icon breaks

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#163]
I have tabular editor in my task bar, and at each release, the icon breaks so i have to unanchor what is there, open it fromthe start menu (or power bi) and then reanchor it. 
I know if I open it from power bi why I need it there? well, not sure either, maybe because as contractor I cannot install things on my corporate machine and I'm used to the portable versions 
not high priority, but maybe it's really easy to fix, no idea. 

![image](https://user-images.githubusercontent.com/40455069/128590380-0646b9d3-f0f1-4ecc-9ea6-239a84fd2c2c.png)

and seems to be just an icon thing, as the shortcut continues to be there 

![image](https://user-images.githubusercontent.com/40455069/128590437-7d53832a-2242-4dfb-9b1b-c8d97721c601.png)

well, no, sorry, it looks like the reference breaks as well (file cannot be found error in catalan)
![image](https://user-images.githubusercontent.com/40455069/128590497-8f3c72dd-c347-4304-80cd-6517da0da73f.png)

[Window Title]
Windows

[Main Instruction]
No es pot obrir aquest element

[Content]
Potser s'ha desplaçat, s'ha canviat de nom o s'ha suprimit. Voleu suprimir aquest element?

[Sí] [No]

**Comment by otykier** [comment]
Are you using the Tabular Editor 3 MSI installer to install the product? As long as the installation location doesn't change, this shouldn't happen.

**Comment by bernatagulloesbrina** [comment]
I just click the link, download the file and double click to install. So
weird. It's the only program where this happens

**Comment by jtgooding42** [comment]
I have the same issue, it updates the start menu and desktop, but if you have a shortcut on the task bar it turns it into a white sheet after each upgrade, to fix is just delete the shortcut then re-create it or get tired of the issue and just use the start menu.

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
