### ISSUE TITLE
Saving DAX Script Indents the DAX Code

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#165]
1. Open DAX Script and Expression in two panes.

2. Make no changes and Apply & Sync the DAX Script

3. The DAX Code in the Expression Editor window is indented

https://user-images.githubusercontent.com/73054674/128636265-e3f08e24-c62a-41e8-ab4c-810048d9998b.mp4

**Comment by otykier** [comment]
That's a bug in 3.0.8/3.0.9. Thanks for reporting.

**Comment by otykier** [comment]
FYI, this issue should only arise when Tools > Preferences > DAX Editor > Use tabs is checked.

**Comment by otykier** [comment]
Fixed in [3.0.10](https://github.com/TabularEditor/TabularEditor3/releases/latest) (even when using tabs).
