### ISSUE TITLE
Pivot Grid is slow and hangs right before droping a column

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#166]
I am using version 3.0.9 and if I launch Pivot Grid, it takes a few seconds to load and then if I drag a column and even before dropping it TE3 starts to hang and after that I have to close it from Task Manager. Also notice there is a small white box towards bottom left side.

Video:

https://user-images.githubusercontent.com/73054674/128637065-11e686c4-a9f5-41ed-a675-5eac697213b9.mp4

**Comment by otykier** [comment]
Thanks for reporting. This seems to be an issue with instances of Analysis Services that require AAD authentication (Power BI XMLA and Azure Analysis Services). Can you confirm this?

We are investigating.

**Comment by SharmaAntriksh** [comment]
Nope, for me it is happening when connecting with Power BI, I am using the Desktop version of TE3.

**Comment by otykier** [comment]
Got it. We identified the issue and will post an updated version shortly.

**Comment by otykier** [comment]
Fixed in [3.0.10](https://github.com/TabularEditor/TabularEditor3/releases/latest).

**Comment by SharmaAntriksh** [comment]
I just tried and Pivot Grid is working perfectly, thanks! there is one issue, right click on the shelf throws an error as shown below:


https://user-images.githubusercontent.com/73054674/128892511-0091bbcc-2b2a-4a9a-86ee-fe037d3070e8.mp4

**Comment by otykier** [comment]
I'll create a new issue for that.
