### ISSUE TITLE
Diagram -> canvas context menu -> add tables: Table Name Search would be handy...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#167]
Some models have a lot of tables - scrolling gets old fairly quickly. :)

**Comment by otykier** [comment]
Agreed - at the very least, we should have incremental search enabled (so you can hit the first few letters of a table name to jump to that table).

**Comment by otykier** [comment]
Incremental search now available in [3.0.10](https://github.com/TabularEditor/TabularEditor3/releases/latest).
