### ISSUE TITLE
Updating PBID Groups works, but breaks visibility

### ISSUE THREAD

**Issue by KD-Nutra** [TabularEditor/TabularEditor3#168]
I can update a "Group" in TE3 and save it back to the model, and the updated group performs as expected in the report. However, if I subsequently try to edit the group in PBID, the changes are not visible.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/82449934/128719123-e6b4166a-2a4e-4e5a-bbc5-e87902fbe578.png">

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/82449934/128719287-e67a1fb6-83eb-416f-881e-1f458bf1d958.png">

**Comment by otykier** [comment]
Hi @KD-Nutra.
Unfortunately, editing calculated columns through external tools is not among the [write operations currently supported by Power BI Desktop](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations). As such, there's nothing we can do on the Tabular Editor side, to improve this behavior. Please raise this issue on the [Power BI community site](https://community.powerbi.com/) for attention at Microsoft.
