### ISSUE TITLE
Unable to sign in with License Key

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#17]
First I tried the evaluation version and then got the license key but after uninstalling 2-3 times the tabular editor still isn't asking for the license key, is there a way to revoke the evaluation period?

![image](https://user-images.githubusercontent.com/73054674/120332892-ca8a0980-c30c-11eb-862f-7624515214f0.png)

Let me know how to fix this, also, If you can implement a login feature like Visual Studio then that would be extremely helpful I suppose. :)

**Comment by otykier** [comment]
Please see #15 (this process will be made much easier in a future update). Thank you!
