### ISSUE TITLE
Record script (Macro) generate script but when save and call again the get error

### ISSUE THREAD

**Issue by thuphamviet** [TabularEditor/TabularEditor3#174]
I am working with tabular editor 3.0.7
**Describe the bug**
Record script (Macro) generate script but when save and call again the get error

**To Reproduce**
1. Go to Open New C# Script
2. Click on Record Script
3. Right click on Tables -> Create -> Calculation Group 
![image](https://user-images.githubusercontent.com/88760266/128970747-8b392dec-5a62-4d5d-bd1c-fdd406eaebfc.png)

4. Stop record and copy code from above generate, paste, and run then get error
![image](https://user-images.githubusercontent.com/88760266/128970971-ccd4574c-3e1d-4379-85e7-454560935e10.png)

**Application specifics**
 - Tabular Editor version: [e.g. 3.0.7]

**Comment by otykier** [comment]
Duplicate of #144 (this was fixed in [3.0.10](https://github.com/TabularEditor/TabularEditor3/releases/latest).

**Comment by thuphamviet** [comment]
> Duplicate of #144 (this was fixed in [3.0.10](https://github.com/TabularEditor/TabularEditor3/releases/latest).

I download version 3.0.10 and working with it but still got the same error, because macro generated script still has "Table" suffix as  below picture
![image](https://user-images.githubusercontent.com/88760266/128982195-3937095f-f9b9-4206-8074-f637dd278089.png)

**Comment by otykier** [comment]
You're right, my mistake, looking into it. Workaround for now is to change `AddCalculationGroupTable` to `AddCalculationGroup` manually in the code.

**Comment by thuphamviet** [comment]
> You're right, my mistake, looking into it. Workaround for now is to change `AddCalculationGroupTable` to `AddCalculationGroup` manually in the code.

Yes, I know. Thanks Otykier very much. Wish your product will be more perfect

**Comment by otykier** [comment]
`AddCalculationGroupTable` now works.

**Comment by thuphamviet** [comment]
> `AddCalculationGroupTable` now works.

Good job @otykier
