### ISSUE TITLE
Right click on Pivot Grid shelf throws an error

### ISSUE THREAD

**Issue by otykier** [TabularEditor/TabularEditor3#175]
https://user-images.githubusercontent.com/73054674/128892511-0091bbcc-2b2a-4a9a-86ee-fe037d3070e8.mp4

_Originally posted by @SharmaAntriksh in https://github.com/TabularEditor/TabularEditor3/issues/166#issuecomment-896114717_

**Comment by SharmaAntriksh** [comment]
Hi Daniel, here is more scenario of this bug:

https://user-images.githubusercontent.com/73054674/129010690-498148eb-b500-4096-a604-0e0a599c701c.mp4

**Comment by helgews** [comment]
+1 (Experienced the same thing today. 3.0.10. Pivotgrid showing values based on some measures, fields, filters from my Azure Analysis Workspace DB.

**Comment by otykier** [comment]
Fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
