### ISSUE TITLE
Missing Ok/Cancel buttons

### ISSUE THREAD

**Issue by vtitte2020** [TabularEditor/TabularEditor3#177]
Missing OK/Cancel button on "Use a Workspace Database?" dialog box. Installed latest TE3 edition 3.0.10
![Missing OK on Use a Workspace Database](https://user-images.githubusercontent.com/63069887/129070925-8bf7a445-964b-4609-86aa-a2cde5fd244e.jpg)

**Comment by otykier** [comment]
I believe this is related to #81. This is a UI scaling issue which can usually be resolved by logging out of your Windows session and back in.

**Comment by otykier** [comment]
Hi @vtitte2020 - do you still have this issue with newer versions of TE3? Did you try logging out of your Windows session and back in?

**Comment by otykier** [comment]
Closing this as duplicate of #81
