### ISSUE TITLE
Inverted commas are added for each table reference

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#18]
TE3 automatically adds inverted commas after referencing a table name:

https://user-images.githubusercontent.com/73054674/120335634-41c09d00-c30f-11eb-97d6-37ad1d4918c6.mp4

While this is useful for cases when we have special characters or spaces in the table names. Other than those cases we should be allowed to refer to the table/column without inverted commas. Please let me know what you think.

**Comment by otykier** [comment]
This is configurable under Tools > Preferences > DAX Editor > Auto Formatting:

![image](https://user-images.githubusercontent.com/8976200/120336651-d799ff00-c2f2-11eb-8e8d-82fbb3657c89.png)

I wasn't kidding when I said this is the most powerful DAX editor in the world ;-)

**Comment by SharmaAntriksh** [comment]
Awesome, thanks for the help. Yep, indeed most powerful!

**Comment by SharmaAntriksh** [comment]
@otykier I changed the setting and it worked, but after closing TE the all the changes made to the settings were reverted back.
