### ISSUE TITLE
Find and Replace doesn't search in Calculation Group Items

### ISSUE THREAD

**Issue by otykier** [TabularEditor/TabularEditor3#180]
### Discussed in https://github.com/TabularEditor/TabularEditor3/discussions/172

<div type='discussions-op-text'>

<sup>Originally posted by **dballanco** August 10, 2021</sup>
The new model-wide find and replace is very useful but doesn't seem to work when I search for the text in the expression of a calculation group item.</div>

**Comment by mlonsk** [comment]
Closing this as it looks to have been fixed in 3.4.0, where it is possible to search in expression of calculation group items
