### ISSUE TITLE
C# Scripts and intellisense

### ISSUE THREAD

**Issue by jtgooding42** [TabularEditor/TabularEditor3#181]
Does this work at all in 3.x, with my model loaded even following the online example of drag a measure in then hit period to get to displayfolder doesn't work.  My model is fairly large but no amount of waiting does it ever appear.

**Comment by SharmaAntriksh** [comment]
This is planned for a future release, probably in Q3, check this: https://github.com/TabularEditor/TabularEditor3/issues/12

**Comment by otykier** [comment]
Correct - IntelliSense when writing C# scripts in TE3 is planned for a release later this year.

**Comment by jtgooding42** [comment]
Thanks, just wanted to make sure, intellisense helps a lot with model discovery and getting the syntax correct, looking forward to it.
