### ISSUE TITLE
Diagram performance when many tables are loaded

### ISSUE THREAD

**Issue by jtgooding42** [TabularEditor/TabularEditor3#182]
I have a fairly large model, if I accidently click the diagram button the app becomes non-responsive for about 10-15 minutes until it finishes, then the whole app becomes unusable if it tries to display the diagram at any time.  Not sure what can be done to optimize it but definitely unusable on a large model.

**Comment by otykier** [comment]
That's strange. Creation of a new (empty) diagram should not be impacted by the size (number of objects) in the model. I would expect some performance degradation if you try to add, say, 50 tables to the same diagram, but not something as bad as you describe.

- Is this using v. 3.0.10?
- Can you confirm this is not an issue when working on a smaller model?

**Comment by jtgooding42** [comment]
Using 3.0.10 and i select say 10 tables from one perspective it performs great, selecting our full model it takes almost 10 minutes to build the diagram, but in 3.0.10 the tool doesn't become non-responsive after its built, while building it is 100% locked.  The full model is 25 perspectives over 62 tables, adding all of them brings it to its knees, but behavior afterwards is better just a bit slow and laggy. Closing the Diagram and it goes right back to normal performance.  I think what's killing it more than just tables is the 159 relationships.  If you want me to share something for future testing reach out directly to me on my work email jgooding@preferredstrategies.com, this is my personal account I am using here. Thanks for the great tool and keep it up :)

**Comment by otykier** [comment]
Hi @jtgooding42 
[V. 3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html) contains a few optimizations which should make the diagram faster when tables are initially added. Could you check this, please? That being said, I would still not try to create a diagram with more than 25 or so tables - even if the performance is acceptable, I'm not sure there's much value in showing so many tables in a single diagram. Generally, I would recommend creating a diagram for each fact table in your model or for groups of highly related fact tables. Thoughts?

**Comment by mlonsk** [comment]
Closing issue as this no longer is reproducable and seems to have been fixed. Please feel free to reopen if the diagram view is still slow
