### ISSUE TITLE
Super-small issue with the diagram -> add tables -> incremental search new feature...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#183]
When you bring up the Add Tables dialog, the list box items control does not have focus (I think the entire dialog does).

Effect: if you IMMEDIATELY start typing to search for your table, the dialog goes away. You have to click into the listbox and THEN start typing.

Suggest setting focus to the listbox on dialog open. 

Yes this is nitpicky. :)

**Comment by otykier** [comment]
I realized this minutes after publishing the latest version. A fix is on the way :-) (I’m totally nitpicky myself)

**Comment by seedjay1** [comment]
And thank you for the responsiveness!

**Comment by otykier** [comment]
Fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
