### ISSUE TITLE
Undo and Redo are screwed up

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#185]
Build 3.0.7892.27443

In the DAX Query editor:

- When I use the undo command or shortcut keys (ctrl + z) my code becomes commented arbitrarily.
- When I use the redo command or shortcut keys (ctrl + y) I get an 'undo'. (Though it is handy given the behaviour in the first point 🤹‍♂️)

**Comment by samaguire** [comment]
Okay. So, I've closed and reopened the Dax Query editor tab, and things have come right. Not sure what's happened, but it is working now so I've closed this.

**Comment by otykier** [comment]
Thanks for letting us know. If you manage to trigger this issue again somehow, don’t hesitate to reach out.
