### ISSUE TITLE
M Expression dropdown/embedded/expanded text box could use a context menu...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#188]
For the normal things: cut, copy, paste, select all.

**Comment by otykier** [comment]
Could you provide a screenshot to indicate what dropdown you are referring to?

**Comment by seedjay1** [comment]
I meant the dropdown text box in the little table partition properties area. But afterward I saw the big expression window for the M code. So yah nevermind it was a stupid issue :).
