### ISSUE TITLE
Vertipaq Output does not show cardinality of columns when Available in MDX column property is set to False

### ISSUE THREAD

**Issue by nariusp** [TabularEditor/TabularEditor3#190]
TE: 3.0.10

The Vertipaq "Collect Stats" and Export do not show any cardinality values at the column level when a table name is expanded in the table view, nor in the Export and also not in the column view. All values are 0

For example:
![image](https://user-images.githubusercontent.com/88670230/130415464-55b5dcf0-8ef8-45a3-b5ed-db783ee50c8a.png)

The same model Vertipaq stats from DAX Studio does show the correct values:

![image](https://user-images.githubusercontent.com/88670230/130415633-8f14c5ef-9d8c-42a9-800f-08872cf150a5.png)

**Comment by nariusp** [comment]
The issue seems to be related to where the table has no internal hierarchy defined because the IsAvailableInMDX property is set to False.

**Comment by marcosqlbi** [comment]
@nariusp I guess that DAX Studio has the same behavior as TE3 if you disable "Read statistics from data" in Options / Advanced. If confirmed, TE3 is not running the complete analysis (which could be time-consuming in large models).

**Comment by nariusp** [comment]
> @nariusp I guess that DAX Studio has the same behavior as TE3 if you disable "Read statistics from data" in Options / Advanced. If confirmed, TE3 is not running the complete analysis (which could be time-consuming in large models).

Hi Marco - yes you are correct, DAX Studio does the same thing and shows zero when the "Read statistics from data" is turned off. On this model DAX Studio only takes a few seconds to get the stats / metrics. 

It would be good to have the choice though in TE3 so we could get the full stats without having to use DAX Studio instead.

**Comment by atmisra** [comment]
> > @nariusp I guess that DAX Studio has the same behavior as TE3 if you disable "Read statistics from data" in Options / Advanced. If confirmed, TE3 is not running the complete analysis (which could be time-consuming in large models).
> 
> Hi Marco - yes you are correct, DAX Studio does the same thing and shows zero when the "Read statistics from data" is turned off. On this model DAX Studio only takes a few seconds to get the stats / metrics.
> 
> It would be good to have the choice though in TE3 so we could get the full stats without having to use DAX Studio instead.

Agreed - I am experiencing this issue also, and I am happy to wait 10 more seconds to see the complete analyzer results.

**Comment by otykier** [comment]
3.1.1 (to be released this week) adds a settings page for VertiPaq Analyzer under Tools > Preferences > File Formats. "Include statistics from data" will be checked by default.

![image](https://user-images.githubusercontent.com/8976200/134309111-6815f4d6-4430-4bcf-875f-f3af6a393950.png)

**Comment by nariusp** [comment]
Excellent thanks @otykier (Daniel)

**Comment by otykier** [comment]
[3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html) is now released. Thanks for reporting!
