### ISSUE TITLE
Unwanted leading line inserted into M code

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#193]
It looks like #26 is also causing a new line to be added in M query partitions when editing. In the below I did a minor tweak to a filter clause (which I then reversed) and a leading line has been inserted.

![image](https://user-images.githubusercontent.com/62320770/130732525-0c7d2963-41bf-4713-a688-72dfd2a35140.png)

**Comment by otykier** [comment]
Fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
