### ISSUE TITLE
Error when applying a workspace

### ISSUE THREAD

**Issue by avatorl** [TabularEditor/TabularEditor3#198]
I created a workspace (XML attached) with a Message window on the bottom and Auto Hide enabled for the window) and when I'm switching to this custom workspace from Classic workspace I'm getting the following error:

<img width="960" alt="rx5dmdlvlD 1" src="https://user-images.githubusercontent.com/59934292/131306186-efaabb5a-b06c-4dde-a1d2-78b141b4ce48.png">

No error when switching to the custom workspace from Default workspace.

[My Workspace 01.zip](https://github.com/TabularEditor/TabularEditor3/files/7075100/My.Workspace.01.zip)

**Comment by otykier** [comment]
Thanks for reporting - we'll investigate.

**Comment by otykier** [comment]
Fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
