### ISSUE TITLE
Apply Display Folder for multiple columns/measures result in error

### ISSUE THREAD

**Issue by relax528** [TabularEditor/TabularEditor3#199]
Steps to reproduce: Highlight multiple measures, click the ellipsis in the Display Folder property to select the folder and you get an error: _Object reference not set to an instance of an object._
![image](https://user-images.githubusercontent.com/19497071/131408617-23caca20-e27f-4983-bf77-d279dcf33ce6.png)
Note, typing the folder name works as expected.

**Comment by otykier** [comment]
Thanks for reporting.

**Comment by otykier** [comment]
Fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
