### ISSUE TITLE
Can't copy just a value from DAX query results (without column name)

### ISSUE THREAD

**Issue by avatorl** [TabularEditor/TabularEditor3#200]
When copying an individual value from DAX query results it copies column header together with the value.

What I get into the clipboard:

TableName[ColumnName]
Value

What I need in the clipboard:

Value

I assume most users expect the same behavior, so the copied value can be inserted into a measure for data filtering.

**Comment by otykier** [comment]
Just to be clear, is this behavior only required when selecting and copying from a **single** cell?

**Comment by avatorl** [comment]
I can't answer for others, but I think column names should be copied only when all columns/rows selected (e.g. Ctrl + A, Ctrl + C)

**Comment by otykier** [comment]
Fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
