### ISSUE TITLE
Open from XMLA endpoint uses the wrong dataset after sort by name

### ISSUE THREAD

**Issue by marcosqlbi** [TabularEditor/TabularEditor3#201]
Open a connection to Power BI Premium using XMLA endpoint to a workspace that has several datasets published.
Sort the list by database name (the sort order must be different than the default one)
Select a database - TE3 opens a different database, likely the one in the same physical position of the original list instead of the selected one.

**Comment by otykier** [comment]
Fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
