### ISSUE TITLE
Wrong number of BPA-issues in bottom toolbar

### ISSUE THREAD

**Issue by helgews** [TabularEditor/TabularEditor3#203]
My TE3 (3.1.0) is showing the wrong number of total BPA-issues in the bottom toolbar.

I am running the Microsoft-ruleset, with some rules disabled. Rules are embedded within current model.

![image](https://user-images.githubusercontent.com/56156227/132206193-671b8e98-c6a0-4e06-a9f6-0b2ffef55015.png)
![image](https://user-images.githubusercontent.com/56156227/132206351-479f2228-a4a6-48af-9e9d-a5a6908aedac.png)

**Comment by helgews** [comment]
The issue is the same, both if I open my model from folder (with the Azure AS-model as my workspace DB) and if I open the AzureAS-model directly.

TE2 shows the same bpa-issues and correct total.

**Comment by otykier** [comment]
This is now fixed in [3.1.2](https://docs.tabulareditor.com/te3/other/release-notes/3_1_2.html). Indeed the problem was that the background analysis considered all rules - even ignored ones.
