### ISSUE TITLE
New theming isn't applying to C# scripts

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#207]
As per the title.

I like a dark mode and run on a hi-res screen so am using the new "Basic" theme. However, C# scripts are opening against a white background rather than a dark background as per the theme selection.

![image](https://user-images.githubusercontent.com/62320770/132262704-c8d71993-ba5a-4059-83c2-7dad08d8c24d.png)

**Comment by samaguire** [comment]
Same issue with the M expression editor.

![image](https://user-images.githubusercontent.com/62320770/133003077-7a64cd42-2259-4d36-8253-3f35e6760f34.png)

**Comment by otykier** [comment]
This is fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). Thanks for reporting!
