### ISSUE TITLE
C# script will run, but won't save

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#208]
I'm trying to save as a macro (for convenience) m-kovalsky's Export Report Objects script (https://github.com/m-kovalsky/Tabular/blob/master/ExportReportObjects.cs) but get the below error. However, it runs fine if I just 'run' the script 🤷‍♂️

(No messages in the messages tab either, so I don't know where it is having an issue...)

![image](https://user-images.githubusercontent.com/62320770/132264421-765d9dd0-e01f-4844-abd9-7c58f5e13e17.png)

**Comment by otykier** [comment]
Thanks for reporting, we'll investigate!

**Comment by otykier** [comment]
This is fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). Thanks for reporting!
