### ISSUE TITLE
Semantic Analysis: Column reference error persists with quoted tables

### ISSUE THREAD

**Issue by smithjl1** [TabularEditor/TabularEditor3#21]
Semantic Analysis is showing column reference errors for calculated table for each column; example: "Column references should always be qualified: [DateKey]" I updated the calculated table to include table name in column reference. Table is one word with no spaces, so excluded quotes and written as: "Dates[DateKey]". 

Expected behavior: SA clears warning. 
Actual behavior: SA refreshes warning as "Column references should always be qualified: 'Dates'[DateKey]"

![image](https://user-images.githubusercontent.com/3843484/120345137-d4395000-c2bf-11eb-9529-721497090e85.png)

Notes: 
- After reviewing Preferences for DAX Editor, I realized "always quote tables" was forcing the issue. I changed the "Preferences/DAX Editor/Auto Formatting/Auto formatting style/Always quote tables" to not checked, and clicked OK: 
![image](https://user-images.githubusercontent.com/3843484/120345202-e1563f00-c2bf-11eb-9977-92222721be94.png)

- Warnings from SA persisted. I had to close and re-open TE3 to refresh the SA results, which were then removed. 
- Re-enabling the preference did not refresh SA results until TE3 close and re-open, after which SA warnings appeared. 
- Added quotes to the column reference's table name in PBI (calculated table expressions cannot be updated in TE3). After update, TE3 did not recognize the TOM update, and the DAX expression for the calculated table was still the older version. TE3 closed and re-opened, and changes to DAX are now visible (I don't know if that's a PBI issue or TE3 issue, but noted anyways)

Preferred Resolution: 
- SA should refresh after changes to Preferences (bonus points for DAX formatting-specific preference changes)

Other thoughts:
- Feature request: Add TOM Refresh menu option to force TOM refresh

**Comment by otykier** [comment]
The preference under "Auto Formatting" should not impact whether warnings are displayed or not. From your description, it sounds like the issue boils down to this:

- When a change is made to the model in Power BI Desktop, while Tabular Editor 3 is connected, TE3 doesn't update the messages to reflect changes made in Power BI Desktop.

Is this correc?

**Comment by otykier** [comment]
See #22. Can we close this issue with the [3.0.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.2) update?

**Comment by smithjl1** [comment]
> The preference under "Auto Formatting" should not impact whether warnings are displayed or not. From your description, it sounds like the issue boils down to this:
> 
> * When a change is made to the model in Power BI Desktop, while Tabular Editor 3 is connected, TE3 doesn't update the messages to reflect changes made in Power BI Desktop.
> 
> Is this correct?

Yes, that's an accurate assessment.



> See #22. Can we close this issue with the [3.0.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.2) update?

Yes, I believe this will resolve the issue.
