### ISSUE TITLE
Simple C# script compile error "Metadata file 'Microsoft.AnalysisServices.Core.dll' could not be found" ?

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#211]
This is being run against an AAS model. What am I missing here?
![image](https://user-images.githubusercontent.com/31414209/132453229-28ff6f85-d7ac-447a-9336-f24e0cecad17.png)

**Comment by otykier** [comment]
See issue #192. Until we fix this bug, you will either have to edit the Tabular Editor 3 shortcut to use the installation directory as the “start in” path, or alternatively, you can modify the script to specify the full path of the DLL (it should be in your Tabular Editor 3 installation directory).

**Comment by otykier** [comment]
@seedjay1 Btw - did you know you can refresh tables directly in Tabular Editor 3, without using a script?

![image](https://user-images.githubusercontent.com/8976200/134333679-e5f2d5ac-20ec-42e4-9abf-70739774dacf.png)

The refresh happens in the background, so you can keep working while Analysis Services refreshes data. On the "Data Refresh" tab you can check the progress.

![image](https://user-images.githubusercontent.com/8976200/134333724-8ca1e302-c1b0-48c9-82f9-9a1127f7ec90.png)

**Comment by otykier** [comment]
Closing this as #192 tracks the issue with loading DLLs from the application directory.

**Comment by seedjay1** [comment]
Yep I'm aware of GUI process ability, and use it regularly :). I was just trying to get a basic code thing working and recalc just happened to be the first thing i tried.
