### ISSUE TITLE
Sort Tables A-Z in "Create Relationship"

### ISSUE THREAD

**Issue by lukiz84** [TabularEditor/TabularEditor3#214]
Hi,

would it be possible to change the sort order in the "To Table"-Dropdowns in the Create Relationship dialog?

With many tables it's very hard to quickly find the right one...

BR and thanks
Lukas

**Comment by otykier** [comment]
This is fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). Thanks for reporting!
