### ISSUE TITLE
Data refresh icon not changing when theme is changed

### ISSUE THREAD

**Issue by albegouws** [TabularEditor/TabularEditor3#215]
When using a darker theme the progress icon when doing a model refresh still has the light background.  
![Icon Color](https://user-images.githubusercontent.com/29041479/132683919-5074b360-2d87-437e-97cc-a6e221c73454.jpg)

**Comment by otykier** [comment]
This is fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). Thanks for reporting!
