### ISSUE TITLE
TE3 not opening - KERNELBASE.dll

### ISSUE THREAD

**Issue by janizz** [TabularEditor/TabularEditor3#217]
I have installed TE3 on my Win10 laptop, but it won't open... pasting the Event Viewer logs:

![image](https://user-images.githubusercontent.com/2431369/132852537-11900cbc-3786-4180-bc2f-0902ff65a36f.png)

Error1:
Application: TabularEditor3.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at TabularEditor.StartupOptimization.ActivateMultiCoreJit(System.String)
   at TabularEditor.Program.Main()

Error2:
Faulting application name: TabularEditor3.exe, version: 3.1.7916.28834, time stamp: 0x61322aa5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x891df6d3
Exception code: 0xe0434352
Fault offset: 0x0000000000034ed9
Faulting process id: 0x3bda8
Faulting application start time: 0x01d7a63e0fba3672
Faulting application path: C:\Program Files\Tabular Editor 3\TabularEditor3.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: dc3e49a5-2af3-4d82-9546-901d57b25731
Faulting package full name: 
Faulting package-relative application ID:

**Comment by otykier** [comment]
This bug occurred in a version of Tabular Editor 3 that was available for download on Friday, but was taken down a few hours later. Could you please perform a manual uninstall through the Control Panel, then download the newest version here: https://docs.tabulareditor.com/te3/other/downloads.html (build number should be **3.1.7918**.xxxxx).

**Comment by janizz** [comment]
Yep, works now!
