### ISSUE TITLE
TOM updates in Power BI Desktop not refreshed in TE3

### ISSUE THREAD

**Issue by smithjl1** [TabularEditor/TabularEditor3#22]
Minor updates to non-editable objects in TE3 are not refreshed after updated in PBI TOM. 

Example:
A user security role in my model was missing a table reference:
![image](https://user-images.githubusercontent.com/3843484/120350738-df42af00-c2c4-11eb-8079-336117ffea82.png)

Roles cannot be updated in TE3, so I updated the role's expression in PBI. I edited and closed the "Edit Role" menu, which updates PBI's in-memory TOM, but did not save the PBIX. 
![image](https://user-images.githubusercontent.com/3843484/120351060-2466e100-c2c5-11eb-810d-b430bd98a882.png)

Expected Behavior: TE3 detects an update to the in-memory TOM and prompts to refresh the model.
Actual Behavior: The in-memory TOM update is not registered by TE3. 

Notes: Saving the PBIX file also did not create a TOM update popup from TE3, but the TE3 TOM did update, as the role expression update was visible after clicking away/reselecting the role expression in TOM Explorer. 

Preferred Resolution:
- Add "TOM Refresh" button to toolbar to force TOM refresh

**Comment by smithjl1** [comment]
After submission, I realized that TOM changes are tracked in TE3 by listening to Analysis Service trace events, not by monitoring the in-memory TOM. My bad. I'm assuming the issue is caused by AS events not being created for these kinds of model changes. However, a TOM Refresh button would still resolve this issue.

**Comment by otykier** [comment]
"Revert" button added to File menu and main toolbar (you may have to reset your workspace by choosing Window > Default to see the new button). Use this to refresh from the remote TOM (unsaved local changes will be lost):

![image](https://user-images.githubusercontent.com/8976200/120603584-7d14b600-c44c-11eb-88a6-15503714ed4d.png)
