### ISSUE TITLE
TE3 automatically closes itself (when there are errors in the measures)

### ISSUE THREAD

**Issue by avatorl** [TabularEditor/TabularEditor3#220]
TE (ver. 3.1.0) automatically closes itself when there are errors in measures.

I was making some changes in a data model and therefore created errors in a few measures (they were referencing removed tables/columns). TE3 crashed (just closed itself with no error message). I wasn't able to open it again (from Power BI External Tools tab), it was closing itself immediately once opened. I had to edit the measures in Power BI. Once I fixed all errors in the measures I was able to open TE3 again.

It happened a few times today.

**Comment by otykier** [comment]
Thanks for reporting. Any chance you could export a .pbit (Power BI Template) and send it to daniel@tabulareditor.com with a description of the data model change that caused the error, for further investigation?

**Comment by otykier** [comment]
Hi @avatorl. Could you check if newly released [v. 3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html) solves this issue? Thanks!

**Comment by otykier** [comment]
Hi @avatorl. Any update on this? Have you had this issue with never versions of TE3?

**Comment by avatorl** [comment]
Hi Daniel,
thank you for your question.
So far I never experience this issue again with newer versions of TE3.
Kind regards,
Andrzej
