### ISSUE TITLE
Add a Macro for Dates Table Creation 

### ISSUE THREAD

**Issue by FowmyM** [TabularEditor/TabularEditor3#222]
Hi There,

I need to create a script and save as a macro to add a standard dates table to any Power BI model. 
Please guide me on the steps that I should take. I ma using TE 3

Here is my DAX code for the dates table:

`Dates = 

ADDCOLUMNS(
    CALENDAR("01/01/2021","31/12/2021"),
    "Month", MONTH([Date]),
    "Month Name", FORMAT([Date],"Mmmm"),
    "Year", YEAR([Date])
)`

Thanks
Fowmy

**Comment by otykier** [comment]
Hi @FowmyM
Apologies for the late reply (you posted this under https://github.com/TabularEditor/TabularEditor/issues which is the issue repository for the open-source version of Tabular Editor - I have moved it to the Tabular Editor 3 issue repository).

To create a calculated table with the above DAX expression using TE3, simply use this script:

```csharp
var dax = @"ADDCOLUMNS(
    CALENDAR(""01/01/2021"",""31/12/2021""),
    ""Month"", MONTH([Date]),
    ""Month Name"", FORMAT([Date],""Mmmm""),
    ""Year"", YEAR([Date])
)";
Model.AddCalculatedTable("Dates", dax);
```

(Notice the double-double quotes `""` in the DAX expression which are necessary to escape the C# string).

**Comment by FowmyM** [comment]
Thanks and appreciate it
