### ISSUE TITLE
TOM Explorer freezes when deleting a data column while the "Show/hide hidden objects" toggle is off.

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#223]
The TOM Explorer freezes completely while the rest of TE3 works as normal.

To reproduce:

1. Hide hidden object.
2. Delete a data column.

**Comment by otykier** [comment]
I wasn't able to reproduce this. Are you using the [latest version of Tabular Editor (3.1.0)](https://github.com/TabularEditor/TabularEditor3/releases/latest)? If so, could you provide a gif or other type of recording showing exactly how to cause the freeze. Thanks!

**Comment by eybert** [comment]
![TE3](https://user-images.githubusercontent.com/31990588/134199993-6c73039a-cd5f-4a60-bba3-6b7a6c61d225.gif)
Here's an example. Happens _every_ time. Not a big problem now that I'm aware of it, but still... :-)

**Comment by otykier** [comment]
Thanks - the issue has been identified. Will be fixed in next update!

**Comment by otykier** [comment]
This is fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). Thanks for reporting!
