### ISSUE TITLE
Creating Measures Table - Tabualr Editor 3.0.10

### ISSUE THREAD

**Issue by 200267** [TabularEditor/TabularEditor3#226]
Unable to create a Measures Table in Tabular Editor - error input, see attached
![Error Message](https://user-images.githubusercontent.com/91125056/134152004-f5fd8f8e-d22b-4694-a601-0fc8d21e2385.png)
d.

Thanks 
F Pasto
![Dragging Measures to New Table](https://user-images.githubusercontent.com/91125056/134152121-abbdf877-b533-45ff-ac7b-f6855ff7da8e.png)
r

**Comment by otykier** [comment]
This error generally occurs when your model contains a table with an empty M partition.

In your screenshot, try to expand the "Partitions" node. You should see a single partition. You must provide an M expression for this partition, for example: `#table(1, {})`

Alternatively, create your measure table using a calculated table and provide a DAX expression such as `{0}`, then hide the resulting column.

**Comment by 200267** [comment]
Thank you Daniel,

Some I guessed out that the table totally empty was the culprit.

😊

F Pastor
