### ISSUE TITLE
Link to more information on changing C# compiler is broken

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#227]
under "Preferences" --> "Tabular Editor" --> "C# Scripts and Macros" there is a link to "more information which is broken 
the link points here
https://docs.tabulareditor.com/Advanced-Scripting.html#compiling-with-roslyn

and this is what I am getting
![image](https://user-images.githubusercontent.com/40455069/134590229-fa0a89aa-bbd0-4d53-9fb7-942683e8cb95.png)

**Comment by otykier** [comment]
Thanks for letting us know. Here is the URL we wanted to show: https://docs.tabulareditor.com/te3/features/csharp-scripts.html#compiling-with-roslyn

**Comment by otykier** [comment]
Fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). Thanks for reporting!
