### ISSUE TITLE
Unable to detect schema changes on table

### ISSUE THREAD

**Issue by JuanLombana** [TabularEditor/TabularEditor3#231]
hi, i'm facing this error when trying to "Update Table Schema".
 
![image](https://user-images.githubusercontent.com/8260513/135198244-0f432fd3-fde1-4dc6-b9e5-093fdaf6b914.png)

i'm using Tabular Editor 3.1.1 (latest) and connecting to Azure SQL DW.

**Comment by otykier** [comment]
Thanks for reporting. We're investigating.

**Comment by otykier** [comment]
This is now fixed in [3.1.2](https://docs.tabulareditor.com/te3/other/release-notes/3_1_2.html).

**Comment by JuanLombana** [comment]
thank you, it's working on 3.1.2
