### ISSUE TITLE
Unable to save a model in the power BI Service as a BIM from Tab Ed v3.1.1 - works in Tab Ed 2

### ISSUE THREAD

**Issue by nariusp** [TabularEditor/TabularEditor3#233]
Using Tabular Editor v3.1.1 am unable to save a connected model as a Bim file, but the same actions work in Tabular Editor v2

1. Connect to a model in a premium workspace.
2. Select Save As, and the error below occurs:

![image](https://user-images.githubusercontent.com/88670230/135233704-1fdbb683-e55d-46c8-a453-d486e7d3a0dc.png)

I had no issue doing exactly the same thing from Tabular Editor v2 at the same time just now. I tried a couple of different models with the same result, and on a couple of different machines; both gave the same error.

**Comment by otykier** [comment]
This is related to #232. A fix will be available shortly.

**Comment by otykier** [comment]
This is now fixed in [3.1.2](https://docs.tabulareditor.com/te3/other/release-notes/3_1_2.html).
