### ISSUE TITLE
Memory leak in v3.1.1 & v3.1.2

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#234]
So, all I've done is open TE3, not even connect to AS or open a model file, and memory consumption keeps going up. In fact, it keeps going up until it crashes 😢

After a few minutes (enough time to go away and make a coffee) I've gone from ~200MB to about ~1.2GB and a crash, at which point the memory usage drops back down to ~200MB and starts climbing again.

**At the time of crash**

![image](https://user-images.githubusercontent.com/62320770/135356443-a2933504-42a5-491f-bc22-f39cbfcb0a43.png)

**Just after crash**

![image](https://user-images.githubusercontent.com/62320770/135356467-3f353bba-418c-4dbb-a95e-5e153ff77e2e.png)

**Message window**

![image](https://user-images.githubusercontent.com/62320770/135355850-8d5ab34f-9d1e-4c09-ad1c-f1393b614805.png)

**Comment by otykier** [comment]
Thanks for reporting. We’ll investigate.

**Comment by otykier** [comment]
We identified the issue and will provide a fix shortly (within the next 20 minutes).

**Comment by otykier** [comment]
Fixed in [3.1.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.3).

**Comment by samaguire** [comment]
> We identified the issue and will provide a fix shortly (within the next hour).

Thanks! Much appreciated. 👍
