### ISSUE TITLE
3.0 release not installing over 18.5 beta

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#24]
I downloaded the final 3.0 release from the website and tried to install. It failed saying a newer version was already installed.
![image](https://user-images.githubusercontent.com/45298358/120376855-3babcb80-c2d1-11eb-8a3a-1c16c8d593f9.png)

Oddly enough, when I launch the 18.5 beta it suggests I get the newer version.
![image](https://user-images.githubusercontent.com/45298358/120376925-50885f00-c2d1-11eb-9426-8fbb73a6b02b.png)

**Comment by otykier** [comment]
Please do a manual uninstall of the beta version before installing 3.0.1. Thank you!
