### ISSUE TITLE
Enhancement request: "Start Tabular Editor now" checkbox on installation finished dialog...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#242]
Fast cadence on releases is wonderful, but many installs are sourced from "there's a new version go here to dl it".

We just want to use the program - please put "start TE now" checkbox on ending install dialog (defaulted to yes), so upgraders can get on with their business without extra clicks? :)

**Comment by otykier** [comment]
Duplicate of #202
