### ISSUE TITLE
Will we ever be able to modify dataflows with tabular Editor? 

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#243]
I am thinking about automating through Tabular Editor general transformations that I often do in power query -- but then I realize that much of my transformations actually take place in dataflows. Given that they use the same language, is there any programatic acces that tabular editor could tap in the future? 

I've seen there are some jsons that you can export and import, but not sure if it's possible to actually modify a dataflow through a XMLA endpoint or simiar 

Regards!

**Comment by otykier** [comment]
This is a request you should raise with Microsoft. Currently, the [REST API for dataflows](https://docs.microsoft.com/en-us/rest/api/power-bi/dataflows) only allows us to start a refresh, delete a dataflow, export a dataflow and update dataflow properties. There is no endpoint for updating the **definition** of a dataflow. If such an endpoint is made available one day, this is certainly a feature we would consider for TE3.

**Comment by bernatagulloesbrina** [comment]
Ok! Worth a try
I'll follow up with Microsoft
And do some prayers too 😃

**Comment by bernatagulloesbrina** [comment]
if someone is reading this, please go and vote! https://ideas.powerbi.com/ideas/idea/?ideaid=aa888470-d925-ec11-b76a-281878bdb01d
