### ISSUE TITLE
TE3 v3.1.3 Update Table Schema Not Working - Works in 3.0.10

### ISSUE THREAD

**Issue by EthanEverett** [TabularEditor/TabularEditor3#244]
After updating to 3.1.3 TE3 is no longer able to update a table schema across multiple models deployed in our enterprise environment. The first picture shows that 3.0.10 will allow the table schema to be updated. The second picture shows the same table schema update resulting in an error in 3.1.3. The third picture is an entirely different model encountering an error in 3.1.3 when trying to update the table schema. 

**1st:**
![TE3 3 0 10 Update Table Schema](https://user-images.githubusercontent.com/78923074/136126394-afe676be-95ef-46eb-9f70-f13fe10c14ef.PNG)

**2nd:**
![TE3 3 0 13 Update Table Schema Error](https://user-images.githubusercontent.com/78923074/136126526-e69fa3e2-d022-4cd2-bd1e-227d03a24be4.PNG)

**3rd:**
![TE3 3 1 3 Update Table Schema Error - New Table](https://user-images.githubusercontent.com/78923074/136126540-1e0ac9db-a907-4bcc-ac14-89fc2c17fdca.png)

**Comment by EthanEverett** [comment]
Sure, see the screenshot below

![image](https://user-images.githubusercontent.com/78923074/136261147-97f9841a-70b1-4319-bde6-79c5b2e42965.png)

**Comment by mlonsk** [comment]
I will close this issue, but feel free to reopen.
