### ISSUE TITLE
Expression Editor window not visible after 3.1.3 install??

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#246]
!!! Please make sure you're using the latest version of Tabular Editor before submitting a bug !!!

**Describe the bug**
I can't see the expression editor, even if I select a  measure

**To Reproduce**
Nothing to do, just open Tabular Editor 3.1.3

**Expected behavior**
there should be a expresison winidow

![image](https://user-images.githubusercontent.com/40455069/136237530-a6b95776-65a8-49c3-b426-77e71bf31d47.png)

**Comment by otykier** [comment]
[3.1.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.5) should no longer have this issue.
