### ISSUE TITLE
Macro Actions Ignore Object Context

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#248]
It looks like the Macro actions ignore the context (or can't determine the context) when you right click on a folder of folders. It is fine if other objects (at least measures in my case) exist as child objects in the folder.

Most (nearly all) of the macros displayed in the below screen clip are set to the 'model' context.
![image](https://user-images.githubusercontent.com/62320770/136325351-f081f818-f2ea-4d0a-8d3e-8f58abc12568.png)

**Comment by otykier** [comment]
Fixed in [3.1.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.5). Thanks for reporting!
