### ISSUE TITLE
C# script is not compiling

### ISSUE THREAD

**Issue by do-nation** [TabularEditor/TabularEditor3#25]
I try to run a simple formatting script, (trial version, updating a Power BI data model on a Premium capacity) but every script I try is returning errors:
Your script cannot be compiled. See the messages window for error details.

The messages say:
Argument 1: cannot convert from 'string' to 'TabularEditor.TOMWrapper.IdaxDependantObject'
The best overload method match for 'TabularEditor.Scripting.ScriptHelper.FormatDax(TabularEditor.TomWrapper.IDaxDependantObject)' has some invalid arguments

Script example:
  //Format All Measures
  foreach (var m in Model.AllMeasures)
  {
      m.Expression = FormatDax(m.Expression);
      /* Cycle over all measures in model and format 
      them all using DAX Formatter */
  }

**Comment by otykier** [comment]
Please use the [new syntax](https://docs.tabulareditor.com/FormatDax.html) for formatting DAX code, as the old method (formatting strings one by one) puts unnecessary strain on the DaxFormatter.com webservice.

**Comment by do-nation** [comment]
Thank you so much for the quick reply. Tabular Editor 3 is awesome!
