### ISSUE TITLE
After running a C# Script the Button for Save back to model dis-appears

### ISSUE THREAD

**Issue by MikeCarlo** [TabularEditor/TabularEditor3#251]
# Issue

One of the first C# scripts I run is to create a group of sum measures, Add them to a display folder, set column format, then hide the numerical columns.  While on this screen I have the following buttons on the menu:

![image](https://user-images.githubusercontent.com/25160592/136683771-33978aa3-5fa5-4e59-9960-83b819c9808e.png)

The third icon is the save button for the C# script.  

When I want to save my changes back to the data model, I have to click on another window such as Expression Editor. Then the icons at the top menu will change to the following:

![image](https://user-images.githubusercontent.com/25160592/136683763-394af8bf-c28f-4c24-8221-45b829f67a7a.png)

I feel this is confusing.  Often I have clicked "Save" while I was in the C# window, Thinking I was saving my changes back to the model.  when in fact I was just saving the C# script file. 

I would prefer when I navigate to the Script window to have an Added icon for saving the script.  Please don't remove the save changes back to model.

**Comment by otykier** [comment]
Also (from https://github.com/TabularEditor/TabularEditor/issues/939) we should make sure to display "ALT+S" as the shortcut to use in order to synchronize the model.
