### ISSUE TITLE
Expression Editor window for RLS filters?

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#257]
The Expression Editor has a dropdown to select the TOM property the expression applies to, but the only listboxitem I see in it is the Detail Rows Expression.

Would be nice to have Expression Editor listboxitem for role RLS expressions.

Am I doing it wrong, or is this an enhancement request?

**Comment by otykier** [comment]
[3.1.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.7) adds a right-click menu option to roles, that makes it easier to add new table permissions:

![image](https://user-images.githubusercontent.com/8976200/146453693-250c976f-f609-4014-bdb1-ca2c4fd11e1e.png)

![image](https://user-images.githubusercontent.com/8976200/146453665-27e28eb3-8cd3-480d-9e68-e3a62aad17b1.png)
