### ISSUE TITLE
Rename and Delete buttons disabled in Customization window

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#260]
I created a new toolbar for my macros, but I didn't even name it properly. For some reason, though, the rename button is disabled so I amb stuck with Custom 11 (I don't remember making so many toolbars) 

![image](https://user-images.githubusercontent.com/40455069/137336671-156d9ad8-a3dd-4a43-b802-1c033f896627.png)

**Comment by otykier** [comment]
Fixed in [3.1.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.5). Thanks for reporting!
