### ISSUE TITLE
Where are custom toolbars stored?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#261]
Hi, is it possible somehow to export and import the configuration of custom toolbars between Tabular Editor 3 instances? 
I have TE3 at work and in my personal PC and it would be nice to update either way if I do some development on the toolbar

**Comment by otykier** [comment]
Sure it is!

Once you're happy with your toolbars, go to the **Window** menu and hit **Capture current layout**. Give it a name. Then, under **Window > Manage layouts...** you have the option of saving the layout you just created as a file. This is an XML file which can be shared and loaded into other instances of TE3, and it holds information about custom toolbars.
