### ISSUE TITLE
No authentication type option when importing tables / updating schemas

### ISSUE THREAD

**Issue by Javanite** [TabularEditor/TabularEditor3#262]
This is an issue when trying to update schemas or import tables. When you are prompted for credentials, you are only given the option to provide a username/password for SQL auth. If you are using, for example AAD with MFA, you have no way to choose that on the initial credential dialogue box. 

A workaround is to put in bad credentials, get an error, and then the NEW dialogue box that pops up does have the option to change auth type, which then you can now select AAD with MFA. 

![image](https://user-images.githubusercontent.com/19479604/137368043-c4362b7a-9a76-4aec-8edf-5b8960da85fa.png)

![image](https://user-images.githubusercontent.com/19479604/137367781-61df9ee4-6266-4fda-b1b6-09c60e61b99d.png)

![image](https://user-images.githubusercontent.com/19479604/137368104-8bcbeec0-2d04-4b98-a99f-80f5277b49af.png)

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
