### ISSUE TITLE
AzureAD Role Member Id value not generated during deployment

### ISSUE THREAD

**Issue by alwortman** [TabularEditor/TabularEditor3#263]
I'm getting the following error when deploying a model that contains an Azure AD role member.

`Deployment failed! The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'The newly created External RoleMembership object in role 'Everyone' for provider 'AzureAD' has no value specified for MemberID. MemberID must be specified when creating an External RoleMembership object.`

Issue happens with TE3 v3.1.4 as well as TE2 v2.16.4

Here is full command line input/output.
```
C:\Users\alwortma>start /B /wait C:\agent4\_work\5\s\TabularEditorPortable\TabularEditor.exe "C:\agent4\_work\5\s\Model.bim" -D "financedata_pp.intel.com" "FAE_BizProcessMetrics_Dev" -O -C -P -R -M -W -V

Tabular Editor 2.16.4 (build 2.16.7940.23396)
--------------------------------
Loading model...
Deploying...
##vso[task.logissue type=error;]Deployment failed! The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'The newly created External RoleMembership object in role 'Everyone' for provider 'AzureAD' has no value specified for MemberID. MemberID must be specified when creating an External RoleMembership object.
'..
##vso[task.complete result=Failed;]Done.
```

If you choose the "TMSL Script" option and inspect the role section you see this:
```
        "roles": [
          {
            "name": "Everyone",
            "modelPermission": "read",
            "members": [
              {
                "memberName": "Everyone",
                "memberId": "S-1-1-0"
              },
              {
                "memberName": "Azure AD - Everyone",
                "identityProvider": "AzureAD",
                "memberType": "group"
              }
            ]
          },.....
```
This is despite the fact that the model definition _does_ include a member id:
![image](https://user-images.githubusercontent.com/13524879/137400332-f0595667-4118-4d1a-b331-aa03b3c5758a.png)

If I manually add the memberId property to the TMSL deployment script the model is able to deploy without issue.

**Comment by otykier** [comment]
Hi @alwortman 
Apologies for the late reply.

Could you confirm that you are deploying the model to an instance of SQL Server Analysis Services? The reason I'm asking is that there seems to be a difference depending on whether the deployment target is Azure AS or SSAS. [The former complains when both MemberID and MemberName are provided](https://github.com/TabularEditor/TabularEditor/issues/906), and (apparently) the latter complains when MemberID is omitted.

If you can confirm that your target is indeed SSAS, it seems that we have to generate slightly different TMSL code depending on which type of instance we are targetting. Unfortunately, Microsoft hasn't documented this anywhere, to my knowledge :-(

**Comment by alwortman** [comment]
@otykier Yes this was deploying to SSAS.

The reason the value existed at all was that there was a period of time we were using something like the master model pattern to deploy (nearly) identical versions of the model to AAS and SSAS.

**Comment by otykier** [comment]
[3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6) now determines if the deployment is against Azure AS / Power BI and only then removes the MemberID property. When deploying against SSAS, MemberID is retained. Thanks for reporting!
