### ISSUE TITLE
Trying to save macro code with errors results in toolbar removing toolbar button

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#266]
So I have my macros, and my macro toolbar. Then I want to make a modification to one of the macros, so I double click it in the macro list, and start editing the code. Then I want to save the changes, but I forgot a ; or whatever. If says it cannot save it because it has errors but does not show where, and the button disappears. So you have to run it as a script, see it works, save it back as macro and put it back on the toolbar. Is this a bug or by design?

**Comment by otykier** [comment]
Fixed in [3.1.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.5). Thanks for reporting!
