### ISSUE TITLE
Option for Setting Max Parallelism on Refresh

### ISSUE THREAD

**Issue by EthanEverett** [TabularEditor/TabularEditor3#267]
For some models the data sources get overwhelmed due to the number of concurrent requests and will time out. We are able to control for this by deploying to SSAS and then specifying Max Parallelism when refreshing in SSMS via the code below:

    {
  "sequence": {
    "maxParallelism": 5,
    "operations": [
        {
          "refresh": {
            "type": "full",
            "objects": [
              {
					"database": "TabularModel"
              }
            ]
          }
        }
    ]
  }
}

Is a setting available for specifying Max Parallelism in TE? If so, any help is much appreciated.

**Comment by helgews** [comment]
This does not feel like an «issue». We also have Discussions available for topics.

Dont get me wrong, I think its great that you posted this, as we can learn from eachother!
