### ISSUE TITLE
Advanced Filtering in TE3

### ISSUE THREAD

**Issue by debashish10** [TabularEditor/TabularEditor3#27]
Hi @otykier,

Thanks for making TE3, it really is an awesome tool.
I have a question on Filtering in TE3.
In TE free version we can use the Filter functionality to perform advanced filtering :

![image](https://user-images.githubusercontent.com/55327056/120608834-413f1800-c46f-11eb-8f6f-a3e890963871.png)

I could not find that option in TE3, can you guide me if that is present in TE3.

**Comment by otykier** [comment]
I got you covered. Hit Ctrl+F to bring up the Find and Replace dialog. You'll see that it has a lot of cool options, and allows searching through specific properties only, even without using Dynamic LINQ.

But if you enter a `:` you will enable Dynamic LINQ mode, just like in TE2. Hit Enter and you'll see the search results in a separate window:

![image](https://user-images.githubusercontent.com/8976200/120623550-1bf6dd80-c460-11eb-9e2a-6ac15058aaa3.png)

**Comment by debashish10** [comment]
This is Great .
Thanks a lot Daniel .
