### ISSUE TITLE
Diagram View enhancement requests...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#275]
1) I use diagram view to make/edit my relationships. When in that view, the Save Model To Server or whatever button disappears. Would be nice to have it, rather than having to flip back to an expression editor tab.

2) Would be nice to be able to grab empty diagram canvas area to smoothly pan around the displayed tables (rather than having only mouse wheel/button. (ADF-style)

**Comment by otykier** [comment]
Panning by grabbing an empty canvas area is now available in [3.1.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.5).
