### ISSUE TITLE
Make folders searchable

### ISSUE THREAD

**Issue by ManuelMendozaLevo** [TabularEditor/TabularEditor3#276]
I was thinking that it would be nice if the TOM Explorer search could search folder names like PBI Desktop does as shown in the example below.
![image](https://user-images.githubusercontent.com/72710475/138340593-2a61ca30-af32-45ad-8a39-d1c6dabb7588.png)
When I type No Net it only shows elements that contains that keyword but not the whole content of the folder.

Great tool as always!

**Comment by otykier** [comment]
[3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6) now has an option that changes how filtering works. See the release notes for more details.
