### ISSUE TITLE
Is it possible to create a GIT for all the macros installed? 

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#277]
I hope this makes sense... 

The workflow for working with macros and improving them is not straight forward, if you also want to keep it in GIT

the easiest way I can think is:
- you double click the macro to get the script
- you make the modifications
- you save it back to modify the existing one, 
- but then you need to do save as and overwrite a file you have in a GIT folder

However if changes happen in the repository, it's not so easy to transfer this changes to the macro 

- you open the script from the repository
- you double click the macro to get the script
- you overwrite the macro script with the script of the repository (copy-paste)
- you save it back to modify the existing one, 

It is often the case that the button for the macro disappears, but I haven't nailed down all the cases in which this happens 

Regards and thank you for the awesome product (I don't post here all the times I'm thrilled to use it :D)

**Comment by otykier** [comment]
Closing this for now. If you need to version control your macros, the best solution for now is to set up your `%localappdata%\TabularEditor3` folder as a local repository with suitable ignore rules (i.e. ignore everything but the MacroActions.json file).

**Comment by bernatagulloesbrina** [comment]
Good point! Trying to sync all caused my macro toolbar to disappear
periodically, so better to stick to only the macros file
