### ISSUE TITLE
Privacy Setting - Deployment Failure

### ISSUE THREAD

**Issue by Stewwe1** [TabularEditor/TabularEditor3#28]
Hello Daniel!

I have the following problem right now:

When I open the same Bim file, the TE2 shows me in the PrivacySetting  "Organizational", but the TE3 shows "None". Strange.

If I now deploy the model, the TE3 deployed version is faulty:

"information is required to combine the data" (translated from German).

Help appreciated!

Stewwe

**Comment by otykier** [comment]
Any chance you could send the bim file to daniel@tabulareditor.com, so we can take a closer look?

**Comment by Stewwe1** [comment]
Hello Daniel,

We have discussed this a few times in the past:

Unfortunately, I'm not allowed to send the bim file even if we were to sign an NDA. I find it totally obstructive myself, because I could make it much easier for you. Sorry

**Comment by otykier** [comment]
Oh right - sorry, I didn't recognize the user name. Alternatively, would it be okay to share the .bim file if you create a copy where you remove everything except the problematic object, and blank out any sensitive property values? Be sure to open that .bim file in a text editor before sending it, so you can make sure it doesn't contain any sensitve data.

**Comment by Stewwe1** [comment]
Hello Daniel,

I don't think it's the bim file, but the workspace that overwrites the values in the bim file:

Step 1:

I open a BIM file and create a workspace. TE3 asks me which PrivacySetting I want to have. I enter "none" everywhere. In the BIM file, the editor says "none" everywhere.

Step 2
I want to correct the PrivacySetting because SSAS gives me the error mentioned above and I enter "Organizational" everywhere. This is then also saved correctly in the BIM file (checked with the editor).

Step 3
I close the TE3 and open it again, the workspace updates, but the privacy setting of the TE3 says "none", although the BIM file still correctly says "Organizational". If I now click on save, the "Organizational" in the Bim file is overwritten and everything is set to "none" again.

I have now helped myself by deleting the TMUO file and entering "Organizational" everywhere. But I still think that the entries in the Bim File should not be overwritten by the values of the Workspace, because otherwise you have no chance to correct them.

**Comment by otykier** [comment]
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.
