### ISSUE TITLE
The GUI freezes temporarily when starting to refresh partitions from a table when another refresh is still running

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#281]
To reproduce:

1. Select some partitions from a table, right click and select refresh
2. Select some partitions from a second table, right click and select refresh

Now the GUI freezes until the first refresh is done.
Note that occasionally the freeze won't occur until you do this on a third table while the first refresh is still running and the second one is in a queue.

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
