### ISSUE TITLE
Impersonation - selecting user creates an incorrectly formed account name 

### ISSUE THREAD

**Issue by thedaxshepherd** [TabularEditor/TabularEditor3#286]
Product level: Enterprise Edition
Build 3.1.7976.21016

On the Select Impersonation window if you select Impersonate User and use the ellipses which opens the AD Select User window this allows you to enter a user and have it resolve the name. When doing this it finds the user and returns the string "WinNT://ThePasture/dshepherd".  Using this user string returns no data. Running a trace on SSAS 2019 returns the following error: "The following system error occurred:  The name provided is not a properly formed account name. ". 

Editing the string I can get it to work if I change it to various combinations such as ThePasture\dshepherd"

I am not finding anything in preferences for locale or anything that would change forward slashes to backslashes.

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
