### ISSUE TITLE
Macro folders like in TE2?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#289]
Hi, I just saw in the useful snippets documentation the fact that you can define like folders for macros if the name has a structure like "Folder\Macro Name" 
https://docs.tabulareditor.com/te2/Useful-script-snippets.html#generate-time-intelligence-measures
does this work in TE3? any other way to group macros like this in a drop down menu?

**Comment by otykier** [comment]
Works in TE3 too!
