### ISSUE TITLE
Custom 11 & the Customization window within the Tools menu

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#29]
The following steps access the 'Custom 11' customization. 

1. Click 'Tools' in the File Menue
2. Click 'Customize'

* I think this is supposed to be an option to add/remove elements from the toolbar but it doesn't actually contain any elements to add or remove. 
* When viewing TE3 on a second monitor, the 'Custom 11' toolbar shows as separated from the regular toolbar.

![image](https://user-images.githubusercontent.com/29556918/120665063-1f0bc100-c494-11eb-84d1-1a0f91209dec.png)

* When clicking on items in the 'Customization' window, it is necessary to click twice on each checkbox in order to activate it. 
* When viewing TE3 on a second monitor, the 'Customization' window spills off the bottom of the screen. Can also see in the screenshot below how the 'Toolbars:' label spill into the list box below.

![image](https://user-images.githubusercontent.com/29556918/120665482-7d38a400-c494-11eb-8da4-36910b38f203.png)

**Comment by otykier** [comment]
- I believe the "Custom 11" toolbar is a remnant from a beta. Could you please try to close Tabular Editor 3, delete your `%localappdata%\TabularEditor3\Layout.gz` file, then restart it to see if it is gone?
- The "Toolbars" label spill is related to the UI scaling issues that arise when TE3 is moved between monitors that use different resolution/scaling settings, or if the resolution on your main monitor was changed (for example by plugging in an external monitor to a laptop), without logging out of your Windows account and back in.
- Will look into the "double click" issue.

**Comment by m-kovalsky** [comment]
I removed the Layout.gz file and now the Custom 11 toolbar does not show. Thanks!
