### ISSUE TITLE
Save password has no impact

### ISSUE THREAD

**Issue by OHelverskov** [TabularEditor/TabularEditor3#290]
When opening af model I'm allways prompted for the password. The user is saved, but the password is not. In this case it's an SQL user for en Azure SQL DB as the data source.

When i check the "Save password" box it has no impact. The next time i open the model i have to give the password again. 

![image](https://user-images.githubusercontent.com/88879415/140881156-9a3b29d8-bc91-4616-ade7-1428756039ae.png)

**Comment by mlonsk** [comment]
This issue should be solved in newer versions of Tabular Editor 3.
