### ISSUE TITLE
Apply Refresh Policy Option Missing?

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#291]
I might've missed something, but it looks like there is no quick option in TE3 to create the shell partitions for incremental refresh (when doing initial setup). Can someone point me to where this is?

![image](https://user-images.githubusercontent.com/62320770/141052931-52900265-f88e-48b7-99b1-662aaf59e5d4.png)

**Comment by otykier** [comment]
Yes, this is an oversight in TE3. It will be available in the next update.

As a work around, you can run the following script to apply refresh policy (once it is enabled on the table):

```csharp
Selected.Table.ApplyRefreshPolicy();
```

**Comment by samaguire** [comment]
Cheers 👍


Regards
Stephen

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!

**Comment by samaguire** [comment]
Perfect timing! 👍


Regards,
Stephen
