### ISSUE TITLE
Creating Calculation Groups - Calc Item Ordinals not correct

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#296]
This is with 3.1.5.

The script that is generated from right-clicking on a CG appears to be correct with the Ordinal values. I have one that is DAY, WEEK, MONTH, QUARTER, YEAR - 0 through 4.

the code has MONTH, YEAR, QUARTER, WEEK, and DAY in the order of the code, but the ordinals shown are 2, 4, 3, 1, 0, so it should work. But when it runs, it comes out DAY, MONTH, WEEK, YEAR, QUARTER.

I'm attaching an image showing the DAX script is correct, it just runs incorrectly.
![image](https://user-images.githubusercontent.com/45298358/141536925-7abdef5a-c330-4e0f-a7ef-62e90517c7b3.png)

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
