### ISSUE TITLE
Shortcut for expand/collapse items doesn't work on TOM Explorer

### ISSUE THREAD

**Issue by pgpaiva** [TabularEditor/TabularEditor3#297]
Hi Folks, 

The shortcut CTRL+Shift_Arrow to expand/collapse current node and all subnodes simply doesn't work on 3.15 Portable version. 

It is here on the shortcuts documentation for Explore Tree (TB 2). Is this feature not available on TB3 or is there a bug? 

Thanks! 

On TB2, I could collapse all opened folder under the _Metrics table by hitting CTRL SHIFT left. It simply doesn't work on TB3!
![image](https://user-images.githubusercontent.com/94234270/141649848-4f68bead-44e5-40bd-b42f-8ea380339f76.png)

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
