### ISSUE TITLE
Calculation Group DAX scripts do not create the calc group with the correct name

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#298]
Even though the column name is specified in the code it is not respected when executed, if you are creating the calculation group with it. 

![image](https://user-images.githubusercontent.com/40455069/141659272-49fb4875-eb52-4f04-947f-50c2f14dbe75.png)

**Comment by otykier** [comment]
Thanks, we’re already aware of this issue - a fix is imminent.

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
