### ISSUE TITLE
Tools -> Preferences

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#30]
When viewing TE3 on a second monitor and switching the theme to 'Bezier', the Navigating to 'Tools'->'Preferences' shows as a tiny window (can't see the options). If this doesn't happen the first time, try going to Tools->Preferences again. After this happens, switching it to other themes doesn't help. Only solution I found was to close and reopen TE3.

![image](https://user-images.githubusercontent.com/29556918/120665993-e7e9df80-c494-11eb-8420-e5fbc6ea9eaa.png)

![image](https://user-images.githubusercontent.com/29556918/120666980-b7567580-c495-11eb-9fb7-38d379ffb854.png)

**Comment by otykier** [comment]
This is a known issue with some of the skins provided by the UI vendor. We have a backlog item to provide our own custom skins to avoid this issue, but it's pretty low priority at the moment. Do the other skins work ok for now?

**Comment by m-kovalsky** [comment]
Ah yes, I remember the other issue we had with skins. I think the issue here is only with this skin. However, once you get this issue, going to any other skin does not make the issue go away. Thanks.

**Comment by otykier** [comment]
Hi @m-kovalsky
Do you still have this scaling issue with the Preferences dialog? In general, I believe that logging out of the current windows session and back in should solve it.

**Comment by m-kovalsky** [comment]
Just tried it and I no longer have the scaling issue. Thanks!
