### ISSUE TITLE
Undo doesn't work right

### ISSUE THREAD

**Issue by ManuelMendozaLevo** [TabularEditor/TabularEditor3#301]
I've noticed that sometimes when I'm working on a large DAX expression on the expression editor and want to undo my last action (ctrl + z ) it goes back way more than intended (and make me loose almost all my work). I'm currently on version 3.1.7976.21016

**Comment by otykier** [comment]
This has been mentioned before, unfortunately I haven't received a reproducible example yet. If you discover a way to consistently reproduce this issue, please let me know. Btw - remember that you can use Redo (Ctrl+Y) to undo the last undo operation - that way at least, you avoid losing your work.

**Comment by yu-eyerus** [comment]
@otykier 
I have found that this happens relatively consistently if I haven't saved. Undo goes back to my last save state instead of back one or two changes, if that makes sense.

**Comment by otykier** [comment]
Any chance you could provide a minimal pbix or bim file with step-by-step instructions on how to reproduce this? Thanks!

**Comment by otykier** [comment]
We believe we have solved the issue with Undo not working correctly in the DAX editor in [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2). Please let us know if the issue occurs again, thanks!
