### ISSUE TITLE
TE 3.1.5 Not updating measures in PBI Desktop on Save (TE)

### ISSUE THREAD

**Issue by tim-pluralgroup** [TabularEditor/TabularEditor3#303]
When copy, paste and then rename for a measure in TE the TE does not update the PBI Desktop model.
When I change/modify a measure in TE – same process is needed to update the PBI Desktop model.

Only after, when I go to PBI Desktop and pick “New Measure” (right click on folder and pick new measure ) does the recently created or changed measure from TE appear/update in the PBI Desktop measure list with the recent detail from TE.

In Prior versions of TE I only had to pick save and the measure from TE would update the model in PBI desktop. 

Now in TE 3.1.5 it does not.

Please advise.

**Comment by otykier** [comment]
In our experience, this is an issue with Power BI Desktop, which occurs randomly. Tabular Editor (or any other external tools) is not responsible for updating the field list in Power BI Desktop, after making a change. Instead, Power BI Desktop should detect that an external change has been made, and then refresh automatically.

Some things that may help:

-	Restarting Power BI Desktop
-	Ensuring that no objects have any errors (DAX expressions, etc.)
-	Ensuring that the model does not use auto date/time

Also, to rule out that v. 3.1.5 of Tabular Editor is causing the issue, could you check if an earlier version of Tabular Editor 3, or using Tabular Editor 2.x produces the same issue?
