### ISSUE TITLE
Where is "Apendix A"?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#305]
I was checking the documentation and it mentions a couple times "Apendix A" but could not find it. Where is it? 
![image](https://user-images.githubusercontent.com/40455069/142851139-90b40bc7-5959-43b3-af5c-36d464f8a771.png)

**Comment by otykier** [comment]
Looks like we accidentally deleted this content when moving our documentation to the new docs site. A backup of the old docs is available [here](https://github.com/TabularEditor/TabularEditor/wiki/TabularEditor.TOMWrapper/9b4a05d03c40e1ae9672b69cc1225cab32c562d3). We'll look into getting this moved to the new site.

**Comment by bernatagulloesbrina** [comment]
Thank you! looks like calculation groups and calculation items are not included?

**Comment by otykier** [comment]
No, unfortunately they weren't available last time that doc was generated. But in general, you can [refer Microsoft's docs for the AMO/TOM library](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular?view=analysisservices-dotnet), as classes and properties in TOMWrapper are largely identical.

**Comment by bernatagulloesbrina** [comment]
Oh, that's much better than what I managed to find by myself. anyway, I realized that checking each class in TE2 repository I could get what I wanted. Thank you!

**Comment by otykier** [comment]
Hi @bernatagulloesbrina - our new [Scripting API](https://docs.tabulareditor.com/api/index.html) docs site is now live!
