### ISSUE TITLE
UI is hiding key fields making the tool unusable 

### ISSUE THREAD

**Issue by DATAXYZLTD** [TabularEditor/TabularEditor3#308]
Some options and information not displaying properly and subsequently make it hard either to select the right option or read key information.
![Load data from Database](https://user-images.githubusercontent.com/74631654/143247651-3f93311a-9778-46e8-9767-74d2fdd51c4c.png)
![About Tabular Editor 3](https://user-images.githubusercontent.com/74631654/143247667-b9897689-79d9-4feb-89df-20deb47ab3f7.png)
![screen 1 resolution](https://user-images.githubusercontent.com/74631654/143247659-59ba8955-3e5c-46da-a1a7-b54b00da0a18.png)
![screen 2 resolution](https://user-images.githubusercontent.com/74631654/143247663-80ba35a4-c89e-499a-b9c4-fec09b3ed7c2.png)
![screen 3 resolution](https://user-images.githubusercontent.com/74631654/143247665-133de18a-4a66-4945-98ef-b47610ab0ac8.png)

**Comment by otykier** [comment]
This is a known issue. The problem arises when the display scaling or resolution is changed mid-session, such as when connecting or disconnecting an external monitor. In general, logging out of your Windows session and back in, then starting TE3 should solve the issue. We are working with our UI vendor on finding a better solution. See also #81

**Comment by mlonsk** [comment]
This issue should be fixed in newer version of Tabular Editor 3.
Do let us know if it reoccurs. 
Thank you
