### ISSUE TITLE
BPA - Show rule info

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#31]
Enhancement request: 

It would be great to right click on a rule within the Best Practice Analyzer window and have the option to view/edit the rule in the 'Manage BPA Rules'. Also for TE2!

**Comment by otykier** [comment]
Hi Michael

We would like to guard rule editing behind the "Manage BPA Rules" dialog box, to avoid users accidentally making rule changes. Moreover, it would be confusing that sometimes rule editing is not possible (for example when a rule is loaded from a remote source) - this is something that is made more clear in the "Manage BPA Rules" dialog.

I understand why this could be useful while authoring a larger number of rules, but this is irrelevant for >99% of users.

**Comment by m-kovalsky** [comment]
The main value here is to be able to view the rule descriptions without having to open a new window, scroll and find the rule. I've found that a significant number of BPA users do not read the descriptions because they don't know they exist (or how to find them). Having the descriptions (and reference link) be more easily accessible will only add value to the BPA.

**Comment by otykier** [comment]
Would a tooltip suffice? Or perhaps an additional column in the BPA view?

**Comment by m-kovalsky** [comment]
Currently, a tooltip already exists (when hovering over an object within a rule it shows the rule description). But I'm not sure people actually see this (unfortunately). 

Perhaps adding a right click dropdown on a rule (or object) with 'View Rule Details'? And could have an icon as well along the top. Just an idea, not sure the best design choice here. I think an extra column in the BPA with the rule description would be too much (long text and repeated for every object within a rule).
