### ISSUE TITLE
Can no longer publish pbix files to the service where a "Detail Rows Expression" has been set

### ISSUE THREAD

**Issue by DirkVanderStraeten** [TabularEditor/TabularEditor3#310]
PBI Desktop Nov'21
"Detail Rows Expression" was set by Tabular Editor build 3.1.7998.273

After you have set a "Detail Rows Expression" on either table or measure, you can no longer publish the file.

When publishing the file to a workspace you receive an error: An error occurred while attempting to publish ‘file name.pbix’: The remote server returned an error. (400) Bad Request.
If you remove the property from the file, you can publish the file without any problem.

The problem can also originate from the PBI Service, but since I just updated TE3, best to start here.

Dirk

**Comment by otykier** [comment]
Adding DetailRowsExpressions to a pbix file is not among the [modeling operations currently supported by Desktop](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations). In any case, the issue is not specific to Tabular Editor as you could trigger the same issue by adding detail rows through other tools.

**Comment by DirkVanderStraeten** [comment]
Hi Daniel,

So I should log a ticket @ Microsoft, that they no longer accept this property when publishing the pbix file.
I just wanted to make sure that there is not an issue with the file format TE3 creates when using "Detail Rows Expressions" because I just upgraded to the latest release.

Dirk

**Comment by DirkVanderStraeten** [comment]
Oh Daniel,
In the link you provided I can reeds this
Supported write operations
Define and edit measures for calculations, including format string, KPI, and **detail rows settings**.

So I would think that it is a supported operation, or am I missing something.

/Dirk

**Comment by otykier** [comment]
Good catch. It should be supported then. Still has nothing to do with TE though, as it solely uses the client library provided by Microsoft to make changes to the model metadata (TE doesn’t touch the pbix file directly).
