### ISSUE TITLE
Semantic Analysis produces unnecessary error message? (function ... has been used in a scalar predicate filter expression)

### ISSUE THREAD

**Issue by V-PL** [TabularEditor/TabularEditor3#311]
Hello, 

The Semantic analysis seems to possibly have incorrect error message when using aggregate function in the short form in calculate.

Reproduceable as follows:

Table contains columns `'Table'[Index]` and `'Table'[Value]` , and measures 

`[Sum of value] := SUM ( 'Table'[Value] )`

and 

`[Cumulative sum] := 
CALCULATE(
    [Sum of value],
    'Table'[Index] <= MAX( 'Table'[Index] )
)`

Technically all works correctly (as indicated in the picture below)

![image](https://user-images.githubusercontent.com/95224955/143869658-e5b2d5da-cd5e-40d3-a220-23841f243d02.png)

But an error message is produced

![image](https://user-images.githubusercontent.com/95224955/143870187-8cbfa8ea-56d4-4c44-8e1b-4bb1b87acf96.png)

DAX editor settings tested with auto-detect as well as with below

![image](https://user-images.githubusercontent.com/95224955/143870754-0a06e81e-4033-4cf1-8f4b-eaa84ade5fea.png)

Thank you for your assistance with this.

**Comment by otykier** [comment]
Hi @V-PL. Thanks for reporting this. Could you confirm that the error only appears in the "Messages View" and not in the DAX code editor?

**Comment by V-PL** [comment]
Thank you for your quick response @otykier!

Indeed, as a confirmation, the first screenshot screenshot is with the auto-detect settings --> only the message view "complains" :)
![image](https://user-images.githubusercontent.com/95224955/143880843-1a970a56-460d-4689-a9d0-a4ab47fb204f.png)


When I set the Measure/Agg Shortcut setting to "Never allow", the error messages are as below and the code is marked in the editor

![image](https://user-images.githubusercontent.com/95224955/143880757-a5ac51a4-dad6-4260-a6a4-d019a844852d.png)

**Comment by otykier** [comment]
Fixed in [3.1.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.7). Thanks for reporting!
