### ISSUE TITLE
FormatDax function isn't respecting shortFormat option

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#314]
As per the title. Setting this option to false as per post https://github.com/TabularEditor/TabularEditor3/issues/307#issuecomment-983601810 isn't working.

i.e. `FormatDax(m.Expression, shortFormat: false);` still returns a short line format

**Comment by dybzon** [comment]
This is fixed in our next release (3.1.7). The issue was introduced with the offline dax formatter in release 3.1.5, as you noted yourself. Using the online dax formatter could be a work-around until next release is out.

Thanks for reporting this.

**Comment by otykier** [comment]
[3.1.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.7) released. Thanks for reporting!
