### ISSUE TITLE
Saving to the model fails to show changes in Power BI Desktop

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#317]
Hi, 

lately I'm experiencing some issues, in which the changes made by tabular editor are not shown in power bi desktop. Saving the file, closing and reopening it "solves" the issue, but it's quite a nuisance 

I don't have a clear cut way to replicate the issue, it happened to me now when saving a calc group to the model.

**Comment by otykier** [comment]
This is an issue with Power BI Desktop. It has been raised before, both for TE2 and TE3. See #303.
