### ISSUE TITLE
Expression Editor is gone

### ISSUE THREAD

**Issue by janey5712** [TabularEditor/TabularEditor3#318]
When I opened the Tabular Editor 3 and clicked the expression editor, it didn't show the pane and it's grey. I closed and open the desktop app again, still cannot see it.

**Comment by otykier** [comment]
Which version of TE3 are you using? As a workaround, try to delete the Layout.gz file in your `%localappdata%\TabularEditor3` folder.

**Comment by janey5712** [comment]
It worked! thank you!

**Comment by otykier** [comment]
@janey5712 could you let us know which version of TE3 you were using?

**Comment by douatwork** [comment]
I had this  same issue. Deleting Layout.gz also worked for me.

**Comment by janey5712** [comment]
My version is 3.1.6
I got a new problem not sure if it's because I deleted Layout.gz file. 
After I made changes in Tabular Editor, the changes will not automatically sync to the POWER BI Desktop until I closed the pbix file and reopened it again. I've clicked the save change button.
Does someone have same issue? Thank you ahead!

**Comment by otykier** [comment]
Hi @janey5712 
This is unrelated to deleting the Layout.gz file. Please see #317.

**Comment by otykier** [comment]
This issue is now fixed in [3.2.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.0). Thanks for reporting!
