### ISSUE TITLE
Issue with /* */ comment construct

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#319]
Looks like TE3 repeats the comments created with /* */ construct after the comment is enclosed in the DAX code. Difficult to explain with words so I recorded a quick video.

https://user-images.githubusercontent.com/73054674/145673214-a39725db-dbcd-46c8-9fa0-32f29c358b81.mp4

**Comment by otykier** [comment]
Thanks for reporting. We'll look into that!

**Comment by otykier** [comment]
Fixed in [3.1.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.7). Thanks for reporting!
