### ISSUE TITLE
TRANSLATIONS

### ISSUE THREAD

**Issue by jmsamso** [TabularEditor/TabularEditor3#320]
Hi,

I just downloaded and installed Tabular Editor (v2 and v3).

So I translated my pbix (ES, FR), but when I save nothing happens in Power Bi. Of course, I change the locale and then I close and reopen Power BI desktop.

Can someone tell me?

Best regards

Jean Marc

**Comment by otykier** [comment]
Power BI **Desktop** does not support displaying translations: https://tabulareditor.github.io/2020/08/11/MultilingualPowerBIDatasets.html#publishing-the-dataset

To test them, you would either have to connect to the model using Excel and specify the LocaleIdentifier in the connection string, or you must publish your report to the Power BI Service: https://www.kasperonbi.com/setting-up-translations-for-power-bi-premium/
