### ISSUE TITLE
DAX Script Ignores Comments at end of DAX

### ISSUE THREAD

**Issue by MattAlington** [TabularEditor/TabularEditor3#323]
I created a video showing the problem. https://www.dropbox.com/s/jnzgvu43d2nxrj6/dax%20script.wmv?dl=1

when I script DAX, eg

SUM(Sales[Amt])

If I try to add comments
SUM(Sales[Amt])  //add a comment

the comment doesn't get added by the script

**Comment by otykier** [comment]
Fixed in [3.1.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.7). Thanks for reporting!
