### ISSUE TITLE
Help needed: How to refer to the model from a class function in a custom dll

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#325]
I keep trying to build a function repository in a custom dll. 
I managed to do a trivial one with just strings, but stuck when trying to do something more sophisticated. 
Even making a function that returns the number of tables in the model does not seem to work --- 

When coding the class it throws an error if I just refer to "Model" so I tried to pass the model as one of the arguments, but this is not working either 

this is the class

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TabularEditor.TOMWrapper;
using TabularEditor;

namespace ExtendedTOMWrapper
{
    public static class TableUtils

    {
        public static int TableCount( Model model)
        {
            return model.Tables.Count; 
        }
    }
}
```

when I try to execute 

```
#r "C:\Users\berna\OneDrive\Documentos\GitHub\ExtendedTOMWrapper\ExtendedTOMWrapper\bin\x64\Debug\ExtendedTOMWrapper.dll"

//#r "ExtendedTOMWrapper.dll"
using ExtendedTOMWrapper;

if (Model.Tables.Count>0 ) {
    Info("tables present (direct reference");
};


if(TableUtils.TableCount(Model) == 0)
{
    Info("Tables present (dll function)"); 
}; 
```

I get this error 

> Script Execution Failed
> 
> Could not load type 'ExtendedTOMWrapper.TableUtils' from assembly 'ExtendedTOMWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Is possible to do what I am trying? Am I missing something? 
I already changed the framework of the dll to 4.7.2

**Comment by otykier** [comment]
I generally find it easiest to copy over the custom dll into the installation directory of Tabular Editor 3 - this way, all the DLL's that might be referenced by your custom dll (such as TOMWrapper.dll, etc.) are guaranteed to be the same version as those that are already loaded by TE3.

When doing so, I have no issues passing the Model object into my custom dll, as seen on the screenshot here:

![image](https://user-images.githubusercontent.com/8976200/146744725-9db68ec8-7d10-410f-a6e3-ed257b73d2cf.png)

**Comment by bernatagulloesbrina** [comment]
Nice, this one works too 
Do I need to close and open Tabular Editor when updating the dll in the home folder?

**Comment by otykier** [comment]
> Do I need to close and open Tabular Editor when updating the dll in the home folder?

That shouldn't be necessary, as the script is re-compiled each time you hit the "Run" button.
