### ISSUE TITLE
Help needed: Optional arguments not allowed in custom class dll? 

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#326]
Hello again, 
In order to create a convenient repository of custom functions in a dll, I need to be able to use optional parameters. I'm quite new to C# so I might be missing something obvious, but the moment I define arguments as optional in the StringUtils class, the script that uses it fails to execute, even informing all arguments, very weird. 

Is it possible to use optional arguments in this setting? 

this code (all named arguments just in case)
```
#r "C:\Users\berna\OneDrive\Documentos\GitHub\ExtendedTOMWrapper\ExtendedTOMWrapper\bin\x64\Debug\ExtendedTOMWrapper.dll"

using ExtendedTOMWrapper;
string myString; 
if(
    !StringUtils.InitString(
        prompt: "Provide a name", 
        label: "Name", 
        defaultValue: "Default Name",
        errorMessage: "Invalid name" ,
        stringToInit: out myString
    )
){return;}; 
```

works fine when the class is like this 
```
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ExtendedTOMWrapper
{
    public static class StringUtils
    {
        public static bool InitString
            (
                string prompt,
                string label, 
                string defaultValue,
                string errorMessage,
                out string stringToInit
                
            )
        {
            stringToInit = Interaction.InputBox(prompt, label, defaultValue, 740, 400);

            if (string.IsNullOrWhiteSpace(stringToInit))
            {
                MessageBox.Show(errorMessage, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            };

            return true;
        }
    }
}
```

but fails if the class is like this 

```
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ExtendedTOMWrapper
{
    public static class StringUtils
    {
        public static bool InitString
            (
                string label, 
                string defaultValue,
                string errorMessage,
                out string stringToInit,
                string prompt = "default prompt"
                
            )
        {
            stringToInit = Interaction.InputBox(prompt, label, defaultValue, 740, 400);

            if (string.IsNullOrWhiteSpace(stringToInit))
            {
                MessageBox.Show(errorMessage, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            };

            return true;
        }
    }
}
```

the error is: 

> Script Execution Failed
> 
> Method not found: 'Boolean ExtendedTOMWrapper.StringUtils.InitString(System.String, System.String, System.String, System.String ByRef, System.String)'.

**Comment by otykier** [comment]
You have to specify `out` in front of the output parameter when calling into the method:

```csharp
var stringToInit = "";
StringUtils.InitString("label", "defaultValue", "errorMessage", out stringToInit);
```

**Comment by otykier** [comment]
I was not able to reproduce this error:

![image](https://user-images.githubusercontent.com/8976200/146743961-6bbbaa24-ab1f-4848-9e7f-0c2ffac672f6.png)

Perhaps you are referencing a wrong version of the dll?

**Comment by bernatagulloesbrina** [comment]
problem is not on the script side -- the problem is when I define an optional parameter in the class it stops working even if I specify all arguments  -- (In the version of the dll I sent you weeks ago there are no optional parameters.) 

if I don't specify all arguments it says it does not find any function that matches the call 

are optional parameters supported? 

here is the dll. 
https://drive.google.com/file/d/16QcrMBFiKOg926MZINlH2rH4eCpA-B8W/view?usp=sharing

and here the entire solution 
https://drive.google.com/file/d/16kuZ1krLOBDOExuqCW5961HDfq7sDyv6/view?usp=sharing

**Comment by otykier** [comment]
They should be supported, yes. Here is a screenshot where I omit the "prompt" argument - as you can see it still works:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8976200/146789398-46395c92-fe17-4f96-b484-ac565fc0f422.png">

**Comment by bernatagulloesbrina** [comment]
This is so frustrating. I develop a bit, something does not work, I post it here, it works on your side, and then for some reason it works on my side too. I tried and now it works fine with the dll in the Tabular Editor 3 folder, or in the Visual studio project folder the same. Oh well, at least it does work, so I guess I'm happy 😁
