### ISSUE TITLE
Application crashes at launch

### ISSUE THREAD

**Issue by jnissley** [TabularEditor/TabularEditor3#328]
Ever since a Windows 10 update was installed a few weeks ago, TE3 (latest version 3.1.7) crashes every time I launch it. 

I have copied in the error I am seeing in Event Viewer.  Any ideas on how I might fix it?

   
Log Name: Application   
Source: .NET Runtime   Date: 12/17/2021 8:29:33 AM   Event ID: 1026   Task Category: None   Level: Error   Keywords: Classic   User: N/A   Computer: DL08WIN10T470s.Delawarelife.com   Description:   Application: TabularEditor3.exe   Framework Version: v4.0.30319   Description: The process was terminated due to an unhandled exception.   Exception Info: System.NullReferenceException   at   TabularEditor.Shared.Services.Preferences.Load(TabularEditor.Shared.Services.ISimpleMessageDialogService)   at   TabularEditor.Shared.Services.Preferences.GetPreferences(TabularEditor.Shared.Services.ISimpleMessageDialogService)   at TabularEditor.Shared.Services.Telemetry.TrackException(System.Exception,   System.String, System.Collections.Generic.IDictionary`2,   System.Collections.Generic.IDictionary`2)   at TabularEditor.Program.Application_ThreadException(System.Object,   System.Threading.ThreadExceptionEventArgs)   at   System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)   at System.Windows.Forms.Control.WndProcException(System.Exception)   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)   at   System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr,   Int32, Int32)   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32,   System.Windows.Forms.ApplicationContext)   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32,   System.Windows.Forms.ApplicationContext)   at TabularEditor.Program.Main()
--

</body>

</html>

**Comment by otykier** [comment]
Hi @jnissley 
Thanks for reporting. We'll investigate. To help us track down the issue, it would be helpful if you could share your `Preferences.json` file from within the `%localappdata%\TabularEditor3` folder.

After sharing the file, try to delete or rename it and then try to launch Tabular Editor 3 again.

**Comment by jnissley** [comment]
Preferences.json was empty. I deleted it, and that did the trick. TE3
launches normally, and it created a new (non empty) Preferences.json.

Thanks!

**Comment by otykier** [comment]
Fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!
