### ISSUE TITLE
error when choosing measure and duplicating it by clicking ctrl+C => cntrl+V

### ISSUE THREAD

**Issue by bogomda** [TabularEditor/TabularEditor3#33]
I got error when clicking on the measure clicking ctrl+C and then Cntrl+V trying to duplicate the measure

![image](https://user-images.githubusercontent.com/66798479/120742530-0a93ec80-c4c5-11eb-90b0-a9d94224f122.png)

**Comment by otykier** [comment]
The issue has been identified and a fix is imminent. Thanks for reporting!

**Comment by otykier** [comment]
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.
