### ISSUE TITLE
M engine error

### ISSUE THREAD

**Issue by koltachin** [TabularEditor/TabularEditor3#333]
![image](https://user-images.githubusercontent.com/46677876/148051213-95017367-0399-49a6-9275-c7e6ed45ba96.png)

get constantly this message not able to update the power BI file

**Comment by otykier** [comment]
Hi Koltachin,

Are you connecting Tabular Editor 3 to Power BI Desktop? In that case, please be aware that adding/editing/deleting tables or partitions is [not supported by Microsoft](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations).

If the error appears even when you have not made a change to any tables in the model, please describe exactly what you were doing, which caused the error to appear. Thanks!

**Comment by otykier** [comment]
Hi @koltachin - have you seen my reply above?
