### ISSUE TITLE
PowerShell & TSML scripts against a Power BI Premium Data Model

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor3#339]
Hi,

Is anyone aware of any PowerShell libraries that can execute TSML scripts against a Power BI Premium Data Model? 
 
I’m trying to process the data models after the CI/CD deployment where I have Incremental Refresh Policies, and I need to Force the Effective Refresh date to get a complete data load.
 
I thought of using Invoke-ASCmd, what's your approach?

Regards

Toby.

**Comment by otykier** [comment]
This question is not really related to Tabular Editor (consider posting it to https://github.com/Microsoft/Analysis-Services instead). Personally, I would use Invoke-ASCmd, as this provides the most flexibility. If you need to initate an async refresh you can use the new [REST API](https://docs.microsoft.com/en-us/power-bi/connect-data/asynchronous-refresh).
