### ISSUE TITLE
Table variables with 2 or more columns aren't accessible inside TOPN

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#34]
Inside TOPN I am unable to access table variable that contains 2 or more columns.

https://user-images.githubusercontent.com/73054674/120754434-4a40ef80-c52a-11eb-9e7f-ff8be416f223.mp4

Table variable is available once instead of whole table I only use a single column

https://user-images.githubusercontent.com/73054674/120754892-e2d76f80-c52a-11eb-8ae5-ecd62150c014.mp4

Also, if you notice, in an argument where TOPN expects scalar value, IntelliSense is suggesting table variables, and DESC keyword also isn't shown in Intellisense.

Please let me know what you think.

**Comment by otykier** [comment]
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.
