### ISSUE TITLE
Diagram - font scaling issue

### ISSUE THREAD

**Issue by albegouws** [TabularEditor/TabularEditor3#351]
I am running v3.1.7.  My monitor scaling is set to 100% on a 4K monitor.

When creating a diagram the column names in the table doesn't look scaled correctly, the font size looks bigger than the height allowed.

![image](https://user-images.githubusercontent.com/29041479/150108128-a9913a13-bea7-411c-acff-ada38eb46366.png)

Changing theme or palette has no impact on this. 

The rest of the app is displayed correctly.

**Comment by otykier** [comment]
Thanks for reporting - we'll look into it!

**Comment by otykier** [comment]
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!
