### ISSUE TITLE
Metadata Synchronisation Does not Work

### ISSUE THREAD

**Issue by PtrckGuo** [TabularEditor/TabularEditor3#353]
Hi,

I ticked all the checkboxes under Metadata Synchronisation, including "Refresh local Tabular Object Model metadata automatically". But after I added a test measure in PBI Desktop, TE3 only shows the initial blank measure that PBI added when I clicked "New Measure" button. Is the auto refresh feature supposed to synchronise measure name and DAX code as well?
![Auto Refresh Fail](https://user-images.githubusercontent.com/98067535/150246906-122d6a98-1a54-4e5a-98ad-f9ea71f8e2f3.jpg)

**Comment by otykier** [comment]
Yes, it is supposed to detect also name and DAX code changes. The way it works is that Tabular Editor subscripes to Analysis Services trace events. Unfortunately, there are situations where these trace messages do not arrive, which we have no control over. When this happens, please use the **File > Revert** option, to load the most updated metadata from Desktop.

**Comment by PtrckGuo** [comment]
Thank you @otykier for replying.

I don't understand why TE2 doesn't have this issue if it is caused by something only under Microsoft's control.
![TE2](https://user-images.githubusercontent.com/98067535/150332192-fb642f86-e65f-4579-8293-6dab0db54126.jpg)

**Comment by otykier** [comment]
@PtrckGuo thanks for getting back. It should work the same in both TE2 and TE3. Any chance you could share the .pbix file (or just the .pbit file without any data), so we can try to reproduce the issue at our end? In that case, please sent it directly to me: daniel@tabulareditor.com

**Comment by otykier** [comment]
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!
