### ISSUE TITLE
Call Tree - font scaling issue with HDPI monitor

### ISSUE THREAD

**Issue by marcosqlbi** [TabularEditor/TabularEditor3#355]
Issues in visualization with a 4K monitor and 200% scale factor.

![image](https://user-images.githubusercontent.com/13840816/150306360-2f3987f7-c855-4fe8-a64a-ea1f76290633.png)

![image](https://user-images.githubusercontent.com/13840816/150306462-cf51cd10-bcb6-4537-ac33-31ad124f9696.png)

**Comment by otykier** [comment]
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!
