### ISSUE TITLE
Issues with Vertipaq Analyzer when using a Import mode Model

### ISSUE THREAD

**Issue by Koushikrishnan** [TabularEditor/TabularEditor3#356]
Hello,

I have been making some changes on one of our Models and trying out the Vertipaq Analyzer to look at the table/column sizes. This is an Import mode model and it has been the same all the time.
Today, when I connected to this model again and was pulling up the 'Collect Stats' via the Vertipaq Analyzer I received this error suggesting this feature doesn't work in Direct Query Mode:

![image](https://user-images.githubusercontent.com/87026967/150413148-839a8120-8d6d-47d4-8558-ee1ab47777de.png)

Could you please check into why this would happen? Let me know if you need more details to look into this.

Thank you.

**Comment by marcosqlbi** [comment]
Do you have one or more tables in DirectQuery? Or did you enable a composite model connecting an external Analysis Services or Power BI database?

**Comment by Koushikrishnan** [comment]
Hello @marcosqlbi ,

We do have one minor table which has been in DirectQuery mode for almost 8 months on the model. Nothing has ever changed on that. Also, we have never seen this error earlier though and it just popped up yesterday.

I tried the Vertipaq Analyzer via DAX Studio for the same model and it worked though. So we are not sure what exactly changed to cause this error on TE3.

Thank you.

**Comment by marcosqlbi** [comment]
Probably you have the following setting disabled in DAX Studio, by enabling it you should see the same issue.
<img width="287" alt="image" src="https://user-images.githubusercontent.com/13840816/150556831-fea14dd0-dd56-4e34-9300-b1ecef9f2327.png">

You can disable this setting in TE3, too:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/13840816/150557557-24c24579-0dee-4dc3-8dde-f176e457aa4b.png">

**Comment by Koushikrishnan** [comment]
@marcosqlbi  : Great thanks, this resolved the issue!
