### ISSUE TITLE
Defnine Translated Display Folders for x selected measures

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#359]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/74975641/150780466-db80ad8d-530f-431a-9038-830a798ede78.png">

it is currently not possible to define translations for displays folders for multiple selected measures. I currently do this measure by measure

**Comment by otykier** [comment]
Transferred to [TE3 issues](https://github.com/TabularEditor/TabularEditor3/issues).

**Comment by otykier** [comment]
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!
