### ISSUE TITLE
DATEADD's 3rd argument shows additional options

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#36]
DATEADD's 3rd argument should only show YEAR, MONTH, QUARTER, DAY, but TE3's IntelliSense goes below the day granularity.

![image](https://user-images.githubusercontent.com/73054674/120765018-664a8e00-c536-11eb-8afc-79900c915c84.png)

**Comment by otykier** [comment]
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.
