### ISSUE TITLE
[TE 3.2.0] - The Data Refresh progress indicator doesn't update automatically

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#360]
_Really_ not a big deal, but the progress indicator animation doesn't update unless you click something or move out of and then back into the Data Refresh tab.
![image](https://user-images.githubusercontent.com/31990588/150987249-49733983-e2f6-48cc-942b-9774e3e5e9b7.png)

**Comment by otykier** [comment]
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!
