### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by awg04** [TabularEditor/TabularEditor3#362]
I keep getting the following error message when opening version 3.2.0

**Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index**

The update was working fine over the weekend but suddenly I get the error message.  

My Model loads fine in v3.1.7 portable

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.2.0 (3.2.8055.2602)
OS version: Microsoft Windows NT 10.0.22000.0
Model details: 
		CompatibilityLevel: 1550
	CompatibilityMode: PowerBI
	IsPbiDesktop: True
	SourceType: Database
	TableCount: 80
	FirstTimeModelLoad: False
	DatabaseNameSHA256: 308b3c35f1be918f352d654a28a57fb73a51d81dd3c69299
	ServerVersion: 16.0.5.24
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: Enterprise64
	ServerNameSHA256: d7460151085974e32db25dcec284937a11765577bb1b8fe2
User description: 
Exception message: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
Exception source: System.Windows.Forms
Stack trace:    at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at TabularEditor.UI.ViewModels.TabularExplorerData.TreeListFullRefresh()
   at TabularEditor.UI.Views.TabularExplorerView.ModelManagerService_SemanticAnalysisCompleted(Object sender, SemanticAnalysisCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
Modules loaded: 
		tabulareditor3.exe

**Comment by otykier** [comment]
See #357
