### ISSUE TITLE
Dependencies won't update with model refresh

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#364]
TE 3.2.0.

If I right-click on a column (normal or calculated) and a calculated column is dependent on it, that shows up in the dependencies. All good.

Then if I change the DAX in the dependent calculated column in Power BI desktop, save the column, then Refresh the model in TE/3, right clicking on the original column still shows the calculated column as being dependent. The only fix is to close and reopen TE/3. Then right-clicking on the original column no longer has the calc column as a dependent.

I run across this trying to clean up excessive calc column models I inherit quite often lately.

**Comment by otykier** [comment]
Good catch - that's a bug. We'll fix it!

**Comment by otykier** [comment]
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!

**Comment by edhans** [comment]
Hi @otykier can you please open this back up. Working on cleaning up calculated columns again today and with 3.2.1 the dependency view isn't updating. I have to close/reopen T/E to reflect changes in calc columns. The DAX is visible and fine, just appears to be the dependency tree.
