### ISSUE TITLE
[TE 3.2.0] - "Replace existing table" causes TE to close without warning

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#368]
The first time you do this operation, everything works. But the second time you try to replace a table in the same session TE closes without any warning.
![image](https://user-images.githubusercontent.com/31990588/151359026-f0db427a-1770-4962-9ad8-7a087ad841d6.png)

**Comment by eybert** [comment]
Perhaps I should mention that I was replacing a version of the table where the source was a dataflow with a Calculated table using DATATABLE().

**Comment by otykier** [comment]
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!
