### ISSUE TITLE
When initiate Dax Debugger, I receive an "Unhandled exception encountered" 

### ISSUE THREAD

**Issue by INPROV-davechupp** [TabularEditor/TabularEditor3#369]
Connected to Power BI Desktop dataset. Tried on different Power BI Desktop reports, some Dax Debugger works, some don't. The ones that don't have a more complex data models. 

![image](https://user-images.githubusercontent.com/32465441/151421282-0a24d771-3749-4bd5-a36f-9067cffa050c.png)
![image](https://user-images.githubusercontent.com/32465441/151421649-b0e9b47b-5676-4c05-977c-03bad661f467.png)

[Tabular Editor Unhandled Exception Error Report.txt](https://github.com/TabularEditor/TabularEditor3/files/7952947/Tabular.Editor.Unhandled.Exception.Error.Report.txt)

**Comment by otykier** [comment]
Thanks for sharing the error report. We will look into it. If you are able to provide a minimal .pbix file that can be used to reproduce the error, that would be very helpful!

**Comment by otykier** [comment]
This should now be fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Please let us know if you still encounter any issues, thanks!

**Comment by INPROV-davechupp** [comment]
Thanks! I verified, it fixed the issue that I had!
