### ISSUE TITLE
Add ability for comment shortcut

### ISSUE THREAD

**Issue by pugliathomas** [TabularEditor/TabularEditor3#371]
Please add the Ctl+Shift+K and Ctrl+Shift+U for comment / uncomment as in PBI Desktop and SSMS

**Comment by yu-eyerus** [comment]
Also looking for a comment/uncomment shortcut. Although would prefer CTRL+/ to be consistent with PBI Desktop and DAX Studio.

**Comment by otykier** [comment]
Short-term, we'll add a shortcut for comment / uncomment which will align with VS comment/uncomment. Longer term, all shortcuts will be configurable.

**Comment by Rasenkantenstein** [comment]
Adding to that feature i'd also suggest to implement other shortcutes from the Microsoft Universe:
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

* Alt + Arrow Up and down -> easily shuffle the coloumns in quries
* Ctrl+Shift+K -> remove line

**Comment by otykier** [comment]
Next update (3.2.2) will add Ctrl+Shift+K and Ctrl+Shift+U for commenting/uncommenting respectively.

@Rasenkantenstein note that today, the following shortcuts already exist:

- Ctrl+T: Transpose line (i.e. swap current line with line above)
- Ctrl+L: Delete current line
- Ctrl+D: Duplicate current line

**Comment by otykier** [comment]
@yu-eyerus note that you can already toggle line comments today using Ctlr+/

**Comment by otykier** [comment]
In addition to the shortcuts mentioned above, we now also have the following shortcuts in [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2):

- Ctrl+Shift+K: Comment selected lines
- Ctrl+Shift+U: Uncomment selected lines
- Alt+Up Arrow: Move selected lines up
- Alt+Down Arrow: Move selected lines down

**Comment by otykier** [comment]
By the way, we've added an overview of all current keyboard shortcuts in TE3 [here](docs.tabulareditor.com/te3/features/shortcuts.html).

**Comment by yu-eyerus** [comment]
@otykier The ctrl+/ shortcut doesn't toggle comments for me in v3.2.2. It has the same behaviour as ctrl+left arrow.
