### ISSUE TITLE
[TE 3.2.1] - Show missing keys, invalid rows and sample RI violations in Vertipaq Analyser Relationships view

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#372]
I can do this in DAX Studio, but it would be very convenient to have all these columns in TE as well.

DAX Studio:
![image](https://user-images.githubusercontent.com/31990588/151565191-1793a864-1b2d-4748-86f9-b328d27b046d.png)
TE:
![image](https://user-images.githubusercontent.com/31990588/151565225-4899d012-40b5-4d5c-9f4f-8b495ba57d59.png)

There's already an option in TE on how many RI samples you want, but nowhere to see them (as far as I can tell... :-) )
![image](https://user-images.githubusercontent.com/31990588/151565396-8ebecfa1-94aa-4410-b782-e8d40eaf546c.png)

**Comment by helgews** [comment]
Agree! This would be phenomenal 👌🏼

**Comment by otykier** [comment]
RI violations are shown on the **Tables** tab, but I agree that we should have the same metadata shown for Relationships as DAX Studio does.

**Comment by otykier** [comment]
[3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2) now presents the same information in VertiPaq Analyzer as DAX studio does. Thanks for reporting.
