### ISSUE TITLE
Format Document and other options show as available, even though the expression is read-only

### ISSUE THREAD

**Issue by totangZP** [TabularEditor/TabularEditor3#378]
License: Enterprise license given by SQLBI (Mastering Tabular Course)
OS: Windows 11
Tabular Editor Version: 3.2.1

Issue:
I can't edit the calculated table or format it in the Expression Editor.

In the gif is I was trying to click the DAX Formatter and try to type in the Expression Editor.
![TabularEditor1](https://user-images.githubusercontent.com/65884271/151653851-97fbaa3d-f862-421e-b1b4-c723563ffd10.gif)

Also, I can't format the expression in debug mode (put the comma in front of the line)

![image](https://user-images.githubusercontent.com/65884271/151653831-6d9bd434-d9b0-4b0c-ac27-c5120676a21f.png)

Have tried to delete the 'layouts,gz' file from '\Local\TabularEditor3' folder also uninstall and re-install the Tabular Editor.

Didn't work in either way.

Let me know if you need more information.

**Comment by otykier** [comment]
Editing calculated table expressions is not among the [supported write operations](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations) when editing a Power BI Desktop model. As such, Tabular Editor makes the calculated table expression **read-only** by default.

We have a small bug in that the "Format Document", etc. options should be visible disabled (grayed-out) when an expression is read-only - we will make sure that is fixed, but this will still not allow you to edit the expression of a calculated table, as this is a limitation for all external tools against a Power BI Desktop model.

If you want to experiment, however, you can do so **at your own risk** by [enabling unsupported Power BI features in Tabular Editor](https://docs.tabulareditor.com/te3/desktop-limitations.html#tabular-editor-and-power-bi-desktop).

**Comment by totangZP** [comment]
@otykier 
I see! I will try to edit it under unsupported feature mode.
Thanks a lot for the prompt response.
