### ISSUE TITLE
Different experience trying to refresh source metadata

### ISSUE THREAD

**Issue by helgews** [TabularEditor/TabularEditor3#38]
Our AAS (S1) model is saved "as folder" in a devops repo, and we have been very happy and productive with TE v2.
We are 3-4 developers on same model, and we can work happily along and rarely have any merge conflicts.

We decided to do a trial on v3 to see how it impacts/improves our workflow. Workflow usually involves adding some columns/changing views in sql, then do a metadata refresh and set descriptions, format strings, translations etc. Finally we deploy from TE v2.

I ran into some issues regarding getting new metadata from our source. Maybe I don't understand how this works now in v3?
I have tried both without connecting to an AAS-model (then the option to refresh table metadata is not there) and when I do connect to our AAS-model it gives me this:
<img width="599" alt="Skjermbilde 2021-06-04 094926" src="https://user-images.githubusercontent.com/56156227/120793609-61d2a500-c537-11eb-820e-3656cfcb82a6.png">

Suggestions?

Notes: The Alwaysusegateway options is set to false, and refreshing metadata works fine in v2.

**Comment by otykier** [comment]
Hi Helge. This is on the backlog, and an "offline" schema update feature, along with the Table Import Wizard, similar to TE2 will be available in TE3 within the next week or two.

**Comment by otykier** [comment]
TE3 now uses "offline" table import and schema update similar to TE2. Version [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0). See also [this article](https://delightful-mud-081affe03.azurestaticapps.net/te3/importing-tables.html).
