### ISSUE TITLE
Measures not showing up in TE3 

### ISSUE THREAD

**Issue by CraigsterT** [TabularEditor/TabularEditor3#382]
Hi Daniel ,

I am creating Measures in TE3 - worked fine yesterday and all weekend - but they are now showing up in TE3. They do show up in Power BI however but I have to force the refresh as I am working with Contoso - any idea what's happening here I am totally flummoxed and sick at the thought that I may have to create measure in Power again. Any help appreciated please.

Craig.

![image](https://user-images.githubusercontent.com/66374274/151869811-03fff109-f9e8-4edb-92bf-f2a240a56d50.png)

![image](https://user-images.githubusercontent.com/66374274/151869490-efaf7d43-a218-4cfc-8230-c6fe19b5f23a.png)

**Comment by otykier** [comment]
This is an issue with Power BI Desktop. We’ve seen it a couple of times before. The workaround, as you saw, is to perform a refresh within Desktop. Some users prefer to keep a dummy calculated table in the model just for this purpose.

**Comment by CraigsterT** [comment]
Hi Daniel ,

Thanks , Yes I've seen it once before however I can't even see let alone
edit the mesures created in TE3 at all - is this also part of the
experience as this is not what I experienced before and very difficult to
work with let alone live with? Will this clear up or should I revert back
to an older version of TE3 as I certainly don't want to move back into
Power as my primary source because as you know the TE3 experience is far
superior to the rubbish Microsoft has churned out.

Craig.

**Comment by CraigsterT** [comment]
Hi Daniel

It's very strange as it doesn't seem to matter what Power BI workbook I
open. I can no longer see any of the measures previously created in TE3 and
only yesterday everything worked fine. I have no feasible explanation for
this. Is this this experience consistent with other users? I am
devastated at the thought of moving back to Power BI to create measures.

**Comment by CraigsterT** [comment]
Apologies,  it's not just measures created in TE3 it is all measures and
nothing is visible in TE3 at all.

**Comment by otykier** [comment]
Check the toggle buttons at the top of the TOM Explorer in TE3. On your screenshot I can see that measures have been toggled off.

**Comment by dpesante** [comment]
@CraigsterT @otykier I have also seen this happen from time to time. Seems like if I wait enough time after pushing the changes from TE3, the changes eventually show. I wonder if there is a TE3 script command that we can add to the C# script that will force a "flush/commit" back to the PBI Desktop datamodel.

Just sharing my experience with this issue in case it helps fix this issue.

**Comment by CraigsterT** [comment]
Hi Daniel ,

It certainly did.  I spotted it the following day. Sincere apologies for
not getting back to you on this.

It was such a relief to discover that I didn't have to go back to the DAX
editor in Power BI again.

Thank you Daniel , you've not only been able to deliver a superior product
but you have also managed to deliver an incredible service to the

Community with all that you do.

Kind Regards,

Craig.
