### ISSUE TITLE
Parameters for custom actions?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#39]
I would like to see the possiblity that when a custom action (or macro as they are called now?)  is run, it could ask for parameter values (with default values) 
an initial version could have just text parameters (or text, and numbers for instance) 
and an advanced version would allow to select table names and field names for values, selecting from the model
of course would be nice if you could first select a table and then on the field selection only fields from that table

currently it only gets selected measure, or column or table as "input" -- that's a bit limiting if your scripts interacts with more parts of the model 

Regards and thank you for this awesome product

ps can I label that as a new feature request? can't see how

**Comment by otykier** [comment]
Tabular Editor 2.x currently has a [number of methods](https://github.com/otykier/TabularEditor/blob/9cee09fc11e3c1a182e8026ef1da1d73ad6b015e/TabularEditor/Scripting/ScriptHelper.cs#L23-L68) that display a list of objects to the user, and returns the selected object.

![image](https://user-images.githubusercontent.com/8976200/120896065-1e079a80-c620-11eb-8656-def67552a56c.png)

These methods will be available in Tabular Editor 3 as well. We can certainly expand on this to also let the user enter text or numbers. It's not a parameter per-say, but it's an easy way to get the user to specify some value that will be used later in the script, without having to modify the code.

**Comment by bernatagulloesbrina** [comment]
Wow, didn't know about this! Probably solves 90% of my use cases

**Comment by bernatagulloesbrina** [comment]
Any thoughts on when this will happen? It would make a nice sequel to the video from guyinacube https://www.youtube.com/watch?v=_j0iTUo2HT0&t=2s no-parameter macros have some limits

**Comment by otykier** [comment]
Hi Bernat
The script you created for adding calc groups is great! If we provide updated documentation for the `SelectObject` and related methods, do you think that would be sufficient?

For example, here is how you can prompt the user for a string (name of calc group), a table (fact table), and a column on that table:

```csharp
#r "Microsoft.VisualBasic"
using Microsoft.VisualBasic;

string calcGroupName = Interaction.InputBox("Provide a name for your Calc Group", "Calc Group Name", "Time Intelligence", 740, 400);
if(calcGroupName == "") return;

var factTable = SelectTable(label: "Select your fact table");
if(factTable == null) return;
var factTableDateColumn = SelectColumn(factTable.Columns, label: "Select date column");
if(factTableDateColumn == null) return;

// ... rest of script ...
```
(Try to run the above script and see for yourself)

The [Interaction class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction?view=net-5.0) is from the Microsoft.VisualBasic namespace. It's not ideal, but it gets the job done.

**Comment by bernatagulloesbrina** [comment]
Wow!

Definately worth a try
I'll let you know how it goes

**Comment by bernatagulloesbrina** [comment]
I'm getting an error 
Do I need to install something to make it run ? 
![image](https://user-images.githubusercontent.com/40455069/134589695-ead24f60-3a29-47c4-817b-6b0386f155b8.png)

**Comment by bernatagulloesbrina** [comment]
Well, but the only really dynamic stuff which is selecting model objects works nice! 
When did these methods become available in TE3?? I missed this new feature -- in your message from June 5 you said they where not available to TE3

**Comment by otykier** [comment]
> I'm getting an error
> Do I need to install something to make it run ?

Remove the `;` at the end of line 1. (Preprocessor directives do not use normal C# syntax).

**Comment by bernatagulloesbrina** [comment]
Oh, yes, it does work indeed! 
Thank you so much

**Comment by otykier** [comment]
Closing this - feel free to open a new issue if you have any more questions.
