### ISSUE TITLE
Idea: Lock Models when Opening from DB

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#398]
Sometimes I query a Model (Open from DB), and while doing something else, leave tabular editor open. When then confronted with another task, e.g. like editing a measure or making changes to a Model, I do this accidentally on the still opened connection and changes are immediately reflected in production. I would like to suggest (if not already available) a feature to automatically lock the opened Model from a DB to avoid unwanted changes to the database when “saving” Dax queries or model changes.

**Comment by otykier** [comment]
Hi @Rasenkantenstein

Are you suggesting some kind of "read-only" mode? How do you envision this would work? Should TE prompt you to open a model in read-only mode whenever you open a model from DB? Alternatively, users could maintain a list of "production" servers/connection strings, where Tabular Editor would automatically mark a model as "read-only" when loaded from one of those servers?

I am not sure what the ideal solution is. In my mind, this should really be solved by not giving developers admin access to production servers, but maybe I'm misunderstanding the requirement. How are you dealing with this, i.e. when using SQL Server Management Studio to connect to a SQL database?

**Comment by Rasenkantenstein** [comment]
Hi Daniel, 

my initial thought was that it would be neat to have a checkbox in the preferences:
![image](https://user-images.githubusercontent.com/6643712/152933463-3e789fbb-e1d8-44d2-aa54-c610e6d1d4b4.png)

* Query-only-mode when connecting to a model from DB

I would not suggest a prompt because some users (including) just auto-click after a while. Eventually it may look a little bit like a Live Connection to AS in PowerBi. One can also browse the model, create new measures but changes are not reflected back to the AS-instance.

**Comment by otykier** [comment]
I don’t think a global preference is a good idea, since you would end up having to toggle it on and off when switching between connections to prod or dev databases. I would much rather investigate if we could somehow allow TE to connect to a model on a server where you do not have admin access, allowing you to use the client tool features (data preview, DAX queries, pivot grids), but without allowing you to make changes or save the model back to the server.

**Comment by Rasenkantenstein** [comment]
I see. Perhaps another alternative is here:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/6643712/152973936-4b21c585-64dd-4d80-b9f3-3ce802bc397f.png">
With the option to toggle it when connecting it seems an easy way to provide a "lock".

**Comment by samaguire** [comment]
Great idea.

I'm often connecting to a model to check something (DAX logic, available fields etc...) it would be great if when connecting we could specify a 'read-only' mode where TE3 doesn't do writebacks - rather notifying the user it is in 'read-only' mode.

(Although the auto-backup feature is great, it is a pain to have to do a restore/reversion...)

**Comment by Rasenkantenstein** [comment]
Released in 3.3.0

**Comment by otykier** [comment]
Thanks, yes indeed this is possible now with 3.3.0 (choose read-only or read/refresh-only during connection)
