### ISSUE TITLE
TE3 crash without error message when saving a new calculated table

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#41]
Being a calculated table it might be on the microsoft side, but here's what happened 
I was doing some DAX queries until I got the outcome that I wanted 
then I created a calculated table, and pasted the same query as definition
all was fine until I saved back to the model, when TE3 crashed without any error, just disappeared.

**Comment by otykier** [comment]
Just to confirm: was this against a Power BI Desktop model?

**Comment by bernatagulloesbrina** [comment]
Yes, power bi desktop

**Comment by otykier** [comment]
This is definitely a bug. Will investigate.

**Comment by otykier** [comment]
I believe this issue should be fixed with [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please let me know if this is not the case.
