### ISSUE TITLE
Pivot Grid requires 2+ items to add item to filter of Pivot Grid

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#412]
I had a calculation group with only one calculation item. It forced the calc to the "current period" depending on the data in the fact table. It is used in the report by adding the CG to the filter pane and checking this one item. It works in PBID.

When i added it to the Pivot Grid though, the "Current Period" calc item was selected in the filter, but the blue filter icon wasn't there and the data in the grid wasn't affected by it. I had to add  a 2nd calc item just so I could uncheck that one and the first was recognized as selected.

**Comment by helgews** [comment]
My guess is it wasnt filtering when you had only the one item. So the calculationgroup item was not part of the context.  Did it calculate properly when adding the calculation group as column/row?

I believe there are some limitations in the PivotGrid-filters Maybe you cant filter if there is only one option? Correct me if Im wrong!

Screenshots would be helpful!

**Comment by edhans** [comment]
Yes, putting a CG with a single Calc Item on a row/column does work, just not in the filter well. 

Good idea. thanks.

**Comment by otykier** [comment]
This seems to be an issue with the Pivot Grid component we're using. I have [opened a ticket](https://supportcenter.devexpress.com/ticket/details/t1066418/pivotgrid-in-olap-mode-does-not-include-single-value-filter) with our UI vendor to see if there is a solution.

Workaround is to use the Row or Column area as you mentioned, or to ensure that the calc group contains at least 2 items.

**Comment by otykier** [comment]
In [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2) we've made the following changes to how Pivot Grids behave when adding a field **that only has a single value** (such as a calculation group with only 1 calculation item):

1. When adding the field to the columns/rows area of the Pivot Grid, the Pivot Grid will now display the field together with the grand total.
2. When adding the field to the filter area of the Pivot Grid, the value will be selected as the current filter. To get rid of the filter, remove the field from the filter area again.

This is illustrated in the gif below.

![new-pivot-grid-behav](https://user-images.githubusercontent.com/8976200/154434162-95d73e70-2cec-4db5-9052-86264a1cc467.gif)
