### ISSUE TITLE
Unable to add buttons to an existing custom toolbar

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#413]
I created a toolbar with a few buttons for macros
I have seens restarted and all and the toolbar remains there, all good. 
However, today, when I try to add buttons it does not work 

I added a recording, but the windows built in tool does not record the customize window... 

(it shows no error, just nothing happens when you drag the macro on to the toolbar as I reguarly do to create toolbars)

**Comment by otykier** [comment]
That's a bug. Note that the additional buttons will appear in the toolbar after restarting the application again.

**Comment by otykier** [comment]
Fixed in [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2), thanks for reporting.
