### ISSUE TITLE
BPA rules not re-evaluated?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#414]
Probably an issue with BPA rules than Tabular Editor itself -- 
it complains that 3 date columns do not have a format string, but once it's assigned it still raises the warning flag. Anyone experienced this? 

https://twitter.com/AgulloBernat/status/1490645466152845315

**Comment by helgews** [comment]
If you go to the rule, under manage rules, I think that particylar rule is «looking» for an american style dateformat-string. It is easy to change the rule to match your own preferred formatstring for dates.

**Comment by otykier** [comment]
@helgews is correct, @bernatagulloesbrina (assuming you're using the BPA rules from [Michael Kovalsky](https://powerbi.microsoft.com/en-US/blog/best-practice-rules-to-improve-your-models-performance/).

[This specific BPA rule](https://github.com/microsoft/Analysis-Services/blob/2bc4805910830391a470954dab1f6f63d2e7997b/BestPracticeRules/BPARules.json#L504) requires you to set the format string to "mm/dd/yyyy". Consider reporting this as an issue [here](https://github.com/microsoft/Analysis-Services/issues).
