### ISSUE TITLE
Idea for the Row Context Iterator browse window in the DAX Debugger - the Expanded Table + Filters

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#416]
Would it be possible to optionally include the expanded table in the row context iterator, perhaps a different shade or something to denote different tables (product, date, customer, etc) and also include filters so we could filter the table to the record(s) we want to iterate over and watch?

Or is there a way to effectively do this and I'm not seeing it?

**Comment by otykier** [comment]
I don't think we have a good way to visualize that (the expanded table could easily grow to several hundred columns for any real-life sized model), so presenting them all in a simple table grid is probably a bad idea. Moreover, it would probably be difficult to generate an efficient DAX query to get the data into the debugger.

Instead, what I normally do when stepping through rows in a row context, is to add `RELATED(Table[Column])` watch expressions for the columns I'm interested in.

Filtering/searching for a specific row in the row context is something we're already planning for a later update (workaround for now is to provide a suitable filter in the Pivot Grid or modify the DAX expressions of your measures temporarily).

**Comment by edhans** [comment]
Thanks. Yes, understand the issue with table width at that point. RELATED is workable, and it sounds like you are already thinking of this overall in your planning comment.
