### ISSUE TITLE
Rename Variable in the DAX Editor Doesn't Always Work

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#42]
I loaded the Marco Russo Date file (1,550 lines long) into the TE3 editor. I scrolled down to about line 360. If I right-click on ReferenceWeekDayNumber and select Rename Variable, all the instances are highlighted as I would expect. However, if I come down a few more lines and right-click on WorkingDays, nothing happens. Go To Definition works but Rename Variable does not in this case.

**Comment by otykier** [comment]
I love how I just instantly know what you’re talking about when you call it “The Marco Russo Date Table” :-)

Thanks for reporting, I’ll look into it.

**Comment by rminder** [comment]
Hi Daniel - That DAX code is a classic. Plus you used it in some of your
videos so I assumed you knew what I was referring to. And, BTW, I have
tried to work with that file in PBI and it's NOT a pleasant experience.

I hope someday Microsoft buys you out and you can spend the rest of your
career counting your money and working on this app. It's wonderful.

**Comment by otykier** [comment]
Finally got around to look into this, but unfortunately I'm not able to reproduce using your description. Does the problem still persist in 3.0.7? If so, could you record a small gif to show the issue?

Thank you!

**Comment by otykier** [comment]
@rminder do you still have this issue with [v. 3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html)? If so, could you provide a detailed example of how to reproduce it? Thanks!

**Comment by otykier** [comment]
@rminder closing this issue as I haven't heard back from you, but feel free to reopen if you encounter the issue again and is able to provide a reproducible example.
