### ISSUE TITLE
Import tables from Excel 2016 (32Bit) Enquiry

### ISSUE THREAD

**Issue by Domaldhino** [TabularEditor/TabularEditor3#426]
Hi Team, I have followed instructions from this link - (https://docs.tabulareditor.com/te2/importing-tables-from-excel.html) but am having difficulties importing tables from Excel. Could I please get your assistance? Anything simple I am just not understanding? A lot of my reporting is Excel/PowerPivot based.

**Comment by otykier** [comment]
Hi @Domaldhino 

Could you provide some more details please? Which point in the instructions have you reached? What error message are you getting?

Please note that Tabular Editor 3 can be installed both as 32 bit and 64 bit - make sure you have the corresponding Excel ODBC driver installed (the guide was written for TE2 which is only available as 32 bit).

**Comment by Domaldhino** [comment]
Hi Daniel,

Thanks for getting back to me. My IT person has installed the 32bit version of Tabular Editor which corresponds to the 32bit Office 2016 version that we have. 

Is there an Add-in for Tabular Editor within Excel that we can export/push the tables (Data) to? 

Kind Regards, 
Dom

**Comment by otykier** [comment]
> Is there an Add-in for Tabular Editor within Excel that we can export/push the tables (Data) to?

I don't understand this question. Tabular Editor does not hold any data - it is an application that lets you edit the **meta**data of a Power BI or Analysis Services tabular model. Please provide a description of your data modelling scenario: I.e. are you creating a Tabular model on SQL Server Analysis Services, and now you want to import some data from an Excel file?

**Comment by Domaldhino** [comment]
Sorry Daniel, I have totally misunderstood. I have the connection fine in PowerBI wanted to connect via Excel PowerPivot.

**Comment by otykier** [comment]
@Domaldhino it is not possible to connect Tabular Editor to an Excel Power Pivot model, as Power Pivot uses an older version of Analysis Services, which is not supported by Tabular Editor.
