### ISSUE TITLE
Diagram View - The Expression Editor Keeps Reappearing

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#43]
When I am in the Diagram View, whenever I click on a table in the Diagram view, the Expression Editor windows keeps reappearing, no matter how many times I closed it. This is rather annoying. I don't know if this is a bug or working as designed but it makes working in the Diagram View quite tedious. 

Also, the quality of the visualization of the tables and the 1:M symbols is really rather poor, IMO. The quality isn't nearly as good as that found in PBI.

**Comment by otykier** [comment]
This is definitely a bug. Will investigate.

**Comment by otykier** [comment]
3.0.5 will fix the issue with the Expression Editor reappearing automatically (you will have to double-click in the TOM Explorer or choose Expression Editor from the View menu to bring it back).

In addition, the diagram visuals have been updated to look better. Here is a preview of how they will look with a dark theme:

![image](https://user-images.githubusercontent.com/8976200/121488982-e6a83d80-c9d3-11eb-8360-9266f5bc18d8.png)

**Comment by otykier** [comment]
Fixed in [3.0.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.5). Thanks for reporting!

**Comment by hbshvn** [comment]
@otykier Hallo Daniel,
I am very excited using your product with enterprice licence.
However I will kindly ask you to reopen this issue
It is extremly annoying.
Check out this small gif:
![expressionEditor](https://user-images.githubusercontent.com/69720211/143448647-6ad32750-e141-40e5-8643-9795e38f2825.gif)

**Comment by otykier** [comment]
Thanks for the gif. We’ll investigate.

**Comment by hbshvn** [comment]
It was 3.1.5.
Just updated to 3.1.6 but unfortunately the same issue
![expressionEditor3 6](https://user-images.githubusercontent.com/69720211/143455053-c3c7d7b4-0dea-4aba-a1b5-708f3a72c6d1.gif)
:

**Comment by otykier** [comment]
Fixed in [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2), thanks for reporting.
