### ISSUE TITLE
Tom Explorer not displaying columns in a table when to file/power bi dataset using TE3.2.1 & TE3.2

### ISSUE THREAD

**Issue by mohitnayar123** [TabularEditor/TabularEditor3#430]
When I connect to a model using TE 3.2.1 and TE 3.2 I am not seeing the columns in the table. The behavior is observed when connecting using .bim or Power BI Dataset in Premium Workspace. Both the file and dataset are the same.

This does not happen in 2.16.2.

TE2
![image](https://user-images.githubusercontent.com/24382274/154341736-1fa89249-3720-4445-95e3-6355f0b8983b.png)

TE3
![image](https://user-images.githubusercontent.com/24382274/154341808-0aa4b52f-b0f9-43c7-bd25-2923a875f76c.png)

**Comment by otykier** [comment]
Check the toggle buttons at the top of the TOM Explorer.

**Comment by mohitnayar123** [comment]
That fixed the issue.
