### ISSUE TITLE
Can't activate free trial

### ISSUE THREAD

**Issue by KennyTenn** [TabularEditor/TabularEditor3#433]
I’d like to start a trail to test out some functionalities through a XMLA connection but the option is greyed out.  As far as I’m aware I’ve only used TE2 in the past. Could you assist me with the activation for 30 days?

**Comment by otykier** [comment]
Hi @KennyTenn 
Sounds like you may have had a trial in the past. Please reach out to sales@tabulareditor.com to request a trial extension.
