### ISSUE TITLE
How to create/update calculation groups in TE3 C# scripting against Power BI Desktop

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#437]
Is creating/updating calculation groups allowed in TE3 connected to PBI Desktop?

**Comment by otykier** [comment]
Yes! Calculation groups are [some of the objects that we can create in a fully supported way](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations), while connected to a Desktop model.

You can create a new calculation group through the **Model** menu (shortcut Alt+7).

**Comment by dpesante** [comment]
Just to clarify, mean to say, using C# scripts? I have not been able to find an example C# code for this...

**Comment by otykier** [comment]
Whether or not you're using C# scripts is unrelated to whether PBI Desktop supports it or not. C# scripting in Tabular Editor is simply a matter of automating things that you could do through Tabular Editor's user interface.

```csharp
var cg = Model.AddCalculationGroup("New calc group");
var calcItem1 = cg.AddCalculationItem("Calc Item 1", "SELECTEDMEASURE()");
var calcItem2 = cg.AddCalculationItem("Calc Item 1", "TOTALYTD(SELECTEDMEASURE(), Calendar[Date])");
// ...
```

Consider using the macro recorder in TE3 to help you get started:

![record-script](https://user-images.githubusercontent.com/8976200/154963294-4f9b7f65-4409-47a0-96da-6cf43c841059.gif)

**Comment by dpesante** [comment]
Wow... not sure why I never saw this before... this is perfect... thanks!
