### ISSUE TITLE
Copy / Paste Roles is no longer working in 3.2.2

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor3#446]
Hi,

In 3.2.1 if you copied and pasted a role the internal filters were also copied. 

This has stopped working in 3.2.2. Now when you copy / paste a role, only the Role Name is pasted.

Thanks.

Toby.

**Comment by otykier** [comment]
Hi @tobimax 
Thanks - we're aware of this issue and a fix is already underway :-)

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3) - thanks for reporting!
