### ISSUE TITLE
Issue with "Save to Folder"- not able to Serialize tables

### ISSUE THREAD

**Issue by Saidheeraj2309** [TabularEditor/TabularEditor3#450]
[](url) I have been trying to to use "Save to folder" in Tabular Editor 3 but I just see that only database.json file is extracted and no Table folders are being saved in selected folder. When I looked into Serialization preferences I have Tables enabled. Is there anything i am missing with this feature.
![TE3_Issue](https://user-images.githubusercontent.com/21086632/156155650-8c64cfbf-b57b-431b-a29b-15997fbfec35.png)

**Comment by otykier** [comment]
Hi @Saidheeraj2309 
These settings are the default for new models created with Tabular Editor. To apply different settings to an existing model, please review the options under **Model > Serialization options**

![image](https://user-images.githubusercontent.com/8976200/156238681-12479e2c-7038-4703-b61a-bff5bbb0488d.png)

**Comment by Saidheeraj2309** [comment]
Thank you @otykier
