### ISSUE TITLE
Can't find "Automatic formula fix-up" in Tabular Editor 3

### ISSUE THREAD

**Issue by Ralle8370** [TabularEditor/TabularEditor3#453]
Hi Daniel,

I recently started using Tabular Editor 3, and I can't find a way to enable "Automatic formula fix-up". Below is a screenshot of the Preferences in TE2, but I can't find anything similar in TE3.

![TE2 Preferences - Formula Fix-up](https://user-images.githubusercontent.com/37557107/156581833-f22ebfbd-c6ee-4025-93fb-9c7ed80dfbb8.png)

In TE3, I do, however, find a _reference_ to "Automatic Formula Fix-up" when selecting "Name" in the Properties of a measure or table. 

![TE3 Properties message ](https://user-images.githubusercontent.com/37557107/156581877-12d24526-819b-44c7-9b03-120c6c86b321.png)

It's frustrating, since the feature seems to be disabled by default.

**What am I missing?**

Kind regards,
Rasmus

**Comment by otykier** [comment]
Hi Rasmus,
Automatic formula fix-up is always on in TE3. Is it not working in your case? If so, could you provide an example of what name change you are making, and which DAX formulas are not updated as expected?

**Comment by Ralle8370** [comment]
Hi @otykier,

Sorry, for not getting back to you with a concrete example. However, the scenario is fairly simple:

* Let's say I have [measure_1] that is referenced in [measure_2].
* If I rename [measure1] to [measure1 TEST] the change is not reflected in [measure_2]. I have to change it manually.
* The same also happens if I have calculated column in a table and I change the table name. The formula for the calculated column of that table needs to be updated manually.

Further information:
* I have only been using a trial of TE3 (which just ran out).
* The problem arose at work where I currently am working with **SSAS models** originally created in Visual Studio.
* Compatibility Level is 1200.
* I believe the SSAS version is 2017.

**NB: I just tried at home with my own setup and a trial version and formula fix works fine (Power BI model, CL 1550).**

Is it related to using SSAS at work?

**Comment by otykier** [comment]
Hi @Ralle8370 
It's difficult to know what's going on without being able to test it on the specific model where the issue arises. Let's close this for now, but in case you come across this issue again, or is able to reproduce it on another model, feel free to reopen the ticket.

**Comment by tbeswick291** [comment]
I had a similar problem last week, Daniel. The best practice pane was telling me not to use CamelCase for my  measures. After I changed them, the dependent formula's had to be updated.(I'm running TE3)
