### ISSUE TITLE
Find & Replace Dialog Box No Longer Opening?

### ISSUE THREAD

**Issue by colin-cronin** [TabularEditor/TabularEditor3#454]
We used to be able to open the Find and Find & Replace Dialog box on our instance of Tabular Editor 3. However, a couple weeks ago this just stopped working. When we try to open it using hotkey (Ctrl+F/H) or from the menu "Edit > Find... / Replace..." nothing happens, even when we have selected an object in the model.

I didn't find any mention that others are experiencing this issue, but we have tried uninstalling and reinstalling the application and the issue persists.

**Comment by otykier** [comment]
Hi @colin-cronin 
Could you please share your `%localappdata%\TabularEditor3\Layout.Json`-file to help us reproduce the issue? Afterwards, please delete or rename the file, which should solve the issue.

**Comment by colin-cronin** [comment]
Sorry for the delay. Attached is the json file
[Layouts.zip](https://github.com/TabularEditor/TabularEditor3/files/8216025/Layouts.zip)

I deleted the file and the find/replace dialog box worked again. Thanks for the hint! Feel free to close this issue once you've verified what you needed from the file.

**Comment by edhans** [comment]
FYI - this happened to me yesterday but with the Show Dependencies view. Tried everything, but had to delete my Layouts.json file to get it to come back at the next reboot, so it is more than just the Find dialog.

**Comment by mlonsk** [comment]
This should be fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html) or newer. 
Do let us know if the issue reappear.
