### ISSUE TITLE
TE doesn't support datatype duration

### ISSUE THREAD

**Issue by rjzomers** [TabularEditor/TabularEditor3#458]
Where Power Query and PowerBI support datatype "Duration", this is not supported in Tabular Editor.
Data sourced as Duration (e.g. formula #duration(day,hours,min,second)) can be mapped to datatype "Time".
However, that's limited to 24 hours (26 hours 2 minutes will be displayed as 2 hours 2 minutes). 

Mapping a duration to datetime (d.hh:nn:ss) is even worse, as the baseline (day 0) for this is 30 december 1899.
Thus 26 hours 2 minutes will be displayed as 31.02:02:00

**Comment by samaguire** [comment]
@rjzomers 

This is not an issue with TE. The semantic model (defined by MS) doesn't natively support the M datatype duration. PBI Desktop converts durations to decimal numbers, which is what a datetime is under the hood giving you the behaviour you're seeing when applying date/time on top.

In working with durations, my previous experience is to use M functions to split the duration into relevant segments (Duration.Days, Duration.Hours, etc...) then recombining into the required unit of measure, i.e. total hours.

![image](https://user-images.githubusercontent.com/62320770/158034942-7c86c763-5dcd-4cac-af6e-94937ce33913.png)
![image](https://user-images.githubusercontent.com/62320770/158034962-be41a02b-89d0-4e05-8acf-73a1d138e070.png)
![image](https://user-images.githubusercontent.com/62320770/158035354-5b66c53c-e321-4dc0-a86e-47c959c075a9.png)

**Comment by otykier** [comment]
Thanks for beating me to the answer @samaguire. Closing the issue, but feel free to add further comments if you have any more questions, @rjzomers
