### ISSUE TITLE
Shortcut key to toggle comment/uncomment

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#46]
Can we please add the shortcut key "ctrl" + "/" to toggle comment/uncomment of code as per PBI Desktop or VSCode

**Comment by otykier** [comment]
This shortcut was added in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for the suggestion!

**Comment by avatorl** [comment]
Is there any way to make it working on a keyboard without numeric key pad?

**Comment by otykier** [comment]
Not right now I’m afraid. By al actions will have configurable shortcuts in a later release.

**Comment by samaguire** [comment]
So, I tried using this in v10 and found it didn't work as expected. It is the same behaviour as "ctrl" + left. Not sure if it recently broke or not.
