### ISSUE TITLE
Renaming 2+ variables in expression doesn't work

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#461]
As you can see by the GIF below renaming 1 variable works great. When I go to rename the 2nd, it seems stuck on the first, and breaks the 2nd renaming step. Either this is a bug, or I'm not clear on how in the UI to stop the first renaming. It seems to me right-clicking on a new variable and selecting Rename should start the process over. 
This is TE 3.2.2.

![RenamingBreaks](https://user-images.githubusercontent.com/45298358/157907648-aa74d219-faf5-429d-94a3-2784fea31591.gif)

**Comment by otykier** [comment]
Hi @edhans 
Hit "Return" to complete the rename (or move the cursor out of the rename area and start typing whatever). Or hit "Esc" to cancel the rename (this will restore the original names of the variables).

Indeed, starting a new rename operation through the right-click menu, should complete the rename operation already in progress - that's a bug.

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
