### ISSUE TITLE
Unpinning the Properties pane causes Layout settings to reset

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#462]
As per the title. When exiting TE3 while the Properties pane is set to autohide, the layout settings will be reset upon reopening TE3.

![image](https://user-images.githubusercontent.com/62320770/158007125-a20cf843-2eac-4580-a215-44b5429907ec.png)

**Comment by otykier** [comment]
Good catch - thanks for reporting!

**Comment by mlonsk** [comment]
This issue has been solved in newer version of Tabular Editor 3. Sorry for not updating sooner. 
Closing the issue.
