### ISSUE TITLE
Comment shortcut keys aren't working

### ISSUE THREAD

**Issue by aexley** [TabularEditor/TabularEditor3#463]
Trying to use the following keyboard shortcuts:

Comment lines | Ctrl+Shift+K
Uncomment lines | Ctrl+Shift+U
Toggle comments | Ctrl+/

on a created measure and none of these are working in the TE 3.2.2 interface.

Connecting to a Power BI (Version: 2.102.845.0 64-bit (February 2022)) Model that is in Import mode.

**Comment by otykier** [comment]
Just to clarify: Are you editing the DAX expression of a measure (as in the gif below)?

![togglecomments](https://user-images.githubusercontent.com/8976200/158160202-102ed5c4-573e-4ec0-9562-4c777dcd14db.gif)

I realise there's an issue with Ctrl+/ not working (unless you use the numpad / button), but the other shortcuts should work fine.

**Comment by aexley** [comment]
Whoops. My bad on this. I discovered my new keyboard has a switch to switch the ALT and CTRL keys around (for if you're using it on a Mac or Win system). Must have accidentally changed it.
