### ISSUE TITLE
Intellisense sometimes won't select using TAB, Enter or mouse click

### ISSUE THREAD

**Issue by aexley** [TabularEditor/TabularEditor3#464]
When tyyping in a reference, the Intellisense kicks in and provides a dropdown of options. Trying to select any of these by usnig TAB, Enter or mouse click fails to do anything. Other keyboard operations such as arrow movement up and down the list or mouse movement over the list works.

Version: TE 3.2.2.

**Comment by otykier** [comment]
Per the issue title, it sounds like this only happens occasionally? Can you confirm that? Have you found a way to consistently reproduce the issue? Thanks!

**Comment by edhans** [comment]
I cannot repro consistently, but I've seen this. Sometimes the only way to get out of the intellisense is to click away or even a different tab or app, then back, then it works.
