### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#466]
With environment variables I refer to a similar concept that we know from e.g. nodeJS. Depending on the environment (such as dev or prod) I can set different attributes. 

This variable could be used for different purposes:

* in C# scripts
* for the property pane, to configure different settings depending on the environment (e.g. Connection Strings, Measure Naming Patterns etc.
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/6643712/158351777-e8c6aee9-db52-4eaf-ac35-13b87f62c173.png">

It may also be used for the deployment wizard to automatically connect to dev/prod databases.

**Comment by otykier** [comment]
Hi @Rasenkantenstein 
This is one of those features, where the potential benefit does not quite match the investment, in my opinion. Especially, considering that you can already achieve this today with a suitable C# script.

Usually, the environment-specific settings do not need to be applied until the model is deployed to a specific environment, and this deployment, ideally, should be performed in an automated way, for example with the Tabular Editor 2.x CLI. Now, this CLI also lets you execute C# scripts, which can read the environment variables and assign them to model object properties, as shown in the example below:

```csharp
var sqldwServer = Environment.GetEnvironmentVariable("SQLDW_Server");
var modelFastCombine = Environment.GetEnvironmentVariable("Model_FastCombine") == "1" ? true : false;
// ...
(Model.DataSources["SQLDW"] as StructuredDataSource).Server = sqldwServer;
Model.FastCombine = modelFastCombine;
```

If you use Azure DevOps, running the TE2 CLI through a command line task, you can easily map pipeline variables to environment variables. I'm sure other types of build servers (GitHub Actions, TeamCity, etc.) have this feature as well.

**Comment by Rasenkantenstein** [comment]
Hi @otykier. Thanks for your evaluation. I agree that benefit and cost may not match for implementing this feature into the software.
Well, I would then change my "feature request" more into a "how-to" request if that's even possible :-) Perhaps one could describe this feature with more detail into the documentation.

**Comment by otykier** [comment]
Absolutely! For a general introduction to DevOps with Tabular Editor, check out this article series: https://tabulareditor.github.io/2019/02/20/DevOps1.html

Here’s a more recent video I did, specifically for CI/CD on Power BI datasets: https://youtu.be/BbYqcSUXOgU
