### ISSUE TITLE
Is there a way to execute a DAX measure from within C# TE3 script and save the result in a C# variable.

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#467]
For example:
var _NumUniqueValues = Model.ExecuteDax("DISTINCTCOUNT(TableName[ColumnName])")
...

**Comment by samaguire** [comment]
TL;DR - Yes

``` CSharp
#r "System.Xml"
#r "System.Data.DataSetExtensions"

using System.Data;

var ds = ScriptHelper.ExecuteDax("EVALUATE {\"123\"}");
var value = ds.Tables[0].Rows[0].Field<string>(0);
ScriptHelper.Output(value);
```

**Comment by dpesante** [comment]
@samaguire .. thanks.. but what would be the syntax for executing a Measure. like:

var ds = ScriptHelper.ExecuteDax("EVALUATE [Average Price]");

I tried this an couple of other variations but does not work...

or better yet, for the example I posted on this issue: DISTINCTCOUNT(TableName[ColumnName])

**Comment by samaguire** [comment]
@dpesante that would be

``` CSharp
var ds = ScriptHelper.ExecuteDax("EVALUATE {DISTINCTCOUNT(TableName[ColumnName])}");
```

You need to use the table constructor as DAX queries only return tables, not scalars.
https://www.sqlbi.com/tv/table-constructor-dax-guide/

**Comment by dpesante** [comment]
@samaguire thanks... that worked but now getting errors on the second part: 
var value = ds.Tables[0].Rows[0].Field<string>(0);

does not like the casting of a number to a string... I tried changing "string" to "integer", "int","Int64","real".. with no luck... 

Any thoughts?

**Comment by samaguire** [comment]
@dpesante this should work

``` CSharp
var value = ds.Tables[0].Rows[0].Field<dynamic>(0);
```

**Comment by dpesante** [comment]
@samaguire fantastic... that did it! I would have never guessed it... :-)

thanks!

**Comment by otykier** [comment]
Hi guys. There’s an even easier way to do this, if you just need a scalar value: 

```csharp
var value = EvaluateDax("DISTINCTCOUNT(TableName[ColumnName])");
```

https://docs.tabulareditor.com/te2/Useful-script-snippets.html#querying-analysis-services

**Comment by samaguire** [comment]
> Hi guys. There’s an even easier way to do this, if you just need a scalar value:
> 
> ```cs
> var value = EvaluateDax("DISTINCTCOUNT(TableName[ColumnName])");
> ```
> 
> https://docs.tabulareditor.com/te2/Useful-script-snippets.html#querying-analysis-services

🤦‍♂️ Yip, that's **way** easier.
