### ISSUE TITLE
Load Model from DB - Power BI Instance Only

### ISSUE THREAD

**Issue by relax528** [TabularEditor/TabularEditor3#469]
I am trying to open a model in the service (premium) to refresh a single table. When I select Open from Model, the dialog only shows Power BI Instance and does not provide a place to paste in my XMLA endpoint. Is there a setting that enables this or something I am missing?

**Comment by samaguire** [comment]
You just paste the endpoint address into the server field/dropdown. Like below.

![image](https://user-images.githubusercontent.com/62320770/158508465-108d12ed-23ca-45ef-a67e-f2ee47d719a2.png)

**Comment by otykier** [comment]
@relax528 if you’re using the Desktop Edition of Tabular Editor 3, loading a model from the Power BI Service [is not supported](https://docs.tabulareditor.com/te3/editions.html).
