### ISSUE TITLE
Run highlighted code

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#47]
When code is highlighted, can we have the tool only run the highlighted section of code - rather than the full script.

e.g. the below code always return 2 results sets, whether code is highlighted or not.

```
EVALUATE
{ 1 }

EVALUATE
{ 2 }
```

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). The shortcut to run highlighted code only is Shift+F5.
