### ISSUE TITLE
Enabling Refresh Policy on Calculated Tables 😕

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#470]
As per title; I'm not sure this should be allowed? Bug maybe?

![image](https://user-images.githubusercontent.com/62320770/158488044-4b54a460-4f47-4cf3-91dd-a2faae080035.png)

**Comment by otykier** [comment]
Good catch, thanks!

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
