### ISSUE TITLE
Bug: ORDER BY is not respected when Execute Selection is called in query window with multiple DAX queries...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#472]

**Comment by seedjay1** [comment]
1) open new DAX query window
2) enter 2 DAX queries (two EVALUATES), where the 2nd has ORDER BY at the end
3) select the 2nd
4) hit the Evaluate Selection toolbar button with the 2nd query selected
5) results are returned UNordered

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
