### ISSUE TITLE
Autocomplete isn't listing datatypes

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#474]
I noticed that when using the convert function the autocomplete wasn't listing datatypes to select from as per the pic below.

![image](https://user-images.githubusercontent.com/62320770/159194756-73562295-0163-416d-858a-214a1783ffe6.png)

**Comment by otykier** [comment]
That's a bug. Thanks for reporting!

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
