### ISSUE TITLE
Aggregate selected results

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#475]
I have a Pivot Table Grid and I want to check some calculation-values:
![image](https://user-images.githubusercontent.com/6643712/159517027-bc14458a-ade4-4a0b-8a6a-327b7c8cb98b.png)

If e.g. I want to check, whether the grand total really equals the sum of each row I would have to go to Excel and check the sums manually.

On the other hand, I use a tool called SQL Complete by devart for SSMS. They have a neat function: I can select a bunch of numbers and the aggregations of the selection are displayed under the result set:
![image](https://user-images.githubusercontent.com/6643712/159517904-b1224eb1-397c-4c27-9c23-4ec0851e2d17.png)

This feature is quite useful when evaluating certain calculations, to quickly check whether a selection contains the expected values.

**Comment by otykier** [comment]
Great suggestion! Adding it to the backlog.

**Comment by DBojsen** [comment]
Hi @Rasenkantenstein 

This is now available in [3.9.0](https://docs.tabulareditor.com/te3/other/release-notes/3_9_0.html?tabs=downloads).
Thanks for suggesting it.

BR David - TE3 Support
