### ISSUE TITLE
Script to Validate Relationships in the Data Model

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#476]
![Relatioship Validator](https://user-images.githubusercontent.com/4983525/159549814-30dab0bc-2f3a-4ea8-9dce-e42ec25a066f.png)

I am trying to automate validating that all relationships to a given table (in this case, VEDA SCLICER 1 DRILLDOWN) are of a certain type, etc. In specific I need to confirm that the relationship is:

- Inactive
- it is against a column called: "Drilldown Value L1"
- It is "Many-to-Many"
- the direction is from VEDA SLICER 1 DRILLDOWN --> <target table>

I am able to find all kind of scripts for creating relationships, etc. but have not been able to find examples of the above.

Can someone point me in the right direction? :-)

thanks!

**Comment by otykier** [comment]
You can do this as a C# script:

```csharp
// Find all relationships FROM table 'VEDA SLICER 1 DRILLDOWN':
var relationships = Model.Relationships.Where(r => r.FromTable.Name == "VEDA SLICER 1 DRILLDOWN");

// Check that there is at least one such relationship (.Any()) and that all such relationships satisfy the criteria:
var isValid = relationships.Any() && relationships.All(r => 
        !r.IsActive && 
        r.FromColumn.Name == "Drilldown Value L1" &&
        r.FromCardinality == RelationshipEndCardinality.Many &&
        r.ToCardinality == RelationshipEndCardinality.Many
    );
    
if(isValid) Info("Relationships for table 'VEDA SLICER 1 DRILLDOWN' are valid.");
else Warning("Relationships for table 'VEDA SLICER 1 DRILLDOWN' are invalid!");
```

...or as a Best Practice Rule (create a new rule with "Relationships" as "Applies to" and the following LINQ expression):

```
FromTable.Name = "VEDA SLICER 1 DRILLDOWN" and
(
    IsActive or
    FromColumn.Name <> "Drilldown Value L1" or
    FromCardinality <> "Many" or
    ToCardinality <> "Many"
)
```

(Note how we inverted the criteria in the Best Practice Rule, since we want to Best Practice Analyzer to output the relationships that are configured incorrectly).

**Comment by dpesante** [comment]
Great! thanks... just what I was looking for... 

:-)

**Comment by dpesante** [comment]
@otykier Quick follow up on this... I now need to force the Cross Filtering DIrection to be BothDIrection. Can you post here the c# script for setting the direction to BothDirection after AddRelationship. This is what I tried but does not work...

var rel = Model.AddRelationship();
rel.CrossFilteringDirection = 2;


thoughts?
