### ISSUE TITLE
Could not deploy workspace database

### ISSUE THREAD

**Issue by Kilsgaard** [TabularEditor/TabularEditor3#478]
Hi 

When i try to create a new model and use "Workspace Database" i get an error
![Workspace database error](https://user-images.githubusercontent.com/11911747/159694994-5de33145-ac94-4bf3-9d28-5792abf2fdf0.png)
 
I have an installed an SSAS 2019 DEV on my computer, and i can deploy cubes to it via SSMS.
I am getting the same bahavior on all the computers I have tried on.

Is there a workaround fixing this?

**Comment by otykier** [comment]
Hi Graves. This is an issue with your SSAS installation, which typically occurs when SSAS is installed on a non us-English operation system. See here for a fix: https://stackoverflow.com/questions/62147670/processing-cube-error-a-device-attached-to-the-system-is-not-functioning
