### ISSUE TITLE
Wrap highlighted text when pressing opening brackets or speech marks

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#48]
When code is highlighted, and you press "{", "(", or """, can you please have the highlighted section wrapped with the opening and closing set for the character pressed. This would be similar behaviour to VSCode.

i.e. in the below code, to wrap the '1' in '{}' you would select the '1' and then press the '{' key - giving the code as it is below.

```
EVALUATE
{ 1 }
```

**Comment by otykier** [comment]
This is now possible in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). You can disable this feature under **Tools > Preferences > DAX Editor > Wrap selection**.
