### ISSUE TITLE
Keyboard Shortcuts in TOM Explorer not working when undocked

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#480]
Hi 

If I undock the TOM Explorer into a seperate window, shortcuts such as Ctr+C, Ctr+V does not work.
As soon as I dock it back to the main window they work again.
As far as I can tell shortcut works fine in other windows when undocked

Using V.3.2.2

**Comment by otykier** [comment]
Thanks for reporting!

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
