### ISSUE TITLE
Impersonate role option should not be available when connecting to the Power BI XMLA endpoint

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#481]
While trying to debug an RLS filter I noticed that the "Impersonation" feature doesn't work as expected. Selecting roles with any kind of filter brings up this error message:
![image](https://user-images.githubusercontent.com/31990588/159914007-d6757821-988d-4b91-aff0-a1d68ec2efc2.png)
Am I doing something wrong here? The roles work fine in the Power BI service.

**Comment by otykier** [comment]
TE3 adds "Roles=..." to the connection string, when impersonating one or more roles ([more details](https://docs.tabulareditor.com/onboarding/refresh-preview-query.html#impersonation)). Unfortunately, impersonation of a role is not yet supported through the Power BI XMLA endpoint. You can, however, [impersonate a specific user](https://powerbi.microsoft.com/en-us/blog/power-bi-bolsters-azure-as-compatibility-with-effectiveusername-support/).

So right now, testing RLS for a specific role on a dataset published to the service, can only be done through the portal:

> Find the Dataset, click the ellipses and go to Security. Hover over a role, click the ellipses and choose Test as role...

From https://community.powerbi.com/t5/Service/Impersonate-Users-for-Security-Role-Performance-testing/m-p/2047040/highlight/true

**Comment by eybert** [comment]
Yeah, I do this in the service all the time. I just thought I could try doing it in TE for once. But shouldn't then this option be removed?
![image](https://user-images.githubusercontent.com/31990588/160090094-62264ae8-6e1b-4c68-b235-8710ec640f87.png)
Or is it perhaps relevant for other scenarios?

**Comment by otykier** [comment]
We should probably remove it while being connected to the Power BI XMLA endpoint. Truth is, we didn't realise this until after we added the impersonation feature to TE3. However, it works great when connected to Desktop, or to SSAS / AzureAS.

**Comment by otykier** [comment]
Hi @eybert 
Just an update on this: Turns out that the Power BI XMLA endpoint actually *does* support Roles impersonation. However, for the impersonation to work, your user must be an explicit member of the roles you intend to impersonate (i.e., it is not enough to be a workspace admin - this is, however, something that Microsoft is planning to support in a few months).
