### ISSUE TITLE
Semantic Error: False Positive

### ISSUE THREAD

**Issue by jonahviakeyboard** [TabularEditor/TabularEditor3#482]
![image](https://user-images.githubusercontent.com/64118593/159929854-bf4b9c1f-b1f9-432d-95ba-5e8fdaec00cd.png)

nothing seems to be wrong with the resulting table, yet TE3 flags it and all dependent measures

DAX for table:

SUMMARIZE(UNION(SUMMARIZE(bud_Rate_Of_Pay,bud_Rate_Of_Pay[Role]),SUMMARIZE(bud_Staffing_Matrix,bud_Staffing_Matrix[Role])),bud_Rate_Of_Pay[Role])

**Comment by otykier** [comment]
Thanks for sharing - that's a bug in our internal DAX analyzer.

Out of curiosity (and unrelated to the issue at hand), what's the purpose of the outer SUMMARIZE call? In fact, why not rewrite the entire query as:

```dax
UNION(VALUES(bud_Rate_Of_Pay[Role]), VALUES(bud_Staffing_Matrix[Role]))
```

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!

**Comment by jonahviakeyboard** [comment]
Thank you! That seals the deal on my evaluation. Purchase complete!

**Comment by otykier** [comment]
Glad to hear it! Don’t hesitate to reach out if you encounter any other issues.
