### ISSUE TITLE
ModelRole.AddExternalMember() unable to provide MemberID

### ISSUE THREAD

**Issue by alwortma** [TabularEditor/TabularEditor3#484]
TE3 v3.2.2

When running a C# script to add members to an existing Azure AD role I am running into issues:

When I try this:
`Model.Roles["Administrator"].AddExternalMember("xxx@intel.com","obj:[ObjectId]@[TenantId]");`
I get:
`No overload for method 'AddExternalMember' takes 2 arguments`

If I try to first add the role member, then modify the "MemberID" property, I get this error (similar to #483):
`Property 'MemberID' of object 'ModelRoleMember' is immutable and can't be changed once set.`

Unlike #483, upon deployment I get an error stating that MemberID is required and can't be resolved in the same way it seems like on-prem AD is able to.

**Comment by otykier** [comment]
Thanks for reporting. `.AddExternalMember` should indeed allow MemberId as an optional parameter as well.

**Comment by otykier** [comment]
By the way, have you tried adding external role members by providing the FQN as the MemberName, as shown below?

```csharp
Model.Roles["Administrator"].AddExternalMember("obj:[ObjectId]@[TenantId]");
```

**Comment by alwortma** [comment]
> By the way, have you tried adding external role members by providing the FQN as the MemberName, as shown below?
> 
> ```cs
> Model.Roles["Administrator"].AddExternalMember("obj:[ObjectId]@[TenantId]");
> ```

No, but I will try that this afternoon.

**Comment by otykier** [comment]
Release [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3) now allows specifying an (optional) memberId (however, for AzureAS and Power BI, it should only be necessary to specify the MemberName):

```csharp
Model.Roles["Administrator"].AddExternalMember("xxx@yyy.com","obj:[ObjectId]@[TenantId]");
```
