### ISSUE TITLE
Is there a way to get a list of all the datatable columns that are referenced in a DAX measure?

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#485]
This may be far fetched but here it goes. I would like to know if there is a way to loop trough all the columns in all the tables and for each column list all the measures that reference that column in their DAX expression. Something like (in speudo code):

foreach (t in model.Tables)
  foreach (c in t.Columns)
     foreach (m in c.ReferencedMeasures)
         info(m.Name)
     endfor
  endfor
endfor

I was thinking of just doing a text search of c.Name in every measure.Expression but was hoping that the data model object already has this info which would be 100% accurate vs text search might not be.

Any thoughts?

**Comment by otykier** [comment]
```csharp
foreach(var c in Model.AllColumns)
{
    foreach(var m in c.ReferencedBy.Measures)
    {
        Output("Column " + c.DaxObjectFullName + " is being referenced by measure " + m.DaxObjectFullName);
    }
}
```

**Comment by dpesante** [comment]
Wow... freaking awesome!!! 

One of these days I want to show you what we are building using your beautiful tool! 

thanks!!!
