### ISSUE TITLE
Table refresh operations limited when selecting calculated tables 

### ISSUE THREAD

**Issue by alwortma** [TabularEditor/TabularEditor3#487]
TE3 v3.2.2

Currently, when selecting a mix of calculated and import tables, TE3 will _usually_ give the full list of refresh operations.

![image](https://user-images.githubusercontent.com/97995966/160200733-8a8d3100-3bf8-4676-a1a5-444766395720.png)

However, sometimes this does not happen, and only the Calculate option is given.

![image](https://user-images.githubusercontent.com/97995966/160200937-367a89f1-e992-4584-bc11-0f2d3496456d.png)

It appears as though the _order_ the tables are picked in controls the available refresh operations, because if I pick the same two tables from above, but the non-calculated one first I get:

![image](https://user-images.githubusercontent.com/97995966/160201035-76d33b39-1b2c-4aa6-917f-864630fe43df.png)

This seems a little confusing. It would be nice to just provide all the options if at least one non-calculated table is selected.

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
