### ISSUE TITLE
AccountKey not encrypted in tmuo User Option file

### ISSUE THREAD

**Issue by user-named-void** [TabularEditor/TabularEditor3#488]
I added a datasource with authenticationkind "Key". (an Azure Table in this case)
Whenever a user starts the model, Tabular Editor prompts the user for the key.
This key is then added to the tmuo file of the user, but this is not encrypted like the users password.

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
