### ISSUE TITLE
Pivot Grid won't let you drag directly onto the 'Drop Filter Fields Here' field

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#49]
As per the title.

I can drag into either the columns or rows and then into the filters, but not directly into the filters

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). There are also a number of additional improvements to the behavior of Pivot Grid as can be seen in the release notes.
