### ISSUE TITLE
Pivot Grid shows values as currency

### ISSUE THREAD

**Issue by user-named-void** [TabularEditor/TabularEditor3#492]
When i create a Pivot grid to test some measurements the values are shown in the currency formatting although all the used measurements and the columns that are used by these measurements are still set to "General" formatting. The data types are set to decimal.

When i use the measurements in powerbi or excel these are still displayed as number and not as a currency, which is correct.

The Pivot Grid should also use the formatting that is defined on the measurements.

**Comment by otykier** [comment]
Hi @user-named-void 
Could you share a screenshot of how the properties on the measure are defined (specifically the `Format String` property), and also show how that measure appears in a Pivot Grid? Thanks!

**Comment by user-named-void** [comment]
Hi Daniel,

These are the format and data type settings for the measurement.
![afbeelding](https://user-images.githubusercontent.com/97679841/161504526-e19cfd29-3238-4aef-afda-df3a4da7d71b.png)

And this is the mesaurement used in a pivot grid.
![afbeelding](https://user-images.githubusercontent.com/97679841/161504630-a4c68213-efc7-4432-a150-f1493760dadc.png)

If i make the same grid in excel or powerbi the values are shown as a decimal instead of currency.
![afbeelding](https://user-images.githubusercontent.com/97679841/161505133-30520c85-03a4-4577-9513-7a8322e43711.png)
![afbeelding](https://user-images.githubusercontent.com/97679841/161505309-de5a59b9-d04f-4302-99ea-bf95fa7e6816.png)

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
