### ISSUE TITLE
Idea: Copy MDX from PivotGrid

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#494]
I have created a pivot grid and I just realized how slow the measure is. To analyse performance, DAX Studio is a blast. Therefore it would helpful to be able to copy the MDX query generated by the PivotGrid and paste it directly to DAX Studio for further analysis.

**Comment by otykier** [comment]
Right-clicking on a cell in the Pivot Grid now allows you to copy the MDX query in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3).
