### ISSUE TITLE
Is the EvaluateDax function impacted by cache?

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#495]
I am trying to use EvaluateDax to measure execution time of different measures. I was wondering if the execution time is impacted by caching and if there is a way to force a flush of the cache before calling EvaluateDax or if there is already some other way to capture the execution time of measures programmatically?

**Comment by otykier** [comment]
Hi @dpesante 
We do not explicitly clear the cache before executing DAX or other commands against AS.

However, it is possible to manually send the XMLA clear cache command to AS:

```xml
<ClearCache xmlns="http://schemas.microsoft.com/analysisservices/2003/engine">  
  <Object>  
    <DatabaseID>AdventureWorks</DatabaseID>  
  </Object>  
</ClearCache>
```

I was hoping we could use the `ExecuteCommand(string tmsl)` method to send the above XMLA string, but this method assumes that a TMSL command is passed, so everything sent is being wrapped in a `<Statement>`-tag, causing the call to fail. We will add a second parameter to make this possible in a future update, i.e. `ExecuteCommand(string tmslOrXmla, bool isXmla = false)`.

In the mean time, you can send the command directly using the following workaround:

```csharp
#r "Microsoft.AnalysisServices.Core.dll"

var clearCacheXmla = string.Format(@"<ClearCache xmlns=""http://schemas.microsoft.com/analysisservices/2003/engine"">  
  <Object>
    <DatabaseID>{0}</DatabaseID>
  </Object>
</ClearCache>", Model.Database.ID);

Model.Database.TOMDatabase.Server.Execute(clearCacheXmla);
```

**Comment by dpesante** [comment]
@otykier thanks... just curious... is this something that you will execute before every EvaluateDax of just once at the top of the script?

**Comment by otykier** [comment]
You should call the `Model.Database.TOMDatabase.Server.Execute(clearCacheXmla);` line whenever you need the cache to be cleared (starting from upcoming v. 3.2.3 a simple `ExecuteCommand(clearCacheXmla, true);` will be sufficient).

**Comment by otykier** [comment]
[3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3) now lets you specify raw XMLA, so the above script can be changed to:

```csharp
var clearCacheXmla = string.Format(@"<ClearCache xmlns=""http://schemas.microsoft.com/analysisservices/2003/engine"">  
  <Object>
    <DatabaseID>{0}</DatabaseID>
  </Object>
</ClearCache>", Model.Database.ID);

ExecuteCommand(clearCacheXmla, true); // 2nd arg set to 'true' to specify raw xmla
```
