### ISSUE TITLE
What is the syntax in C# to detect if a measure has "errors"

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#496]
Trying to determine if a measure has errors. Something like:

if (measure.ErrorMessage > "") ....

I tried this but it did not work. i took a look at the measure class in this link but could not find a property that has this. https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.measure?view=analysisservices-dotnet

How do I check?

thanks!

**Comment by albertospelta** [comment]
This property is part of the  Microsoft.AnalysisServices.Tabular namespace.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.measure.errormessage?view=analysisservices-dotnet#microsoft-analysisservices-tabular-measure-errormessage
