### ISSUE TITLE
Add an option to default saving new models to either a file or folder

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#50]
As per title, so that when you do the initial save it uses the mode as specified in the default.

**Comment by otykier** [comment]
This is now available in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). The first time you save a new model you will be prompted for whether you want to use file or folder. You can also choose a default save mode under **Tools > Preferences > File formats > General > New models**
