### ISSUE TITLE
First 100 Rows Only

### ISSUE THREAD

**Issue by Stewwe1** [TabularEditor/TabularEditor3#500]
Hello Daniel,

I have a quick question:

I can only see the first 100 rows with the preview data function. This was never the case before. Can I set somewhere that I can see all rows again? :-)

Thank you for your help

Stewwe

**Comment by Stewwe1** [comment]
I found it. There is a setting that sets the 100 row limit for directquery data. But my tables are (almost) all in import mode. If I change the setting there, I can at least see 10,000 records, but I would still like to see all records from import mode tables.

Thanks for the help

**Comment by otykier** [comment]
Are you using 3.2.3? If so, that might be a regression. We’ll look into it.

**Comment by Stewwe1** [comment]
Hello Daniel,
I have one more hint:

We converted a table to a hybrid table about a week ago.  Maybe that is the reason? The limitation to max. 10000 rows definitely affects all of our more than 50 tables in imported mode. Thanks

**Comment by otykier** [comment]
Yes, indeed it seems like hybrid tables are the culprit, however I would expect the issue to only occur on tables that have a DQ partition (so pure DQ tables + hybrid tables would be affected). Could you confirm if the issue also occurs on tables that are pure import (i.e. no DQ partition)? Thanks!

**Comment by Stewwe1** [comment]
On all of my tables without exception :-\

**Comment by otykier** [comment]
Hi @Stewwe1 
This has been fixed in our [latest release](https://docs.tabulareditor.com/te3/other/release-notes/3_7_1.html?tabs=downloads). Please note that we're still only able to show the first 100 rows on tables that are hybrid (i.e. have a DirectQuery partition). However, tables that are pure import are now fully viewable.
