### ISSUE TITLE
Copy paste cultures from one TE session into another

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#507]
Select 3 cultures 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/74975641/163250100-5bcf0476-65f5-4bf5-9691-b540d106c7ef.png">
and copy paste from TE3 session A to TE3 session B -->
<img width="525" alt="image" src="https://user-images.githubusercontent.com/74975641/163250337-bfb9c5a6-9cd5-429c-ac44-567bc8e5b76b.png">

**Comment by otykier** [comment]
Thanks for reporting. We'll look into it. Maybe as a workaround, you can export the translations (right-click > Export selected translations...) from session A and then import in session B (right-click on "Translations" folder > Import translations...)?

**Comment by MarioMue13** [comment]
@otykier  thx I'll give it a try

**Comment by MarioMue13** [comment]
@otykier  Hi, so error is gone but it seems that  only an empty culture is pasted:
![image](https://user-images.githubusercontent.com/74975641/177996023-0e636007-cc5c-4dcb-a3d9-62e547807443.png)

I tried to copy paste the fr-culture from TE2 to TE3

**Comment by mlonsk** [comment]
Closing the issue has it seems to have been fixed, please reopen if this is not the case

**Comment by MarioMue13** [comment]
HI, I just gave it try: https://github.com/TabularEditor/TabularEditor3/issues/798
