### ISSUE TITLE
Previous Week anomaly TE2 vs TE3

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#508]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/74975641/163258438-827ed0a7-fd7a-4b3c-8617-539f21707594.png">

**Comment by otykier** [comment]
Hi @MarioMue13 
Thanks for reporting. Indeed, the issue is that the TE3 DAX parser thinks that "WEEK" is allowed as a 3rd argument for DATEADD, which is a bug.

**Comment by otykier** [comment]
Fixed in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0).
