### ISSUE TITLE
Cannot resize the "preferences" or "save macro" dialogue boxes

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#51]
I can't resize these to make them bigger - so I can see all options on screen at once.

**Comment by tpeplow** [comment]
There's a related issue that when using two monitors at different DPIs you get something like this:

![image](https://user-images.githubusercontent.com/278561/141406299-8cab2ee2-36e1-483d-b81f-8b9194ec7ddc.png)

**Comment by otykier** [comment]
@samaguire the resize issue is fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting.

@tpeplow this is unrelated, but we are aware of this issue.
