### ISSUE TITLE
Add Process Clear Option to Tables/Partitions

### ISSUE THREAD

**Issue by alwortma** [TabularEditor/TabularEditor3#511]
Enhancement Request

Using TE3 v3.2.3 (with workspace)

Current options for table include Auto, Full, Calc, and Data Only
![image](https://user-images.githubusercontent.com/97995966/163475277-25da93a9-5e47-4570-a459-93a7dd80715b.png)

Reason for request:
Today, I made a table schema change converting a text column to a date column. I was unable to save this change (and sync to workspace) because I had already processed data into this column that SSAS couldn't convert to Date (I had resolved this for future refreshes by adding a data cleaning step in the partition's M code). The easiest way around this is to clear the data from the table/partition, save/sync to workspace, then reprocess the data.

I had to go to SSMS to do the clear step.

**Comment by otykier** [comment]
Now available in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0). Enjoy!
