### ISSUE TITLE
Failed to resolve name error - but name is there

### ISSUE THREAD

**Issue by ImkeF** [TabularEditor/TabularEditor3#513]
Getting error that a name couldn't be found, but it's clearly there (and evaluates correctly in the final result):

![image](https://user-images.githubusercontent.com/18321412/163664875-da2b3975-1d84-4113-80bf-5d5e86f1b00f.png)

**Comment by otykier** [comment]
That’s a bug. Thanks for reporting!

**Comment by otykier** [comment]
Fixed in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0).
