### ISSUE TITLE
False Positive: Semantic Error

### ISSUE THREAD

**Issue by jonahviakeyboard** [TabularEditor/TabularEditor3#516]
this measure produces an alert for a semantic error in TE3, but the comparison is supported in PowerBI

VAR _numerator =
    CALCULATE (
        DISTINCTCOUNT ( Revenue_Schedule[AccountId] ),
        KEEPFILTERS ( Revenue_Schedule[Health_Cache] IN { "Poor", "Average" } )
    )
VAR _denominator =
    CALCULATE ( DISTINCTCOUNT ( Revenue_Schedule[AccountId] ) )
VAR _result =
    DIVIDE ( _numerator, _denominator )
RETURN
    _result
    
![image](https://user-images.githubusercontent.com/64118593/164029348-c54b09cd-fe1d-4d5a-a5fa-e6adea0a337b.png)

**Comment by otykier** [comment]
Good catch, thanks for reporting!

**Comment by otykier** [comment]
Fixed in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0).
