### ISSUE TITLE
Serialize BPA-rules when saving to folder

### ISSUE THREAD

**Issue by helgews** [TabularEditor/TabularEditor3#518]
Hi,

I would like you to consider an option to serialize a models BPA-rules to a separate json-file (same as with roles, perspectives, etc) instead of saving it into database.json.

This would help us share and distribute a golden set of BPA-rules across models (folders in repos) and clients (repos). 

As of now, we have to save our bpa-rules for a given model into database.json in order to seamlessly cooperate on a model. Because references to local bparules.json-files would not work for all consultants out of the box. For that to work, the path to bparules.json would need to be specific to each model (and interpreted upon opening TE).

**Comment by otykier** [comment]
Hi Helge,
This is possible. You can use the **Tools > Manage Best Practice Rules** option to create a new rule collection as a separate .json file, then copy or move the rules over to that collection. That .json file will then be referenced by the model currently loaded. You can have multiple such collections referenced by a single model, so you can mix and match between rule files that should be common for all models, and rule files which should only be applied to specific models.

See [this article](https://docs.tabulareditor.com/te2/Best-Practice-Analyzer-Improvements.html#managing-best-practice-rules) for more information (it was written for Tabular Editor 2.x but everything applies in TE3 as well).

**Comment by helgews** [comment]
Thank you, Daniel
Naturally this was thought of already (by using relative path pointing to bpa-rules in same folder/subfolder related to database.json). 
Case closed! 👍
