### ISSUE TITLE
Certain editor actions not available when Expression Editor is docked as a tool window rather than a tabbed document

### ISSUE THREAD

**Issue by PalombieChamonix** [TabularEditor/TabularEditor3#519]
since one week, the icons to format the DAX and to update the datamodel to PowerBI Desktop are no longer available. 
I am connected to a local model with the latest version of Tabular Editor.
![image](https://user-images.githubusercontent.com/91263359/164430781-29d94a84-d5c3-4b09-98c6-3e160ed8aadf.png)

**Comment by otykier** [comment]
Please try to reset your windows layout to “Default”:

Window menu > Default layout

**Comment by PalombieChamonix** [comment]
Many thanks !

**Comment by otykier** [comment]
Fixed in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0).
