### ISSUE TITLE
Changing measure in specific perspective

### ISSUE THREAD

**Issue by MSmerdel** [TabularEditor/TabularEditor3#52]
When changing a measure while viewing the details of a perspective, it happens that you cannot go back to viewing the full model.

Steps to reproduce:
1) Select a perspective
2) Edit a measure in the perspective
3) Save (to folder and workspace db)
4) De-select the perspective to view all

The TOM explorer do not update to reflect the full model view.
A workaround seems to be re-saving the model (CTRL+S), while all perspectives are de-selected.

Best regards,
Mogens Smerdel

**Comment by MSmerdel** [comment]
With the release 3.0.7 the workaround is not possible any longer. The TOM explorer is now stuck with the prior selected objects of the perspective.

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
