### ISSUE TITLE
Some text not visible in the status bar

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#521]
Minor issue, but should be looked at.

![image](https://user-images.githubusercontent.com/45298358/164765150-1cef44f3-dac6-4da8-bebd-776f9214c393.png)

This is on Windows 10, using the "Blue" default theme. I've done no customizations. The "View Refresh Queue" text is almost invisible.

**Comment by otykier** [comment]
Fixed in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0). Thanks for reporting!
