### ISSUE TITLE
Cross Filtering Options in M2M Cardinality Relationship in AS 2019

### ISSUE THREAD

**Issue by ruve1k** [TabularEditor/TabularEditor3#526]
Does Analysis Services 2019 support OneDirection cross filtering behavior for M2M cardinality relationships?
In Visual Studio the only option that shows up for filter direction is "To Both Tables" (BothDirections).
TE allows the setting to be changed to OneDirection but do the options available in VS imply that it's not supported?

![image](https://user-images.githubusercontent.com/20305564/165833769-64d721de-49c6-49da-a055-d981c2c69c2f.png)

**Comment by otykier** [comment]
My initial thought is that it’s not supported, since SSAS 2019 was released before weak relationships (M2M) were announced in Power BI. Give it a try and let us know if it works :-)

**Comment by ruve1k** [comment]
Setting the cross filtering to OneDirection appears to work just fine in AS 2019. (I.e. the filter propagates in only one direction.)
Not sure why Visual Studio doesn't allow that configuration to be set.
