### ISSUE TITLE
Error message on CustomData() not valid

### ISSUE THREAD

**Issue by yeykawb** [TabularEditor/TabularEditor3#527]
Hey,

I'm working with an Analysis Services instance and implementing Power BI Embedded in our application.

The error message in TE3 is indicating that the CustomData() function is returning an integer, when it's returning a string.

See prints for clarification.
![image](https://user-images.githubusercontent.com/97282358/166434021-113b5a22-f9a4-4086-bcba-23373ca2acc0.png)

![image](https://user-images.githubusercontent.com/97282358/166434077-2a4e9eaa-9689-4bea-a38c-fe287ac8b70e.png)

**Comment by otykier** [comment]
Thanks for reporting.
