### ISSUE TITLE
TOPN function doesn't exist in auto-complete

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#529]
As per the title and below screen clip. However, it does give a hint 🤷‍♂️

![image](https://user-images.githubusercontent.com/62320770/166860107-b56657e5-ca17-4002-9e52-1894f4d47e45.png)

![image](https://user-images.githubusercontent.com/62320770/166860218-71622fc4-cc2f-43f2-8dbc-86bbb277d1f6.png)

**Comment by otykier** [comment]
TOPN returns a table, not a scalar. You’re currently entering the DAX expression for a measure, which should return a scalar value. For the same reason, you’ll find that autocomplete suggests CALCULATE but not CALCULATETABLE.

**Comment by samaguire** [comment]
🤦‍♂️ Sorry had a moment.
