### ISSUE TITLE
Unable to detect schema changes - bug or user issue?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#533]
I added a new column to a table via Power Query. It is only the "AddedQuarterDesc" field. The "AddedMonthInFiscalQuarter" was there.

```
let
    Source = #"Fiscal Calendar Dataflow",
    // The Fiscal Select logic requires altering periods when it is the 1st vs 2nd/3rd month in a quarter, so using this field to make that determination.
    AddedMonthInFiscalQuarter =
        Table.AddColumn(
            Source,
            "Month in Fiscal Quarter",
            each Number.Mod([Fiscal Month] + 2, 3) + 1,
            Int64.Type
        ),
    AddedQuarterDesc =
        Table.AddColumn(
            AddedMonthInFiscalQuarter,
            "Quarter Desc",
            each "Q" & Text.From([Fiscal Quarter]),
            type text
        )
in
    AddedQuarterDesc
```

When I tried to update the table schema, I got the following error:

![image](https://user-images.githubusercontent.com/45298358/167743887-c6b968ce-3109-410c-bb4a-2ff8b723577f.png)

I don't really think my column addition caused this, but maybe the first column added is causing the problem - I did read where T/E 3 doesn't fully support some M transformations for table schema updates, but as transformations go, these are pretty simple.

I finally did get to update it by swtiching T/E to Analysis Services mode for detecting changes, then I turned that preference off again once I got this table fixed.

So, bug, user error, other comments? (and sorry about the code - I cannot get it to honor my line breaks - code is below in a readable image - comment on line 3 is truncated in the image)
<img width="397" alt="image" src="https://user-images.githubusercontent.com/45298358/167744274-4df79b2f-e2a3-40dc-ac13-37e343e4d114.png">

**Comment by otykier** [comment]
(Enclose the code in a pair of triple-backticks ``` to retain line breaks)

I think the problem here is that you're pointing to another M expression `#"Fiscal Calendar Dataflow"` which I'm guessing originates from a Power BI dataflow. Unfortunately, TE3 can not currently obtain schema data from dataflows on its own, which explains why you need to use Analysis Services for change detection. In some cases, TE3 can automatically fall back to Analysis Services mode, but apparently that didn't happen here. We'll see if that can be improved.

**Comment by edhans** [comment]
Thanks! Appreciate the feedback, and at least I know it wasn't just me. Lots of dataflows in this model.
