### ISSUE TITLE
Power BI data conversion to French

### ISSUE THREAD

**Issue by bala811** [TabularEditor/TabularEditor3#535]
Hello,
I am working on power BI reports. I am trying to add French language conversion. currently the report is in English. There is no frech language data in data model. and for that report I am trying to add french conversion that happens dynamically with the report.
please help me with language conversion using tabular editor. thankyou

**Comment by otykier** [comment]
Hi @bala811 
Power BI doesn't have native support for data conversions. However, there is a clever workaround which you can read more about in [this blog post](https://blog.crossjoin.co.uk/2021/02/21/implementing-data-as-well-as-metadata-translations-in-power-bi/).

Going forward, if you have questions regarding Power BI (which are not specific to Tabular Editor), consider posting them to the [Power BI community forums](https://community.powerbi.com) as you might have better luck getting an answer there.
