### ISSUE TITLE
Creating an Implicit Data Source to Snowflake Database with OAuth

### ISSUE THREAD

**Issue by natpalmer** [TabularEditor/TabularEditor3#546]
When attempting to do an implicit data source in Tabular Editor 3 like we do with Power BI Desktop, the only option for authentication is a named Snowflake user and password.

My organization's security policies will not allow us to use a named user and must us SSO (OAuth). How can I configure an implicit connection to Snowflake using OAuth? I can use an ODBC driver, but would really like to keep things consistent with Power BI Desktop as we are deploying to a Power BI Premium Capacity Workspace.

I am currently evaluating TE3 on a trial license to see if it fits our need for development. This is something we would need to leverage TE3 for our team.

**Comment by otykier** [comment]
Hi @natpalmer 
OAuth connections to snowflake are currently not supported within TE3, although the feature is in the backlog.

However, you can still use TE3 to import tables from snowflake after a dataset has been published to the Power BI service, using the [workaround described here](https://docs.tabulareditor.com/te3/tutorials/importing-tables.html#importing-new-tables-through-analysis-services).

The easiest way to use this technique, is to create a dummy model in Power BI Desktop, which imports a sample table from Snowflake. Publish it to the Power BI Service, and make sure the data source has been authenticated in the Service. Then, open that model (or another model from the same workspace) in Tabular Editor, using the XMLA endpoint. To import new tables, copy/paste the sample table, update the M expression with the name of the table you wish to import, then right-click on the table and choose "Update table schema...". This way, Tabular Editor does not directly connect to Snowflake, but instead uses the credentials/authentication specified in the Power BI service.

**Comment by otykier** [comment]
Did you enable the “Use Analysis Services for change detection”-option as described in the link?

**Comment by natpalmer** [comment]
It would definitely help if I read through everything :)...I didn't catch that step. 

After applying that option I'm getting a DM_GWPipieline_Gateway_InvalidConnectionCredentials error. I'll get with our gateway admins to see what additional details are coming through the logs, but it looks like my local credentials are not being passed to the PBI dataset and it's effectively coming through as anonymous.

@otykier, do you think there is anything on the TE3 side that could help facilitate the authentication? If not, I think I'm ok with closing this ticket while I work with gateway admins.

**Comment by otykier** [comment]
Not sure what is causing that error, as credentials are not entered in Tabular Editor when using this workaround. The Power BI Service is authenticating against Snowflake, and Tabular Editor is then “connecting” to Snowflake through the Power BI Service.

Anyway, we expect to have full client-side support for Snowflake OAuth and browser-based (SSO) authentication with the next TE3 update due end-of-month.

**Comment by natpalmer** [comment]
Thank you so much for the support, looking forward to testing out those updates. I'll see what we can figure out with the gateway admins.

**Comment by otykier** [comment]
It’s still upcoming. We expect to release v 3.3.0 tomorrow - stay tuned :-)

**Comment by otykier** [comment]
Now available in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0). Enjoy!
