### ISSUE TITLE
Not all sections of TE/3 adjust to different DPI setting when moving monitors

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#548]
My laptop is a Surface Laptop Studio which is an HDPI screen of 2400x1600. I opened TE/3 from the Start Menu, then moved it to my 2nd monitor which is not HDPI - it has a resolution of 1920x1080.

You can see the Properties section has a HUGE font

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45298358/169896238-11225647-634a-444a-a33d-5675c80f8a8d.png">

And here the connection dialog box is next to unusable (legacy). On the non-HDPI screen, there is no database dropdown visible - the "Connect to Database" section at the bottom shows nothing.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/45298358/169896593-eb3f05d7-ea96-495c-a7be-f62f9913bfb6.png">

When I move it to my HDPI screen I can at least navigate, but it isn't pretty.
<img width="287" alt="image" src="https://user-images.githubusercontent.com/45298358/169896752-a44dc8fb-412b-40fb-8c27-b5705b81d850.png">

**Comment by otykier** [comment]
A fix for this is underway and will be available in the next update.
