### ISSUE TITLE
Suggestion - Update Table Schema Function

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#55]
This is not really a bug, I don't think, but more of a suggestion. I had PBI loaded with a data model and TE was connected to the model.  In TE I right-clicked on a table and selected Update Table Schema... Since I saw the ellipses I expected a dialog to appear before the update operation began to confirm something. 

What I got instead was a message saying "Please Wait Detecting Schema Changes" or something like that. I waited 5-10 minutes and nothing was happening. I thought TE had hung up. What I didn't realize was the Power BI had 

displayed a dialog asking me to confirm a query it wanted to execute and TE was waiting for me to confirm the query in PBI. I had no idea PBI had displayed this dialog and was waiting for me to confirm or cancel. 

It would be very helpful if TE told the user that PBI was going to ask me to confirm refreshing of the data source and I had to go there to confirm or cancel before TE would continue.

![TE1](https://user-images.githubusercontent.com/20615192/121177205-1f58e300-c82b-11eb-98eb-7a1efd89ffa7.png)
![TE2](https://user-images.githubusercontent.com/20615192/121177207-1ff17980-c82b-11eb-91f5-bf55a4675b63.png)
![TE3](https://user-images.githubusercontent.com/20615192/121177208-1ff17980-c82b-11eb-94b6-d37a3e35333e.png)

**Comment by otykier** [comment]
Truth be told, the "Update Table Schema" feature shouldn't be allowed when connected to a Power BI Desktop model, since Power BI Desktop doesn't support adding/changing/removing columns through external tools anyway... However, I didn't get the prompt during my testing - perhaps it's a matter of sensitivity levels for queries. Could you post a screenshot of the prompt you saw? Thanks!

**Comment by rminder** [comment]
Hi Daniel - Here are some screen shots:

#1: TE menu option showing Update table schema...

[image: image.png]

#2: Message I get after selecting the menu item, from within TE:
[image: image.png]

#3: Message from within PBI...

[image: image.png]

**Comment by otykier** [comment]
Looks like you replied to an e-mail from GitHub - unfortunately, pictures and attachments are not included when replying by mail, so I can't view the images. Could you reply on the original thread https://github.com/TabularEditor/TabularEditor3/issues/55 instead? Thank you!

**Comment by rminder** [comment]
I have done so

**Comment by otykier** [comment]
Thanks - I see the images now

**Comment by otykier** [comment]
Just for future reference: When updating table schema while connected to PBI Desktop, Tabular Editor should display something like: "You may have to confirm native query executing in Power BI Desktop for this operation to complete".

**Comment by otykier** [comment]
Update 3.1.6 will be available soon, which will switch focus to Power BI Desktop immediately before starting a schema update that can cause Desktop to display the popup prompt. This should hopefully make it more clear that the prompt needs to be accepted before the schema update can complete.

**Comment by otykier** [comment]
Fixed in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Thanks for reporting!
