### ISSUE TITLE
new Share Expression causes crash

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#550]
I have a model where I have 3 times tried to create a new Shared Expression. It creates the new blank item for naming, which needs to be RangeStart (for incremental refresh). As soon as I press the letter R, Tabular Editor 3 just vanishes.

Opening the same model in TE/2 allowed me to create it with no problems.

**Comment by edhans** [comment]
Hi Daniel. I cannot repro, and now it works, so whatever little glitch was going on, adding it via TE/2 seems to have cleared it up.

For my future benefit, how do I create a PBIT file from an online dataset? There is no PBIX with this data.

**Comment by otykier** [comment]
@edhans since we can't download pbit/pbix files from the service, once they've been touched by a 3rd party tool, an equivalent approach is to use Tabular Editor (2 or 3) to save the model as a .bim file - it contains all of the model metadata, same as a .pbit file, but no actual data.
