### ISSUE TITLE
REQ: don't expand everything when searching (TOM Explorer)

### ISSUE THREAD

**Issue by lukiz84** [TabularEditor/TabularEditor3#552]
Hi,

it's a bit annoying that my whole TOM tree is expanded when I search for something... Is it possible to just leave the affected branches open and keep the others closed (or close them after search)?

Br
Lukas

**Comment by otykier** [comment]
Just to clarify: Do you want the search restricted, such that it only considers nodes that are currently expanded/visible?

**Comment by lukiz84** [comment]
Hi,

for now its like this: I search <anything> and the whole tree opens, when I delete the search term, the whole tree stays opened

What I want is, that only those nodes stay opened, where something is found or those that where already open when starting the search.

Pseudocode:
IF (node.isOpen() && searchTerm.notFound()) doNothing
IF (node.isClosed() && searchTerm.notFound()) doNothing (keep closed)
IF (searchTerm.isFound()) openNode (and leave open).

I hope it's clear now :)

BR
Lukas

**Comment by lukiz84** [comment]
Hi Daniel,

the "Show full branch" option did the trick. Thx, I think this request can be closed :)
