### ISSUE TITLE
Typo: TOM Explorer

### ISSUE THREAD

**Issue by FinBIDev** [TabularEditor/TabularEditor3#553]
There's a typo in **Tools --> Preferences --> Tabular Editor --> TOM Exporer** (should be Explorer):

![image](https://user-images.githubusercontent.com/96748102/170834133-eace6746-f174-4358-935c-17bf12e7ab24.png)

**Comment by otykier** [comment]
Good catch, thanks for reporting!

**Comment by otykier** [comment]
Fixed in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0).
