### ISSUE TITLE
Wrong semantic error: CALCULATETABLE+USERELATIONSHIP

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#556]
Hi,
Not sure if it has been reported already:
On a model with an inactive relationship, the following expression gives (on TE3.2.3) a CALCULATETABLE+USERELATIONSHIP, which is correct, a semantic error  

`calculatetable(
    summarize(
        FacturaVirtual,
        Lineas[SERVICE_KEY]
    )
    , USERELATIONSHIP( -- relationship inactive by default
        Lineas[SERVICE_KEY]
        , FacturaVirtual[SERVICE_KEY]
    )
)`

![image](https://user-images.githubusercontent.com/27723187/171473489-6a913325-1fad-436a-a548-8ca23ec6a5a2.png)

**Comment by otykier** [comment]
Hi @zenzeinet 
Could you show us the relationship(s) between FacturaVirtual and Lineas?

**Comment by zenzeinet** [comment]
Sure:

{
  "InstanceID": "39e91ed1-6998-402e-b141-0318bcc50120",
  "singlecolumnrelationships": [
    {
  "name": "489bdb8b-3bc8-4388-878a-d033d5fc436c",
  "fromTable": "FacturaVirtual",
  "fromColumn": "SERVICE_KEY",
  "toTable": "Lineas",
  "toColumn": "SERVICE_KEY",
  "isActive": false,
  "state": "ready",
  "modifiedTime": "2022-05-30T18:49:52.123333",
  "refreshedTime": "2022-05-30T18:49:52.123333",
  "annotations": [
    {
      "name": "Vertipaq_RelationshipSize",
      "value": "32593352",
      "modifiedTime": "2021-07-27T22:41:55.163333"
    },
    {
      "name": "Vertipaq_MaxFromCardinality",
      "value": "8148336",
      "modifiedTime": "2021-07-27T22:41:55.163333"
    }
  ]
}
  ]
}

![image](https://user-images.githubusercontent.com/27723187/171638683-bf1536d8-dce0-41fd-903e-e99842379c69.png)

**Comment by otykier** [comment]
Are there no other relationships between the tables? If this relationship is the only one, may I ask whats the purpose of having it inactive?

**Comment by zenzeinet** [comment]
The model is large and has multiple fact tables. To simplify, lets think only of two, and call them FT1 and FT2. Both FT are linked by two table dimensions, DM1 and DM2.
The fact tables are usually joined using DM1 with an active relationship, while DM2 is inactive because it is not the typical join criteria.
But for some scenarios, we need to join by DM2, so we activate and use the inactive relationship.

DM2 cannot stay always active, or some logic would change. For example, we have some calculated columns on FT1 that get data from FT2 (very easy using the expanded table which only follows active relatoins), and for this we only want to be joining by DM1, and not DM2.

Hope this helps ;)



![image](https://user-images.githubusercontent.com/27723187/171640553-d99f25a0-9557-427d-b54d-242c2262af22.png)
