### ISSUE TITLE
Modify SQL statement for imported table in TE3?

### ISSUE THREAD

**Issue by thodegaard** [TabularEditor/TabularEditor3#557]
Hi,

I have imported ia table in TE3 through a legacy connection to a SQL Database by providing a SQL statement.
How can I edit this SQL statement in TE3 after the table has been imported?

By Thomas

**Comment by otykier** [comment]
Hi @thodegaard 
You can locate the SQL expression on the partition within the table:

![image](https://user-images.githubusercontent.com/8976200/171573018-6a129f43-5655-40b6-a035-e8ddbb9df72d.png)

After modifying the expression, hit F5 to apply the change and then right-click on the table or partition and choose "Update table schema" to have TE3 detect if any columns should be added/removed based on the new SQL expression.

![image](https://user-images.githubusercontent.com/8976200/171573122-fbfe4fa8-7c07-4e4c-b479-5b4476e25d37.png)

**Comment by thodegaard** [comment]
Awesome! Thank you very much for the quick respons @otykier
