### ISSUE TITLE
Different theme with each launch - Pie in the Sky feature Request

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#558]
My preferred theme is the default, but whenever I launch a 2nd, 3rd, or more instances of TE/3, I change the theme so I can sort of keep them straight. I am often working in two datasets that are nearly identical and running tests on the code - Dev ver1, Dev ver2, etc.

It would be nice if there was a setting to enable "Change theme with new instance of Tabluar Editor." A theme preference and order would be nice, but honestly I wouldn't care if they were fairly random. I'd rather deal with a [Hot Dog Stand color scheme](https://blog.codinghorror.com/a-tribute-to-the-windows-31-hot-dog-stand-color-scheme/) instead of making the wrong changes to the wrong model.

But when all sessions are closed, the first relaunch goes back to my preferred theme, not the last one closed.

**Comment by otykier** [comment]
We actually had something like [this](https://solutioncenter.apexsql.com/how-to-set-different-connection-colors-in-ssms/) in mind, for being better able to distinguish multiple sessions. Do you think that would cover what you need?

**Comment by edhans** [comment]
That could work - Yes!
