### ISSUE TITLE
New Version of TE 3 Detection Not Working Correctly?

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#56]
I am using TE 3.0.3 and I am getting prompted to upgrade to v 3.0.3 (see screen shot). Is this working correctly?

![TE4](https://user-images.githubusercontent.com/20615192/121177447-67780580-c82b-11eb-8c30-52309cf4f92b.png)

**Comment by otykier** [comment]
It should say "3.0.4". I just fixed it - thanks for reporting.
