### ISSUE TITLE
Connection to PowerBI Datamart dataset missing admin rights

### ISSUE THREAD

**Issue by SMiddletonBray** [TabularEditor/TabularEditor3#560]
I've created a new Datamart in Power BI, which auto generates a Dataset that I wish to connect Tabular Editor to (so that i can copy already commonly used measures on to this dataset). I have enabled XMLA read/write endpoints in the Tenant settings and I am an admin of the workspace.  When connecting to the workspace on TE3 via MFA i can see and load other datasets not related to the Datamart. However, when I try to connect to this particular dataset, I can see it in the workspace list, but get the error -  '**No Database with ID or name 'DM_Test' was found on the server, or the user account does not have administrative rights**'. My workspace is PowerBI Premium and i am on a Trial version of TE3. Has anyone else had issues connecting to Datamart related datasets?

**Comment by otykier** [comment]
Third party tools cannot connect to the dataset resulting from a Power BI datamart. This is a limitation of the Power BI service currently. As a workaround, consider exporting the dataset as a pbix which you can then republish or open in Power BI Desktop and then connect with Tabular Editor.

**Comment by SMiddletonBray** [comment]
Hi Daniel, Thanks for your answer, I was wondering if this might be the case.  I don't think you can currently download Datamart related datasets in PBIX format (or at least there is no option to when selecting the dataset settings) and you can't deploy measures via TE3  to pbix files linked to datasets.  Any other possible avenues i can try?

**Comment by otykier** [comment]
I must admit I haven’t tried it myself, just saw someone post this: https://twitter.com/hribberink/status/1531716432710582279?s=21&t=MPGGG8CkmO8RqGnXaR6RxQ

**Comment by SMiddletonBray** [comment]
this works! (as a workaround, not sure if there will be a more official solution to this in the future from Microsoft).  Thanks for your help :)
