### ISSUE TITLE
Yellow banner says CTRL+S To Synch, but that opens save dialog box

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#561]
not a show stopper, but it's been there for a while so I post it here. 

I run a script that creates a calculation group and a banner says I need to push CTRL+S to synchronize. Fine, so I do it. And then save dialog appears... 

![image](https://user-images.githubusercontent.com/40455069/173433175-c21dfab7-2c5e-40c6-a37c-70fd10598824.png)

![image](https://user-images.githubusercontent.com/40455069/173433253-3679b68f-b27c-4977-ab71-6e5e0f9073fc.png)

Apparently it's CTRL+SHIFT+S to make it work, but this also launches the save dialog for some reason

**Comment by otykier** [comment]
Yea, there's a small kink here where CTRL+S saves the currently focused document (in this case a DAX script). When no document is focused, CTRL+S saves the model. CTLR+SHIFT+S is "Save all", which also prompts you to save any open documents. We need a dedicated shortcut for saving the model only, regardless of which document is focused.

**Comment by otykier** [comment]
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html): We now have the CTRL+ALT+S shortcut which allows to save the model no matter the context. The text in the yellow banner should reflect this.
