### ISSUE TITLE
Incorrect Semantic Analysis?

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#562]
So, I have a calculated column that is giving me a semantic error because another calculated column in the same table which references it gets a circular dependency error. This only happens when I use `REMOVEFILTERS( )` to clear the filter context after context transition. Changing to `ALL( )` fixes the error. I'm thinking this is a bug?

![image](https://user-images.githubusercontent.com/62320770/173538918-374e05c4-fad0-4c9b-83c6-1f613f08a38d.png)

![image](https://user-images.githubusercontent.com/62320770/173539572-9e4d5dc0-0d27-4baa-bf7d-971bebaf70a0.png)

**Comment by otykier** [comment]
Thanks for reporting. A fix is on the way.

**Comment by otykier** [comment]
Fixed in [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0).
