### ISSUE TITLE
Regular "Open" does not work with database.json files

### ISSUE THREAD

**Issue by GKilsgaard** [TabularEditor/TabularEditor3#563]
When adding the "Open Model from folder.." to the toolbar, the icon is the same as the "Open.." icon.

It would be nice if it was different icons
![2022-06-15 05_54_13-Clipboard](https://user-images.githubusercontent.com/84013871/173733618-eb6e3877-9abf-423e-85dd-1b95082a5820.png)
.

**Comment by otykier** [comment]
The intention was that the regular "Open" option (Ctrl+O) should also let you pick a database.json file. There's a bug in 3.2.3 where that doesn't work, but that will be fixed in the next release. We may also provide a different icon at some point, as you point out. Thanks!

**Comment by otykier** [comment]
[3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.0) should now let you open database.json (folder structure) files even when you use the regular "Open..." (CTRL+O) option.
