### ISSUE TITLE
YOY % Cal with C# script 

### ISSUE THREAD

**Issue by praghi** [TabularEditor/TabularEditor3#565]
Hi Team
![YOY Cal_C#Script](https://user-images.githubusercontent.com/83985254/174082341-56751dff-4d56-4846-b2f9-ad197dabef34.PNG)
, 

I try to calculate the YOY% with C# script to automate my measures as per the attach instructions. The YOY% Calculation seems wrong, The YOY% calculation should be DIVIDE (YOY, LY) but as per given C# script it shows ( Total, YOY) . I tried my best to modify but couldn't succeed , Please could you help me out. Thank you  

Regards, 
Pratik

**Comment by otykier** [comment]
You're right, the calculation in the docs is wrong. We'll make sure it's fixed. Here's the right version:

```csharp
    // Year-over-year %:
    m.Table.AddMeasure(
        m.Name + " YoY%",                                           // Name
        "DIVIDE([" + m.Name + " YoY], [" + m.Name + " PY])",    // DAX expression
        m.DisplayFolder                                             // Display Folder
    ).FormatString = "0.0 %";  // Set format string as percentage
```

If you're using TE3 (v.3.3.0 or newer), you can use string interpolation to make the DAX expression a little easier to type:

```csharp
    // Year-over-year %:
    m.Table.AddMeasure(
        m.Name + " YoY%",                                           // Name
        $"DIVIDE([{m.Name} YoY], [{m.Name} PY])",    // DAX expression
        m.DisplayFolder                                             // Display Folder
    ).FormatString = "0.0 %";  // Set format string as percentage
```

**Comment by praghi** [comment]
Thank you so much Daniel. It works fine now woow !!!!
Tabular editor has made my life so easy especially c# script to automate
DAX measures and updating the metadata | SSAS cube ,  really appreciate
your hard work.

*Best Regards, *
*Pratik Ghimire*
*0469734228*
