### ISSUE TITLE
TE3 doesn't open with a fresh installation of latest build 3.3.0.x64 on Windows 11

### ISSUE THREAD

**Issue by vickar** [TabularEditor/TabularEditor3#566]
I was attempting to do a fresh installation of  TE3 v3.3.0.x64 on Windows 11, it installs successfully but doesn't open after installation.
I tried multiple times with no success. same with the portable version too.

Had to download TE3 v3.2.3x64 and it worked.

**Comment by otykier** [comment]
Could be related to missing .NET runtimes. Could you please try one or both of the following:

- Install the .NET 6.0 Desktop Runtime from [this site](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime) (most likely you'll need the [x64 Windows Desktop App runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer))
- If the application still doesn't start, take a look in the Event Viewer after attempting to launch. Look for any .NET Runtime errors within the Windows Logs > Application section (example in screenshot below) and share the details here or with support@tabulareditor.com, so we can investigate:
<img width="921" alt="Screenshot 2022-06-16 at 19 41 02" src="https://user-images.githubusercontent.com/8976200/174133105-ea881562-ce1f-4ec0-b4bc-894c20191eaf.png">

**Comment by vickar** [comment]
yup installing the .NET 6.0 Desktop Runtime worked for me. thank you.
