### ISSUE TITLE
Unable to create calculated column/hierarchy etc.

### ISSUE THREAD

**Issue by markjdm0117** [TabularEditor/TabularEditor3#567]
Hi,

I'm just wondering if this is a normal issue. I'm trying to create a calculated column in Tabular Editor 3 but only seem to get the option to create a measure. I currently have the below version of Tabular editor 3 which is the most recent one. If I right click to create to try to create a calculated column, this only allows me to create a measure? I'm under the impression there is more options than this one.  Is this only available for 'Enterprise' license?  Any ideas/help would be appreciated.

Runing on the below device and OS
![image](https://user-images.githubusercontent.com/107659059/174202329-b3189f6e-8c20-46ac-ae09-6ef71a8b8f85.png)

![image](https://user-images.githubusercontent.com/107659059/174201964-3f2b7c81-0a4b-4c7b-9049-badb32c339bd.png)

![MissingCreateOptions](https://user-images.githubusercontent.com/107659059/174201419-7a510ca3-09dc-4664-ab37-2082fba05fb1.jpg)

**Comment by otykier** [comment]
See [this](https://docs.tabulareditor.com/te3/desktop-limitations.html#data-modeling-operations).
