### ISSUE TITLE
Update for TE 3.3.0 is not notified

### ISSUE THREAD

**Issue by albertospelta** [TabularEditor/TabularEditor3#568]
Hi Daniel,
I am not sure that this is an issue, but just to let you know that the availability of version 3.3.0 is not notified to me, either when TE starts or by manually checking for an update.

I am using version 3.2.3 and the /UpgradeCheck API returns the following content
`{"latest": "3.2.8132.16105", "message": "A newer version of Tabular Editor 3 is available (3.2.3). ... }`

Thanks!
Alberto

**Comment by otykier** [comment]
This is intentional :-) we push out notifications a few days after announcing a new version on GitHub/Twitter to avoid everyone upgrading at once, to give us time to fix any bugs which may have escaped our internal tests.

**Comment by albertospelta** [comment]
I had missed this detail, I had never noticed it before.
Thanks for the quick reply!
