### ISSUE TITLE
[3.3.0] Update table schema throws authentication error

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#569]
Hi,

I have installed TE 3.3.0 portable and TE 3.2.3 portable. 
I receive this error message:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/6643712/174597480-72aacfed-8f65-4c91-bce0-8fb94219f1b2.png">

However, with TE3.2.3 the update table schema-options works without problems.

I use a onprem SQL Server:
ConnectionString: Data Source=int;Initial Catalog=DATABASE;Integrated Security=True and the Microsoft SQL Server (SqlClient) .NET Data-Provider.

**Comment by otykier** [comment]
3.0.0 uses updated SQL client drivers. Could you try to add `Encrypt=true` to the connection string?

**Comment by Rasenkantenstein** [comment]
Unfortunately the error message remains the same.

**Comment by otykier** [comment]
Could you also try `TrustServerCertificate=true`? Thanks

**Comment by Rasenkantenstein** [comment]
That worked. Thank you Daniel!
