### ISSUE TITLE
[3.3.0] Macros disappeared from the context menu

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#570]
In 3.3.0 the option "Macros" disappeared from the context menu:

I have two marcos:
![image](https://user-images.githubusercontent.com/6643712/174602445-e32b40bd-316d-4e83-bc57-d66a71c568b0.png)

But when clicking on the Model-context, there's no option for "Build Model.bim".
![image](https://user-images.githubusercontent.com/6643712/174602592-0050e55f-8e64-4a64-828c-33daaf71488a.png)

There's a workaround:
New macros work. If I use the same code and create a new macro, the macro-option in the context menu appears.

**Comment by otykier** [comment]
Could you send me the original definition of the macros? That is, the MacroActions.json file in your `%LocalAppData%\TabularEditor3` folder. Thanks!

**Comment by otykier** [comment]
Fixed in [3.3.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.1). Thanks for reporting!
