### ISSUE TITLE
Diagram View doesn't update with model refresh

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#572]
1. I created a new relationship in a model in the TEST workspace and did all of my testing.
2. I had a 2nd instance of T/E 3 open for the model in PROD and the diagram view had the relevant tables, not not all necessary relationships - only TEST had them for now.
3. I used ALM Toolkit to push the changes from TEST to PROD
4. In TE for the model in PROD, the Diagram view did not update with relationship changes.

I had to remove and re-add tables for the relationships to show up.

TE 3.3.

**Comment by otykier** [comment]
Just to clarify - did you reconnect TE3 to the prod model between step 3 and 4? (TE3 does not receive update notifications from the Power BI service XMLA endpoint, when another tool or another instance of TE3 makes a change)

**Comment by edhans** [comment]
No. I clicked on the "revert model" button that says it will reload model data from the service. Does that not include relationships?

**Comment by otykier** [comment]
I see - thanks for clarifying. Indeed, that's a bug.

**Comment by otykier** [comment]
Fixed in [3.3.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.1). Thanks for reporting!
