### ISSUE TITLE
Error when I try to save import "custom actions" from version 2

### ISSUE THREAD

**Issue by rvgfox** [TabularEditor/TabularEditor3#573]
Hi Daniel,

I've export/import all my custom actions but it can not be edited. I always get an error when I try to save it:

"Macro cannot be saved because the script contains one or mere errors"

But the script runs correctly.

_Originally posted by @rvgfox in https://github.com/TabularEditor/TabularEditor3/issues/79#issuecomment-1161320506_

**Comment by otykier** [comment]
Hi @rvgfox there is an issue in v. 3.3.0, in that it won't save custom actions (aka. macros) that have a backslash in their name. A fix (3.3.1) will come out later today. Could you confirm if that is indeed the issue in your case as well?

**Comment by rvgfox** [comment]
Yes, Daniel that it's the issue because I'm using the backslash to distinguish the folder name.

**Comment by rvgfox** [comment]
One question, is it possible to use the macros in a context menu on the measurements instead of in a toolbar?

**Comment by otykier** [comment]
Not sure what you're asking. Normally, the macros should appear in the context menu based on the macro context specified when saving the macro:

![image](https://user-images.githubusercontent.com/8976200/174737046-eca1dc88-4137-4824-87dd-3201169f8a4f.png)

The macro above appears as shown below:

![image](https://user-images.githubusercontent.com/8976200/174736972-7ecc86d0-d041-4aa3-8f40-01fc55f4325b.png)

**Comment by rvgfox** [comment]
Hi @otykier 
As you can see in the screen shot I cannot see my macros migrated from Tabular Editor 2 in the context menu:

![image](https://user-images.githubusercontent.com/72302636/176718702-f7c74676-f60e-4454-b38d-765818ba8242.png)

**Comment by otykier** [comment]
@rvgfox we’re working on that. Would be helpful if you could send your MacroActions.json file from `%localappdata%\TabularEditor3` to support@tabulareditor.com so we can verify that it works before the next release.

**Comment by rvgfox** [comment]
Sent

**Comment by otykier** [comment]
Fixed in [3.3.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.3). Thanks for reporting!
