### ISSUE TITLE
.Net namespace does not exist. (after upgrade to .Net 6.0)

### ISSUE THREAD

**Issue by verscev80** [TabularEditor/TabularEditor3#574]
Dear support,

I have a script to generate an Excel with all the descriptions.
After the latest update of Tabular Editor it is not working anymore, it gives following error:
**The type or namespace name 'Office' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)**
This presume it is related to the update to .Net framework V6.0
Is their anything I can do to get this fixed?

**Comment by otykier** [comment]
Could you share a small piece of your script? Specifically, I'm curious to know which assemblies you include (if any) by using the `#r` syntax.

For example, if you're using `#r "Microsoft.Office"`, it may be sufficient to change this to `#r "Microsoft.Office.Core"`.

**Comment by verscev80** [comment]
I use both the #r indication as the using indication:

#r "System.IO"
#r "Microsoft.Office.Interop.Excel"

using System.IO;
using Excel = Microsoft.Office.Interop.Excel;

Strange thing is that this code was perfectly working in the previous release.
