### ISSUE TITLE
Unable to access the Format DAX menu option on a Calculated Column

### ISSUE THREAD

**Issue by randyminder** [TabularEditor/TabularEditor3#575]
Hello. Is there some reason why we cannot access the Format DAX menu option for DAX code in a calculated column?

**Comment by otykier** [comment]
Are you connected to a Power BI Desktop (.pbix) model? In that case, please be aware that editing column properties (such as their DAX expressions) is not among the [supported write operations for External Tools](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations).

(To unlock all modelling operations enable the **Allow unsupported modelling operations** option under **Tools > Preferences** - just make sure to keep a backup of your .pbix file)

**Comment by randyminder** [comment]
Yes I am connected to a Desktop PBIX. Thank you for letting me know this limitation. To support this, is this a change that needs to occur in Tabular Editor or in PBI Desktop?

**Comment by otykier** [comment]
In PBI Desktop (the link I provided is for Microsoft's own documentation - the limitation applies to all third party tools, not just Tabular Editor)
