### ISSUE TITLE
Installation issues with newest version

### ISSUE THREAD

**Issue by gmuenster** [TabularEditor/TabularEditor3#577]
When trying to install the newest version, I always get this error message:
![image](https://user-images.githubusercontent.com/40482124/175103681-754b2bf1-fb2b-4283-a8b1-99ca2711e0e8.png)

I downloaded the framework from the link behind the button (https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore), installed, restarted, repaired TE, removed and reinstalled TE, nothing works. Everything works fine with the previous version.

**Comment by otykier** [comment]
Hi Gabi,
Make sure you download the **Desktop** runtime that matches the platform of Tabular Editor 3 (x64 vs x86):

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/8976200/175264579-74db2871-004e-48b9-a507-8dcd1569bf97.png">

**Comment by gmuenster** [comment]
Hi Daniel,

Thanks for the quick response, and sorry for bothering you. That happens if you do installation topics on the side, because “they don’t require so much attention”. ☹

Thanks,
Gabi
