### ISSUE TITLE
Load Model from Power BI Instance not available

### ISSUE THREAD

**Issue by bogdanlozyak** [TabularEditor/TabularEditor3#579]
Hi!
I've just downloaded TE3 3.3.0 **portable** Desktop Edition.
When i try to load the model, the "OK" button remains deactivated.

<img src="https://user-images.githubusercontent.com/12935758/175312817-1dbf90dd-ce6e-4266-a6f1-3848de50bcd3.png" width="450">

Previous TE3 3.2.3 **portable** Desktop Edition works fine.

TE3 portable build: 3.3.8102.25492
PBI Desktop  build: 2.106.582.0 (June 2022)

**Comment by otykier** [comment]
Thanks for reporting. As a workaround, until we get this fixed. If you launch TE3 from the windows command line, you can specify the servername:portNumber like below, which should cause TE3 to connect and open the Power BI Desktop model:

```cmd
TabularEditor3.exe localhost:52665
```
