### ISSUE TITLE
Provide option for formatting keywords/functions as lowercase

### ISSUE THREAD

**Issue by SteiniMiracle** [TabularEditor/TabularEditor3#58]
If you open the **Preferences** dialog and uncheck **Fix keyword/function casing** and click **OK** the changes are not saved.

**Comment by otykier** [comment]
Thanks for reporting (there's a bug in the UI in which this checkbox has been tied to the "Fix object reference casing" field instead).

Bonus-question, out of curiosity: What is your reason for wanting to disable automatic fix of keyword/function casing? Thanks!

**Comment by SteiniMiracle** [comment]
Lucky me to get the bonus question :-)  
T-Sql and Dax seems to be the only query/programming languages to use upper case for keywords.  
The original reason for the upper case was probably that it was easier to identify the keywords.  
For at least the last decade color coding has replaced the upper case  role in every good code editor (of course including Tabular Editor).  
The bottom line is that for me personally I find it much easier to read lower case text than upper case.

**Comment by otykier** [comment]
I see - thanks. Follow-up question: would you be interested in a setting that would allow keywords to be auto-formatted as lowercase?

**Comment by SteiniMiracle** [comment]
That would be, to put it mildly, FANTASTIC FEATURE :-)

**Comment by otykier** [comment]
Fix keyword/function casing now works in [3.0.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.5).

**Comment by otykier** [comment]
You can now configure keyword/function casing in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). See [docs](https://docs.tabulareditor.com/onboarding/personalizing-te3.html#casings-and-quotes) for more information.
