### ISSUE TITLE
Can't run macros from context menu

### ISSUE THREAD

**Issue by MattAlington** [TabularEditor/TabularEditor3#581]
I am using the latest version
![image](https://user-images.githubusercontent.com/34114455/175753384-3f50133d-9cde-4d29-bdb2-4fe5bdaa4771.png)

I have a macro to create measures from columns
![image](https://user-images.githubusercontent.com/34114455/175753400-9f85ee71-16f7-4b56-865f-83cf255c6a1b.png)

It is set as a valid context for Columns
 
When I right click in the TOM, I don’t see “run macro"
![image](https://user-images.githubusercontent.com/34114455/175753409-e46194b4-bc45-446b-aab7-57a6fb0aac7a.png)

**Comment by otykier** [comment]
Duplicate of #570
