### ISSUE TITLE
Macros Toolbar is gone once again

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#584]
With the version change I've lost again my macros toolbar. 
Even though I saved it as as part of a custom layout, it does not show when selected
I'm using the latest version
![image](https://user-images.githubusercontent.com/40455069/175822307-ff9a76e8-d545-4aa2-b6de-670f4b20ef52.png)

![26-06--2022_17-44-43](https://user-images.githubusercontent.com/40455069/175822375-ad64f7ab-7a9d-4d08-abdf-5b31e793c851.gif)

**Comment by otykier** [comment]
I suspect this might be related to the issue with macros not compiling, causing all items to disappear from the toolbar. Could you check under **Tools > Customize** if the custom toolbar still exists?

**Comment by bernatagulloesbrina** [comment]
Is gone from there too

**Comment by bernatagulloesbrina** [comment]
Oh, now that I fixed my macros using ScriptHost instead of ScriptHelper, the toolbar is back!!
