### ISSUE TITLE
Many properties missing when TE is in Read Only mode

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#596]
I love the new Read Only mode when in Tabular Editor, but I should be able to see all of the properties of the model, tables, etc. When in Read Only mode though many properties are missing from the property pane, and I cannot figure out a way to show them without closing TE and going to read/write mode.
The items in red are not visible. Many I admit I don't know what they are, but I was trying to document the refresh policy of a model and had to go to read/write mode as that entire section was not showing in Read Only mode.
Items in red are not visible in Read Only mode.

TE/3 3.3.2
![image](https://user-images.githubusercontent.com/45298358/177812509-b5228318-a611-4909-9d7e-edc66a68ce9d.png)

**Comment by otykier** [comment]
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html), thanks for reporting!
