### ISSUE TITLE
Minor tweak with Intellisense in commented lines

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#597]
I don't think there should be any typing assistance if the line is in a comment block. I am often getting two single or double quotes. For example, typing this 

// I don't think I need this variable

will actually result in
//I don't think I need this variable'

Because when I typed don't it automatically gave me the second single quote.

Super minor, one of those things to add to the backlog. As someone that has a lot of code comments, I see this often.

**Comment by otykier** [comment]
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html), thanks for reporting!
