### ISSUE TITLE
Diagram View report conflicts with Properties window

### ISSUE THREAD

**Issue by bogomda** [TabularEditor/TabularEditor3#6]
![Tabular Editor Diagram View](https://user-images.githubusercontent.com/66798479/119888247-20bd0e00-bf03-11eb-9e58-e4438b1c5d77.PNG)
Tabular Editor 3 Diagram View Create Relationship dialog box incorrectly reports relationship cardinality - circled in red

While properties screen shows  relationship cardinality accurately - circled in blue

**Comment by otykier** [comment]
Thanks for reporting. We will investigate.

**Comment by otykier** [comment]
Fixed in [3.0.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.1). Thanks for reporting!
