### ISSUE TITLE
DAX Query Results Table - Not the same functionality as in Preview Data

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#60]
I don't know if this is working as designed but when I preview data I get a nice table with a lot of options to sort and display the data. None of that exists when a table displays the results of a DAX query in a DAX Query tab.

**Comment by otykier** [comment]
I guess my reasoning when creating the DAX Query view was that users would use the DAX query itself to sort/filter the result. But I'm perfectly happy to allow local sorting/filtering of query results, if that is useful.

**Comment by rminder** [comment]
Thank you. I think it would be and I don't see any downside for doing so.

Randy

**Comment by otykier** [comment]
Fixed in [3.0.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.6).
