### ISSUE TITLE
Best Fit All Columns works differently for Tables and Vertipaq analysis

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#603]
When you preview a table, right-click on the columns and select Best Fit All Columns, it makes all of the columns wide enough to show all data and column names. This is good. 👍

When looking at Vertipaq stats though, the same command shrinks all columns to fit the widest _data_ but the column names are often truncated. Would be nice if it operated the same way as doing it on a Table preview.

TE 3.3.2

**Comment by otykier** [comment]
Fixed in [3.3.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.3). Right-click on a column header and uncheck "Lock column widths" to enable the horizontal scrollbar. After this, "Best fit (All columns)" should work as expected.
