### ISSUE TITLE
BPA Include File from URL not working against private GitHub Repo

### ISSUE THREAD

**Issue by alwortma** [TabularEditor/TabularEditor3#604]
Previously we were using GitLab for source control and were storing our BPA Rules files there.

We could add them to our models by specifying a URL with token like this:
`https://gitlab.devtools.XXX.com/api/v4/projects/132318/repository/files/BPARules.json/raw?ref=master&private_token=XXXXX`

Now we moved to GitHub and I can't figure out a way to add a BPA rules file in the same way that we did before.

I created a token on GitHub and can use it with cURL to successfully get the file:
`curl https://ghp_XXXX@raw.githubusercontent.com/XXXX/frameworks.business.ssas.documents.ssas-best-practices/master/BPARules.json >> GitHubBPARules.json`

However when trying to use this URL in TE3 I get a timeout error:
![image](https://user-images.githubusercontent.com/97995966/178844308-2df5de47-5b61-4b89-b584-53b865c955a9.png)

Am I missing something? Is there any way to do this using a file in a private GitHub organization?

**Comment by otykier** [comment]
Tabular Editor does not currently convert the token, which is part of the URL, to the required http authorization header. We’ll make sure that is fixed in the next update.

**Comment by otykier** [comment]
Fixed in [3.3.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.3). Thanks for reporting!

**Comment by alwortma** [comment]
@otykier Thanks so much for the quick turn around!!

**Comment by alwortma** [comment]
@otykier I was having issues, but I just had to change the proxy setting to _None_, then it worked great!
