### ISSUE TITLE
Vertipaq analyzer nto working with new parameters fields

### ISSUE THREAD

**Issue by AndreJaarconsult** [TabularEditor/TabularEditor3#605]
Hi,
when collecting stats vertipaq analyzer generate an error saying it couldn't collect data because the column of parameters fields have composite key, and not all composite keys are included in the expresion or have independent expresion  (My error is in portuguese, so i'm trying to translate here as close as possible).

But to reproduce just add a new parameters fields and try to collect stats

**Comment by otykier** [comment]
See #547
