### ISSUE TITLE
Macro on right-click not yet there? 

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#606]
I just downloaded the  latest version (3.3.3) and I see that the macro menu on right click is still not showing. I guess it's something known as I've seen it on twitter, but could not find it in the issues. Am I missing some configuration ?

![image](https://user-images.githubusercontent.com/40455069/179387727-6538ce47-1294-49ed-be3b-2487c23f776d.png)
`
I have plenty of macros that run on measures
![image](https://user-images.githubusercontent.com/40455069/179387761-12806990-af54-4af3-ba11-07b6f3091856.png)

**Comment by otykier** [comment]
This happens when one or more macros can’t be compiled. Could you send us your MacroActions.json file from `%LocalAppData%\TabularEditor3`, so we can investigate? support@tabulareditor.com

in the mean time, check the MacroActionErrors.log file in the same directory for more details about why the compilation failed.

**Comment by bernatagulloesbrina** [comment]
right away -- seems to be on the Error and SelectTable functions

**Comment by otykier** [comment]
Hi @bernatagulloesbrina 
Thanks for sending your MacroActions.json file. You have several macros that are explicitly using the `ScriptHelper` class, for example in calls such as `ScriptHelper.Error(...)`. The correct syntax is simply `Error(...)`, as the static methods on `ScriptHelper` are internal and not intended to be used directly (the fact that this worked in previous versions of TE3 was actually a bug). If you open your MacroActions.json file in a text editor and replace all occurrences of `ScriptHelper.` by an empty string, the macros compile without issue afterwards.

**Comment by otykier** [comment]
If you want to have the methods fully qualified (for example, to avoid compile errors when writing scripts in Visual Studio), use the [`ScriptHost`](https://docs.tabulareditor.com/api/TabularEditor.Shared.Scripting.ScriptHost.html#TabularEditor_Shared_Scripting_ScriptHost_Error_System_String_) class instead.

**Comment by bernatagulloesbrina** [comment]
Oh, that was it, then. Indeed I replaced ScriptHelper.xxx by ScriptHost.xxx and everything is working now! 
thank you very much
