### ISSUE TITLE
Refreshing table fails, refreshing model does not

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#609]
I have a model where I have modified one of the DIM tables, and that DIM table is also used in 2 calculated tables in addition to the various relationships it has to FACT tables.

When I right-click on the table and select Refresh Table, Full Refresh (Table) it runs for a few minutes, then fails with "The remote server returned an error: (400) Bad Request"

No additional details, The thing is it appears the table successfully refreshed. The new column is there and populated.

During the refresh, it also reports that it "Finished processing hierarchy on" and then about 50 column names, plus it appears to automatically recalculate any dependent calculated tables.

How can I debug this issue? Is there a refresh log that would be more beneficial, or is this a bug and TE isn't properly interpreting a return from the server? (Power BI Service)

As I said in the title, if I refresh the entire model, or a few other tables I've tried, it works fine.

**Comment by otykier** [comment]
Hi @edhans - could you share a screenshot or short recording to show the error? Most likely, this is an issue in the Power BI Service, as TE3 communicates with the service using Microsoft-provided client libraries. A (400) Bad Request error is a HTTP status code, which seems unrelated. Does your model perhaps contain power query / M code that tries to load data from a website / web api?

Anyway, to debug further, you would need to attach [SQL Server Profiler to the Power BI XMLA endpoint], and get a hold of the Progress Report Error events. Then, while the trace is running, try to perform a table refresh from TE3. You should then be able to gather more detailed error information through the SQL Profiler trace.

**Comment by edhans** [comment]
All M code goes to Dataflows, so no websites or APIs. I am unable to do a trace. The SQL profiler will connect, but says I don't have permissions to perform that operation. Does that require Admin role on the workspace?

**Comment by otykier** [comment]
When connecting with SQL Server Profiler, make sure to specify the name of the dataset under the "Connection Properties" tab (see screenshot).

One other thing to try is to start the refresh through SSMS (SQL Server Management Studio). You may get a more detailed error message here.

![image](https://user-images.githubusercontent.com/8976200/181439550-3e62df26-8f1b-44f8-865e-d3187d4e1909.png)

**Comment by edhans** [comment]
Sorry just getting back to this. Check your Support inbox for a trc file. It refreshed fine in that it repopulated the table (did a full refresh on the table) but gave the 400 error again at the end.

**Comment by otykier** [comment]
Thanks for providing the trace file. Unfortunately, it seems the 400 error was not captured in the file. Could you share a screenshot that shows the full error message once it appears? Thanks!

**Comment by edhans** [comment]
animated GIF of the full refresh with the error showing up sent to the support email.

**Comment by edhans** [comment]
Hey @otykier  - noticed you added bug to this. Did you find a repro on your side?

I spent time dealing with this over the weekend where refreshing partitions in an incremental refresh table did the same thing. every partition failed. I came back and saw the label was changed.

**Comment by edhans** [comment]
Will do. Haven't run across this recently but will be on the lookout for it.

**Comment by otykier** [comment]
Hi @edhans 
We will mark this issue as solved for now, but do reach out if it occurs again. Thanks!
