### ISSUE TITLE
Refreshing Partition Data In Parallel

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor3#61]
Hi,

When processing Partition Data in TE3 they are queued up in a per request queue. In SSMS you can run Partition refreshes in parallel, please could we have a feature where multiple refreshes can be started at the same time, or even a max number of refresh requests running.

Regards

Toby.

**Comment by otykier** [comment]
Notice that if you multi-select a number of partitions, ctrl-click and select multiple partitions (even across different tables), you can right-click and choose "Refresh partition" to process all the selected partitions in parallel. Does this solve your need?

**Comment by tobimax** [comment]
Yes, Thanks that's helpful.
