### ISSUE TITLE
Build 3.3.3 preventing table schema updates

### ISSUE THREAD

**Issue by otykier** [TabularEditor/TabularEditor3#612]
### Discussed in https://github.com/TabularEditor/TabularEditor3/discussions/610

<div type='discussions-op-text'>

<sup>Originally posted by **campeauslalom** July 22, 2022</sup>
Hello,

I updated to the latest Tabular Editor build (3.3.3) yesterday afternoon, and ran into an issue this morning where when attempting to update table schemas of both new and existing tables or partitions in a model, none of the columns were recognized - so, in the case of new tables there would be partition that was created with no columns, and updating existing tables removed all columns in said table. This behavior was occurring with all of our models whether connecting directly to the server or opening a .bim and using a workspace DB.

I was still able to successfully refresh the model both via XMLA endpoint from Tabular Editor and in the Power BI service without issue. A colleague had not yet installed the newest version and was still on build 3.3.2 and did not run into this issue, and when I uninstalled 3.3.3 and reverted to 3.3.2 I was also once again able to update tables normally.

For reference, these tables use M partitions connected to a Snowflake data warehouse without any transformations - just direct imports. When reverting to 3.3.2, functionality was restored using the same .bim and XMLA endpoints - the other change was the Tabular Editor build.  </div>

**Comment by otykier** [comment]
@campeauslalom thanks for reporting. We're investigating. As a workaround, consider enabling the "Use Analysis Services for change detection" option, as described [here](https://docs.tabulareditor.com/te3/tutorials/importing-tables.html#updating-table-schema-through-analysis-services).

**Comment by otykier** [comment]
@campeauslalom
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html)

**Comment by campeauslalom** [comment]
@otykier thank you so much, greatly appreciated!

**Comment by ChristianVolder** [comment]
TE3 v. 3.3.5 The issue might be back
![image](https://user-images.githubusercontent.com/114397663/192248048-8b90212d-4bc4-4118-b740-246d11582400.png)

**Comment by ChristianVolder** [comment]
@otykier Thank you! It works👍
