### ISSUE TITLE
Format String across multiple measures not working.

### ISSUE THREAD

**Issue by GilbertQue** [TabularEditor/TabularEditor3#614]
Hi there

When I select multiple measures and then select "Format String" and change them all to be whole number it does not change all the measures with the new format string.

I am using TE 3.3.3

**Comment by otykier** [comment]
Thanks for reporting. A workaround for now is to specify the format string value itself (i.e. "#,##0")

**Comment by GilbertQue** [comment]
Thanks Daniel, I will use that for now

I appreciate the hard work!

**Comment by otykier** [comment]
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html), thanks for reporting!

**Comment by GilbertQue** [comment]
Awesome thanks !
