### ISSUE TITLE
Intellisense with NAMEOF doesn't work at all

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#620]
I am trying to modify a Field Parameter table, and the Intellisense is only suggesting measures and functions in the NAMEOF(FieldName, Order) function.

Once I manually type the entire table and field name correctly, the red squiggly goes away, but it offers no help in selecting the table/field. Even after typing the table name and the opening bracket ( example: **'Products'[** ) it only suggests measures, not fields in the table.

**Comment by otykier** [comment]
Good catch. Yeah, the NAMEOF function is a recent addition to Dax and rarely (never?) used outside of field parameters, so it hasn’t gotten as much love in TE3 yet, as other functions.

**Comment by otykier** [comment]
Upon testing this with 3.3.3, I wasn't able to reproduce what you describe. When I invoke the autocomplete (ctrl+space) or by typing the first few characters, I get the full list of columns and measures in the model:

![image](https://user-images.githubusercontent.com/8976200/183045532-de3a71ad-bfba-44d5-bbd7-a897346dc39e.png)

The only discrepancy I noticed, was that auto-complete suggests the VAR keyword (variable definition), but that is nonsensical in the context of `NAMEOF`. Could you share a screenshot or some more details on how to reproduce this?

By the way, the NAMEOF function only takes a single argument - in your comment you indicate that it supports both a "FieldName" and an "Order" argument, but that is not the case, so I wonder if you made a typo somewhere else in your code?

**Comment by edhans** [comment]
You have to have the opening paren to describe the field, then the NAMEOF function. the order I was talking about is the 2nd field in the record. I guess the opening paren of the record is what is messing up the intellisense engine.

![NAMEOFIntellisense](https://user-images.githubusercontent.com/45298358/183110633-56e96167-d16f-46ad-94d7-fbf200b6b26f.gif)

**Comment by otykier** [comment]
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html), thanks for reporting!
