### ISSUE TITLE
Way to lock the Expression editor when browsing the TOM?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#621]
This is either a feature request or a display of my ignorance.

How can I lock the Expression Editor and still browse the TOM? When writing measures or doing whatever, I often need to browse the TOM in the TOM Explorer on the right, but when I do, whatever is in the Expression Editor either goes to a blank display, or shows what I am looking at in the TOM.

I tried the "pin" icon but that does nothing in this regard. A little padlock icon to freeze the Expression Editor on what I am working on that wouldn't navigate away until I unlocked it, no matter what else I am looking at.

I know I can use the back arrow to get where I am going, which does work sometimes, but not always. But I can be 2-3 clicks to get back to my expression, and in a long expression, it doesn't return me to where I was. And sometimes it doesn't work and I have to browse/search the TOM for what I was working on.

Or is there another way to browse the TOM without causing the Expression Editor to change focus?

**Comment by otykier** [comment]
Have you tried using the DAX Script option? (right-click on the measure you want to edit in the TOM Explorer, then “Script DAX”)

**Comment by edhans** [comment]
Nice. Beautiful workaround. 👍
