### ISSUE TITLE
Can't change name of new roles, making feature useless

### ISSUE THREAD

**Issue by Xtinction** [TabularEditor/TabularEditor3#624]
Hi there,

maybe I'm not understanding something, but when I try to create a new role using tabular editor 3 (or 2), I don't seem to have any control over the name of the new role. It will get its default name "New Model Role" and there doesnt seem to be anything I can do about it. I also cannot edit the name after (which would be OK if it gave me the option to name the new role upon creation)

Is this feature supposed to work like this, or should you be able to change role names somehow?

Thanks for all the hard work!

**Comment by otykier** [comment]
That’s a bug. You can allow editing of role names by enabling unsupported modeling operations. In TE2, you’ll find the setting under **File > Preferences**. In TE3, it’s under **Tools > Preferences**

**Comment by Xtinction** [comment]
Thanks for the workaround and quick response!

**Comment by otykier** [comment]
Fixed in [3.3.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.5). Thanks for reporting!
