### ISSUE TITLE
Missing keyboard shortcut: CTRL+D --> Select next occurrences of current selection

### ISSUE THREAD

**Issue by blomdahldaniel** [TabularEditor/TabularEditor3#630]
Hi!

I am a former programmer so I am used to advanced text editors. It is really surprising to me that seems to not be able to do
`CTRL+D => "Select next occurrences of current selection"`

It is even available in native Power BI dax editor. 

Is there something that I've missed? How can I activate this? This is a small thing but also important thing. Makes me not able to use tabular editor in many scenarios. I have to copy the text to a real text editor like visual studio code. 

When can we expect actual better text editor features in Tabular Editor 3?

**Comment by otykier** [comment]
May I ask what you would use "Select next occurrences of current selection" is, in the context of DAX? If you're looking for a way to rename all instances of a variable, for example, Tabular Editor has a refactor (Ctrl+R) feature - this is much better than simply selecting all identical occurrences, as the refactor feature also takes scope into consideration (you could have two similarly named variables in different scopes).

I guess what constitutes a "real text editor" is a matter of preference. For instance, in Visual Studio, CTRL+D is used to duplicate the current selection. In Notepad++, CTRL+D will duplicate the current line. Tabular Editor uses Scintilla which is the same text editor component used by Notepad++. It does have the ability to ["Add next occurrence to selection"](https://www.scintilla.org/ScintillaDoc.html#SCI_MULTIPLESELECTADDNEXT), but we haven't mapped this command to any keyboard shortcut currently. Here is the [list of TE3 text editor shortcuts](https://docs.tabulareditor.com/te3/features/shortcuts.html#textcode-editing-general) for reference.

We do have plans to expose all available Scintilla commands as configurable shortcuts - this is targetted for release in Q3/Q4 this year.

> When can we expect actual better text editor features in Tabular Editor 3?

Other than "Select next occurrences of current selection", what other features are you missing?

**Comment by otykier** [comment]
Just an update on this. With 3.4.0 it is possible to assign custom keyboard shortcuts, allowing you to use the Editor.MultipleSelectAddEach / Editor.MultipleSelectAddNext commands.

![D0BCDEC0-9A93-4B00-A8C3-435C7F25801E](https://user-images.githubusercontent.com/8976200/209364426-f62cce3d-7c69-4eed-8bbf-26831151781f.png)

If there are any other code editor features you’re missing, please feel free to open a new issue.
