### ISSUE TITLE
Debugger doesn't work with this Perf. Analyser DAX query

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#631]
As requested (https://twitter.com/DOtykier/status/1559500821712277504?s=20&t=1diukSb7GGQZdg5hz2Clzg), this is an example of where the DAX debugger isn't working.

A copy of the DAX generated by the Power BI Desktop Performance Analyser and the output from VertiPaq Analyser in TE3 [DaxAndVpax.zip](https://github.com/TabularEditor/TabularEditor3/files/9354995/DaxAndVpax.zip)

![image](https://user-images.githubusercontent.com/62320770/184994846-cdd24678-8faa-4271-9548-ce51341243c4.png)

![image](https://user-images.githubusercontent.com/62320770/184994811-e16e0964-2dfc-4f79-88ca-094655e9ba40.png)

**Comment by otykier** [comment]
Thanks for sharing. The culprit is the `SAMPLEAXISWITHLOCALMINMAX` DAX function which is not documented by Microsoft. I believe this to be one of the special AI functions, that are only available in Power BI - not Analysis Services in general, although this is the first time I'm seeing it. The DAX parser used by TE3 doesn't know about it, so you should also see that the TE3 query editor displays a wavy red line underneath that function call, indicating an error. When there's an error in the DAX query (from TE3's point of view), the debugger doesn't work.

May I ask how you arrived at a PBI query that includes this function? Are you using some kind of forecasting or other AI visual functionality in Power BI?

In any case, we'll update our DAX parser to support this function in the next release of TE3. At that point, you should be able to debug the query. We'll let you know once it's available.

**Comment by samaguire** [comment]
The visuals don't current use the AI features, but that's not to say that they didn't at some point - and there is some residual setting left in the background.

I'll see if I can squeeze in some time in the next few days to play with this some more on my end.


Regards
Stephen

**Comment by samaguire** [comment]
Well, I never would've guessed it, but `SAMPLEAXISWITHLOCALMINMAX()` related to the X-axis being a continuous type.

![image](https://user-images.githubusercontent.com/62320770/186067585-ad682958-0cbb-4d9d-b17b-7c21e43d9063.png)

The date table in the model uses dates to represent months and years, formatted appropriately, which by default translates to a continuous X-axis by default (and report requirement in this case). Changing the type to categorical removes that function from DAX that is generated.

However, the debugger can't debug the expression... 😢

![image](https://user-images.githubusercontent.com/62320770/186068429-b6a5bde5-ffba-4970-8a69-2c623e74724f.png)

```
// DAX Query
DEFINE
  VAR __DS0FilterTable = 
    TREATAS({"Apple"}, 'Variety'[Commodity])

  VAR __DS0Core = 
    SUMMARIZECOLUMNS(
      'Date'[Year Month],
      'Variety'[Variety],
      __DS0FilterTable,
      "Production_Gross", '​Measures'[Production Gross]
    )

  VAR __DS0PrimaryWindowed = 
    TOPN(201, SUMMARIZE(__DS0Core, 'Date'[Year Month]), 'Date'[Year Month], 1)

  VAR __DS0SecondaryBase = 
    SUMMARIZE(__DS0Core, 'Variety'[Variety])

  VAR __DS0Secondary = 
    TOPN(62, __DS0SecondaryBase, 'Variety'[Variety], 1)

  VAR __DS0BodyLimited = 
    NATURALLEFTOUTERJOIN(
      __DS0PrimaryWindowed,
      SUBSTITUTEWITHINDEX(
        __DS0Core,
        "ColumnIndex",
        __DS0Secondary,
        'Variety'[Variety],
        ASC
      )
    )

EVALUATE
  __DS0Secondary

ORDER BY
  'Variety'[Variety]

EVALUATE
  __DS0BodyLimited

ORDER BY
  'Date'[Year Month], [ColumnIndex]
```

**Comment by otykier** [comment]
Thanks for looking into that. I just realized that the SUBSTITUTEWITHINDEX function effectively removes contextual information from the result, meaning the debugger won’t be able to infer the filter context from a particular cell in the result. I’ll have to get back to the drawing board to figure out how we can enable debugging specific cells in the result, when actual column values have been substituted with an index in the result. Will keep you posted, thanks!

**Comment by otykier** [comment]
[3.3.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.5) adds debugger support for SUBSTITUTEWITHINDEX and more. Could you try the query again and let us know if it works now? Thanks!

**Comment by samaguire** [comment]
🚀🚀🚀 We have lift off! Great job, that's working. 👌

![image](https://user-images.githubusercontent.com/62320770/188747013-762dcd3e-f53c-4a57-bc44-659f9b10ad76.png)
