### ISSUE TITLE
The server sent an unrecognizable response

### ISSUE THREAD

**Issue by databiker** [TabularEditor/TabularEditor3#637]
Hi,

I'm getting the error message "The server sent an unrecognizable response" when trying to connect to a power bi service XMLA endpoint with Tabular Editor 3. I've tried connecting to the same XMLA endpoint using Tabular Editor 2, SSMS, and ALM Tool kit and all 3 have successfully connected. I'm assuming the issue is therefore with Tabular Editor 3. Can you please advise?

Thanks,

Travis

**Comment by otykier** [comment]
Hi Travis

This appears to be an issue with the AMO client library. Adding `;Protocol Format=XML` to the connection string when connecting to the Power BI XMLA endpoint should solve the problem.

To help Microsoft track down this issue, may I ask what [region](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-where-is-my-tenant-located#how-to-find-the-default-region-for-your-organization) you’re connecting to? Also, if you could share a sample pbix file that demonstrates this issue with support@tabulareditor.com, that would be helpful. Thanks!

**Comment by otykier** [comment]
One more thing: If possible, could you install [Fiddler](https://www.telerik.com/download/fiddler) and send us the details for the last /webapi/xmla request made before you get the error message in Tabular Editor? You will need to configure Fiddler to [decrypt https traffic](https://docs.telerik.com/fiddler/configure-fiddler/tasks/decrypthttps) and then restart Tabular Editor, for the traces to show up:

![image](https://user-images.githubusercontent.com/8976200/187150494-0183311d-6379-45b9-8fdf-31c114769d7c.png)

I know it's a big ask, but the fiddler traces should help the Microsoft product team track down exactly what is causing this issue.

Thanks a lot!

**Comment by otykier** [comment]
[3.3.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.5) will now automatically add `Protocol Format=XML` to the connection string, if BinaryXml fails. Thanks for reporting!
