### ISSUE TITLE
Token recognition error at: 'ø'

### ISSUE THREAD

**Issue by MrPets** [TabularEditor/TabularEditor3#638]
Hello, Tabular Editor team. 

Using characters like "ø" in column names, I get the following error message.

![image](https://user-images.githubusercontent.com/80754714/187206118-6a847e8e-3f12-426f-bf51-c60111b36257.png)

As a workaround I am currently renaming the columns, but hopefully there is an easy fix here. 

MrPets

**Comment by otykier** [comment]
Thanks for reporting. We've identified the problem and will apply a fix in the next update.

**Comment by otykier** [comment]
Fixed in [3.3.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.5). Thanks for reporting!
