### ISSUE TITLE
Unable to save file upon creating calculation group

### ISSUE THREAD

**Issue by Mpnazim** [TabularEditor/TabularEditor3#64]
Hi All,

I am unable to save to power bi after creating the calculation group, TE3  gets hang, i need to force shutdown TE3.

Another issue, while editing dax the error messages doesn't get updated, i am unable to see which line has the error. In some occasions, i can see the error message and the line in which the error is. 

I tried everything possible, but no success. I even tried to update to version 3.03 & 3.04, but i am getting many error messages (circular dependencies). Would appreciate community support and I am looking forward to purchase the subscription as it a wonderful tool to have.

Many thanks

Nazim

**Comment by otykier** [comment]
Hi Nazim.
I'd like to look into this in more detail. Is there a chance you can send me the .pbit file? (Power BI Template file without any data: In Power BI Desktop, go to File > Export > Power BI template). Also, which version of Power BI Desktop are you using, and what is the DAX code of the calculation item you tried to add, when TE3 was hanging?

Best regards,
Daniel - daniel@tabulareditor.com

**Comment by Mpnazim** [comment]
Hi Daniel,

Thanks for your swift response. I am using the Power BI may version -  2.93.981.0 64-bit (May 2021).

Unfortunately, i will not be able to share the template file due to our internal policy. Is there anything that i can reset to fix it, I tried clearing the Cache memory in power bi desktop file.

Reards,
Nazim

**Comment by otykier** [comment]
> when i save, it tells me there is an error, but it doesn't tell which line.

Could you provide a screenshot of this error message?

**Comment by Mpnazim** [comment]
Hi Daniel,

Please see below error message, i have intentionally referenced to wrong column name,  i see error message only when i hit save button and it doesn't highlight which line has error.


![image](https://user-images.githubusercontent.com/85615660/121471015-ad69d080-c9c7-11eb-84c8-4aeef0a5a85c.png)

**Comment by otykier** [comment]
It seems like Tabular Editor is not analyzing the DAX at all (there should also be a red dot on the measure icon to indicate the error).

Does this only happen when you're editing this specific model, or are you able to reproduce it on other models as well?

**Comment by Mpnazim** [comment]
Dear Daniel,

It is actually happening to this specific model. I tried to create a separate simple PB file, in that the error message was fine showing the specific line number.

further i downloaded the latest TE3 version 3.0.4. in that i am getting many circular reference error for the same file; please see below screen shot.

![image](https://user-images.githubusercontent.com/85615660/121526610-3867bc80-ca02-11eb-85c4-e89ce9eb890d.png)

**Comment by otykier** [comment]
The circular dependency issues have been fixed in [3.0.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.5). Thanks for reporting!

**Comment by Mpnazim** [comment]
Thanks Daniel, with the updated version 3.0.5, all of the above issues are resolved now. 

Much appreciated for your support and for this great tool. I am now one of your loyal customers, already purchased the license. 😊
