### ISSUE TITLE
I cannot see the Connect to Tabular Server pop-up screen 

### ISSUE THREAD

**Issue by dionisof** [TabularEditor/TabularEditor3#644]
![tabedit2](https://user-images.githubusercontent.com/9368985/188173200-ca78db71-3d07-4994-95ad-3ad80086492c.jpg)

I have installed on my laptop TE ver 2.16.5 and TE3 ver 3.3.82. Using TE2 I can connect to Tabular server using my power BI workspace connection url(as seen). Using TE3 I can only connect to localhost(opening first a power bi file). There is no way I can use TE3 standalone.
Is this some kind of option that I need to enable?
Thanks
Dennis

**Comment by otykier** [comment]
Are you using Tabular Editor 3 Desktop Edition? Is so, only connections to local instances of Power BI Desktop are allowed.

**Comment by dionisof** [comment]
Yes, I am using the Desktop edition...why is there this restriction for the commercial version??? SO I can use the free version and connect to Analysis services and I can only connect to a local instance using the paid version?

**Comment by otykier** [comment]
You would need Business Edition or Enterprise Edition to connect to other instances of Analysis Services, as per the link I provided above. Feel free to reach out to sales@tabulareditor.com if you have more questions, or if you would like a refund for your Desktop Edition purchase.
