### ISSUE TITLE
Incorrect tooltip for 'New Dax Script'

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#648]
The tooltip for the 'New DAX Script' icon shows the tooltip for the C# script editor.

![image](https://user-images.githubusercontent.com/29556918/188917396-a7817e7e-9923-4384-8aec-89010ae94b8e.png)

**Comment by otykier** [comment]
Good catch, thanks for reporting!

**Comment by otykier** [comment]
Closing this. Will track this on #678 instead.
