### ISSUE TITLE
unable to debug a cell in the [NameOfTheMeasure] column of the FILTER function

### ISSUE THREAD

**Issue by Klimkiv** [TabularEditor/TabularEditor3#649]
I've got this message when trying to debug a sell

unable to debug a cell in the [NameOfTheMeasure] column of the FILTER function

Please, advise

**Comment by otykier** [comment]
Could you share the full DAX query you are trying to debug? If you’re not comfortable sharing it here, feel free to send it to support@tabulareditor.com. Thanks!

**Comment by Klimkiv** [comment]
thank you!
