### ISSUE TITLE
DAX query // Either the session does not exisist or it has already expired

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#650]
Hi, after being idle for a while I want to execute a DAX query again. But this error message appears:
![image](https://user-images.githubusercontent.com/6643712/189108088-6560e6c5-c117-45ff-b01e-a0adb076b7d9.png)

Is there a button to reconnect to the server in order to execute the DAX query again?

Workaround: Copy the DAX query and paste it into a new DAX query window.

**Comment by otykier** [comment]
Thanks for reporting. We'll make sure that TE3 can automatically reconnect when the session has expired.

**Comment by otykier** [comment]
This is now fixed in [3.5.0](https://docs.tabulareditor.com/te3/other/release-notes/3_5_0.html?tabs=downloads). Thanks for your patience!
