### ISSUE TITLE
Difference in Object Type Property format 

### ISSUE THREAD

**Issue by pawarbi** [TabularEditor/TabularEditor3#659]
When you export column properties from TE3, the  Object type is `Model.T.TableName.C.ColumnName` whereas if you export from TE2, it's `Model.TableName.ColumnName` why ? 

I was having issues importing properties and I ma not sure if it's causing that.

**Comment by otykier** [comment]
The TE2 and TE3 import/export functionality is not currently compatible. At some point, we will change the format used in TE2 to match that of TE3.

**Comment by otykier** [comment]
However, import/export within the same version should not cause any problems. If that's the case, please open a separate ticket with an example of what doesn't work.
