### ISSUE TITLE
Reserved words used for variable not showing as an error

### ISSUE THREAD

**Issue by nayjay91** [TabularEditor/TabularEditor3#66]
I used 'cases' as a variable name in a DAX measure in TE3. The editor didn't flag this as an issue, but when saved to the PBIX the measures errored and displayed an informative message about 'cases' being a reserved word. Tabular Editor never flagged the measure as having an error.

**Comment by otykier** [comment]
Interesting. I never realized that this word is reserved in DAX. I wonder why. Anyway, will update the parser to flag this as an error when used as a variable name.

**Comment by otykier** [comment]
Fixed in [3.0.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.5). Thanks for reporting!
