### ISSUE TITLE
Request: Calculate Table from "Preview data" view

### ISSUE THREAD

**Issue by lukiz84** [TabularEditor/TabularEditor3#665]
Hi,

it would be nice to be able to Refresh (calculate) a calculated table using right click on the tab title. Because when I use a measure for the creation of the table which is not on the screen (because the model is too large) I always have to scroll, select the table and then click refresh (calculate).

thx

**Comment by otykier** [comment]
You can recalculate the current table through the **Table preview** > **Calculate table** menu option. There is also a toolbar button for this.

![D47CFBEA-EC46-40B8-8A86-61C5155D5EB6](https://user-images.githubusercontent.com/8976200/192032566-0a66c971-3091-4443-83c1-488fb86d62d3.jpeg)

**Comment by lukiz84** [comment]
Thx, this can be closed. Sorry, missed the option.
