### ISSUE TITLE
Bug: Closing an unsaved window doesn't ask to save it

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#673]
If you close a tab that is unsaved, like a diagram, it will prompt you to save it, and name it if necessary.

If that tab though is pulled out a floating window, pressing the X just closes it with no prompt to save. Any work will be lost.

**Comment by otykier** [comment]
Fixed in [3.3.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.6), thanks for reporting!
