### ISSUE TITLE
Unable to login to SQL Server database

### ISSUE THREAD

**Issue by nimishnagpal** [TabularEditor/TabularEditor3#677]
I am a model that has existing connections. It is Refresh fine. 
But in the tabular editor, if I try to "Update Schema" or "Import New Table" using those existing connections it is not allowing me to login. 

Error Message:
Unable to Connect to Source.
Unable to connect to the database 'xxxx' on 'ServerName': A Connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)

**Comment by otykier** [comment]
Hi @nimishnagpal 
This is a known issue in v. 3.3.5. To workaround, edit the connection details, click "Advanced" and then set "Trust Server Certificate" to "true".

**Comment by nimishnagpal** [comment]
Thanks for the quick response. That works for me. 

Once I have set "Trust Server Certificate" to "true" under the advance settings, I am unable to re-visit the advance properties of the connection. Where again can I find the advanced settings for the connection?

**Comment by otykier** [comment]
You can edit connection details on the Data Source object of your model:

![image](https://user-images.githubusercontent.com/8976200/192997529-86282242-51e3-49b5-b618-319fd0e1c840.png)

**Comment by nimishnagpal** [comment]
This data source property shows the GENERAL connection properties. I am looking for Advance settings like "Trust Server Certificate" property. Cannot find them here.

**Comment by otykier** [comment]
For a legacy data source, these settings are stored within the Connection String property. Click on the ellipsis button to bring up the connection details dialog:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/8976200/193001251-c37c2c54-e3a7-4752-8c36-3d29ba85cd7e.png">

For a structured data source, these options are not stored within the data model, as the Analysis Services engine uses some other data provider for connectivity. Tabular Editor, however, still uses the SqlClient provider, and so for that reason, it stores the advanced settings in the .tmuo file, which is saved next to your Model.bim file:

![image](https://user-images.githubusercontent.com/8976200/193001946-decf70a8-0d2c-4621-94ff-96ee29713a74.png)

**Comment by mlonsk** [comment]
@otykier has this issue been resolved in never versions of Tabular Editor 3?

**Comment by otykier** [comment]
Yes, I am not aware of any current issues with SQL connections (except for a very specific case with dedicated Synapse pools, which will be fixed in the next update).
