### ISSUE TITLE
New DAX Script Button Tooltip Wrong

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#678]
The tooltip text detail for this button is the tooltip text detail for the C# Script button

![image](https://user-images.githubusercontent.com/62320770/192919781-9c99feab-11ea-4f57-b0e6-9e2a3a686487.png)

**Comment by otykier** [comment]
Fixed in [3.3.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.6)!
