### ISSUE TITLE
Idea: Notification when Refresh is done

### ISSUE THREAD

**Issue by Rasenkantenstein** [TabularEditor/TabularEditor3#679]
Hi TE-Team.

I would like to suggest to receive a notification once a Data Refresh is done. Sometimes loading the data takes several minutes where the user is leaving TE3. A notification would help in order to be reminded, once the processing is done.

Thank you!

**Comment by otykier** [comment]
This is a great suggestion - at least as a toggleable option. Did you have a specific type of notification in mind, or would it be ok to use the [Windows Toast notification](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/toast-notifications-overview)?

**Comment by Rasenkantenstein** [comment]
No, nothing in particular. The function should just create awareness for a job done. As an additional info it would be nice to see whether the refresh failed or was successful. But that'd just be a bonus :-)

**Comment by otykier** [comment]
Currently, the status bar in the bottom left corner of the app will display the outcome of a refresh operation, but I guess you are looking for something more visible?

**Comment by zenzeinet** [comment]
Toast would be perfect.

**Comment by otykier** [comment]
This is already implemented and available since v. 3.3.6. I believe the toast notification only shows when TE3 does not have focus, though.
