### ISSUE TITLE
Idea: Copy/Format DAX in Format String Expression

### ISSUE THREAD

**Issue by FinBIDev** [TabularEditor/TabularEditor3#680]
Editing DAX in Format String Expression could be improved with two features:

1. Copy DAX
2. Format DAX

I edit lengthy expressions in Notepad++ because it’s easier to work with. It would be helpful to have a “Copy DAX” button so we don’t have to manually select the DAX and copy it.

Being able to format DAX directly in Format String Expression would be helpful. Maybe allow F6 to format DAX as it does in Expression Editor?

**Comment by otykier** [comment]
Are you aware that you can edit Format String Expressions directly in the main expression editor?

![image](https://user-images.githubusercontent.com/8976200/193218427-bd6f5bd1-1c8f-4f8d-b0aa-d32de1c35817.png)

Another option is to use the DAX Script feature (right click on a table or other object and choose "Script DAX"):

![image](https://user-images.githubusercontent.com/8976200/193218747-bca4a3be-252b-45c7-828b-5729bea5184e.png)

**Comment by FinBIDev** [comment]
Perfect! I was not aware of these features. Thank you for this amazing tool! :)
