### ISSUE TITLE
Bug in comments

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#681]
Look at the following code:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/45298358/193164946-7ece8f30-4225-4cfc-afde-1d88bd34ab45.png">

This is in Power BI Desktop, and it works. The way this came about is I commented out the code  line 5 with  /* and */

Then later I decided to comment out a much larger block and added an opening /* on line 2 and a closing */ on line 8.

But Tabular Editor doesn't like this:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/45298358/193165089-664b6c20-ae3f-4661-a30a-a1d11cf9e988.png">
It is ignoring the 2nd opening /* and is closing out the entire thing at line 6, so reports an error for lines 7 and 8.

So I got rid of the closing comment on line 6 and now it shows it is all commented out.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/45298358/193165196-803ce3e5-8bc1-456a-8b2a-4424c7aa8df8.png">
But... Power BI Desktop isn't having it. 
<img width="261" alt="image" src="https://user-images.githubusercontent.com/45298358/193165241-a0ee73a2-9ca8-4691-8def-5d03558d316d.png">

I know this isn't the best way to comment out blocks, and I should have just highlighted a bunch of stuff and used the comment button, but I didn't. But the editor in T/E should correspond to how the desktop works.

**Comment by otykier** [comment]
Right, I wasn't aware that DAX comment blocks could be nested. We'll make sure that's fixed, thanks!

**Comment by otykier** [comment]
This is now fixed in [3.4.1](https://docs.tabulareditor.com/te3/other/release-notes/3_4_1.html?tabs=downloads). Thanks for reporting!
