### ISSUE TITLE
TOM Explorer appears cut-off

### ISSUE THREAD

**Issue by jw-dax** [TabularEditor/TabularEditor3#685]
Hi - first time posting. The TOM Explorer in TE3 appears to be cut-off. The names of measures and tables are shortened and have "..." at the end. This makes it difficult to use and navigate. Any ideas? Thanks!

**Comment by otykier** [comment]
Is this using version 3.3.5? See #629

**Comment by jw-dax** [comment]
Yes, 3.3.5. CTRL+7 fixes it.
