### ISSUE TITLE
Unable to view macros

### ISSUE THREAD

**Issue by MaddyTP** [TabularEditor/TabularEditor3#687]
Trying to view macros through View > Macros has no affect in 3.3.5.  Unable to access existing macros.

**Comment by otykier** [comment]
Just to get this straight: does nothing happen when you go to View > Macros. Does it work after resetting the window layout (Window > Default layout)?

**Comment by MaddyTP** [comment]
Ah, it does show when using the default layout but still doesn't show any macros:

![image](https://user-images.githubusercontent.com/45469378/194138382-0fbe0158-0321-400a-9421-c601dfe18aa0.png)

So it would seem this issue is two parts:  macro window doesn't show in custom layout, macro window when shows doesn't reflect actual saved macros.  Image above should reflect ~5 macros I have saved (and use often).

**Comment by otykier** [comment]
I believe this is a bug that occurs when the macros window is not visible during startup. Restarting TE3 should cause the macros to appear.

**Comment by otykier** [comment]
Just an update: This issue was fixed since v. 3.4.0. Get the latest version here: https://docs.tabulareditor.com/te3/other/downloads.html
