### ISSUE TITLE
Context Menu differs depending on the direction you select variable name

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#692]
This one is kinda weird, but finally figured it out.

If you select the name of a variable from left to right, when you right-click the Rename Variable is there.
But if you select the name from right to left, Rename is not there. CTRL-R is reserved for Refactor, and that is grayed out, and I am not sure what that even means in the context of selecting a variable name.

It also works when double-clicking, but double-clicking is a bit tedious for me when the variable is 1 character, and the first thing I do when I see a 1 char variable name is rename it!

![DifferentMenus](https://user-images.githubusercontent.com/45298358/194626119-f4264e15-7b06-4b1c-9747-5b66c2d3a678.gif)

**Comment by edhans** [comment]
Note that pressing CTRL-R is the same. Left-to-right it works. Right-to-left nothing happens.

**Comment by otykier** [comment]
Fixed in [3.12.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.12.0), thanks for reporting!
