### ISSUE TITLE
Trouble changing the Sort By Column in the GUI

### ISSUE THREAD

**Issue by frerus** [TabularEditor/TabularEditor3#693]
Hi!

Had trouble updating the sort by column in the properties window,

![image](https://user-images.githubusercontent.com/55258466/194774556-61d9ed5e-3c6a-4543-8ce6-6e19bf73cb79.png)

![image](https://user-images.githubusercontent.com/55258466/194774572-be3df744-8650-494a-867c-23934a622ae0.png)

It is however possible to execute a "C#" Script to do the operation;

![image](https://user-images.githubusercontent.com/55258466/194774639-8cddd6b0-450f-4697-b9bb-5a7ce999d537.png)

![image](https://user-images.githubusercontent.com/55258466/194774648-edbc4907-261f-467f-aaf9-8f2fe1b2729d.png)

**Comment by otykier** [comment]
This was fixed in 3.3.5. See #625

**Comment by frerus** [comment]
Oh, thanks. Better get IT to give me the newest version then, sorry for the trouble and thanks for quick feedback :)
