### ISSUE TITLE
Valid C# Script cannot be saved as Macro (even in TE3)

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#694]
Hello,

this script can be executed without problem, but not stored as macro. Why? 

https://github.com/bernatagulloesbrina/TabularEditor-Scripts/blob/main/Advanced/One-Click%20Macros/Create%20measures%20with%20a%20calculation%20group.csx

Regards!

**Comment by otykier** [comment]
Hi @bernatagulloesbrina 
You are using `ScriptHelper.Error(...)` and `ScriptHelper.Info(...)` a few places within the script. This needs to be changed to `Error(...)` and `Info(...)`. Once I did that, the script ran fine in both TE 2.17.1 and TE 3.3.5, and I was able to save it and run it as a macro as well.

**Comment by bernatagulloesbrina** [comment]
Oh! Sorry
I thought i had searched for those but said there was none. Might have
searched badly...
