### ISSUE TITLE
Tabular Editor 3 doesn't recognize all relationships in the model when connecting to Analysis Services

### ISSUE THREAD

**Issue by bogomda** [TabularEditor/TabularEditor3#7]
Tabular Editor 3 doesn't recognize all relationships. I am connecting to the same model on Analysis Services Tabular but see different results. Tabular Editor 3 only shows 9 relationships, where Tabular Editor and Power BI Desktop show correctly 13.
![TabularEditor - relationships](https://user-images.githubusercontent.com/66798479/119895609-f9b70a00-bf0b-11eb-93cc-a608eb25ac1d.PNG)
![TabularEditor3 - relationships](https://user-images.githubusercontent.com/66798479/119895611-fa4fa080-bf0b-11eb-83fa-159f52beaa0c.PNG)
![PowerBI - relationships](https://user-images.githubusercontent.com/66798479/119895612-fa4fa080-bf0b-11eb-933d-2420402ff199.PNG)

**Comment by otykier** [comment]
Thanks for reporting. Any chance you can send a .bim file that reproduces this error to support@tabulareditor.com? Then we will take a closer look.

**Comment by otykier** [comment]
Fixed in [3.0.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.1). Thanks for reporting!
