### ISSUE TITLE
Dynamic LINQ Filter not working for Partition Object Types

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor3#70]
Hi,

When using CTRL-F the Dynamic LINQ Filter i.e. :State <> "Ready" it leaves out partitions in the result set. This is a different behavior to TE2.

Regards

Toby

**Comment by otykier** [comment]
Fixed in [3.0.5](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.5). Thanks for reporting!
