### ISSUE TITLE
ColumnConverter cannot convert from TabularEditor.TOMWrapper.DataColumn

### ISSUE THREAD

**Issue by pmalmquistKayne** [TabularEditor/TabularEditor3#700]
When attempting to sort one column by another column (straightforward in Power BI), I get the error above. I have searched google and can't find anything relating to this specific issue. We will attempt to re-install the software and resolve, but for now, has anyone else seen this?

**Comment by otykier** [comment]
See #625. This issue was fixed in the latest update.
