### ISSUE TITLE
Server sent an Unrecognizable Response

### ISSUE THREAD

**Issue by CPAanalytics** [TabularEditor/TabularEditor3#705]
This occurs across workspaces and on all machines:

![image](https://user-images.githubusercontent.com/79522568/200175200-38635710-f9a1-4593-9129-ba588b524ea1.png)

**Comment by CPAanalytics** [comment]
Looks like a re-install to latest version solves the issue.

**Comment by Dinesh-Sankaran** [comment]
Is there any solution to fix this issue?

**Comment by otykier** [comment]
@Dinesh-Sankaran yes, update to the latest version or modify the connection string as described in #637
