### ISSUE TITLE
Bug or bad code on BPA rule for Partitions?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#709]
I have the following expression for my TODO rule in BPA:

    Expression.IndexOf("TODO", StringComparison.OrdinalIgnoreCase) >= 0 or 
    Description.IndexOf("TODO", StringComparison.OrdinalIgnoreCase) >= 0 

I have checked "Partition" for scope, but when I enter TODO in the description of a partition, it doesn't show up. 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/45298358/201174204-d5b1b2cb-07c0-43f2-8f74-19ec4c3ccf62.png">

**Comment by otykier** [comment]
Have you tried manually refreshing the BPA results view? It seems we have an (unrelated) bug currently, where as the BPA results view does not always refresh on its own.

<img width="640" alt="Screenshot 2022-11-10 at 20 06 12" src="https://user-images.githubusercontent.com/8976200/201184277-d17b6e46-6d00-4275-be45-82f69da7f218.png">

**Comment by edhans** [comment]
No, I tried that. Restarting TE did fix it though. I have now installed 3.3.6, and now _none_ of my TODO rules are showing in the BPA pane, even though it is active in the "Rules for the local user"

Was working fine with 3.3.5 (other than the partition) yesterday.

**Comment by edhans** [comment]
If you have any suggestions as to how to fix, would love to hear it. I've restarted the app, restarted Power BI and TE/3.3.6, I've disabled and enabled the rule, changed the priority, etc. All the other rules seem to be firing, but not this one. My full rule is below. 

```
  {
    "ID": "DAX_TODO",
    "Name": "[CRITICAL] Revisit TODO expressions",
    "Category": "DAX Expressions",
    "Description": "Objects with an expression containing the word \"TODO\" (typically as a comment), should most likely be revisited.",
    "Severity": 4,
    "Scope": "Table, Measure, Partition, CalculatedColumn, CalculatedTable, CalculationGroup, CalculationItem",
    "Expression": "Expression.IndexOf(\"TODO\", StringComparison.OrdinalIgnoreCase) >= 0 or \r\nDescription.IndexOf(\"TODO\", StringComparison.OrdinalIgnoreCase) >= 0 ",
    "FixExpression": null,
    "CompatibilityLevel": 1200,
    "ObjectCount": 0,
    "ErrorMessage": "No property or field 'Expression' exists in type 'SingleColumnRelationship'"
  },
```

**Comment by otykier** [comment]
You should remove “Table” from the scope, since regular tables do not have an Expression property, and as such, the entire rule will fail to evaluate. Consider splitting the rule into two: One for expressions, the other for descriptions (which are available on more object types).

**Comment by edhans** [comment]
That did it. No idea why it was working in 3.3.5 though. Thanks.
