### ISSUE TITLE
Login to TE3 - "Please Wait" spinner appears in front of login window

### ISSUE THREAD

**Issue by nariusp** [TabularEditor/TabularEditor3#712]
More of a irritation than a real issue but one that does not occur with other 3rd party power bi tools. This has persisted through multiple releases of TE3. When the login box come up, when you try to enter the password, the "Please Wait" dialogue with the spinner appears in front of the login window and you have to click again into the password box:

![image](https://user-images.githubusercontent.com/88670230/201481440-f1df5783-c346-44d9-94f7-e3df689a3e7a.png)

**Comment by nariusp** [comment]
TE3 Version:

![image](https://user-images.githubusercontent.com/88670230/201481488-fc9bb981-4649-4615-a75a-f13f1f5a4219.png)

**Comment by otykier** [comment]
Could you confirm if this issue is still present in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html?tabs=downloads)? Thanks.

**Comment by nariusp** [comment]
Yes it is still doing it with the latest version (just downloaded it just now to retest, as you can see the spinner dialog appears as soon as I click back to the password box.

***@***.***


Please note the website text has not been updated to show version 3.4, even though it is downloading version 3.4.

***@***.***

**Comment by otykier** [comment]
@nariusp we have not been able to reproduce this. Could you let us know which type of authentication dialog you are seeing this happening with? Is it when you connect to Analysis Services / Power BI, or when using the Import Table Wizard / Update Table Schema (and if so, what type of data source are you connecting to?). Thanks!

**Comment by nariusp** [comment]
It’s OKTA mfa authentication dialogue (still appears with the new build)

**Comment by mlonsk** [comment]
Hi @nariusp 
This issue should have been solved in newer versions of Tabular Editor 3. Sorry for not updating sooner.
I will close the issue, but if you are still experiencing it do reopen it again.
Thank you
