### ISSUE TITLE
Cannot Update Table Schema from Power BI Dataflows

### ISSUE THREAD

**Issue by TedCStack** [TabularEditor/TabularEditor3#715]
Hi Daniel,
I upgraded to the newest version; I am trying to "Update Table Schema" from the TOM Explorer window. The Update Table Schema pops up and stalls. Do you have an idea how to resolve. 
Thank You 
Ted Stack

**Comment by otykier** [comment]
Thanks for reporting this. As mentioned offline, the workaround, until we get this fixed, is the following:

1. Delete the .tmuo file next to your model
2. Open the model in TE3
3. From the **Model** menu, choose **Import tables...**
4. Choose **Import tables from a new source** then hit OK.
5. Choose **Power BI Dataflows** then hit OK
6. Sign in to your Power BI account and choose the workspace in which your dataflow resides. Hit OK, and confirm that you can see your dataflows.
7. **Cancel** the Import Table Wizard.
8. Now, you should be able to perform an Update table schema on the existing tables in your model8.

**Comment by otykier** [comment]
Fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html?tabs=downloads). Thanks for reporting!
