### ISSUE TITLE
TOM Object Names Appear Cutoff

### ISSUE THREAD

**Issue by juaguirre** [TabularEditor/TabularEditor3#716]
For some reasons, all 6he TOM objects like tables and measures appear cutoff which makes it very difficult to identify them, see attachment, thanks!! 
![TOM Names Cutoff](https://user-images.githubusercontent.com/113481504/202585954-a43d7a40-fcbb-40e2-a044-b5ad42619403.png)

**Comment by otykier** [comment]
Thanks for reporting this. Please try to toggle the info columns (CTRL+7)

**Comment by juaguirre** [comment]
That worked thanks a lot Daniel !!

Best Regards,

Juan L Aguirre - WIPRO
Data Analyst / Power BI
***@***.******@***.***>
SMS +1 5127396096

***@***.***

**Comment by otykier** [comment]
This bug should now be fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html?tabs=downloads).
