### ISSUE TITLE
No Display of Errors in DetailRowExpression

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#718]
![image](https://user-images.githubusercontent.com/74975641/202718189-c3c68404-81c0-4f5e-a506-ccf3e4e27df5.png)

1) the Error in the Detail Row Expression is shown but I am missing a Info (Mousover like in TE2)
2) an Error in the DetailRow Expression on table level is not shown at all

**Comment by otykier** [comment]
Regarding the info, please check the **Messages** view, which should show information about all DAX expressions that have errors.

Your point 2) is a bug. We'll look into it. Thanks!

**Comment by mlonsk** [comment]
This bug has been solved in newer version of Tabular Editor 3.
![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/bf4c9cc4-6b8e-4e70-b1a6-c3192579f4e2)

Closing the issue, thank you for reporting it so it could be fixed.
