### ISSUE TITLE
Where is the Macro toolbar option?

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#72]
How do I get the Macro toolbar option to appear regularly? I loaded TE and it doesn't appear (as you can see in the image below). But, sometimes it seems to appear randomly.

![TE1](https://user-images.githubusercontent.com/20615192/121400139-3845bf00-c925-11eb-87a9-f786074c77c8.png)

**Comment by SharmaAntriksh** [comment]
Also, after enabling a toolbar from the view menu if I click anywhere on the model the toolbar goes away.

**Comment by otykier** [comment]
By default, inactive toolbars are hidden. For example, the macro toolbar does not have any available actions if you're not looking at a C# script.

If you'd like to see all toolbars (even inactive ones) at all times, uncheck "Hide inactive toolbars" under Tools > Preferences >  User Interface

![image](https://user-images.githubusercontent.com/8976200/121483336-59aeb580-c9ce-11eb-803d-d67a8b13ae9e.png)

**Comment by otykier** [comment]
@rminder and @SharmaAntriksh did my reply above help? Can we close the issue?
