### ISSUE TITLE
CustomAction is not finding macros

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#720]
As per the below screen clip, CustomAction doesn't find macros if they are more than one level deep?

![image](https://user-images.githubusercontent.com/62320770/202845165-6aaa812d-89ad-4dab-bcda-8808ddaacffa.png)

**Comment by samaguire** [comment]
Upon working further on this, it looks like the macro couldn't be found due to editing the name of the macro directly in the name column, rather than right clicking on the macro and selecting edit and changing the name in the dialogue box.

![image](https://user-images.githubusercontent.com/62320770/202845827-a51a18ea-4ee3-42a9-ad37-d4a100cd5a87.png)

**Comment by samaguire** [comment]
And when I restart TE3 it goes back to not finding the macros again...

**Comment by otykier** [comment]
Hi @samaguire 
With the release of [3.5.0](https://docs.tabulareditor.com/te3/other/release-notes/3_5_0.html?tabs=downloads), this issue has now been fixed! Also, you can use `Macro(...)` instead of `CustomAction(...)` (both methods do the same thing - it's just an alias).
