### ISSUE TITLE
The right-click menu on the SourceExpression field on a table with a refresh policy does not have an "Edit expression" option

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#721]
Editing the SourceExpression for tables where you've set a refresh policy has always been a painful experience. So I had high hopes for this new "Edit Expression" feature in 3.3.6. But I suspect there is a bug here that blocks this menu option from showing up:
![image](https://user-images.githubusercontent.com/31990588/203272232-94024fbf-f826-49ed-a267-7ebd765f727e.png)

**Comment by otykier** [comment]
Thanks for reporting. It'll be fixed in the next update.

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
