### ISSUE TITLE
Shortcut for selecting all occurences.

### ISSUE THREAD

**Issue by toledorifat** [TabularEditor/TabularEditor3#722]
Dear team, 

First of all, thank you for this amazing product! 
I'm onboarding myself to TE3 from the default DAX editor in PBI. Understanding TE3 has been a great experience so far and I already requested a monthly subscription from the firm I work in!

I have a question that I wasn't able to find on keyboard shortcut documentation. (Tried searching online, in various forums as well.)
Is there a shortcut for selecting every occurence of the selection? (Ctrl + Shift + L in DAX editor)

I read about Ctrl + R and how it is applicable for measure names, but there is an essential difference between that and my question. 

Is there any way that I can select multiple occurences for (table name, keyword, function, operators, etc.) basically any kind of text reoccurrence?

Cheers!

**Comment by otykier** [comment]
Hi @toledorifat 
Our latest version [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html?tabs=downloads) allows you to set custom keyboard mappings through **Tools > Preferences > Keyboard**. If you like, you can assign a shorcut to **Editor.MultipleSelectAddEach** and **Editor.MultipleSelectAddNext**, which should do exactly what you want.

![image](https://user-images.githubusercontent.com/8976200/209955165-45a77874-79ff-45eb-8532-27a9c80f432a.png)
