### ISSUE TITLE
Dax debugger not working with simple SUMMARIZECOLUMNS : debug not available

### ISSUE THREAD

**Issue by oberthou** [TabularEditor/TabularEditor3#723]
Hi team,

I don't get why on this particular pbix file I get this "debug not available" message.

This is a very simple dax request with SUMMARIZECOLUMNS.
It is not according to me in the list of not supported features of the debugger.

I use a very simple explicit measure  : 
![image](https://user-images.githubusercontent.com/24804373/203856333-3a386bea-8947-42ee-b690-14d90dc7271d.png)

It seems to me this might be linked to a particular setting of the model in this file ?
Anyway to debug why it does not work ?
Thanks ! 

![image](https://user-images.githubusercontent.com/24804373/203855903-1e1f7a17-86bc-446c-a1c4-a3cb0fd08580.png)

**Comment by otykier** [comment]
Hi @oberthou 
That's weird. Are you seeing any error/warning messages on the 'Incidents'[Category] column? Does this also happen if you choose a different column or a different measure in your query?

If you can send me the .pbit file of your model, I'm happy to take a closer look: daniel@tabulareditor.com

**Comment by oberthou** [comment]
Hi Daniel. 

Same issue on this file , whatever the column, whatever the measure ..
I sent you the .pbit file for investigations.

Thanks !

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!

**Comment by oberthou** [comment]
Thanks a lot. Nice Christmas Present 😀

Le ven. 23 déc. 2022 à 15:14, Daniel Otykier ***@***.***> a
écrit :
