### ISSUE TITLE
Sort By Column error

### ISSUE THREAD

**Issue by JulianeCC** [TabularEditor/TabularEditor3#727]
Hi, I am getting an error when trying to sort the text column Month Short Name by the numerical column Month Number. I keep getting the error "_ColumnConverter cannot convert from TabularEditor.TOMWrapper.DataColumn_."
Is it a bug or does anyone have an idea how to fix this? 

<img width="446" alt="Annotation 2022-11-30 152529" src="https://user-images.githubusercontent.com/119512487/204821352-ae815503-2e7e-4335-a420-1a4b6db0040f.png">

**Comment by otykier** [comment]
Please see #625
