### ISSUE TITLE
Perspectives - How do I tables to them?

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#73]
I was able to add a Perspective in TE 3 but I don't seem to be able to add any tables to it. How do I go about doing this?

**Comment by otykier** [comment]
There will be a perspective editor in a near term update. Until then, you can use the property grid (this works even if you ctrl+click or shift+click to select multiple tables in the TOM Explorer):

![image](https://user-images.githubusercontent.com/8976200/121483066-0f2d3900-c9ce-11eb-9ba3-8ad1a53413f3.png)

**Comment by samaguire** [comment]
Have you tried using this in TE3? (At least until it gets a native editor.)

https://www.elegantbi.com/post/perspectiveeditor

**Comment by otykier** [comment]
You can now add/remove objects from perspectives directly through the context menu, similar to TE2: [v. 3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0)
