### ISSUE TITLE
Allow cancel or warn, when saving model that is being processed/blocked

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#730]
TE3: When saving a model, it would be nice if te3 would first check if a transaction is open, so that te3 doesn't become frozen while trying to save (until the open transaction finishes), and allow/warn the user. Alternatively, allow to cancel saving the model.

**Comment by otykier** [comment]
Performing the check upon every save could add precious seconds to the time a save operation takes (especially when working against a remote AAS or Power BI model, as there is a round-trip overhead). And the [TOM SaveChanges](https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.model.savechanges?view=analysisservices-dotnet) method unfortunately does not allow cancelation, so I'm afraid we're a bit out of luck on this for now. I've reached out to Microsoft, to see if they can provide any suggestions.

**Comment by zenzeinet** [comment]
Maybe if the TOM SaveChanges itself doesn't allow cancelling, then it should be possible doing the following (have done it manually sometimes). Would this be possible?

- After the SaveChanges, independently
- Query the SPID [1]
- if the user wants to cancel , push an XMLA Cancel [2]
- reconnect if needed

[1] -- similar to the following
SELECT 
	ssasSessions.SESSION_SPID AS [SPID],
	ssasSessions.SESSION_USER_NAME AS [User ID],
	ssasSessions.SESSION_CURRENT_DATABASE AS [Database],
	ssasConnections.connection_host_name AS 'Client IP address',
	ROUND(CAST(ssasCommands.COMMAND_CPU_TIME_MS AS int)/1000, 2) AS [Command Time(in sec)],
	ssasCommands.COMMAND_START_TIME AS [Command Start Time],
	ssasCommands.COMMAND_END_TIME AS [Command End Time],
	ssasCommands.COMMAND_TEXT AS [MDX Command],
	connection_host_application AS 'Application',
	CHARINDEX('</Process>',ssasCommands.COMMAND_TEXT) AS ProcessRunning
	, ssasSessions.*
	, ssasCommands.*
	, ssasConnections.*
FROM OPENQUERY(SSAS,'select * from $system.discover_sessions') AS ssasSessions
	LEFT JOIN OPENQUERY(SSAS,'select * from $system.discover_commands') AS ssasCommands ON ssasSessions.SESSION_SPID = ssasCommands.SESSION_SPID
	LEFT JOIN OPENQUERY(SSAS,'select * from $system.discover_connections') AS ssasConnections ON ssasSessions.SESSION_connection_id = ssasConnections.connection_id
where 
    ((ssasCommands.COMMAND_END_TIME is null) OR (@showFinished = 1))
    AND NOT (try_cast(ssasCommands.COMMAND_TEXT as nvarchar(2000)) = N'select * from $system.discover_commands')
ORDER BY [Command End Time], [Command Start Time] DESC

[2] -- similar to
<Cancel xmlns="http://schemas.microsoft.com/analysisservices/2003/engine">
  <ConnectionID>[CID]</ConnectionID>
  <SessionID>[SID]</SessionID>
  <SPID>[SPID]</SPID>
  <CancelAssociated>[true/false]</CancelAssociated>
</Cancel>

**Comment by otykier** [comment]
This is now possible in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
