### ISSUE TITLE
multi-cursor edit bugs with ( and "

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#734]
TE3: editing DAX in column (multi-cursor) mode is sometimes interrupted by autoformat code - e.g. when opening a parenthesis, or writing " , and wrong formatting is done

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
