### ISSUE TITLE
multi-cursor editing in M 

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#737]
TE3: Partition: M Expression Editor: multi-cursor editing does not work properly - multiple lines are selected, but when typing the multi-editing goes away. (Works properly when editing DAX measures)

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
