### ISSUE TITLE
App Link to Tabular Editor 3 Docs is not a link to the root page of the docs

### ISSUE THREAD

**Issue by AnalyzeThis** [TabularEditor/TabularEditor3#74]
On the Help menu item, Tabular Editor 3 Docs, it links the user to "the latest" page (https://docs.tabulareditor.com/projects/te3/en/latest/) of the docs, and not to the root of the docs (https://docs.tabulareditor.com/).

The current setting definitely leaves the impression of there is a lot left undocumented.

I can see the value for the current setting for a "new" product or a "new release", but its gives a clunky impression that to get to the root, I have to go up to the address bar and backspace. I noticed on the "latest" page that there is a home icon, but clicking did not take me to the root page of the docs.

**Comment by otykier** [comment]
We're still in the process of cleaning up our documentation pages. Our problem is that a lot of articles, blogs, etc. point to articles on docs.tabulareditor.com, which is documenting Tabular Editor 2.X. So we're considering a different subdomain for Tabular Editor 3 docs.

**Comment by otykier** [comment]
FYI, our new docs site for Tabular Editor 3 documentation is: https://docs3.tabulareditor.com - it will be a couple of weeks before all our URLs are updated to point to this site.

**Comment by otykier** [comment]
We're launching our new docs site today, consolidating all documentation for TE2 and TE3: https://docs.tabulareditor.com (DNS may take a few days to fully update - the new site should look like this: https://delightful-mud-081affe03.azurestaticapps.net/index.html)
