### ISSUE TITLE
Revert/Reload 

### ISSUE THREAD

**Issue by dim123dim123** [TabularEditor/TabularEditor3#744]
In last version build 3.3.8350  Revert not work correctly and almost time is disabled state.
It is very bad - need any time go to open DB select server and model 
Restore Revert/Reload button is Always active and possible to press it

**Comment by otykier** [comment]
Possible duplicate of #729

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
