### ISSUE TITLE
Vertipaq Analyzer shows 0 for cardinality of columns in Table view

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#750]
Cannot reliably reproduce and cannot get a screencap from a client machine, but the cardinality of most columns in a 200M record fact table (10 partitions, 20 segments) via the XMLA endpoint in PPC sometimes shows 0 for the cardinality of most columns in that table.

Vertipaq Analyzer in DAX Studio shows it just fine, so doesn't seem to be a dataset issue. In TE/3 I'm connected via a JSON folder to the workspace. Compatibility level is 1569.

**Comment by edhans** [comment]
Got some screen caps. You can see TE is showing 0 for all columns.
Tabular Editor 3.3.6
![image](https://user-images.githubusercontent.com/45298358/206236659-5baaf321-3f13-4292-87dc-258a64e4c645.png)

DAX Studio 3.0.5
![image](https://user-images.githubusercontent.com/45298358/206236767-679f9ec8-23d2-47f4-a184-e3bf0a1bd09e.png)

**Comment by otykier** [comment]
Hi Ed. Could you try to enable the **Read statistics from data** setting under **Tools > Preferences > VertiPaq Analyzer**? This seems to be the default setting in DAX Studio:

![image](https://user-images.githubusercontent.com/8976200/206676064-1665fc7e-903d-494c-ad7d-f3fb2445cac6.png)

**Comment by edhans** [comment]
Indeed. That was it. I had it disabled because of [bug 547](https://github.com/TabularEditor/TabularEditor3/issues/547), but that seems to have been fixed. Thanks.
