### ISSUE TITLE
Changes not saving from the "SQL Connection Details" dialog to "Connection String" 

### ISSUE THREAD

**Issue by jobosol** [TabularEditor/TabularEditor3#755]
It might be that this is me using TE3 wrong, but when I use the "SQL Connection Details" dialog the password, user id, server name is is not updating the connection string. 

![image](https://user-images.githubusercontent.com/38816188/206724277-9c6938ba-cf6d-4e92-823a-80569b0dbdc7.png)

So when I want to change the connection string I have to paste this manually in instead of using the dialog like this:
Data Source=dwh;Initial Catalog=dwh;User ID=user;Password=************

See example in video. I tried to change user from user55 to user999, but when I clicked "OK" the connection string still shows user55. 

https://user-images.githubusercontent.com/38816188/206735695-e75bd45d-ab50-4811-899d-b12ca3ba777f.mov

**Comment by cos3c** [comment]
yes this is annoying, found a temp solution by updating the .bim file in notepad and reopening the TE3 application and updated the data source

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
