### ISSUE TITLE
Dependency View - Show Objects on which this depends - crashes

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#758]
Is anyone else seeing consistent crashes with 3.3.6 and the December 2022 Power BI Desktop with Dependency View? The "Objects that depend on this" works fine, but as soon as I select "Objects on which this depends" it crashes. I have sent 2-3 error reports.

I am not seeing this issue when connected to a dataset in the service, and Tabular Editor 2 is not crashing when doing the same.

I can repro this on two different PCs in two totally different environments, so I am doubtful of any local PC software conflicts.

**Comment by otykier** [comment]
It’s a known bug in 3.3.6. Not related to PBI Desktop.

**Comment by kaDargo** [comment]
I'm using build 3.3.8350.24632 and "Show Dependencies" opened once and caused TE3 to abort.  I then tried opening it again and the dialog box does not display at all.

**Comment by otykier** [comment]
@kaDargo try to reset your window layout: **Window > Default Layout** - this should at least make the dependency view show up again. However, the bug that @edhans mentioned persists, and there is unfortunately no known workaround in 3.3.6. We hope to have a new version with a fix available before the end of the week.

**Comment by kaDargo** [comment]
Thanks for the info!

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
