### ISSUE TITLE
Exported Stats of the Vertipaq Analyser do not track Properties like IsHidden, AvailableInMDX. 

### ISSUE THREAD

**Issue by nimishnagpal** [TabularEditor/TabularEditor3#76]
The export from the Vertipaq Analyser in Tabular Editor 3 is unable to include all the information about the column property, like IsHidden, AvailableInMDX. 
By default, all the attributes are coming as False.

**Comment by otykier** [comment]
I am not able to reproduce this issue using TE 3.0.7. Could you provide a detailed step-by-step that displays a model with a column having IsHidden = true, but where the vpax file displays "IsHidden": false?

**Comment by otykier** [comment]
@nimishnagpal do you still have this issue in newer versions of TE3? Have you tried enabling the new **Tools > Preferences > File formats > VertiPaq Analyzer > Read statistics from data** option?
