### ISSUE TITLE
Filtering databases causes the wrong database to be opened

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#761]
Even in alphabetical order, with dozens and dozens of datasets to scroll through it can be tedious finding the one you want. A search field for the DB name would help greatly.
![image](https://user-images.githubusercontent.com/45298358/207893713-b9c91e18-2642-4989-9cc7-fb5cd94a5535.png)

**Comment by edhans** [comment]
I did not notice that. Thanks!

**Comment by edhans** [comment]
Hey @otykier  - I cannot get this to work.

1. Open the Database dialog box
2. Select the filter for the name
3. Type in a keyword
4. Check the one I want
5. Now, only one is in the database dialog box. I open that.
That is not what opens. It seems to open the first one in the _unfiltered_ list.

**Comment by otykier** [comment]
That's a bug :/ will look into it

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
