### ISSUE TITLE
Bug: Partitions after implementing Incremental Referesh not visible until closing/opening TE/3

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#764]
I implemented Incremental Refresh, Applied the changes, refreshed the table. All partitions were hydrated, but the TOM view still only showed the single partition. Vertipaq Analyzer showed all 6 correctly. The only way I could figure out how to get the TOM to update was to close/reopen TE/3.

This is on Premium Capacity if it matters.

And in fact I must close after the update is done and a full refresh on that table has been completed. Any further saves result in an error about a partition key not existing, because the TOM in TE/3 still shows the single partition, not the historical partitions.

**Comment by otykier** [comment]
Thanks for reporting!

**Comment by mlonsk** [comment]
This issue has been solved in newer version of Tabular Editor 3 with the apply refresh policy option on the table level. Closing the issue.
