### ISSUE TITLE
Displaying the default language of the data model between two updates of the web page

### ISSUE THREAD

**Issue by SteveNzeko** [TabularEditor/TabularEditor3#767]
Dear community, hello!

 I have an operation in my display that I find logical, but I would like to be sure; I explain it to you: I have a dataset in which the metadata is translated into English (American) by TE3. I would like to remind you that the default language of the model in power bi desktop is French. Once my dataset is published and the browser language is set to English, when I refresh my web page several times, the report is sometimes displayed in English (American) and sometimes in French (default language of the model in power BI). My question is the following: Is this phenomenon normal? Or is it a bug?

**Comment by otykier** [comment]
I'm sorry, but this question is not related to Tabular Editor. Please ask this question on the [Power BI support forum](https://community.powerbi.com/) instead.
