### ISSUE TITLE
Nested /* /* */ */ comments not properly parsed

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#768]
Hi,
In DAX (as per "it works correctly in SSAS") , the following is allowed as the /* */ comments can be nested, but returns a parsing error in TE3:

````
evaluate 
{ 3
/*
/* */
*/
}
````

**Comment by otykier** [comment]
Duplicate of #681

**Comment by zenzeinet** [comment]
Oops true!. Didn't find it on a quick scan of the open issues :)
