### ISSUE TITLE
dependencies navigator: does not work with keyboard to expand/contract items

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#775]
The Dependencies navigator does not work with keyboard (left-right) to expand/contract items.

Also, would be nice to have a toggle to show/hide measures and implement relationships from the list (already requested elsewhere)

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Relationships can now be shown as well. Please open a separate ticket for show/hide measures (maybe other object types should be togglable as well?)
