### ISSUE TITLE
Tom Explorer: quick show distinct values from column

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#778]
Tom Explorer: would be nice if for columns there would be a option or dropdown for quickly viewing the top (100?) distinct values, like in Excel PivotTable fields

**Comment by otykier** [comment]
Great suggestion, although I think this should ideally be solved using macros (provided our scripting API provides an easy way to launch a new DAX query, for example)

**Comment by zenzeinet** [comment]
Is the macro something us users would program / do? any way to test? (the macros doc page is WIP). Or is it a future development?

**Comment by otykier** [comment]
See [this answer](https://github.com/TabularEditor/TabularEditor3/issues/776#issuecomment-1363795695).

[Macro docs](https://docs.tabulareditor.com/onboarding/cs-scripts-and-macros.html#saving-a-script-as-a-macro).

**Comment by zenzeinet** [comment]
I commented over your answer - the macro route works great! 

(and i somehow stumbled upon an old macro doc page - your link is fine)

**Comment by otykier** [comment]
Great - closing this ticket then. It’s a pretty advanced use case which I think is better for scripting/customization anyway.

**Comment by zenzeinet** [comment]
For the brave that read up to here, here is a more advanced version (with a few quirks and extras) to see the top 50 values together with its count, % of total, and an extra column to distinguish blank() from empty string, and also a row with the "other" remaining below the top 50. Feel free to copy and improve!

```
foreach(var c in Selected.Columns)
{
string cName = c.Name;
string cTable = c.Table.DaxObjectFullName;
var cColumn = c.DaxObjectFullName;
var cColumnName = c.DaxObjectName;
string daxQuery =
 " VAR _TotalRows = COUNTROWS( " + cTable + " ) "
+" VAR _TOP = "
+" TOPN(50 ,                                                        "
+"    ADDCOLUMNS(                                                   "
+"        VALUES( " + cColumn + " )                                 "
+"        , \"@" + cColumnName + "\" , IF(ISBLANK( " + cColumn	 + " ) , \"!!____ BLANK ____!!\"  "  
    +"            ,  IF(FORMAT( " + cColumn + " , 0.0000 )==\"\", \"!!____ EMPTY STRING ____!!\" "
+ "           , FORMAT( " + cColumn + " , 0.0000 ))"
    + ")" 
+"        , \"@CR\" , CALCULATE(COUNTROWS(+ " + cTable + " ))       "
+"        , \"@%CR\" ,ROUND(100*CALCULATE(COUNTROWS(+ " + cTable + " ))/_TotalRows , 2)      "
+"    )                                                             "
+"    , [@CR] , DESC                                                "
+") "
+" VAR _REMAINING = _TotalRows - sumx(_TOP, [@CR])  " 
+ "var _DUMMY = topn(1, VALUES( Actos[FE_ACTO] ))"
+" VAR _ROWREMAIN = { ( _DUMMY - _DUMMY  , \"!!____ OTHER ____!!\" , _REMAINING , ROUND(100*_REMAINING/_TotalRows , 2) )}  "
+" VAR _FINAL = FILTER(UNION( _TOP , _ROWREMAIN), [@CR] > 0 ) "
+ "RETURN _FINAL "
+ "ORDER BY [@CR] DESC " ;
// daxQuery.Output()	;
var cResult = EvaluateDax(daxQuery);
cResult.Output();
}

```

**Comment by mlonsk** [comment]
Nice @zenzeinet 
Can I suggest you submit it to https://github.com/PowerBI-tips/TabularEditor-Scripts so the rest of the community can get it there?

**Comment by zenzeinet** [comment]
Good idea, wasn't aware of that place. Code updated & pull requested --> https://github.com/PowerBI-tips/TabularEditor-Scripts/pull/27
