### ISSUE TITLE
deleting all tables in pbix from TE3 doesn't delete them, tables come back

### ISSUE THREAD

**Issue by bogomda** [TabularEditor/TabularEditor3#78]
Typically I develop initial reports in pbix with the model, then i re-publish most recent dataset, delete the model from the pbix file and then reconnect report to published dataset.
Following this procedure, I tried separate the report from dataset by deleting all tables from the model using TE3, when I refresh the pbix file, tables come back.

**Comment by otykier** [comment]
It's [not currently possible](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations) to use external tools to delete/modify tables in a pbix file.
