### ISSUE TITLE
Feature request: Keep filters in "Preview data" view after table is processed/calculated

### ISSUE THREAD

**Issue by jobosol** [TabularEditor/TabularEditor3#780]
In Power BI Desktop and Visual Studio filters set on a table interface is kept when the table is refreshed, but this is not the case for Tabular Editor and "Preview Data". It is a bit annoying when working with calculated columns in Tabular Editor.  

Example here I have filters on Year 2023 to 2027, but when I recalculate the table this filter is gone, and I need to apply the filter one more time to see that the calculated column is giving me the expected result. 

Is it possible to keep the table filters after the table is recalculated? 

![image](https://user-images.githubusercontent.com/38816188/209938876-a74e8c90-4b60-4f12-b947-908b652ce80c.png)

**Comment by otykier** [comment]
Great suggestion. We'll make sure that's fixed, thanks!

**Comment by otykier** [comment]
Hi @jobosol.
This is fixed in our [latest release](https://docs.tabulareditor.com/te3/other/release-notes/3_7_1.html?tabs=downloads). Thanks for your patience.
