### ISSUE TITLE
TE 3.4.0: Revert is not synchronizing changes done in live SSAS model

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#781]
Hi,

In TE 3.4.0, the Revert button is not properly re-synchronizing with external changes made in the SSAS model.

Tried using the Revert button to synchronize after a colleague edited some relationships in the model, and no changes were displayed. 

Re-opening the model fixed the issue - but that's the point of the revert button! (also, not having to re-create DAX queries & diagrams)

**Comment by otykier** [comment]
Are you using workspace mode or purely open from database (Ctrl+Shift+O)?

When hitting Revert in workspace mode, the model metadata is loaded from disk and then redeployed to the workspace database, causing any changes that were made to the SSAS model through a different instance of TE, to be overwritten.

When using open from database, you should see the changes that were made (and any changes *you* made without saving, will be discarded, as per the warning).

**Comment by zenzeinet** [comment]
Thanks for the reply, trying it again it seems to work correctly (great for that)

I know what I think happened - there was a colleague working with TE2 that got de-sychnronized, and was seeing and saving some old data that then changed. On his side, saving his changes again did not re-update the model (i.e. - TE2 was not re-synchronizing, as it probably did not think of re-saving it - it works incrementally). So it was probably our fault.

If I find any instances of it not synching with TE3 I will get back to you, meanwhile you can close this.

Thanks!
