### ISSUE TITLE
TE 3.4.0: crashes with dependencies panel

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#782]
Hi, with "track tom explorer" active, double-clicking on relationships in the dependencies panel results in a soft crash.

**Comment by mlonsk** [comment]
Hi @zenzeinet 
Thank you for reporting, we will look into fixing it.

**Comment by otykier** [comment]
This is now fixed in [3.4.1](https://docs.tabulareditor.com/te3/other/release-notes/3_4_1.html?tabs=downloads). Thanks for reporting!
