### ISSUE TITLE
Keyboard shortcuts dialog filtering does not work

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#785]
Hi, 

I noticed that entering any text in the "Show commands containing" text box results in an empty list of commands
not the end of the world, but it would be nice if it worked

regards!

![imatge](https://user-images.githubusercontent.com/40455069/210849483-5d73ca4b-9653-474a-85ee-10a124116647.png)

**Comment by mlonsk** [comment]
Hi @bernatagulloesbrina 
Thank you for reporting, we will look into fixing it.

**Comment by mlonsk** [comment]
This was fixed in 3.4.1, but was not closed then, so closing it now.
