### ISSUE TITLE
Bug: Diagram relationship lines issue

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#787]
Hello,

I notice an issue when using the digram where relationship lines are not moving when table are being move around.
![image](https://user-images.githubusercontent.com/102403055/211237582-b2289480-5482-402d-aa08-ce536b7bf0ca.png)
![image](https://user-images.githubusercontent.com/102403055/211237634-40bfb753-d044-4e60-a611-ed3ee8aa3f8d.png)

To reproduce the bug:
Add a table which has relationships to other table(s), right click on header and choose "add all related tables".
Add a disconnected table, right click on header and choose "add all related tables".

Try to move a table on one side of the relationships.

I am using TE 3.4.0 and I haven't tested on previous version.

Thank you

**Comment by mlonsk** [comment]
Hi @rem-bou 
Thank you for reporting, I can confirm that this is a bug.

**Comment by otykier** [comment]
This is now fixed in [3.4.1](https://docs.tabulareditor.com/te3/other/release-notes/3_4_1.html?tabs=downloads). Thanks for reporting!
