### ISSUE TITLE
Import Custom Actions from Tabular Editor 2

### ISSUE THREAD

**Issue by steved-MarketGrunt** [TabularEditor/TabularEditor3#79]
Hi,
I may have missed this in the documentation but, is there a simple way of importing the custom actions created in TE2 to TE3. Also, when trying to call custom actions using CustomAction(@"Time Intelligence/Create QTD measures") TE3, I receive a message that "Time Intelligence/Create QTD measures" does not exist. However, I can see the measure in the Cscript window. #Question

**Comment by otykier** [comment]
Sorry for the late reply.

To migrate your custom actions, simply copy the file `%localappdata%\TabularEditor\CustomActions.json` to your `%localappdata%\TabularEditor3` folder and rename it as "MacroActions.json".

As for the issue with `CustomAction(...);` not working, this will be resolved in 3.0.6.

**Comment by otykier** [comment]
The `CustomAction` method should work in [3.0.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.6).

**Comment by rvgfox** [comment]
Hi Daniel,

I've export/import all my custom actions but it can not be edited. I always get an error when I try to save it:

"Macro cannot be saved because the script contains one or mere errors"

But the script runs correctly.
