### ISSUE TITLE
Show FACT tables (many side) at the bottom (2nd row) of diagram mode

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#790]
I know that if you ask 10 devs how they like their diagrams you'll get 11 answers, but...

It would be nice when adding tables automatically (add tables that filter this table, or add all related tables) it would be nice if we had an option that the tables on the many side were below the tables on the 1 side.

It would prevent this kind of display
![image](https://user-images.githubusercontent.com/45298358/211362956-2dea5749-4bf9-4045-879c-83cad591abba.png)
And maybe put any disconnected tables at the very top, or something.

I know it wouldn't be perfect, bridge tables would be in the "wrong place" for example, but it would give us a head start on getting it arranged in a viewable manner. 

Also open to ideas. Just trying to prevent the layout view above from being so tedious to fix.

**Comment by rem-bou** [comment]
I am using _Auto Arrange_ feature (available on right click on the canveas.)
It works well for star schema models from what I saw. I am not sure if that would help you?

**Comment by edhans** [comment]
Thanks. Somehow never saw that, and it does a pretty good job of betting me started.
