### ISSUE TITLE
Semantic error reported when there is none

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#792]
I've seen this before, but this seems to be happening more often in 3.4. Impossible to repro. Just clicking away from this expression and back into it will clear the false error. I do know it has nothing to do with having recently edited these measures, like putting one in an error state when editing then fixing it and TE hasn't read the fix in yet in dependent measures.

I've even seen this report errors on _imported columns_ where there is no DAX - SELECTEDVALUE('Date'[Month Name]) for example can report there is a problem with that column.

![image](https://user-images.githubusercontent.com/45298358/211631907-8e40c608-37db-4729-9d0a-649d2bbdf6bb.png)

Not a show stopper, just a nuisance.

**Comment by mlonsk** [comment]
Hi @edhans 
Could it be that this error happens when the object is newly created?
We have seen some instances where newly added objects get a red line bellow, but the object is fine and is even included in auto-complete.

**Comment by edhans** [comment]
No, this happens more often when I am just opening the model and I click on a measure. That measure has been in the model since the dawn of time though. I can repro this, particularly on this measure, when I want. It also shows up as an error in the Messages window, but the object name is missing. The message is an Error that says _"This expression references measure [Daily Waterfall Forecast] which has an error."_

It has no error.

**Comment by edhans** [comment]
If the BIM file would help I could send that to support. Perhaps there is some unusual cruft in there. But once I go to the measure with the "error" and then navigate back to this measure, the error goes away.

**Comment by mlonsk** [comment]
Hi @edhans 
It would be great if you could send the BIM file to support@tabulareditor.com
Thank you.
