### ISSUE TITLE
Save model.bim backup doesn't work in TE3

### ISSUE THREAD

**Issue by Klimkiv** [TabularEditor/TabularEditor3#796]
![image](https://user-images.githubusercontent.com/57611080/212467228-09718525-b42e-4db0-a073-76084d055f87.png)

this feature did work in TE2 but doesn't work in TE3, the folder is empty

**Comment by mlonsk** [comment]
Hi @Klimkiv 
I am having trouble reproducing this.
When I put in the exact folder string as yours I get this:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/11939114/212694265-f2354339-ab91-4c29-a7c3-f40eadfa39bd.png">

Which version of TE3 are you using?

**Comment by Klimkiv** [comment]
TE 3.4.0 doesn't work but TE 2 works as usual, this is from TE 2
![image](https://user-images.githubusercontent.com/57611080/212780833-ee4d7b49-1ab1-4abf-9649-fbc3fa7b938d.png)

**Comment by edhans** [comment]
How is this supposed to work? The [way I am reading this](https://docs.tabulareditor.com/te2/Advanced-features.html#metadata-backup) is if the model is in the service and I am connected to it, after every saved to the model, a backup should be created. 

Yet I have this setting on in 3.4, a valid folder path, but no backups are being created.

**Comment by mlonsk** [comment]
Hi @Klimkiv and @edhans 
I have been able to reproduce this now. 
It seems that there is an issue where saving the model in TE3 does not create the backup, but a deployment through the deployment wizard does. 
This currently works differently in TE2 where every save creates a backup file. 
Thank you for reporting and we will look into fixing it so it works the same in both.

**Comment by edhans** [comment]
Just curious on a timeline here. This would be IMHO an invaluable safety net that would prevent me from manually making copies of BIM files as I work when I want to track iterations.

**Comment by otykier** [comment]
We’ve included it in our current sprint, so it will be fixed in our next update (expected mid-July)

**Comment by DBojsen** [comment]
Hi @Klimkiv & @edhans 

This is now fixed in [3.9.0](https://docs.tabulareditor.com/te3/other/release-notes/3_9_0.html?tabs=downloads).
Thanks for reporting.

BR David - TE3 Support
