### ISSUE TITLE
Batch Rename Folders

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#797]
Hi,

It looks like we  can not batch rename folders. 
When selecting several folders and using command "Batch Rename" or F2, TE3 renames objects within folders (children) instead of folder themselves:
![image](https://user-images.githubusercontent.com/102403055/212587316-1717c585-0fa1-4519-af73-b78353cfb12e.png)

**Comment by mlonsk** [comment]
Hi @rem-bou 
Thank you for reporting, we will look into it.

**Comment by otykier** [comment]
Fixed in [3.11.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.11.0). Thanks for reporting!
