### ISSUE TITLE
After switching to Classic Workspace, cannot use some views

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#8]
Hi,
After selecting the Classic Workspace, the View > Data Refresh, View > Macros and View > Vertipaq Analyzer don't show their respective windows. After switching back to Default Workspace, the Data Refersh and Macros remain unavailable.

Going back to Default WS and restarting TE3 seems to solve the issue

TE3 3.0.7817.31872

**Comment by otykier** [comment]
That’s a known bug. To work around: 

1. Close Tabular Editor.
2. Delete your `%localappdata%\TabularEditor3\Layout.gz` file
3. Restart Tabular Editor

**Comment by otykier** [comment]
Fixed in [3.0.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.1). Thanks for reporting!
