### ISSUE TITLE
Refresh (Calculate) Calculation Group table option no longer available

### ISSUE THREAD

**Issue by ay5h** [TabularEditor/TabularEditor3#801]
I'm pretty sure there used to be an option to refresh (re-calculate) tables of type Calculation Group or Field Parameter from within TE3. Currently if I edit a Calc Group e.g. to add an item I cannot re-calculate it in TE3 and have to switch to another tool to achieve this. 
Has the option been removed?

See attached image of the right-click menu.

![te3](https://user-images.githubusercontent.com/29549509/214564666-5d2b84c7-64da-4f49-9e61-9e83bddfb102.png)

**Comment by mlonsk** [comment]
Hi @ay5h 
Yes this is a bug. Thank you for reporting. 
As a workaround, open a preview of the table. With the preview focused, you should see a “calculate” button on the toolbar. Alternatively, perform a calculate refresh of the entire model through the “Model” menu.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11939114/214826702-163c4f9d-1a76-487a-8a85-a6b226039a56.png)

**Comment by ay5h** [comment]
Thanks, the calculate via Preview is doing the job as a workaround for me at the moment.

**Comment by edhans** [comment]
I noticed this too, but thought I must be mis-remembering. I am currently using the Refresh menu from the Model, then Calculate. Nice to know about Preview doing it too.
