### ISSUE TITLE
Can not deploy model to Power BI Premium with OLS members added

### ISSUE THREAD

**Issue by TedCStack** [TabularEditor/TabularEditor3#804]
I am trying to deploy model with added OLS and I am getting an error message about Invalid role memberships in roles. I have attached a screenshot of the error. 
 
![RoleMembers](https://user-images.githubusercontent.com/98836307/214939417-8149fd57-bec9-4214-95b5-102c991ca62e.JPG)

**Comment by otykier** [comment]
Are you seeing this error message even when leaving role members out of the deployment?

<img width="566" alt="image" src="https://user-images.githubusercontent.com/8976200/217504088-940a6c43-54a3-43bc-a86a-3543e0b99eec.png">

**Comment by DBojsen** [comment]
Hi @TedCStack 

Since we have not received a reply, I'll go ahead and close this issue.
Please reach out, if you still have issue.

BR David - TE3 support
