### ISSUE TITLE
Window Function false positive error

### ISSUE THREAD

**Issue by nayjay91** [TabularEditor/TabularEditor3#807]
Using TE3 build 3.4.8392.26581. Writing a measure with a window function and getting an error

`The WINDOW function expects a table expression for argument '5'`

However, in the documentation it is clear this is an optional argument and the measure runs find without it specified.

**Comment by otykier** [comment]
Could you share the full DAX code you use for the WINDOW function?

**Comment by nayjay91** [comment]
VAR age = SELECTEDVALUE( 'Age_of_Forecast'[Age_of_Forecast] )
RETURN 
 CALCULATE(
     SUMX(
         WINDOW(
             0,
             abs,
             age,
             abs,
             ,
             ORDERBY(
                 'bq_r_all_forecasts_history_pivot'[Age_of_Forecast]
             ),
             KEEP,
             PARTITIONBY(
                 'bq_r_all_forecasts_history_pivot'[InventoryItemID],
                 'bq_r_all_forecasts_history_pivot'[CompanyDescription],
                 'bq_r_all_forecasts_history_pivot'[Forecast_Type],
                 'bq_r_all_forecasts_history_pivot'[Training_Month_End]
             )
         ),
         CALCULATE(
             SUM( 'bq_r_all_forecasts_history_pivot'[ForecastValue] )
             - SUM( 'bq_r_all_forecasts_history_pivot'[qty_sold_cleaned] )
         )
     ), ALL( 'Age_of_Forecast'[Age_of_Forecast] )
 )

**Comment by otykier** [comment]
Thanks, we're looking into it!

**Comment by otykier** [comment]
This is now fixed in [3.4.1](https://docs.tabulareditor.com/te3/other/release-notes/3_4_1.html?tabs=downloads). Thanks for reporting!
