### ISSUE TITLE
Somethign wrong with the 3.4.1 installer. Says 3.4.0 is newer

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#809]
Just downloaded and tried to install 3.4.1. It won't. Note that I had 3.4.0 closed when installing. I launched it after this error came up to get it all in one screenshot.

![image](https://user-images.githubusercontent.com/45298358/216640132-10cdd1b0-762b-46a0-8187-455a49bda3c3.png)

**Comment by otykier** [comment]
Thanks for letting us know. You should be able to workaround this by uninstalling 3.4.0 before launching 3.4.1.

**Comment by otykier** [comment]
This issue should be fixed now, but please let us know if you encounter it again (assuming you have more TE3 installations that need to be upgraded)

**Comment by edhans** [comment]
It is fixed. Thanks!
