### ISSUE TITLE
Second Monitor Error Dialog Boxes

### ISSUE THREAD

**Issue by blynchdata** [TabularEditor/TabularEditor3#81]
On a second monitor, all error / warning diaglog boxes are too small to read the full output. Sometimes the box can be closed, the full window moved to main smaller monitor, then the error can pop up again fully readable.

Sometimes, like when I push DAX formatter on the second monitor, the dialog box is unclose-able and the entire program must be ended via TaskMgr, losing all unsaved work. 

Thank you.
Brad

**Comment by otykier** [comment]
Hi @blynchdata. Do you still have this issue with newer versions of TE3?

**Comment by blynchdata** [comment]
> Hi @blynchdata. Do you still have this issue with newer versions of TE3?

Yes. I just checked on 3.1.2. I clicked Update Schema knowing there were no changes and the dialog box is unreadable. Thank you!

**Comment by otykier** [comment]
Could you post a screenshot? Also, other users have reported that logging out of your Windows session and back in should solve any scaling issues. Could you try that, please? Thanks!

**Comment by blynchdata** [comment]
Hi Daniel,
Here is a screenshot. In this particular one, I can click OK (which I usually don't see a button like that in the small box) and I can also close it which is nice.

![Tabular editor dialog box 2nd monitor](https://user-images.githubusercontent.com/2792035/135485622-5a77e381-2099-4626-b808-fb9eef48b954.png)

I do log out and reboot on a daily basis and this has been consistent. Maybe there is something set on my system. If it helps, I'm using an extremely large 2nd monitor, a 50-inch Roku TV with an HDMI cable.

**Comment by blynchdata** [comment]
Here is another one. This is when I open from a file and the dialog box is asking if I want to use a Workspace:
![image](https://user-images.githubusercontent.com/2792035/135884392-7707e846-c36e-4f2f-9991-5d8ff1844dc6.png)

**Comment by otykier** [comment]
Thanks. Could you post a screenshot of what the "new model" dialog looks like on the same monitor? (**FIle > New > Model...**)

**Comment by blynchdata** [comment]
![image](https://user-images.githubusercontent.com/2792035/136255889-78abff8b-ce52-4b32-93bc-82e59c336796.png)

**Comment by mlonsk** [comment]
This issue should be fixed in newer version of Tabular Editor 3.
Do let us know if it reoccurs. 
Thank you
