### ISSUE TITLE
Circular Dependency Error in 3.4.1

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#811]
In 3.4.1 there is a known issue of a circular dependency error being shown by Intellisense in certain cases.
This is a bug as there are in effect no circular dependencies. 

<img width="264" alt="Screenshot_20230209_083258" src="https://user-images.githubusercontent.com/11939114/217747845-1592f1ae-a490-433e-b730-4c4ece212859.png">

We are actively working on a fix for it

**Comment by otykier** [comment]
Fixed in [3.4.2](https://docs.tabulareditor.com/te3/other/release-notes/3_4_2.html?tabs=downloads).
