### ISSUE TITLE
Calculated Table and Calculation Group Partition

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#818]
Hi,

While reviewing the BPA - I found that at last 2 type of tables have partitions which are not exposed in TE.
These tables are Calculated Table and Calculation Group Table.

This seem inconsistent with the regular tables which have partition(s) and are exposed to users.

Example Import Table from SQL:
![image](https://user-images.githubusercontent.com/102403055/218364838-58fe99d1-60c5-4b0e-93dc-cc9c0c00fb0d.png)
![image](https://user-images.githubusercontent.com/102403055/218365009-d04995dd-e027-452a-986e-82746a283f92.png)
![image](https://user-images.githubusercontent.com/102403055/218365335-505a4433-c76e-4077-8b03-ba0427320b95.png)

Example Calculation Group table
![image](https://user-images.githubusercontent.com/102403055/218364944-a1a7cef5-b97a-4fda-8c3a-00e502237374.png)
![image](https://user-images.githubusercontent.com/102403055/218365041-43a8c3e8-7bf0-4cee-bec8-0925db4e5b08.png)
![image](https://user-images.githubusercontent.com/102403055/218365202-c1ad7dd2-085b-4a6b-9456-e744c7734861.png)

Example Calculated Table (Field parrameter in this case):
![image](https://user-images.githubusercontent.com/102403055/218365123-a7658e9c-2670-447f-9d22-3ad216675445.png)
![image](https://user-images.githubusercontent.com/102403055/218365097-832df833-6f87-4004-b26b-1bc5a8d265f5.png)
![image](https://user-images.githubusercontent.com/102403055/218365177-429dccc9-0c43-4c07-954a-59d12072e5ac.png)

It's not too much of a big deal but it does bring the issue of reviewing BPA which tells that partition names should match table names.
If this is intended and won't be change I'll submit a pull request to update BPA rules

**Comment by mlonsk** [comment]
Hi @rem-bou 
It is intentional that Tabular Editor hides those partitions, as the settings there can/should not be changed. 
You can still access them, however, using the following small script>
`Selected.Table.Partitions[0].Output();`

**Comment by rem-bou** [comment]
Thanks @mlonsk. 
It would make sense (to me) to expose them but grey them out in a similar fashion as other properties.
