### ISSUE TITLE
Call to a different CustomAction is not working

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#819]
Hello, 

I tried running this script in a new model 
https://github.com/bernatagulloesbrina/TabularEditor-Scripts/blob/main/Advanced/One-Click%20Macros/Referential%20Integrity%20Check%20Measures.csx

but I'm getting the error message that there is no custom action with the name "Dynamic Measure" and there is one indeed. Is the Macro I create by storing this script 
https://github.com/bernatagulloesbrina/TabularEditor-Scripts/blob/main/Advanced/One-Click%20Macros/Dynamic%20Measure%20Calculation%20Group%20Script.csx

Has there been any change regarding the calls to different custom actions from a c# script? 

Regards,

**Comment by bernatagulloesbrina** [comment]
Oh wait
something wrong on my end 

apologies

**Comment by mlonsk** [comment]
No worries, closing the issue then.
