### ISSUE TITLE
Process refresh progress pane items don't show detail drill-down option?

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#823]
This happens sometimes-not-always. I often like checking the M code execution status (# rows loaded etc). But sometimes the option to drill into the object being processed doesn't show (missing drill down triangle icon):

![image](https://user-images.githubusercontent.com/31414209/219691554-ca7e1bb6-2d90-41e2-a7ea-0bd222263883.png)

**Comment by DBojsen** [comment]
Hi @seedjay1 

Since we have not recieved a reply, I'll go ahead and close this issue.
Please reach out again, if you have other issues.

BR David - TE3 Support
