### ISSUE TITLE
TE3: Invoke multiple CustomActions not working

### ISSUE THREAD

**Issue by PBIQueryous** [TabularEditor/TabularEditor3#824]
I have previously been able to create multiple measures by using multiple CustomAction macros within a single script. However, for some reason it is now producing an error, so there are "no macros with the name...", when they most definitely do exist.

I've tried creating new measures also, but with no joy. Could an update have broken this? I appreciate any help or guidance. Thank you.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/95970959/219974792-36debf9b-83c9-4282-a0c2-33e75d8a193b.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/95970959/219974820-9201a23a-71d1-4593-9539-1b7319a68615.png">

**Comment by mlonsk** [comment]
Hi @PBIQueryous 
This is a bug, it ought to work the way you are doing it. 
Thank you for reporting it 😊

**Comment by rem-bou** [comment]
Hi Morton,

We have the issue when developing scripts to be called - Would you be able to share a timeframe of when we can expect a fix to be deployed?

**Comment by mlonsk** [comment]
Hi @rem-bou 
We are actively working on it, and plan to have it fixed in our March release.
We are aiming at mid-March currently.

**Comment by otykier** [comment]
Hi @rem-bou 
This issue has now been fixed in [v. 3.5.0](https://docs.tabulareditor.com/te3/other/release-notes/3_5_0.html?tabs=downloads).
