### ISSUE TITLE
C# Script: Delete Relationship

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#826]
I seem to be unable to delete relationship using C# in a model created directly as .bim file from TE3 and no database is attached to it.
Issue occurs when no database is connected to model - It works when a database is connected.

![image](https://user-images.githubusercontent.com/102403055/220238319-68636cc4-f83a-41ba-8718-cff314ed02c9.png)

When using `r.CanDelete()` to check if relationships are deletable it does return `True`.

I have no issues running the script when TE is connected to a PBI desktop model.

**Comment by otykier** [comment]
In C#, it's not possible to add/remove elements to a collection that you are iterating. So make a copy of the collection (using `IEnumerable.ToList()` before iterating it:

```csharp
foreach (var r in Model.Relationships.ToList())
{
    r.Delete();
}
```

**Comment by otykier** [comment]
The reason the script runs without failure, while connected to a PBI Desktop model, is that the `r.Delete()` operation does nothing, unless you enable **Unsupported modeling operations** under **Tools > Preferences** (modifying relationships is not among the [supported modeling operations for Power BI Desktop external tools](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations)).

**Comment by rem-bou** [comment]
Thank you Daniel for the quick reply and to provide the proper code.
Indeed, I have the **Unsupported modeling operations** turned on which unable the script to run and to delete the relationships.
