### ISSUE TITLE
Ctrl + K: unomment on C# script not working

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#827]
Hi team,

When using `CTRL + K` shortkey on TE3 to uncomment a row or a block (which is commented), it adds `//` instead of removing them.

**Comment by mlonsk** [comment]
Hi @rem-bou 
This is a bug that well be fixed in the next realease. The correct shortcut for uncommenting is actually `Ctrl+U`, but the binding is wrong in TE3 3.4.2

**Comment by otykier** [comment]
This is now fixed in [3.5.0](https://docs.tabulareditor.com/te3/other/release-notes/3_5_0.html?tabs=downloads). `Ctrl+K` comments. `Ctrl+U` uncomments. You can also use `Ctrl+/` to toggle the line comment. All shortcuts can be remapped under **Tools > Preferences > Keyboard**.
