### ISSUE TITLE
Help with C# scripting - How to create a relationship using a script

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#83]
Hi everyone. I am looking for the code that will allow me to do the following:
1) Check to see if there is already a relationship between "table1[Key]" and "table2[Key]"
2) Delete the relationship from # 1
3) If there is no relationship then create the relationship (either Single or Both directions)

Is this something that is supported against a Power BI Desktop model?

**Comment by m-kovalsky** [comment]
This is not a supported write operation against a Power BI Desktop model (see this link https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations). That being said, below is the code.

```C#
var fromColumn = Model.Tables["FactSales"].Columns["DateKey"]; // Enter the 'from' part of the relationship
var toColumn = Model.Tables["DimDate"].Columns["Datekey"]; // Enter the 'to' part of the relationship

// If the relationship above exists, delete it
if (Model.Relationships.Any(a => a.FromColumn == fromColumn && a.ToColumn == toColumn))
{
    Model.Relationships.First(a => a.FromColumn == fromColumn && a.ToColumn == toColumn).Delete();
}
// Else, create the relationship
else
{
    var r = Model.AddRelationship();
    r.FromColumn = fromColumn;
    r.ToColumn = toColumn;
    r.FromCardinality = RelationshipEndCardinality.Many;
    r.ToCardinality = RelationshipEndCardinality.One;
    r.CrossFilteringBehavior = CrossFilteringBehavior.OneDirection; //CrossFilteringBehavior.BothDirections
}
```

**Comment by otykier** [comment]
@dpesante did you get the answer you needed? Can we close the issue?

**Comment by dpesante** [comment]
Really appreciate the info. We will be looking into Azure AS and test it out there. Thanks!!!

**Comment by jasonlaw997** [comment]
CrossFilteringBehavior.BothDirections failure!  The relationship always will be OneDirection. How should the code be written?

**Comment by otykier** [comment]
@jasonlaw997 you need to use the commented line of code, that sets the CrossFilteriBehavior property to “BothDirections”

```csharp
var fromColumn = Model.Tables["FactSales"].Columns["DateKey"]; // Enter the 'from' part of the relationship
var toColumn = Model.Tables["DimDate"].Columns["Datekey"]; // Enter the 'to' part of the relationship

// If the relationship above exists, delete it
if (Model.Relationships.Any(a => a.FromColumn == fromColumn && a.ToColumn == toColumn))
{
    Model.Relationships.First(a => a.FromColumn == fromColumn && a.ToColumn == toColumn).Delete();
}
// Else, create the relationship
else
{
    var r = Model.AddRelationship();
    r.FromColumn = fromColumn;
    r.ToColumn = toColumn;
    r.FromCardinality = RelationshipEndCardinality.Many;
    r.ToCardinality = RelationshipEndCardinality.One;
    r.CrossFilteringBehavior = CrossFilteringBehavior.BothDirections;
}
```

**Comment by lina-sheremet** [comment]
is there a way to set active vs inactive?

**Comment by otykier** [comment]
Yes, in the example above that would be a matter of setting `r.IsActive = false;` to deactivate the relationship (it will be active by default).
