### ISSUE TITLE
Show/View in Perspective Editor isn't opening

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#832]
I'm clicking on the 'Show in perspective editor' option but nothing is happening. No error message, no detail in the log files. Is this supposed to bring up a new window of some kind?

![image](https://user-images.githubusercontent.com/62320770/221676109-0b4e03d8-2110-4d36-bdff-8f6a314665da.png)

I also have the same issue when clicking on 'View > Perspective Editor'

![image](https://user-images.githubusercontent.com/62320770/221677056-85114dc3-54dd-46f3-a56c-f156c6e01d71.png)

**Comment by mlonsk** [comment]
Hi @samaguire 
You most likely need to reset your windows layout. Go to Window -> Default Layout and the perspective editor should start showing up.

**Comment by samaguire** [comment]
@mlonsk that worked 👍
