### ISSUE TITLE
Maximum of 10.000 rows on all tables

### ISSUE THREAD

**Issue by Stewwe1** [TabularEditor/TabularEditor3#837]
Hello TE3 community,

I think I just found a bug: We have just added a single table in hybrid mode all other tables are in import mode.

Now we can only have a maximum of 10,000 rows on all tables as this setting says:
![image](https://user-images.githubusercontent.com/49725984/222484177-de1c0b7f-c180-4fd1-b741-f2ad3b7d56af.png)

Thank you for your help!
Stewwe

**Comment by mlonsk** [comment]
Hi @Stewwe1 
Yes I think you are right, and I believe it is related to issue #500 
Thank you for reporting, we will look into fixing it.

**Comment by otykier** [comment]
Closing this (related to #500)
