### ISSUE TITLE
Composite Model: Connection error

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#838]
Hello,

There is a interesting error happening when trying to connect to a PBI desktop composite model from tabular editor:
![image](https://user-images.githubusercontent.com/102403055/222573002-5b90f11c-c1e7-47ce-976e-c3c58a13264a.png)

This error only occurs (from my limited testing) the first time you try to connect to the PBI file from tabular editor via _Open Model from DB_ and selecting the Local Instance.
Interestingly, if you are opening TE from the _External Tools_ , then no issues. TE can be closed and reopened and it connects to the PBI with no issue by selecting the Local Instance.

**Comment by mlonsk** [comment]
Hi @rem-bou 
I am unable to reproduce this. Could you try to see if this is still an issue in 3.5.0?
Thank you

**Comment by rem-bou** [comment]
Hi @mlonsk,

I can confirm I still have the same issue with TE 3.5 and PBI march 2023 update.
However, I am not sure how to provide reproductible example.

**Comment by DBojsen** [comment]
Hi @rem-bou 

Could you provide a short video/gif (using something like https://www.screentogif.com/) of the issue.
We still cannot reproduce on our end.

BR David - TE3 Support

**Comment by rem-bou** [comment]
Hi David,

Please see below.
I though my PBI file was corrupted at first, so I started from a blank file (same model tho) and it worked ok until I closed and repoen PBI file and TE to test it once all model and report set up on the new file. Same error occured.

![Gif Composite Model Issue](https://user-images.githubusercontent.com/102403055/228405943-9e7ed822-a09d-4c06-ac88-1102d09da6ac.gif)

**Comment by DBojsen** [comment]
Hi @rem-bou 

I have just opened and closed 30 times locally with a composite model in Power BI Desktop, and I have not been able to reproduce.
Would it be possible for you to try on a different machine with the same model?

BR David - TE3 Support

**Comment by rem-bou** [comment]
Hi @DBojsen,

My problem seems resolved with TE 3.5.1.
Closing this issue.
