### ISSUE TITLE
Copy / Paste with a folder structure does now work.

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor3#84]
Hi,

When copying and pasting a folder or set of nested folders and objects the copy paste function does not work. You have to hide folder and copy the individual objects  and then paste. 

It would be nice to have the TE2 mode back as picking out columns/measures in the midst of a lot of columns/measures is quite time consuming.

Thanks

Toby.

**Comment by otykier** [comment]
Fixed in [3.0.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.6). Thanks for reporting!
