### ISSUE TITLE
Comment/Uncomment code

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#840]
In version 3.4.2, there is a bug where the tooltip for the 'commenting code' and 'uncommenting code' are both Ctrl-K. Also, I have code which has been commented out and when I highlight it to uncomment it using the button, the button is greyed out and I cannot uncomment the code (besides manually removing the // from each line). The shortcut also doesn't seem to work (actually I'm not sure what it is).

**Comment by mlonsk** [comment]
Hi @m-kovalsky 
Yes, indeed. We will fix it in our March Update. The shortcut is currently not working, but will in the future be Ctrl+U
Thank you for taking the time to report it.

**Comment by mlonsk** [comment]
Hi @m-kovalsky 
This bug has been solved in 3.5.0
