### ISSUE TITLE
Diagram view: Calculation Group Table issue

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#845]
Hi Team,

We are unable to bring a calculation group table on the diagram view (not available when drag and drop or when using right click on the calculation group). While it isn't too much an issue as relationships can't be created, it stops to have a complete diagram view of a model.
Other issue, is selecting all tables at once, the drag and drop is not available, but the right click and "Add to diagram is".

**Comment by mlonsk** [comment]
Hi @rem-bou 
This is indeed a bug that we will have fixed in our March release of TE3. A bit more patience and it should be solved :)

**Comment by rem-bou** [comment]
No worries, Thank you.
I really like TE, so I am happy to provide feedback or report bug when I see one (which isn't that many really :) )

**Comment by mlonsk** [comment]
Hi @rem-bou 
This issue has been resolved in 3.5.0
