### ISSUE TITLE
Using .BIM file overwrites partitions in Incremental Refresh

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#847]
I am not sure if this is a bug or not. 

I export a BIM file of the model I want to use then connect it back to the same model in the service. This way I have a local copy of the model and SharePoint keeps versions of it. (I would use the backup feature, but that doesn't work for me #796 )

If the model has Incremental Refresh though, this doesn't work great. If the refresh of the model in the service causes an old partition to be removed and a new partition created for the current month for example, when I open the BIM file and TE/3 connects to the model, it recreates the old partition, empty of course, and deletes the new partition that the service created.

I won't go so far as to say that is a bug, but it does seem to be a counter intuitive design issue. Any way around this? My current workaround is after a refresh, I just export the BIM again, then reconnect it. Not horrible for monthly partitions, but horrible for daily partitions.

**Comment by mlonsk** [comment]
Hi @edhans 
It is certainly an undesired effect of the current implementation around incremental refresh. But hold tight, we have a fix on the doorsteps which I hope will solve your issue.

**Comment by mlonsk** [comment]
Hi @edhans 

This issue has been solved in 3.5.0
Thank you for reporting
