### ISSUE TITLE
help Window pops up over the Dax text you are trying to enter and the suggested fields/measures are obscured.

### ISSUE THREAD

**Issue by tim-pluralgroup** [TabularEditor/TabularEditor3#85]
![image](https://user-images.githubusercontent.com/59617629/122091518-e1356380-cdd6-11eb-8a5a-281a2279db3c.png)
See attached screenshot.
is it possible to position the popup so it does not cover the text you are entering and the suggested fields/measures?
You can hit escape and the window goes away but the suggested fields/measures do as well and the cursor position is lost.

**Comment by otykier** [comment]
This is a bug. Normally the popup wouldn't be so large. I suspect it is related to UI scaling. Without connecting/disconnecting any external monitors, could you try to log out of your Windows session, then log back in, launch Tabular Editor 3 and see if the issue persists? Also, does this happen to all DAX functions, or only some of them (like MIN in your screenshot)? Thanks!

**Comment by otykier** [comment]
Hi @tim-pluralgroup
Do you still have this issue with newer versions of TE3?

**Comment by mlonsk** [comment]
Closing as this looks to have been solved in newer version of TE3, please do not hesitate to reopen if this is not the case
