### ISSUE TITLE
"Model" should be treated as a reserved word

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#852]
I have a calculation group called "Model" and I realized that autocomplete does not put the table name inside simple quotes. However, this creates an dax error. If I add the single quotes manually the error disappears

**Comment by mlonsk** [comment]
Hi @bernatagulloesbrina 
As the TOM apparently allows Model as a name for a object it is unlikely that we will stop the user from using it. 
This could be a good case for a BPA rule that checks on this for you.

**Comment by bernatagulloesbrina** [comment]
It can be used, but in the same way that if you have a table called "Date"
tabular editor will write 'Date' when used in a expression, the same should
happen with "Model"

El dl., 20 de març 2023, 12:28, Morten Lønskov ***@***.***>
va escriure:

**Comment by mlonsk** [comment]
Sorry, then I misunderstood what you meant. I will report it back to our development team.

**Comment by otykier** [comment]
This is fixed in [3.5.1](https://docs.tabulareditor.com/te3/other/release-notes/3_5_1.html?tabs=downloads).
