### ISSUE TITLE
Metadata-Translations not duplicated

### ISSUE THREAD

**Issue by alexrobe** [TabularEditor/TabularEditor3#854]
CTRL+C works fine, but if I don't want to lose the contents of my clipboard i use "duplicate" and would expect the same behaviour. But translations are not transferred to the new object when using "duplicate".

![image](https://user-images.githubusercontent.com/46502923/226392802-8639e1f2-a85d-4d81-aa99-d6f0af90d3d6.png)

You can see in the screenshot, that the duplicated object does not have the blue colour indicating existing translations.

Apologies, if I missed the documentation that this was on purposse. Otherwise thanks for the fix.
BR, Alex

**Comment by otykier** [comment]
That is indeed a bug. Thanks for reporting!

**Comment by mlonsk** [comment]
The duplicate function looks to be working correctly in 3.15.0 so closing this issue.
Do feel free to reopen if this is not the case on your end.
