### ISSUE TITLE
Query output doesn't honor field types for numerical formatting

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#859]
Not sure if this is a bug or feature request.

Here is my query:
<pre>DEFINE
    TABLE varHeader =
        FILTER(
            DATATABLE(
                "Snapshot Date", STRING,
                "Record Count", CURRENCY,
                {
                    { BLANK(), BLANK() }
                }
            ),
            FALSE()
        )
    TABLE varDailyRecords =
        SUMMARIZECOLUMNS(
            'Sales History'[Snapshot Date],
            "@RecordCount", COUNTROWS( 'Sales History' )
        )

EVALUATE
UNION(
    varHeader,
    varDailyRecords
)</PRE>

The query output looks like this:
![image](https://user-images.githubusercontent.com/45298358/227314072-fc72f63f-c2fb-4645-b8bb-374883af2f40.png)

It should look like this (from DAX Studio 3.0.6)
![image](https://user-images.githubusercontent.com/45298358/227314439-6193dbec-8b16-4fb3-bc2f-1b3966f1087c.png)

I am less concerned about the column headers and date format. I did this so I could have some commas in there to read those larger numbers without putting a pencil on my screen.

**Comment by DBojsen** [comment]
Hi @edhans 

This must be new in DAX Studio 3.0.6 - when testing in 3.0.5, I get the exact same result as in TE3 3.5.0.
We currently do not have any plans to apply default formatting to query output - only thru the use of configured format strings.

Regards 

David - Tabular Editor Support
