### ISSUE TITLE
Can't clear "Sort by column"

### ISSUE THREAD

**Issue by MrPets** [TabularEditor/TabularEditor3#861]
Hello, Tabular Editor Team.

I assigned "Sort by column" to a column, but now wish to clear the field. This does not seem possible and gives error message "Object reference not set to an instant of an object". Furthermore, i cannot find the column itself in the list of available columns to sort by. Am I missing something or is this a bug?

![image](https://user-images.githubusercontent.com/80754714/228253688-954c1a6b-e302-469b-bf36-387487cfb544.png)

**Comment by DBojsen** [comment]
Hi @MrPets 

I'm having a ard time reproducing in 3.5.0 - are you also on latest version?
If not - could you upgrade and see if the issue is still there?
If you have already upgraded, could you provide som repro steps or a video/gif?

BR David - TE3 support

**Comment by DBojsen** [comment]
We haven't heard back from you regarding this inquiry, and we will respectfully close this issue.
Please do not hesitate to let us know if we can be of further assistance. 
Thank you

**Comment by MrPets** [comment]
My apologies for not returning, @DBojsen  - a version update solved the problem.
