### ISSUE TITLE
Unable to connect to SSAS Tabular (or Model.bim file)

### ISSUE THREAD

**Issue by bsteinweg** [TabularEditor/TabularEditor3#866]
**Describe the issue**
When I try to connect to a Tabular Model from an existing DB (EDWSSASPROD\ssas_tabular), using AD authentication, I get the error: "**Invalid Argument**".   Very similar to Tabular Editor 2.x (except that 2.x gives a weird JIT error, or crashes)...

** Which version are you currently using? **
Tabular Editor 3 edition: Trial

**To Reproduce**
Trying to connect to SSAS  (File, Open, Model from DB...)

**Expected behavior**
Connect and view/edit/download Model.bim

** NOTE **
I have also tried connecting to a working Model.bim file directly, after changing the Compatibility Level from 1100 to 1400, but then I get the error:  "Unexpected character encountered while parsing value: <. Path '', line 0, position 0"  (see attached image).  Tabular Editor 2.x returns a very similar error.    Now what??
![LoadingModelError](https://user-images.githubusercontent.com/32370093/228983062-6abd28b6-9c28-49c8-a337-91117aa2adb6.png)

**Comment by otykier** [comment]
Tabular Editor doesn't support models at compatibility level 1100. You'll have to convert them to 1200+ using Visual Studio first. Changing the Compatibility Level directly within the .bim file is not enough. Is the model you're trying to connect to on SSAS also using CL 1100? In that case, it needs to be upgraded to 1200+ as well.
