### ISSUE TITLE
Tabular Editor not updating Power BI shared expressions

### ISSUE THREAD

**Issue by nate-86** [TabularEditor/TabularEditor3#869]
I am trying to update modified shared expressions into my pbix and it doesn't work.
Here's the steps I have taken:

1. Exported a pbit file from Power BI Desktop
2. Modified the pbit file in Tabular Editor 3
3. Saved the model properly (CTRL + S)
4. Opened the saved pbit with Power BI Desktop
5. Modifications not updated in Power Query

My OS is Windows 11 and I am working on excel files hosted on Sharepoint folders.

I tried also TE2 but the result is the same.
I thought that problem is due to the fact that Power BI doesn't allow this type of modification. Is it so?
Or maybe I have a wrong setting in Power BI Desktop.

All this doesn't happen with new measures.
I mean that I am able to use Tabular Editor successfully with measures and update my pbix file.

Thanks in advance for your help.

**Comment by otykier** [comment]
Power BI Desktop doesn't support modifications to shared expressions through external tools. [Here](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations) is a list of currently supported modeling operations.
