### ISSUE TITLE
Creating a table or renaming just created table often crushes TE3

### ISSUE THREAD

**Issue by bogomda** [TabularEditor/TabularEditor3#87]
Creating a table or renaming just created table in the model hosted on Power BI Premium often (let's say 5 out of 10 times) crushes TE3.

![image](https://user-images.githubusercontent.com/66798479/122276265-9e48be00-ceb2-11eb-993a-a1c18eb214c8.png)

![image](https://user-images.githubusercontent.com/66798479/122276277-a1dc4500-ceb2-11eb-8aa4-6cc310641b8b.png)

**Comment by otykier** [comment]
Could you provide some more details, please:

- Does the crash happen immediately when adding the table or some time after that?
- Do you get any error messages? If not, maybe you can locate an error message or a stack trace in the Windows Event Log?

Thank you!

**Comment by bogomda** [comment]
Does the crash happen immediately when adding the table or some time after that? - it crashes either immediately or 1-3 sec (it freezes first and then crushes) after table got created,
Do you get any error messages? - no error message shown

If not, maybe you can locate an error message or a stack trace in the Windows Event Log? - i don't know how to do that but will be happy to follow instructions if available

**Comment by otykier** [comment]
> If not, maybe you can locate an error message or a stack trace in the Windows Event Log? - i don't know how to do that but will be happy to follow instructions if available

After TE3 crashes, open the "Event Viewer" application in Windows (or hit [⊞ Win]+[R] and type `eventvwr`).

Then, under "Windows Logs" > "Application", look for events with source "Windows Error Reporting", "Application Error" or ".NET Runtime", and see if any of these contains text that references "TabularEditor" in one way or another, in the "General" tab (see screenshot below). If you find any of these events, please send me the full text for all of them.

The events are sorted by time (most recent events at the top), so if you just experienced a crash, you should be able to find the events relatively easy.

Thank you!

![image](https://user-images.githubusercontent.com/8976200/122342630-27a8d080-cf45-11eb-8d4f-2a4135ae10a4.png)

**Comment by otykier** [comment]
This may be related to #95 (in which the application crashes without any error message). A fix for that is already in the works. If you could save the model as a Model.bim file, and send that file to me with a description of the steps that would cause the crash, I would be happy to debug it further!

**Comment by otykier** [comment]
@bogomda I just released an updated version [3.0.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.7). When you get a chance, could you let me know if this version also crashes in the same way? Thanks!

**Comment by otykier** [comment]
Reply by mail. Feel free to reopen this issue or create a new one if the problem persists.
