### ISSUE TITLE
[Issue] Pivot grid gives error on Measure that is working fine in PowerBI

### ISSUE THREAD

**Issue by luukhendrikscordstrap** [TabularEditor/TabularEditor3#871]
**Describe the issue**
I've got a measure that's been called upon too many times within my report and its making a visual slow. When trying to debug the code in TE3 i couldnt get it to show up. thinking my TE3 was bad i updated, i tweaked the code i tried to put the whole thing in a calculate clause. Nothing seemed to do the job. 

The only time Pivot Grid does NOT have an issue with the measure is when the Last year version of this measure is used. IT is literally referring to the original "Broken" measure and uses SamePeriodLastYear. What gives? 

** Which version are you currently using? **
Tabular Editor 3.5.1
Tabular Editor 3 edition: Business

**To Reproduce**
PowerBI

`VAR SelDate =
	SELECTEDVALUE( Calendar[Date], MAX( Calendar[Date] ) )
VAR Result =
	SUMX(
		VALUES( 'fMinimum Balance'[Item_Facility_IDKey] ),
		VAR HistoricalDate =
			CALCULATE(
				MAX( 'fMinimum Balance'[From Date] ),
				'fMinimum Balance'[From Date] <= SelDate
			)
		RETURN
			IF(
				HistoricalDate <> BLANK( ),
				CALCULATE(
					MIN( 'fMinimum Balance'[Minimum Balance] ),
					'fMinimum Balance'[From Date] = HistoricalDate
				)
			)
	)
RETURN
	CALCULATE( Result ) //* DIVIDE(Result, Result)`

**Expected behavior**
i expected values to show up, sadly they don't. A different measure with the same code shows the same. Somehow the same period last year seems to fix it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/128694820/229792886-4ab7b921-4059-4c41-b1a9-bfdbf95a6141.png)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
When scrolling through the "results" in Debug mode the final step shows it should return data. its simply not showing in pivot grid.

**Comment by luukhendrikscordstrap** [comment]
Yeah i had no problems running it somewhere else. ended up rewriting the whole thing because it was super inefficient. 

That being said this is our first week trying out TE3 and i'm just curious as to why such a thing would happen. It was legacy code, but i'm pretty sure i will find more legacy code as the days pass by.

**Comment by otykier** [comment]
@luukhendrikscordstrap is the measure hidden? There is a known issue currently in TE3, where hidden measures do not work with the Pivot Grid.

**Comment by DBojsen** [comment]
Hi @luukhendrikscordstrap 
I wanted to ping you to see if you still have this issue - if so, could you please reply if the measure you are using is a hidden one, as Daniel asks above.

BR David - TE3 Support

**Comment by luukhendrikscordstrap** [comment]
Hi Sorry for the late reply, Yes It was a hidden measure. after unhiding it the pivottable worked as expected. Now for the more difficult task of convincing my teammember not to hide any and all measures.
