### ISSUE TITLE
Index was out of range

### ISSUE THREAD

**Issue by Klimkiv** [TabularEditor/TabularEditor3#874]
TE3 crashed with an error 
... Exception message: Index was out of range. Must be non-negative and less than the size of the collection.
I do not know if it has link to my question, but what do you think about practice like that:
1. we have star schema, in FactTable we have a [Flag] column with 30 mln and a DimFlagTable with 20000 rows
2. to avoid RI errors we change in some rows of the [Flag] column blank values to = -1 and add a row with -1 (Unknown) to DimFlagTable
3. In the result we do not have RI errors, but is it good practice?

Thank you very much!

![error](https://user-images.githubusercontent.com/57611080/230710382-80080af9-c231-4797-afd7-5703b7099894.png)

**Comment by Klimkiv** [comment]
Good Day!
1. It's was the first time we bulid model 1600 and make some copy-paste from model 1500
2. TE3 3.5.1 crashed every time when we try [sort by column], [Index was out of range] I just stopped doing things like that
3. For me it's not a big deal to do such things in TE2, the value of TE3 is obvious :) Thank you!

**Comment by otykier** [comment]
Hi @Klimkiv - thanks a lot for providing these additional details. Unfortunately, we are still not able to reproduce the issue based on your description. It would be very helpful if you could share a short screen recording or GIF, that shows how to trigger the crash. Thanks a lot!

**Comment by DBojsen** [comment]
Hi @Klimkiv 

Just a friendly ping to see if you could help with a screen recording as Daniel requests above.

BR David - TE3 Support

**Comment by Klimkiv** [comment]
Good Day
Now I can't reproduce the crash! Thank you!

**Comment by DBojsen** [comment]
Hi @Klimkiv 

Thank you.  If it reappears, please reopen or create a new issue.

BR David - TE3 Support
