### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by mshparber** [TabularEditor/TabularEditor3#875]
I want to set "Group by Columns" property for my Power BI Desktop Model.
I just don't see it in the available properties.
Actually I don't see many of the properties I see in YouTube videos such as this:
https://youtu.be/RCEoAvru8rY?t=566
I've spent 2 hours searching what do I miss, and I cannot find.
Probably it has something to do with External Tools / Desktop Model Compatibility (1567)
Please help! What do I do wrong?
Thank you

**Comment by rem-bou** [comment]
Hey @mshparber 

Have you checked the box in preference "Allow unsupported modeling operations"?
It might be your issue - be mindfull that some change can result in broken file. I personally haven't encoutered any issue when using it but your milleage may vary.
![image](https://user-images.githubusercontent.com/102403055/231314159-65bb5429-46d7-4c91-873e-e8bf4e7d4dd6.png)

**Comment by otykier** [comment]
Correct - by deault TE2/TE3 hides a lot of the model properties that are [not supported by the External Tools integration](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations), but you can unlock all of them by enabling that preference.
