### ISSUE TITLE
Filtered list of datasets doesn't open the one that is clicked on

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#886]
**Describe the issue**
I filtered a list of datasets in a Power BI workspace down to 1. I double-clicked to open it and it instead opened the first dataset in the workspace (alphabetically) not the one that was showing in my filtered list.

** Which version are you currently using? **
3.6, Enterprise

**To Reproduce**
Power BI

1. Click the Open Model button
2. Enter the Power BI Workspace URL
3. Filter it down to something. Just don't filter it for the first dataset shown, make sure that is filtered out.
4. Double-click the first one in your filtered list.
5. The first one in the workspace is opened.

**Desktop (please complete the following information):**
Windows 10

**Additional context**
This could be especially problematic when connecting a BIM file or folder to a dataset. I _never_ use the filter functionality for this because if it opens the wrong one, I will have overwritten it with an entirely different model. And that dialog box the worst because that dataset list isn't alphabetical.

**Comment by DBojsen** [comment]
Hi @edhans 

I can reproduce in my end.  We'll make sure to get that fixed.

BR David - TE3 Support
