### ISSUE TITLE
TE version in advanced scripting

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#89]
Is there an easy way to find the user's Tabular Editor version via advanced scripting? It would be helpful - also to fix the script in this issue https://github.com/microsoft/Analysis-Services/issues/114

**Comment by otykier** [comment]
```csharp
using System.Windows.Forms;

Info(Application.ProductName + " version " + Application.ProductVersion);
```
In Tabular Editor 2:
![image](https://user-images.githubusercontent.com/8976200/122346971-d51de300-cf49-11eb-9ba2-ee689972fbbe.png)

In Tabular Editor 3:
![image](https://user-images.githubusercontent.com/8976200/122346997-da7b2d80-cf49-11eb-893e-b049c82b2830.png)

**Comment by m-kovalsky** [comment]
Thanks for the blazing fast response! Perfect :)
