### ISSUE TITLE
AutoComplete doesn't take a defined COLUMN into account as a CALCULATE predicate

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#890]
Tabular Editor 3.6.0

You can see below I created a column using the DEFINE statement. The CALCULATETABLE() function for autocomplete doesn't take it into account. The query runs fine so there is no issue. Autocomplete just needs to handle it properly

You can see in the FILTER function highlighted it works fine. (This query makes no sense, you'd never include that field filter in both places, just showing it is recognized by FILTER but not as a CALCULATE predicate.)

![image](https://user-images.githubusercontent.com/45298358/235030652-ed3f84bd-210b-43cc-8fad-75b96fdb9683.png)

**Comment by otykier** [comment]
Thanks for reporting and for the great repro and explanation of the issue! We’ll make sure that’s fixed.

**Comment by otykier** [comment]
This is fixed in our [latest release](https://docs.tabulareditor.com/te3/other/release-notes/3_7_1.html?tabs=downloads). Thanks again for reporting!
