### ISSUE TITLE
[Issue] Updating measures via te3daxs script deletes format strings

### ISSUE THREAD

**Issue by RafalBombolewski** [TabularEditor/TabularEditor3#891]
**Describe the issue**
I have measure definitions in te3daxs script, and these definitions include format string, like below:

    FormatString = "#,##0"

When I run the script (F5), it does update model with new measures included in the script, but at the same time it deletes all format strings from existing measures properties, so those that had "#,##0" as measure formatting, now have it empty.

I suspect this might have something to do with following improvement in 3.6.0 version, but we do not have any dynamic string formatting (so our static formatting should not be deleted by the script?) :

"When adding a dynamic format string expression to a measure, we now clear the static format string property (as it is not possible for measures to have both static and dynamic format strings assigned)."

** Which version are you currently using? **
Tabular Editor 3, version: 3.6.0
Tabular Editor 3 edition: Enterprise Edition

**Comment by otykier** [comment]
Thanks for reporting, we’ll look into it

**Comment by DBojsen** [comment]
Hi @RafalBombolewski 

I can reproduce in my end - we'll make sure to get that fixed.

BR David - TE3 Support

**Comment by otykier** [comment]
This was fixed in our [latest release](https://docs.tabulareditor.com/te3/other/release-notes/3_7_1.html?tabs=downloads).

Thanks again for reporting!
