### ISSUE TITLE
SQL BI dimDate Won't Refresh

### ISSUE THREAD

**Issue by JeridInsight** [TabularEditor/TabularEditor3#895]
I am using TE3 and I am trying to create a dimDate table (the one provided by SQLBI.com).  I have used this table many, many times by publishing the .pbix to The Service and then connecting to it from TE3, but I've never created it in TE3 by creating a new calculated table and populating it's Expression property with the DAX.  I even took the DAX expression and put it into a DAX Query (prefixed with an EVALUATE) and it works fine!  The error that I'm getting when I choose "Calculate Table" is very nebulous:

![image](https://user-images.githubusercontent.com/105085417/236261028-2adbee43-dbac-4594-8e69-c8eab74cd3fc.png)

What am I missing here?  I even scripted the table out (from a local model that it works in) and ran that script to recreate the table, but still no dice!  ¯\\_(ツ)_/¯

**Comment by JeridInsight** [comment]
@otykier  Any advice on this?

**Comment by otykier** [comment]
The error message originates from Analysis Services, which usually indicates some internal error. Try to delete and redeploy the database/dataset.
