### ISSUE TITLE
[Issue] Evaluate DAX returns Incorrect Error Message

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#897]
For SSAS on premise, if I don't run Model Recalc, the error message doesn't provide the correct info.

![image](https://user-images.githubusercontent.com/73054674/236889003-c463a393-51f8-4c8b-9ea8-9fd278080820.png)

Once the model is recalculated everything is fine.

**Comment by DBojsen** [comment]
Hi @SharmaAntriksh 

When executing DAX Queries thru a C# script, we do not parse neither the query nor the result.
The error message you are seeing is coming directly from SSAS.

So unfortunately not something we can fix.

BR David - TE3 Support
