### ISSUE TITLE
Pivot Grid always give an error when reading data

### ISSUE THREAD

**Issue by janpetterholmberg** [TabularEditor/TabularEditor3#899]
**Describe the issue**
When using the Pivot Grid it always returns the error message: "Error during parsing XML response"

** Which version are you currently using? **
Tabular Editor 3, version: 3.6.0.27344
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Connect to a Power BI Premium dataset, if connected to a local power bi desktop dataset it work ok

1. Open a new Pivot Grid
2. Add a measure, column, or filter.
3. If a column or filter click the filter icon
4. An error message opens: "Error during parsing XML response"

**Expected behavior**
That it should show values instead of an error message

**Screenshots**
![image](https://github.com/TabularEditor/TabularEditor3/assets/101556689/1a3a7eb4-0de7-4f2f-b5e8-bff87636608f)

**Desktop (please complete the following information):**
 - Windows version:11

**Comment by DBojsen** [comment]
Hi @janpetterholmberg 

This is unfortunately a known issue with 3.6.0.
It will be fixed in next release (due next week).

Only workaround is unfortunately to downgrade (you can have multiple versions at the same time by using the portable version)

BR David - TE3 Support

**Comment by otykier** [comment]
Hi @janpetterholmberg 
Happy to let you know that this was fixed in our [latest release](https://docs.tabulareditor.com/te3/other/release-notes/3_7_1.html?tabs=downloads).
Thanks again for reporting.
