### ISSUE TITLE
Wrong error reported when using EARLIER() with row-context columns like CALENDAR()

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#9]
When creating a calculated table with the CALENDAR() function, which creates a [date] column, TE3 marks as non-valid (error) the code that references the [date] column, when it is used together with EARLIER 

Error: column [DATE] cannot be found... 
Error: the EARLIER function only accepts a column...

Eg:

```
ADDCOLUMNS(
    CALENDAR(date(2017 , 1 , 1) , date(2022 , 1 , 1) )
    , "EOM" , EOMONTH([Date],0)
    , "BOM" , DATE(year([Date]) , MONTH([Date]) , 1)
    , "año" , year([Date])
    , "MonthInt" , year([Date]) * 100 + month([Date])
    , "Previous date with data in fact table"
    , 
       calculate(
          if(ISBLANK(max(FactTable[DATA_DAY])) , BLANK() , max(FactTable[DATA_DAY]))
          , all(FactTable)
          , FactTable_Dates[fact_Date] < EARLIER([Date])  --<<<<non-existing issue here
          , FactTable_Dates[fact_Date] > (-31 + EARLIER([Date])) --<<<<non-existing issue here
       )  
)
 
```
P.S.: yes, I know I could use VAR ;-)

EDIT: It also happens in other uses of EARLIER:

    sumx(
        values( 'Table'[Column] )
        , CALCULATE(
            sum('Table'[SomeOtherColumn])
            , keepfilters(Table2[Whatever] <= EARLIER([Column]))  --<< non-existing issue here
        )
    )

**Comment by otykier** [comment]
Fixed in [3.0.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.1). Thanks for reporting!
