### ISSUE TITLE
Naming folders quickly

### ISSUE THREAD

**Issue by Stewwe1** [TabularEditor/TabularEditor3#90]
Hello Daniel,

not really a big deal, but a bit annoying:

When I create a folder, I can usually rename the folder immediately. Now it says "New Folder" and I have to click on it to rename it.

Many thanks for the help

Stewwe

**Comment by otykier** [comment]
This has been fixed in [3.0.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.7), thanks for reporting!

In addition, copy/pasting a single object now also retains the text editor so you can immediately rename the pasted object.
