### ISSUE TITLE
How to set featured tables in Tabular 3?

### ISSUE THREAD

**Issue by MrPets** [TabularEditor/TabularEditor3#901]
**Describe the issue**
Not sure if this is an issue per se.

After looking for ten minutes I was unable to find how to set feature tables in Tabular, as described for Power BI desktop here:
https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-excel-featured-tables. 

** Which version are you currently using? **
Tabular Editor 3.5.1 - Enterprise Edition

**Expected behavior**
Find the option in table properties.

**Comment by DBojsen** [comment]
Hi @MrPets 

As of now, this feature in Power BI Desktop is poorly documented and makes multiple checks and changes to the model.
It will set properties on the table, key column and default label column.

We don't currently have plans to add native support for making this change, but this script can help you (doesn't validate the columns though):
``` C#
using Microsoft.VisualBasic;

foreach (var table in Selected.Tables) 
{
	// Check if already set as featured table
	var hasFeaturedTableTurnedOn = table.ExtendedProperties.Keys.Any(k => k == "IsCuratedForDataSearch");
	if (hasFeaturedTableTurnedOn)
	{
		Info($"Table {table.Name} is already a featured table!";
		continue;
	}

	// Get description for table
	var description = table.Description ?? "";
	description = SuspendWaitForm(() => Interaction.InputBox("Please set the description for the table", $"Set {table.Name} as featured table", description));
	
	// Get key and default label column for table
	var keyColumn = table.SelectColumn(label: $"Please select the key column for {table.Name}, it needs to be unique for each row");
	var defaultLabelColumn = table.SelectColumn(label: $"Please select the default label column for {table.Name}");
	
	// If everything looks ok, make the changes
	if (keyColumn != null 
			&& defaultLabelColumn != null
			&& description != "")
	{
		defaultLabelColumn.IsDefaultLabel = true;
		keyColumn.IsKey = true;
		table.Description = description;
		table.SetExtendedProperty(
			"IsCuratedForDataSearch",
			"{}",
			ExtendedPropertyType.Json);
		Info($"Table {table.Name} has been set as a featured table");
	}
}
```

**Comment by DBojsen** [comment]
Hi @MrPets 

I completely forgot to update you - we have received confirmation from Microsoft, that it is not possible for any tool apart from Power BI Desktop to set featured tables, as the functionality is not available for external tools.
If that changes, we'll put it on our backlog.

BR David - TE3 Support

**Comment by MrPets** [comment]
@DBojsen  

Thank you for looking into this, too bad there is no solution - maybe some day down the road!

**Comment by otykier** [comment]
@MrPets I suggest you post this feature request, i.e. "Allow 3rd party tools to mark a table as a featured table", on the Power BI ideas site (now known as Fabric ideas): https://ideas.fabric.microsoft.com/ - when done, please share the link here, as I'm sure more Tabular Editor users could benefit from this feature as well.

**Comment by MrPets** [comment]
@DBojsen and others

Please see the link: https://ideas.fabric.microsoft.com/ideas/idea/?ideaid=a9a4c42c-0310-ee11-a81c-0022484f371d.

**Comment by otykier** [comment]
Thanks - voted!

**Comment by DBojsen** [comment]
Same here
