### ISSUE TITLE
Import Export (Excel) for Meta Data Translation

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#907]
Often Business User are responsible for translations and object naming. An easy Import / Export would benefit collaboration and speed.

Reviewed solution (not succesful) : 
https://github.com/microsoft/Analysis-Services/tree/master/MetadataTranslator

Error:
![image](https://github.com/TabularEditor/TabularEditor3/assets/74975641/c0dbff33-75df-40f0-b7cc-2ddafbf1440b)
some culture was not availalbe in the Expando Object

**Comment by otykier** [comment]
Another option is to export the translations as a tsv (tab-separated) file.

Tabular Editor can do that with just a few lines of c# script:

```csharp
var translatableObjects = Model.GetChildrenRecursive(true).Where(obj => obj is ITranslatableObject);
var translations = ExportProperties(translatableObjects, "TranslatedNames,TranslatedDescriptions,TranslatedDisplayFolders");
translations.Output();
SaveFile(@"c:\Temp\translations.tsv", translations);
```

Opening the produced file in Excel:

![image](https://github.com/TabularEditor/TabularEditor3/assets/8976200/47ee025f-b769-41f1-80a6-6d9b39ca3609)

Save the file as tab-separated values in Excel, then, to load the translations back into Tabular Editor, use the following script:

```csharp
var translations = ReadFile(@"c:\Temp\translations.tsv");
ImportProperties(translations);
```

**Comment by MarioMue13** [comment]
thx a lot, I will give this a try asap
