### ISSUE TITLE
New column not visible in Perspective Editor window

### ISSUE THREAD

**Issue by MartinNordestgaard** [TabularEditor/TabularEditor3#908]
**Describe the issue**
When I "update table schema" and adds a new column to a table the column is not visible in the Perspective Editor.
If I deploy/save to the model the column still does not update in the Perspective Editor window.

**Which version are you currently using?**
3.7.1 (EE)

**To Reproduce**
Connet to a model (AAS)

1. Go to a table
2. Right click -> "update table schema"
3. Accept changes (ex. add new column(s))

**Expected behavior**
Added columns visible in the Perspective Editor, when they are added to the model (or after a deply/save)

**Desktop (please complete the following information):**
 - Windows version 10

BR, Martin

**Comment by otykier** [comment]
Thanks for reporting this, Martin. We're looking into it!

**Comment by otykier** [comment]
Hi Martin. This is now fixed in v. [3.8.0](https://docs.tabulareditor.com/te3/other/release-notes/3_8_0.html?tabs=downloads), which was just released.
