### ISSUE TITLE
Mark as a date table

### ISSUE THREAD

**Issue by Klimkiv** [TabularEditor/TabularEditor3#91]
Please, where is this option in te3?

**Comment by marcosqlbi** [comment]
It is not strictly needed, even though it is probably a good idea to add it.
In the meantime, just identify the "Date" column in the "Date" table and set the "Key" property to True on the Date[Date] column.
The Tabular model doesn't have a "marked as date table" property, it's just a way to identify the unique date column in the Date table in a more user-friendly way.

**Comment by Klimkiv** [comment]
Thank you

**Comment by marcosqlbi** [comment]
Just to complete the feature, the Mark As Date table operation performs two steps:

1. Set the Key property of the Date column to True
2. Set the Data Category property of the table to Time

**Comment by otykier** [comment]
Mark as Date Table is now available in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
