### ISSUE TITLE
Tabular editor 3 changes column names UPPERCASE to lowercase for Power BI

### ISSUE THREAD

**Issue by MatMatiss** [TabularEditor/TabularEditor3#911]
In last weeks for Power BI reports are multiple times when visuals are crashed because multiple Column names are changed to lowercases what Power Bi can' find.

When in tabular editor update table schema  - then it can be fixed back. 

There are multiple tables with columns what changes. Most of all issues are with columns "NAME" to "name" and vice versa.

These changes don't make anybody manually.

**Comment by otykier** [comment]
Hi @MatMatiss 
Are you using TE3 as an external tool for Power BI Desktop? If so, you should be aware that adding/removing/modifying columns is not among the [supported write operations for external tools]( https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations), and Tabular Editor should normally prevent you from performing an update table schema, unless you enabled the “unsupported modeling operations” option, under *Tools > Preferences*. Could you confirm if this is the case?

**Comment by MatMatiss** [comment]
Hi!
Yes, I use as an external tool for Power BI Desktop and haven't  enabled
![image](https://github.com/TabularEditor/TabularEditor3/assets/135211046/ca2d291e-cd69-4ab6-8b94-58c85953b0b3)

I don't need to modify column names in TE3, use how they are in Power BI dataflows, but they changes somehow by TE3 so I update table schema to get them back as it is in Power BI dataflows

**Comment by otykier** [comment]
Hi @MatMatiss 
Sorry, I'm afraid I don't understand the problem then. When "Allow unsupported modeling operations" is disabled, TE3 will not give you the option to update table schemas:

Allow unsupported modeling operations **disabled**:
![image](https://github.com/TabularEditor/TabularEditor3/assets/8976200/9acf3031-8d33-45bf-94aa-3e78b77f778c)

Allow unsupported modeling operations **enabled**:
![image](https://github.com/TabularEditor/TabularEditor3/assets/8976200/ef6c511c-57d8-49ab-8312-0fab66907ee9)

**Comment by MatMatiss** [comment]
Sorry for delay response.
So I have **enabled** unsupported modeling operations. And that could be the issue I have (some time haven't get it)
