### ISSUE TITLE
Execute selection fails if script file contains multiple EVALUATE sections

### ISSUE THREAD

**Issue by dennislebedev** [TabularEditor/TabularEditor3#912]
**Describe the issue**
"Execute selection" fails if script file contains multiple EVALUATE sections, whereas "Execute" runs all the EVALUATE successfully

**Which version are you currently using**
Tabular Editor 3, version: 3.7.1.16393
Tabular Editor 3 edition: Business

**To Reproduce**
I'm connected to the SSAS 2019 Developer

![Fail](https://github.com/TabularEditor/TabularEditor3/assets/123240643/4a2a8104-369e-4a73-9186-3181d31ab4bf)
![Success](https://github.com/TabularEditor/TabularEditor3/assets/123240643/6fba76d7-f96a-4172-ae36-89b9d7cff2f5)

**Comment by otykier** [comment]
Thanks for reporting. We'll make sure that's fixed!

**Comment by mlonsk** [comment]
This issue has been fixed in Tabular Editor 3.13.0 
Closing the issue
