### ISSUE TITLE
Return row count of DAX query

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#915]
It would be nice if we could quickly get a row count of a query we just ran. I get why by default it only returns 1,000 records, and that is fine. 

But sometimes when optimizing the query, getting the total record count is a first line indication that the query is returning the same results. 

right now I have to wrap the query in {(COUNTROWS(the query)} to see. I don't want to click on the link to return all records - that takes too long and is memory/processor intensive.

So not sure if there is a way to say (1,000 records returned of 123,304,004 records) or another link for the app to rerun the query and just return the record count, saving me the time of doing the COUNTROWS method.

**Comment by DBojsen** [comment]
Hi @edhans 
There is no way for us to get the row count without actually running the query or doing as you are doing yourself.
This could effect query runtime - which is the reason we only show x number of result rows.

So unfortunately this is not something we plan to invest in now.
