### ISSUE TITLE
[Issue] Error "... could not collect Vertipaq Analyzer stats: The specified column was not found in the context ..."

### ISSUE THREAD

**Issue by PtrckGuo** [TabularEditor/TabularEditor3#923]
**Describe the issue**
When TE3 is connected to a local pbix model, I always get this error message. It only happens to this dataset. But I'm able to export stats of this dataset using DAX Studio.

** Which version are you currently using? **
Tabular Editor 3, version: Build 3.7.1.16393
Tabular Editor 3 edition: Desktop

**To Reproduce**
 Working offline and connecting to a local pbix

1. Go to 'Vertipag Analyzer'
2. Click on 'Collect Stats'
3. See error

**Expected behavior**
See Vertipag Analyzer stats in the window.

**Screenshots**
![Screenshot 2023-06-21 111034](https://github.com/TabularEditor/TabularEditor3/assets/98067535/f1888731-0ff4-4feb-94d2-dc71b44e8026)

**Desktop (please complete the following information):**
 - Windows version: 11

**Additional context**
PBI is the latest version.

**Comment by DBojsen** [comment]
Hi @PtrckGuo 

This is a known bug, which we have fixed. 
The fix will be in next release (expected next week)

BR David - TE3 support

**Comment by PtrckGuo** [comment]
Thanks, @DBojsen. I thought I accidentally did something unusual to my dataset.
