### ISSUE TITLE
Unable to create inactive relationship in a PBIX file with TE 3.8.

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#929]
**Describe the issue**
Unable to create inactive relationship in a Power BI Desktop file

** Which version are you currently using? **
Tabular Editor 3, version: 3.8
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Connected to Power BI June 2023 build - This is on an AdventureWorks dataset

Create a 2nd relationship between two tables, attempt to make the 2nd relationship inactive. It will not. See attached GIF.

![InactiveRelationship](https://github.com/TabularEditor/TabularEditor3/assets/45298358/fd6909f0-8de5-426e-af94-6fa448e171a2)

**Comment by otykier** [comment]
Thanks for reporting - as a workaround, enable **Allow unsupported modeling operations** under **Tools > Preferences**

**Comment by DBojsen** [comment]
Hi @edhans 

This is now fixed in [3.9.0](https://docs.tabulareditor.com/te3/other/release-notes/3_9_0.html?tabs=downloads).
Thanks for reporting.

BR David - TE3 Support
