### ISSUE TITLE
Unable to create Calculated Table in PBIX file 

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#930]
**Describe the issue**
I am unable to create a calculated table in a PBIX file and save it back to the model. June 2023 Power BI update.
<img width="541" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/45298358/326e64f0-6532-4932-8412-4a1e6b5365cb">

** Which version are you currently using? **
Tabular Editor 3, version: 3.8.0
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Connected to Power BI June 2023

Create a simple calculated table. See the code in the above error message screen cap.

The SourceColumn property is empty, and I cannot type in that box to manually set it. There is no dropdown for it either.
<img width="282" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/45298358/cec8f2fb-5582-4f8e-9f6f-4a7bb3204476">

Creating the same table in the PBIX file shows the source column property, but it is grayed out. 
<img width="289" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/45298358/cbd0cbd1-803e-4cbe-a9ba-7f030830887a">

So either TE/3 needs to fill in the source column property when the table is created, or that field needs to be editable. When doing this against a model in the service, TE/3 populates that property for me.

**Comment by otykier** [comment]
Thanks for reporting - this is the same root cause as #929 - enabling **Allow unsupported modeling operations** should help for now.
