### ISSUE TITLE
Incorrect "Circular Dependency" error

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#931]
**Describe the issue**
This is saying that the Snapshot Monthly Compare Index field is dependent upon the Snapshot Monthly Compare Date field and vice versa. This is not correct as far as I can tell. Their code doesn't reference each other (they only reference imported columns) and neither is sorting on the other. The dependency view appears to be correct.

![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/406198b6-d5b0-419a-ac4f-23dcbe855c46)

![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/dd8d1185-d97e-4686-93df-cee5c6b197f7)

![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/b5f4599b-12e9-4d50-b717-89f622fca33a)

 
** Which version are you currently using? **
Tabular Editor 3, version: 3.8.0
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Power BI Service

**Comment by edhans** [comment]
Related to this - I am working on a project to eliminate a field from a DIM table so heavily using the Dependency feature. One of the more complex measures rather than fixing it I created a duplicate, but no matter what I did, the Dependencies view would not show it, and when I selected that newly duplicated measure and showed what it was dependent upon, it showed nothing. Had to close and reopen TE/3 3.8.0, then it worked fine.

**Comment by edhans** [comment]
And now the 'Snapshot 1 Calendar'[Snapshot Monthly Compare Date] field is supposedly referencing itself. It is not. The word "compare" does not appear in the code, so it cannot be referencing itself.
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/78e4c78d-cd5e-4a7a-9b69-44107ed15b46)


Is there some metadata I have messed up?

**Comment by otykier** [comment]
Seems like our semantic analysis of the DAX is a bit too sensitive, compared to the real DAX engine in Power BI. Any chance you could share the .bim or .pbit file with us, so we can better investigate? support@tabulareditor.com - thanks!

**Comment by otykier** [comment]
Possible related to #920

**Comment by edhans** [comment]
Yeah, I saw #920 before posting this, but that was related to NAMEOF().This model does have Field Parameters, but none that are touching the table/fields in question. I will try and get the BIM file to support today.

**Comment by tbeswick291** [comment]
I'm seeing the same error. Can't see what's driving the error:
![image](https://github.com/TabularEditor/TabularEditor3/assets/22554170/edd18581-4b0c-418c-a8b0-12f28d7081a9)
![image](https://github.com/TabularEditor/TabularEditor3/assets/22554170/3f3018f5-940f-4643-8e18-7db11f312561)
![image](https://github.com/TabularEditor/TabularEditor3/assets/22554170/4f83ab8c-a1f9-4559-bd43-478b1c6bc4af)
![image](https://github.com/TabularEditor/TabularEditor3/assets/22554170/007f7fa0-25e5-4ed4-8e72-e6cbeab0860c)

**Comment by otykier** [comment]
@tbeswick291 are you also only seeing this in the DAX editor (and not in the TOM Explorer and the Messages view)?

**Comment by tbeswick291** [comment]
Hi Daniel
Thanks for the reply. No I am seeing the alert in the TOM and Warnings:
[image: image.png]

**Comment by otykier** [comment]
@tbeswick291 any chance you could send us the model.bim file, so we can investigate further? support@tabulareditor.com

**Comment by tbeswick291** [comment]
> @tbeswick291 any chance you could send us the model.bim file, so we can investigate further? [support@tabulareditor.com](mailto:support@tabulareditor.com)

Sent via email :)

**Comment by DBojsen** [comment]
Hi @edhans & @tbeswick291 

This is now solved in 3.9.0.
Thank you for reporting.

BR David - TE3 Support
