### ISSUE TITLE
Rename New Workspace dialog box to New Layout?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#935]
**Is your feature request related to a problem? Please describe.**

When I create a new layout via the Capture New Layout menu item, I am presented with the New Workspace dialog box:
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/71d9e38a-3821-4e73-a129-4f8a823733b0)

Then it shows up in the list of layouts, and I can manage the layouts.
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/2f026ce4-a281-4434-91b5-270c9f3e9b3c)

Never is the "workspace" name used again. Just a bit confusing, or there is another component I am missing.

**Comment by otykier** [comment]
No, you’re right. This is just an oversight - it should indeed be named “New layout” and “Layout name” (our UI vendor originally used the term “workspace”, but we wanted to avoid confusion with PBI workspaces and workspace databases)

**Comment by otykier** [comment]
Fixed in [3.10.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.10.0). Thanks for reporting!
