### ISSUE TITLE
Valid PowerPlatform.Dataflows code causes error box

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#936]
**Describe the issue**
I created an M query using Power Query online in a dataflow and generated good code, but when I tried to update the table schema I got this error:

<img width="406" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/45298358/0583b0d9-d7ed-4dd7-816c-3e2705d0206a">

The M code generated was this:

let
  Source = PowerPlatform.Dataflows([]),
  Navigation = Source{[Id = "Workspaces"]}[Data],
  #"Navigation 1" = Navigation{[workspaceId = "xxxxxxxxxxxxxxxx"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[dataflowId = "xxxxxxxxxxxxxxxxxxxxxx"]}[Data],
  #"Navigation 3" = #"Navigation 2"{[entity = "Sales", version = ""]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 3", {{"Unit Price", Currency.Type}, {"Net Price", Currency.Type}, {"Unit Cost", Currency.Type}})
in
  #"Changed column type"

By changing the first line to this:
`Source = PowerPlatform.Dataflows()`

it fixed the issue - removing the square brackets from inside the parenthesis.

** Which version are you currently using? **
Tabular Editor 3, version: 3.8
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Power BI Service

1. Create a simple connection to a Power Platform dataflow in PQO
2. Create new M partition table in TE3
3. Paste the M code in the Partition expression
4. Update Table Schema

Error shows up.

**Comment by DBojsen** [comment]
Hi @edhans 

This is now fixed in [3.9.0](https://docs.tabulareditor.com/te3/other/release-notes/3_9_0.html?tabs=downloads).
Thanks for reporting.

BR David - TE3 Support
