### ISSUE TITLE
TOM window goes blank - no way to fix. Have to restart TE3

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#937]
**Describe the issue**
Sometimes the TOM window goes blank. It happened a few weeks ago a few times and thought it was a fluke, but it just happened again. No way to get it back either, short of restarting, which means losing a lot of open windows/queries/pivots, etc.
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/fdf2353d-ee81-4fc8-8815-32f6daf627ef)

** Which version are you currently using? **
Tabular Editor 3, version: 3.8.0
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Power BI Service

No clue. It just happens. I've never seen it just "vanish" but when I switch back to it. So I can be in the BPA window and tab back to the TOM and it is empty, or I switch away from TE/3 entirely and then back and the TOM is empty.

Windows 10

**Comment by otykier** [comment]
Thanks for reporting. As you can probably guess, this is difficult to debug when we don't have a way to reproduce it, so please share any additional info you can, if it occurs again.

**Comment by edhans** [comment]
I definitely will. This was more of "Hey, if you see this or get other reports, I'm seeing it too."

If I can ever repro I will definitely report back.

**Comment by DBojsen** [comment]
Hi @edhans 

This should now be fixed in [3.9.0](https://docs.tabulareditor.com/te3/other/release-notes/3_9_0.html?tabs=downloads).
Thanks for reporting.

BR David - TE3 Support
