### ISSUE TITLE
DETAILROWS column references appear as error (intellisense) when used within a measure

### ISSUE THREAD

**Issue by natolira** [TabularEditor/TabularEditor3#938]
DETAILROWS is an sub-optimal alternative (maybe not so suboptimal) alternative to have table measures within DAX.

So, if you have a complex logic that needs to be added to several measures, it's better (at least thinking about maintenability) to have a single place to create/update the code and use it to other measures.

I'm currently using version 3.4.2 (yes, I need to update), but I'm pretty sure this issue persists at 3.8.0

To reproduce you need to set DETAILROWS expression that returns a table, let's say at Measure [MyTableMeasure] that has something like:
ADDCOLUMNS(
     ALLSELECTED('Dates'[Date]),
     "@Sales", [Sales Amount]
     )
     
So, I can create a measure:
Total Sales (external filters only) =
SUMX(
    DETAILROWS([MyTableMeasure]),
    [@Sales]
    )

And it works fine. The issue is that when I open Tabular editor, I see several intellisense error messages saying that

"The value for [@Sales] cannot be determined. Either [@Sales] doesn't existe or there is no current row for a column named [@Sales]."

The expected behaviour is that:
1) no error
2) even better, intellisense recognizes [@Sales] as a column of the table DETAILROWS([MyTableMeasure])

PS: I know this example doesn't make sense, it's just to make it ieasier to reproduce using contoso/adworks, for example.

**Comment by otykier** [comment]
Yup, that's a bug, still in 3.8.0. Our DAX parser currently doesn't propagate the static analysis of the detail rows expression to expressions that use DETAILROWS. We'll make sure that's fixed in an upcoming release. Thanks for reporting!

**Comment by DBojsen** [comment]
Hi @natolira 

This is now fixed in [3.9.0](https://docs.tabulareditor.com/te3/other/release-notes/3_9_0.html?tabs=downloads).
Thanks for reporting.

BR David - TE3 Support
