### ISSUE TITLE
add "-Copy" to duplicated measures, not " Copy"

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#940]
**Is your feature request related to a problem? Please describe.**
I duplicated about 10 measures that were part of a Daily forecast. Did the batch rename to find Daily and replace with Weekly.
Then did a batch rename of "Copy" to an empty box getting rid of copy. But I later found out as I was updating measure references changing [Daily Update] to [Weekly Update] was throwing errors, and figure out it was because there is no [Weekly Update] but [Weekly Update ] with the leftover space.

**Describe the solution you'd like**
if it had shown [Daily Update-Copy] I would have known to replace "-Copy" with nothing.

**Describe alternatives you've considered**
An alternate would be since the desktop cannot handle trailing spaces, and neither can humans, after any Batch Rename, remove any trailing spaces automatically.

**Comment by otykier** [comment]
Sometimes it’s the smallest things :-) but it’s a really good point, though, so we’ll make sure that’s fixed.

**Comment by otykier** [comment]
This is now fixed in [3.10.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.10.0). Thanks for reporting!
