### ISSUE TITLE
I'd like to record a Macro and then run this via the command line to support a scheduled task.  Does anyone know if this is possible?  I am on version 3.7.1 but can update to the latest build if required.

### ISSUE THREAD

**Issue by MikkyD2** [TabularEditor/TabularEditor3#943]
**Describe the issue**
A clear and concise description of what the issue is.

** Which version are you currently using? **
Tabular Editor 3, version: [Help -> About will show you]
Tabular Editor 3 edition: [Trial/Desktop/Business/Enterprise]

**To Reproduce**
Are you connected to SSAS/AAS/Power BI or working offline?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version: [e.g. 10/11]

**Additional context**

**Comment by otykier** [comment]
@MikkyD2 command line execution of C# scripts can be done through TE2 (since TE3 does not have a CLI). You can use TE3 to record the macro, then save the generated script as a file, which you can then pass into the TE2 CLI using `-S myscript.cs`.

**Comment by MikkyD2** [comment]
Thank you! I thought I was going mad with not finding command line references in the documentation

**Comment by otykier** [comment]
Tabular Editor uses C# scripts - not TMSL. For this reason, it should not be used for data refresh.
If you want to execute TMSL, consider using PowerShell instead: [Invoke-ASCmd](https://learn.microsoft.com/en-us/powershell/module/sqlserver/invoke-ascmd?view=sqlserver-ps).

Username/password login does not work with Power BI because of MFA/interactive logins. Instead, you’d have to use a [service principal](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools).

**Comment by MikkyD2** [comment]
Thank you so much.  The connection is now working and the following may be helpful to someone else (ids all changed)

-- using my username and password
start /wait TabularEditor.exe "Data Source=powerbi://api.powerbi.com/v1.0/myorg/MyWorkspace;User ID=MikkyD2@uk.com;Password=Mypassword" MyDatasetName

-- using an SPN.  I had this created, added as admin to the workspace and sent to Azure Portal -> App registrations to create a secret/key aka password for logons
start /wait TabularEditor.exe "Data Source=powerbi://api.powerbi.com/v1.0/myorg/EO DEV PRIMA DWH;User ID=app:ac64df9f-a018-44ba-c023-5bbded06fa75@ce56fae6-055d-4c9f-b6c9-9d341505a492;Password=0401f629-d368-42af-8c30-77d5d6c3c1a5" MyDatasetName

Documentation used from
https://docs.tabulareditor.com/te2/Command-line-Options.html
https://github.com/TabularEditor/TabularEditor/issues/828

**Comment by MikkyD2** [comment]
An issue I get now is that running the c# script directly in TE causes no issues and triggers an XMLA endpoint refresh.

However I get the following error from the command line. Any/all help would be appreciated as c# is all new to me

Executing script 0...
Script compilation errors:
Error CS1024 on line 1, col 2: Preprocessor directive expected
Error CS1025 on line 1, col 4: Single-line comment or end-of-line expected
