### ISSUE TITLE
Find Panel in Preview Data doesn't work

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#955]
**Describe the issue**
If you are looking at a table, and select Table Preview, then right-click on a field and open the Find Panel, the search returns no results. Instead the Message window shows an error - Argument 1 in SEARCH Function is required.

<img width="950" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/45298358/46f41c89-4840-4e25-8829-b81175d7aaee">

** Which version are you currently using? **
Tabular Editor 3.9, Enterprise

**To Reproduce**
Power BI Desktop

Adding wildcard characters (*, ?) doesn't help. Either does searching for values vs strings. The Find result always returns no records and has an error in the Messages window.

**Comment by DBojsen** [comment]
Hi Ed

I have reproduced the issue - we'll make sure to get that fixed.

Best Regards

David - Tabular Editor 3 Support

**Comment by otykier** [comment]
Fixed in [3.10.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.10.0). Thanks for reporting!
