### ISSUE TITLE
Include PBIX File Name for BIM Backups vs just the GUID

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#958]
**Is your feature request related to a problem? Please describe.**
Now that the backup feature has been fixed - #796 it would be nice if when working with a Power BI Desktop file if the backup had the name of the PBIX file in it. Currently it just has a GUID.
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/27a8ef49-380a-4013-8d11-e1bdd11c8435)

BIM backups for models saved to the service work fine - the model name is part of the ZIP file name.

**Describe the solution you'd like**
Include the PBIX File name when creating the backup.

**Comment by DBojsen** [comment]
Hi @edhans 

Of course it should be the model name and not the guid.
I have added it to the backlog.

Again, thank you for everything you do - we REALLY do appreciate it.

Best Regards

David - Tabular Editor 3 Support

**Comment by otykier** [comment]
Fixed in [3.10.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.10.0). Thanks for reporting!
