### ISSUE TITLE
[Issue] I cannot see the partitions of the tables

### ISSUE THREAD

**Issue by GilbertQue** [TabularEditor/TabularEditor3#959]
**Describe the issue**
When I look at a table I cannot see the partitions in the table. This could be a table with a single partition or multiple partitions.

** Which version are you currently using? **
Tabular Editor 3, version: [Help -> About will show you]
3.9.0
Tabular Editor 3 edition: [Trial/Desktop/Business/Enterprise]
Enterprise

**To Reproduce**
Both PBIX and online.

1.I go to a table and expand I expect to see the partitions as shown below in TE2
![image](https://github.com/TabularEditor/TabularEditor3/assets/72849240/ac2a7858-4c18-414f-a53e-0d650faaa6f2)
2. When I am in TE3 This is what I see for the same table.
3. 
![image](https://github.com/TabularEditor/TabularEditor3/assets/72849240/3d49176f-ca74-4641-849d-0cf810c349bd)

**Expected behavior**
I should be able to see the partitions

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Server 2016 Enterprise 
 -

**Comment by DBojsen** [comment]
Hi @GilbertQue 

Please verify if you by accident turned off displaying of partitions in the TOM Explorer menu bar:
![image](https://github.com/TabularEditor/TabularEditor3/assets/22237520/e35ea2da-a8aa-4180-bc64-c963c4c40843)

BR David - TE3 Support

**Comment by GilbertQue** [comment]
Hi David, you were 100% right. I do not recall pressing that button, after making the change I can now see the partitions. Apologies for the confusion from my side.
