### ISSUE TITLE
Add "Debug Commas" Option to DAX Formatting

### ISSUE THREAD

**Issue by bjulius** [TabularEditor/TabularEditor3#96]
Daniel,

I really like the new "Debug Commas" option in DAX Studio 2.16 that moves commas to the beginning of the next line, allowing you to comment out a line of code without having to delete then later reinsert the comma on the previous line.

If at some point, that could be added as an enhancement to the TE3 DAX formatting options, that would be great.

Thanks for considering.

- Brian

**Comment by otykier** [comment]
Yes, I love that feature! I'm working on providing offline DAX formatting capabilities (i.e. without relying on daxformatter.com). Makes a lot of sense to have a "Debug Commas" mode in there as well.

**Comment by bjulius** [comment]
Awesome, thanks!

**Comment by zenzeinet** [comment]
Please, make this so that the commas are at the beginning of the code rather than at the beginning of the line!
I have always formatted my code manually in order to have this "Debug commas" *"feature"* which for me is the natural formatting :)

**Comment by otykier** [comment]
This is now possible in [3.1.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.6). Right click in the DAX editor and choose **Format document (debug commas)**. Keyboard shortcut will be available later on. Thanks for reporting!
