### ISSUE TITLE
The Go To Definition button rarely lights up, and F12 doesn't work

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#962]
**Describe the issue**
The button to go to the DAX.Guide definition page rarely lights up. Almost never. I got it to a few days ago and no clue how I did. Here I am clicking around on function names, even adding a new function, and the button never activates. Pressing F12 does nothing, so the whole feature is not working correctly.

![DAXDefinition](https://github.com/TabularEditor/TabularEditor3/assets/45298358/b24adc53-39cb-4012-b34c-17c7fe83757e)

** Which version are you currently using? **
Tabular Editor 3.9 Enterprise

**To Reproduce**
This is in Power BI Desktop

**Expected behavior**
Any time my cursor is on a function name or one is selected, or I've just typed one in and am immediately after the opening paren after the autocomplete has filled in the remainder of the function name, the Define button should be working.

**Desktop (please complete the following information):**
 -Repro'd on both Windows version: 10 & 11

**Comment by edhans** [comment]
Oh, after playing around a bit, it seems the Define button is tied to the activation of the Peek Defintion button. Put your cursor on a measure and both Peek and Define become availble, and Define will define the measure itself, but doesn't do the dual purpose of also defining the function, even though the tooltip says "AVERAGEX Documentation - F12"

**Comment by DBojsen** [comment]
Hi @edhans 

This is a bug - I have added it to our backlog.

Best Regards

David - Tabular Editor 3 Support

**Comment by otykier** [comment]
Fixed in [3.10.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.10.0). Thanks for reporting!
