### ISSUE TITLE
Make the field selector list wider. Much much wider

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#965]
**Is your feature request related to a problem? Please describe.**
The default width of the field selector is never big enough. I know I can open it, but it would be nice if it was either:

![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/d2bf45f3-5327-490c-afbe-3a021792fc1b)

**Describe the solution you'd like**
- dynamic and go to either the width of the widest value it is currently holding, with some limit to ensure it doesn't go beyond the window I am in (expression editor, dax query, etc.
- Set to at least 4x-5x as wide as it is now
- Remembers my preference between windows within the current session, and preferably between sessions, so store in the layouts.JSON file
Don't care, whatever is easiest.

**Describe alternatives you've considered**
None, other than setting it for _each_ _and_ _every_ _window_

**Comment by DBojsen** [comment]
Hi @edhans 

Makes sense - added to backlog.

Best Regards

David - Tabular Editor 3 Support

**Comment by otykier** [comment]
We now auto-adjust the width in [3.10.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.10.0). Thanks for reporting!
