### ISSUE TITLE
Filename of Model.BIM backups uses incorrect timestamp

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#967]
**Describe the issue**
I _think_ there is an issue with the naming convention used for Model.BIM backups when a ZIP files is saved after each model save.

The filename created is:
Backup_ModelName_YYYYMMDDhhmmssnnn
YYYY - Year
MM - Month
DD - Day
hh - Hour
mm - Minute
ss - Second
nnn - milliseconds? 

The problem is hour. It doesn't seem to handle AM/PM. I saved a model at 2:24pm (14:24 military time) and the file name is Backup_Model_20230724**02**2423678. The bold should be 14 I believe, otherwise there is no way to tell if that is AM or PM.

** Which version are you currently using? **
Tabular Editor 3.9 Enterprise

Windows 10.

**Comment by DBojsen** [comment]
Hi @edhans 

Completely agree - added to backlog as a bug.

Best Regards

David - Tabular Editor 3 Support

**Comment by otykier** [comment]
Fixed in [3.10.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.10.0). Thanks for reporting!
