### ISSUE TITLE
[Issue] Measure Data Category - What is this?

### ISSUE THREAD

**Issue by kschaefersclap** [TabularEditor/TabularEditor3#968]
**Describe the issue**
I am not sure what the feature "Data Category" is within the Measure Definition window:
![image](https://github.com/TabularEditor/TabularEditor3/assets/141055920/2418339e-f329-4e91-9321-73a6728aa1c9)

is there any documentation on this feature?

**Comment by otykier** [comment]
Unfortunately, Microsoft hasn’t provided a lot of documentation for this property. One example is that you can use it to specify that a measure represents a hyperlink: https://www.kasperonbi.com/creating-a-hyperlink-with-filters-through-dax/

The full range of supported values is specified in the MS-SSAS-T protocol, but it is up to the individual client tools (such as Power BI or Excel), if they want to observe the Data Category assigned.
