### ISSUE TITLE
Use VS Compiler in C# scripting

### ISSUE THREAD

**Issue by samusaran** [TabularEditor/TabularEditor3#97]
One of the biggest drawbacks of the built-in Tabular Editor C# compiler is the lack of support for string interpolation.

Is there a way, like in the free TE to use the VS compiler?

**Comment by otykier** [comment]
Not currently, but a future update will allow you to specify a custom C# compiler.

**Comment by otykier** [comment]
[3.0.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.7) now lets you specify a custom compiler similar to Tabular Editor 2.X.

Find this setting under Tools > Preferences > C# Scripting and Macros:

![image](https://user-images.githubusercontent.com/8976200/123978499-31f4b100-d9c0-11eb-8333-12251430e368.png)

Refer to [this document](https://docs.tabulareditor.com/Advanced-Scripting.html#compiling-with-roslyn) for information on how to set up the Roslyn compiler.
