### ISSUE TITLE
Unable to Save changes to Direct Lake dataset

### ISSUE THREAD

**Issue by tlanza89** [TabularEditor/TabularEditor3#979]
**Describe the issue**
I am trying to edit a direct lake dataset using version 3.10.0 (Enterprise), but I receive an error when I save. I have XMLA read/write enabled and I'm on the Fabric trial.

** Which version are you currently using? **
3.10.0 Enterprise

**To Reproduce**
Are you connected to SSAS/AAS/Power BI or working offline?
Connected to my Fabric workspace. 

1. I'm simply duplicating a measure as a test (Inv Amt-copy)
2. Hit ctrl+S to save.

**Expected behavior**
Expecting TE to properly save my changes back to the service.

**Screenshots**
![image](https://github.com/TabularEditor/TabularEditor3/assets/84323100/96d7e61a-d6d8-4b7e-9b86-8c12c692b5ba)

**Desktop (please complete the following information):**
 - Windows version: 11

**Additional context**
I've been using Tabular Editor to manage my models via XMLA for over 1 year now. Import models work just fine.

Thank you!

**Comment by mlonsk** [comment]
Hi @tlanza89 

The issue you are facing is that the XMLA endpoint of your Fabrical Trial tennant is not set to read/write. This is a different setting than the Power BI XMLA endpoint.

In the Fabric admin portal you need to navigate to Capacity Settings > Trial and then choose your trial: 

![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/7216084e-a3eb-4081-8034-a39aeea3f5be)

Inside the trial settings under "Power BI Workloads" you will find the setting for XMLA read/write.
![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/1cd423c3-5473-4269-958f-4886a12b4814)


It is documented by Microsoft here:
https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview#enable-xmla-read-write

Hope this helps
