### ISSUE TITLE
Highlight colour when doing a text search in Script DAX

### ISSUE THREAD

**Issue by matthewkaess** [TabularEditor/TabularEditor3#98]
The line highlight colour is bright blue and obscures the visibility of the text. :(

![image](https://user-images.githubusercontent.com/63028659/123184901-0cefd200-d4d8-11eb-9fdf-c7d2dd7d0919.png)

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
