### ISSUE TITLE
Minor bug or design issue? Execute Selection in a DAX query doesn't work if cursor is in the ORDER BY clause

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#988]
**Describe the issue**
I just discovered last week I don't have to select a portion of text in a query to run just that portion. I can just put my cursor in that area and the Execute Section. _Awesome_.

But today I discovered that doesn't work if my cursor is on the ORDER BY line. I am not sure if that is a bug, or if the ORDER BY clause isn't actually considered part of the query.

![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/11286d3a-7acf-4998-b631-3bfac52e1062)

If my cursor is where the (1) is, Execute Selection works.
If my cursor is where the (2) is, Execute Selection does nothing.

** Which version are you currently using? **
Tabular Editor 3.10.1 Enterprise

**To Reproduce**
Power BI

1. Write a simple query with an order by line
2. move cursor to that line
3. press Execute Selection button

**Desktop (please complete the following information):**
 - Windows 10

**Comment by mlonsk** [comment]
Hi @edhans 
I believe this is expected behavior. 
Just placing the cursor on a line corresponds to selecting the whole of that line.
It is not possible to run a ORDER BY query on it own, which is why running selection does not do anything.

**Comment by edhans** [comment]
Thanks for the confirmation. I'll close this.
