### ISSUE TITLE
Power BI File not applying the changes made in TB3

### ISSUE THREAD

**Issue by admin-pio-amdn** [TabularEditor/TabularEditor3#989]
**Describe the issue**
I'm currently on trial license, just activated. Any changes i make in tabular editor 3, be it m code update or table name or measures wont reflect in my pbi file after applying changes. However, once i press control+save in TB3 i could see the change in pbi file but the changes disappear once i Apply the changes in PBI file itself.

** Which version are you currently using? **
Tabular Editor 3, version: 3.10.1.16685
Tabular Editor 3 edition: [Trial]

**To Reproduce**
Are you connected to SSAS/AAS/Power BI or working offline? Power BI

**Expected behavior**
Changes made in Tabular Editor 3 to apply to Power BI File.

**Screenshots**
1 - Before any changes (note the m code: source)
![image](https://github.com/TabularEditor/TabularEditor3/assets/81223015/eb78ad98-e28e-4cb9-9609-c238998d3332)

2 - Making the change in TB3 (notice the change in m code source
![image](https://github.com/TabularEditor/TabularEditor3/assets/81223015/1a91bbf3-4fb2-46e4-ad65-01d683662f99)

3 - Pressed control+s for saving
![image](https://github.com/TabularEditor/TabularEditor3/assets/81223015/8cc78b56-f7cc-4a23-94bc-2eadf52e5008)

4 - No changes reflected in Power BI Data Model
![image](https://github.com/TabularEditor/TabularEditor3/assets/81223015/ed2413e4-dd27-49d7-933d-0a782b30bad4)

5 - same even if i try to duplicate the table. it does not reflect in power bi file.
![image](https://github.com/TabularEditor/TabularEditor3/assets/81223015/8e4e601c-c488-47f0-88eb-1c853daffe7d)

**Desktop (please complete the following information):**
 - Windows version: 11

**Additional context**
I had restarted the machine, closed the power bi files/tb3 and reopened and did the same and still the issue exists.

**Comment by otykier** [comment]
This is a limitation of Power PBI Desktop. For a full list of supported modeling operations, see here: https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations

As a workaround, save the report as a [.pbip folder](https://powerbi.microsoft.com/en-us/blog/deep-dive-into-power-bi-desktop-developer-mode-preview/), then make the changes in TE3 without having Desktop open.
