### ISSUE TITLE
Please add an option to ignore Semantic Analysis errors for LocalDateTable and DateTableTemplate tables

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#99]
As per title. This would help keep the focus on the important things :-)

![image](https://user-images.githubusercontent.com/62320770/123338570-2dce2b00-d59d-11eb-9b72-533846ae28a9.png)

**Comment by otykier** [comment]
[3.0.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.7) now has an option to hide these warnings:

Tools > Preferences > Tabular Editor > (Check) Hide auto date/time warnings

![image](https://user-images.githubusercontent.com/8976200/123978314-0e316b00-d9c0-11eb-842a-d21db9ae40e0.png)
