### ISSUE TITLE
Import/Update Schema failing when connecting to Azure Synapse SQL Database[Issue] 

### ISSUE THREAD

**Issue by rem-bou** [TabularEditor/TabularEditor3#992]
**Describe the issue**
There is an error message before failing when using "Update Table Schema..." or "Import tables" from view on Azure Synapse SQL Database source. As a result no update of schema happens or when  importing, no columns are available. I have tested this on a model with compatibility 1550.

I am using SQL Server Authentication and I can browse SQL database to select table or view so credential are working.

** Which version are you currently using? **
Tabular Editor 3, version: 3.10.0 & 3.10.1
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Are you connected to SSAS/AAS/Power BI or working offline?
I have tried when connected to Power BI service only and when using 'Save to Folder' in parallel to being connected to Power BI Service

Update Table Schema:
1. Select table to update
2. Right Click on 'Update Table Schema...'
3. Enter Credentials if required
4. Click on "OK"
5. See error

Import Table :
1. Right Click on 'Table' Folder
2. Click on 'Import tables...'
3. Select Existing source
4. Click on "Next"
5. Select 'Choose from a list of available tables and views'
6. Click on 'Next'
7. Enter Credentials if required
8. Select view or table and Click on 'Next'
9. Click on 'Finish'
10. See error

**Expected behavior**
Functionality import table schema

**Screenshots**
![image](https://github.com/TabularEditor/TabularEditor3/assets/102403055/addf5300-236c-4014-8ff0-7cb574b647b9)
![image](https://github.com/TabularEditor/TabularEditor3/assets/102403055/a11c44a5-e20b-43cf-90d7-6c58599273e5)

**Desktop (please complete the following information):**
 - Windows version: 10

**Additional context**
This feature is still working as expected on TE 2.17.1

**Comment by mlonsk** [comment]
Hi @rem-bou 
Thank you for reporting.
Can I ask you to specify if you are using any special characters in your database name, username or password such as +,= etc.
If you would prefer not to say in this open forum, please email us at support@tabulareditor.com

We are trying to understand how this error message came about as it looks to be a problem in the connection string.

**Comment by rem-bou** [comment]
Hello,
We do not use special characters in our database name, username or password.
I've rolled back Tabular Editor to version 3.8.0 & 3.9.0 today and I am able to use these functions with no problem.

**Comment by mlonsk** [comment]
Hi @rem-bou 
This is very curious. 
Would it be possible for you to send the .bim file or alternatively the anonymized M queries and shared expression to us at support@tabulareditor.com referencing this issue?
We can then take a deeper look at what is going on.

**Comment by otykier** [comment]
Hi @rem-bou 
This issue is fixed in the [latest version](https://docs.tabulareditor.com/te3/other/release-notes/3_12_1.html?tabs=downloads) of Tabular Editor. Thanks for reporting and for your patience.
