### ISSUE TITLE
snowflake connectivity  Update Table Schema or Sourcing new tables -- failure

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#993]
### Discussed in https://github.com/TabularEditor/TabularEditor3/discussions/990

<div type='discussions-op-text'>

<sup>Originally posted by **cosminioan-sonos** September 12, 2023</sup>
hi Daniel,
still having problems with the ODBC connectivity within TE3, but ONLY when I attempt to do an "Update Table Schema" OR  when attempting  to **add new tables** off of the same ODBC connection , I get the following error:
![image](https://github.com/TabularEditor/TabularEditor3/assets/121896036/8b5e13d2-5fe7-4652-9f87-051cac7e4ec7)

I have NO problem REFRESHING the entire db or individual tables (within TE or SSMS), once deployed  -- it all works fine when trying to process.

I feel there's something going on with the M methods or code, somewhere, it's not carrying  through *all the connection properties*, that otherwise seem fine when processing the db/tables.  Doing a subsequent table import or  table metadata refresh works just fine in Visual Studio. (the TE is using the bim file created by VS)

(This seems to be what I had encountered, in issue #973,   before, but I was not able to pinpoint the problem with more accuracy.)

any thoughts?
thanks kindly --
Cos
 </div>

**Comment by otykier** [comment]
Fixed in [3.12.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.12.0), thanks for reporting!
