### ISSUE TITLE
[Issue] Data Refresh not available for DirectLake models (at the table level)

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#999]
**Describe the issue**
When live-connected to a DirectLake model, there is no way to use the Data Refresh functionality in TE3 on a table. There is only the option to use data refresh on the whole model itself.

** Which version are you currently using? **
3.11.0.26496

1. Connect to a DirectLake model
2. Right click on a table
3. There is no option for Refresh...

**Expected behavior**
Although it is commonly thought that DirectLake models do not need to be refreshed as it is managed in Fabric, this is not always the case. Adding/updating RLS necessitates 'framing' or refreshing the model. Additionally, folks can turn off the 'auto-sync' refresh option for their dataset which would that make it necessitate 'framing' (refreshes). In such a case, folks likely want individual control over which tables are synced with the lakehouse at a given time (so don't want to frame/refresh the entire model, just a table or several tables).

**Desktop (please complete the following information):**
 - Windows version: 11

**Comment by otykier** [comment]
Good catch! We’ll make sure the tool allows refresh of individual tables. Am I correct in my assumption that DirectLake tables only need the “Full” refresh option?

**Comment by m-kovalsky** [comment]
Great, thanks Daniel! Yes, 'full' should be enough for DirectLake models. However if composite models becomes supported with DirectLake models then other processing modes will become relevant as well.

**Comment by otykier** [comment]
Fixed in [3.12.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.12.0), thanks for reporting!
